### ISSUE TITLE
Problem during installation with "pavement.updategeoip" in "./paver_local.sh setup"

### ISSUE THREAD

**Issue by AlRaCh** [GeoNode/geonode#10219]
## Expected behavior
I'm installing geonode with the Advanced Core documentation for ubuntu-22-04-1lts.
In the "Update settings to use PostgreSQL database" section, there is the code block below:
```
workon geonode
cd /I should expect nearly 260,000KB./geonode
chmod +x *.sh
./paver_local.sh reset
./paver_local.sh setup
```
The `./paver_local.sh setup` line of code should download some files and install accordingly. 
It is expected that the code lines bellow should download nearly 260,000KB :
```
---> pavement.updategeoip
 python -W ignore manage.py updategeoip -o,
```

## Actual behavior and steps to reproduce the problem
With "./paver_local.sh reset", I had to manually kill the Java process/service.
With "./paver_local.sh setup", errors occur. It seems that "python -W ignore manage.py updategeoip -o" downloads a ridiculous 1 KB file... It indicate that it can't open the tar. 

Is it broken Partial download in the cache ?!?

```
(geonode) geonoder@geonoder-VirtualBox:/opt/geonode$ ./paver_local.sh setup
---> pavement.setup
---> pavement.setup_geoserver
/home/geonoder/.virtualenvs/geonode/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'artifacts.geonode.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
warnings.warn(
168422KB [00:05, 30899.99KB/s]
/home/geonoder/.virtualenvs/geonode/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'repo1.maven.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
warnings.warn(
8880KB [00:02, 3893.50KB/s]
/home/geonoder/.virtualenvs/geonode/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'artifacts.geonode.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
warnings.warn(
153KB [00:00, 519.22KB/s]
---> pavement.updategeoip
python -W ignore manage.py updategeoip -o
1KB [00:00, 2053.01KB/s]
Cannot process <_io.BufferedReader name='output.bin'>: file could not be opened successfully:

    method gz: ReadError('not a gzip file')
    method bz2: ReadError('not a bzip2 file')
    method xz: ReadError('not an lzma file')
    method tar: ReadError('truncated header')
    Traceback (most recent call last):
    File "/opt/geonode/geonode/monitoring/management/commands/updategeoip.py", line 87, in handle_new_format
    with tarfile.open(fileobj=f) as zfile:
    File "/usr/lib/python3.10/tarfile.py", line 1639, in open
    raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
    tarfile.ReadError: file could not be opened successfully:
    method gz: ReadError('not a gzip file')
    method bz2: ReadError('not a bzip2 file')
    method xz: ReadError('not an lzma file')
    method tar: ReadError('truncated header')
    GeoNode development environment successfully set up.If you have not set up an administrative account, please do so now. Use "paver start" to start up the server.

(geonode) geonoder@geonoder-VirtualBox:/opt/geonode$
```

## Specifications
  - GeoNode version: Lastest (2022-10-28) ==> 4.0.1.dev0
  - Following Advanced Core documentation for ubuntu-22-04-1lts.
  - Distributor ID:	Ubuntu
  - Description:	Ubuntu 22.04.1 LTS
  - Release:	22.04
  - Codename:	jammy
  - Linux geonoder-VirtualBox 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 >>UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
  -  Python list:
```
aiohttp                            3.8.3
aiosignal                          1.2.0
amqp                               5.1.1
asgiref                            3.5.2
asttokens                          2.0.8
async-generator                    1.10
async-timeout                      4.0.2
attrs                              22.1.0
Automat                            20.2.0
backcall                           0.2.0
beautifulsoup4                     4.11.1
billiard                           3.6.4.0
bleach                             5.0.1
boto3                              1.24.66
botocore                           1.27.96
Brotli                             1.0.9
cachetools                         5.2.0
celery                             5.2.7
certifi                            2022.9.24
cffi                               1.15.1
charset-normalizer                 2.1.1
click                              8.1.3
click-didyoumean                   0.3.0
click-plugins                      1.1.1
click-repl                         0.2.0
constantly                         15.1.0
contextlib2                        21.6.0
coverage                           6.4.4
cryptography                       38.0.1
decorator                          5.1.1
defusedxml                         0.7.1
Deprecated                         1.2.13
dj-database-url                    1.0.0
dj-pagination                      2.5.0
Django                             3.2.15
django-allauth                     0.51.0
django-appconf                     1.0.5
django-autocomplete-light          3.5.1
django-bootstrap3-datetimepicker-2 2.8.3
django-celery-results              2.4.0
django-contrib-comments            2.2.0
django-cors-headers                3.13.0
django-downloadview                2.3.0
django-filter                      22.1
django-floppyforms                 1.9.0
django-forms-bootstrap             3.1.0
django-geonode-mapstore-client     4.0.3       /home/geonoder/.virtualenvs/geonode/src/django-geonode-mapstore-client
django-grappelli                   3.0.3
django-guardian                    2.4.0
django-haystack                    3.2.1
django-imagekit                    4.1.0
django-invitations                 1.9.3
django-ipware                      4.0.2
django-js-asset                    2.0.0
django-markdownify                 0.9.2
django-modeltranslation            0.18.5
django-mptt                        0.13.4
django-polymorphic                 3.1.0
django-recaptcha                   3.0.0
django-select2                     7.10.0
django-sequences                   2.7
django-storages                    1.13.1
django-taggit                      1.5.1
django-tastypie                    0.14.4
django-tinymce                     3.5.0
django-treebeard                   4.5.1
django-user-agents                 0.4.0
django-uuid-upload-path            1.0.0
django-widget-tweaks               1.4.12
djangorestframework                3.12.0
djangorestframework-gis            1.0
djangorestframework-guardian       0.3.0
dnspython                          2.2.1
docker                             6.0.0
drf-extensions                     0.7.1
drf-spectacular                    0.23.1
drf-writable-nested                0.7.0
dropbox                            11.33.0
dynamic-rest                       2.1.2
elastic-transport                  8.4.0
elasticsearch                      8.4.3
exceptiongroup                     1.0.0
executing                          1.1.1
factory-boy                        3.2.1
Faker                              15.1.1
filelock                           3.8.0
flake8                             5.0.4
flaky                              3.7.0
frozenlist                         1.3.1
future                             0.18.2
geoip2                             4.6.0
geolinks                           0.2.0
GeoNode                            4.0.1.dev0  /opt/geonode
geonode-announcements              2.0.2
geonode-avatar                     5.0.8
geonode-django-activity-stream     0.10.0
geonode-oauth-toolkit              2.2.2
geonode-user-messages              2.0.2
geoserver-restconfig               2.0.8
gisdata                            0.5.4
glob2                              0.7
gn-arcrest                         10.5.5
gn-gsimporter                      2.0.4
google-api-core                    2.10.2
google-auth                        2.13.0
google-cloud-core                  2.3.2
google-cloud-storage               2.5.0
google-crc32c                      1.5.0
google-resumable-media             2.4.0
googleapis-common-protos           1.56.4
greenlet                           1.1.3.post0
gunicorn                           20.1.0
h11                                0.14.0
hashids                            1.3.1
httplib2                           0.20.4
hyperlink                          21.0.0
idna                               2.10
incremental                        22.10.0
inflection                         0.5.1
iniconfig                          1.1.1
invoke                             1.7.1
ipython                            8.4.0
isodate                            0.6.1
jdcal                              1.4.1
jedi                               0.18.1
jmespath                           1.0.1
jsonschema                         4.15.0
jwcrypto                           1.4.2
kombu                              5.2.4
lxml                               4.9.1
Mako                               1.2.3
Markdown                           3.4.1
MarkupSafe                         2.1.1
matplotlib-inline                  0.1.6
maxminddb                          2.2.0
mccabe                             0.7.0
mercantile                         1.2.1
mock                               4.0.3
multidict                          6.0.2
numpy                              1.23.4
oauthlib                           3.2.0
outcome                            1.2.0
OWSLib                             0.27.2
packaging                          21.3
parse                              1.19.0
parse-type                         0.6.0
parso                              0.8.3
Paver                              1.3.4
pexpect                            4.8.0
pickleshare                        0.7.5
pilkit                             2.0
Pillow                             9.1.1
pinax-notifications                6.0.0
pinax-ratings                      4.0.0
pip                                22.2.2
pixelmatch                         0.3.0
pluggy                             1.0.0
ply                                3.11
prompt-toolkit                     3.0.31
protobuf                           4.21.9
psutil                             5.9.2
psycopg2                           2.9.3
ptyprocess                         0.7.0
pure-eval                          0.2.2
py                                 1.11.0
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycodestyle                        2.9.1
pycountry                          22.3.5
pycparser                          2.21
pycsw                              2.6.1
pyflakes                           2.5.0
pygdal                             3.4.1.10
Pygments                           2.13.0
PyJWT                              2.4.0
pylibmc                            1.6.3
pyOpenSSL                          22.0.0
pyparsing                          3.0.9
pyproj                             3.2.1
pyrsistent                         0.18.1
PySocks                            1.7.1
pytest                             7.1.3
pytest-bdd                         6.0.1
pytest-django                      4.5.2
pytest-splinter                    3.3.1
python-dateutil                    2.8.2
python-dotenv                      0.21.0
python-etcd                        0.4.5
python-memcached                   1.59
python-mimeparse                   1.6.0
python-slugify                     6.1.2
python3-openid                     3.2.0
pytz                               2022.2.1
PyYAML                             6.0
rdflib                             6.1.1
redis                              4.3.4
requests                           2.28.1
requests-file                      1.5.1
requests-oauthlib                  1.3.1
requests-toolbelt                  0.9.1
rsa                                4.9
s3transfer                         0.6.0
schema                             0.7.5
selenium                           4.5.0
selenium-requests                  2.0.0
setuptools                         65.3.0
Shapely                            1.8.4
sherlock                           0.3.2
six                                1.16.0
smart-open                         6.1.0
sniffio                            1.3.0
sortedcontainers                   2.4.0
soupsieve                          2.3.2.post1
splinter                           0.18.1
SQLAlchemy                         1.4.40
sqlparse                           0.4.3
stack-data                         0.5.1
stone                              3.3.1
text-unidecode                     1.3
timeout-decorator                  0.5.0
tinycss2                           1.1.1
tldextract                         3.4.0
tomli                              2.0.1
tqdm                               4.64.1
traitlets                          5.5.0
trio                               0.22.0
trio-websocket                     0.9.2
Twisted                            22.4.0
typing_extensions                  4.4.0
ua-parser                          0.16.1
uritemplate                        4.1.1
urllib3                            1.26.12
user-agents                        2.2.0
uWSGI                              2.0.20
vine                               5.0.0
wcwidth                            0.2.5
webdriver-manager                  3.8.3
webencodings                       0.5.1
websocket-client                   1.4.1
wheel                              0.37.1
whitenoise                         6.2.0
wrapt                              1.14.1
wsproto                            1.2.0
xmljson                            0.2.1
xmltodict                          0.13.0
yarl                               1.8.1
zipstream-new                      1.1.8
zope.interface                     5.5.0


```

**Comment by davekennewell** [comment]
I took a quick look at this and it seems the master branch is dependent on this file:
https://github.com/GeoNode/geonode/blob/master/geonode/monitoring/management/commands/updategeoip.py#L30
which is now returning a 404.

@afabiani - is it possible for Geosolutions to either restore the file or change this link to a community based version?

**Comment by giohappy** [comment]
Closing as part of a repository cleanup: this issue was last updated before 2025-01-01. Not a judgment on the report itself — feel free to reopen or file a fresh issue against `main` if it's still relevant. Thanks for the report.
