### ISSUE TITLE
Deploy a vanilla GeoNode with Docker fails on 4.x

### ISSUE THREAD

**Issue by christianurich** [GeoNode/geonode#10486]
The startup of django4geonode fails on 4.x because PyOpenSSL is outdated.

Bumping PyOpenSSL  22.0.0 to 22.1.0 in requirements.txt or backporting #10049 would resolve the issue

Traceback is attached blow

```
Traceback (most recent call last):
  File "/usr/src/geonode/manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.10/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/geonode/geonode/base/models.py", line 68, in <module>
    from geonode.utils import (
  File "/usr/src/geonode/geonode/utils.py", line 73, in <module>
    from geonode.storage.manager import storage_manager
  File "/usr/src/geonode/geonode/storage/manager.py", line 34, in <module>
    from geonode.storage.data_retriever import DataItemRetriever, DataRetriever
  File "/usr/src/geonode/geonode/storage/data_retriever.py", line 25, in <module>
    import smart_open
  File "/usr/local/lib/python3.10/site-packages/smart_open/__init__.py", line 34, in <module>
    from .smart_open_lib import open, parse_uri, smart_open, register_compressor  # noqa: E402
  File "/usr/local/lib/python3.10/site-packages/smart_open/smart_open_lib.py", line 35, in <module>
    from smart_open import doctools
  File "/usr/local/lib/python3.10/site-packages/smart_open/doctools.py", line 21, in <module>
    from . import transport
  File "/usr/local/lib/python3.10/site-packages/smart_open/transport.py", line 101, in <module>
    register_transport('smart_open.s3')
  File "/usr/local/lib/python3.10/site-packages/smart_open/transport.py", line 49, in register_transport
    submodule = importlib.import_module(submodule)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/site-packages/smart_open/s3.py", line 17, in <module>
    import boto3
  File "/usr/local/lib/python3.10/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/usr/local/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/usr/local/lib/python3.10/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 17, in <module>
    from botocore import waiter, xform_name
  File "/usr/local/lib/python3.10/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/usr/local/lib/python3.10/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/usr/local/lib/python3.10/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/usr/local/lib/python3.10/site-packages/botocore/docs/client.py", line 14, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/usr/local/lib/python3.10/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/usr/local/lib/python3.10/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/usr/local/lib/python3.10/site-packages/botocore/utils.py", line 34, in <module>
    import botocore.httpsession
  File "/usr/local/lib/python3.10/site-packages/botocore/httpsession.py", line 46, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/usr/local/lib/python3.10/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.10/site-packages/OpenSSL/crypto.py", line 3268, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
Restarting periodic command scheduler: cronStopping periodic command scheduler: cron.
Starting periodic command scheduler: cron.
start-stop-daemon: warning: failed to kill 39: No such process
```

**Comment by afabiani** [comment]
@christianurich the branch 4.x has been deprecated in favour of 4.0.x

**Comment by christianurich** [comment]
The basic installation guide for docker still refers to 4.x might be good to change it to 4.0.x

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by afabiani** [comment]
@christianurich definitely, thanks for letting us konw!

**Comment by afabiani** [comment]
Documentation PR sent [here](https://github.com/GeoNode/documentation/pull/268)
