### ISSUE TITLE
Error during import/delete resource with goserver 2.20.6

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#10559]
## Expected Behavior
As a user, I should be able to delete/import a file using geoserver 2.20.6

## Actual Behavior
Geoserver raises different errors based on the kind of action that the user is performing:

During the Upload : (the dataset is imported even if the issue is raised)

```
Fixup GIS Backend Security Rules Accordingly on resource geonode:Negozi_e_Locali_Storici1 True
Error setting default style "Negozi_e_Locali_Storici1" for layer "Negozi_e_Locali_Storici1
Traceback (most recent call last):
  File "/opt/core/geonode/geonode/geoserver/helpers.py", line 1182, in set_styles
    gs_catalog.save(gs_dataset)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/geoserver/catalog.py", line 301, in save
    raise FailedRequestError(f'Failed to save to Geoserver catalog: {resp.status_code}, {resp.text}')
geoserver.catalog.FailedRequestError: Failed to save to Geoserver catalog: 500, Ambiguous handler methods mapped for '/geoserver/rest/layers/Negozi_e_Locali_Storici1.xml': {public void org.geoserver.rest.catalog.LayerController.layerPut(org.geoserver.catalog.LayerInfo,java.lang.String,java.lang.String), public org.springframework.http.ResponseEntity org.geowebcache.rest.controller.TileLayerController.layerPut(org.geowebcache.layer.TileLayer,java.lang.String) throws org.geowebcache.GeoWebCacheException,org.geowebcache.rest.exception.RestException,java.io.IOException}
Error 404 reading Style Filter Params GeoWebCache at http://localhost:8080/geoserver/gwc/rest/layers/geonode:Negozi_e_Locali_Storici1.xml
 -- Finalizing Upload for geonode:Negozi_e_Locali_Storici1... RUNNING
```

During the delete:

```
Traceback (most recent call last):
  File "/opt/core/geonode/geonode/resource/api/tasks.py", line 122, in resouce_service_dispatcher
    _output = getattr(resource_manager, _request.func_name)(*_bindings.args, **_bindings.kwargs)
  File "/opt/core/geonode/geonode/resource/manager.py", line 301, in delete
    ResourceBase.objects.filter(uuid=uuid).delete()
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/django/db/models/query.py", line 746, in delete
    deleted, _rows_count = collector.delete()
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/django/db/models/deletion.py", line 404, in delete
    signals.pre_delete.send(
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/core/geonode/geonode/decorators.py", line 56, in wrapper
    return func(*args, **kwargs)
  File "/opt/core/geonode/geonode/geoserver/signals.py", line 64, in geoserver_pre_delete
    geoserver_cascading_delete.apply_async((instance.alternate,))
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/celery/app/task.py", line 572, in apply_async
    return self.apply(args, kwargs, task_id=task_id or uuid(),
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/celery/app/task.py", line 793, in apply
    ret = tracer(task_id, args, kwargs, request)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/celery/app/trace.py", line 464, in trace_task
    I, R, state, retval = on_error(
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/celery/app/autoretry.py", line 54, in run
    ret = task.retry(exc=exc, **retry_kwargs)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/celery/app/task.py", line 730, in retry
    raise ret
celery.exceptions.Retry: Retry in 3s: FailedRequestError("Failed to make DELETE request: 500, Ambiguous handler methods mapped for '/geoserver/rest/layers/Negozi_e_Locali_Storici1.xml': {public void org.geoserver.rest.catalog.LayerController.layerDelete(java.lang.String,java.lang.String,boolean) throws java.io.IOException, public org.springframework.http.ResponseEntity org.geowebcache.rest.controller.TileLayerController.doDelete(javax.servlet.http.HttpServletRequest,java.lang.String) throws org.geowebcache.GeoWebCacheException,org.geowebcache.rest.exception.RestException,java.io.IOException}")
```

The error during the delete makes the dataset impossible to be deleted

## Steps to Reproduce the Problem

  1. run geonode with the master branch and geoserver 2.20.6 installed
  2. upload a dataset
  3. delete the dataset

## Specifications

  - GeoNode version: master
  - Installation type (vanilla, geonode-project):
  - Installation method (manual, docker):
  - Platform:
  - Additional details: tested only on master with the new importer and without it the issue is the same

**Comment by mattiagiupponi** [comment]
@afabiani Also during the deletion, even this issue is raised (I guess is due the previous one)

During the handling of the above exception, another exception occurred:
```python
Traceback (most recent call last):
  File "/opt/core/geonode/geonode/base/api/views.py", line 948, in resource_service_delete
    resouce_service_dispatcher.apply_async((_exec_request.exec_id,))
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/celery/app/task.py", line 572, in apply_async
    return self.apply(args, kwargs, task_id=task_id or uuid(),
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/celery/app/task.py", line 793, in apply
    ret = tracer(task_id, args, kwargs, request)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/celery/app/trace.py", line 468, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/core/geonode/geonode/resource/api/tasks.py", line 147, in resouce_service_dispatcher
    _exec_request.update(
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/django/db/models/query.py", line 783, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1162, in execute_sql
    sql, params = self.as_sql()
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1525, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 842, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 837, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/django/db/models/fields/json.py", line 93, in get_prep_value
    return json.dumps(value, cls=self.encoder)
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type __proxy__ is not JSON serializable
```

**Comment by kaloyan13** [comment]
Have the same issue with Geonode 4.0.x and Geoserver 2.20.7

**Comment by afabiani** [comment]
Add the option `-Dgwc.context.suffix=gwc` to the `JAVA_OPTS`
