### ISSUE TITLE
Edit style does not work

### ISSUE THREAD

**Issue by brunolvs** [GeoNode/geonode#10594]
I installed geonode 4 in a docker conteiner, almost everything is working, but when a try to edit a dataset style I get this message:

b"HTTPConnectionPool(host='geoserver', port=8080): Max retries exceeded with url: /geoserver/rest/workspaces/geonode/styles/ribeirao_preto_sombra?raw=true&access_token=X1SXdoRwBlD6T2jv2VZoY3p7ve2xke (Caused by ResponseError('too many 500 error responses'))"

Does anybody can tell me what is going on?

For example, edit metadata is working.

**Comment by geogeek11** [comment]
I have encountered the same issue.

To reproduce the issue:
- Create a new dataset.
- Edit style.
- Click on apply button.

After clicking on Apply button, a PUT query is sent to this URL `https://XXXXX/gs/rest/workspaces/geonode/styles/point?raw=true&access_token=XX`, then I get a 401 response with the text "You don't have permissions to change style for this layer"

The issue does not occur after uploading a new SLD style, after the upload, you can edit the style, this might be a temporary workaround. 

The issue does not occur for uploaded datasets.

Env: Geonode 4.0.2, Vanilla, Docker, Ubuntu.

**Comment by afabiani** [comment]
This happens whenever you try to edit a style with no workspace or one of the GeoServer default styles.

**Comment by geogeek11** [comment]
> This happens whenever you try to edit a style with no workspace or one of the GeoServer default styles.

I agree with your remark, in my server setup the new dataset uses the default Geoserver style.

I have tried to reset my local geonode project by removing volumes, then starting again I remark that with each new dataset, a new style is created with an uuid name. which does not happen in my server setup, for an unknown reason may be the new style creation is not done.

idk if this could help, in the django side I see no errors, but in  the server's geoserver side these are errors from the log  :

`2023-02-03 10:18:21,283 WARN [impl.RuleDAOImpl] -  ORIG: Rule[id:153 pri:168 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY]
2023-02-03 10:18:21,283 WARN [impl.RuleDAOImpl] -  DUP : Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY]
2023-02-03 10:18:21,283 ERROR [geoserver.rest] - Duplicate Rule Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY]
org.geoserver.geofence.core.dao.DuplicateKeyException: Duplicate Rule Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY]2023-02-03 10:18:21,283 WARN [impl.RuleDAOImpl] -  ORIG: Rule[id:153 pri:168 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY]
2023-02-03 10:18:21,283 WARN [impl.RuleDAOImpl] -  DUP : Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY]
2023-02-03 10:18:21,283 ERROR [geoserver.rest] - Duplicate Rule Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY]
org.geoserver.geofence.core.dao.DuplicateKeyException: Duplicate Rule Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY]`

`2023-02-03 10:18:18,881 WARN [geofence.rest] - INVALIDATING CACHE
2023-02-03 10:18:18,881 WARN [geofence.cache] - Forcing cache invalidation
2023-02-03 10:18:18,958 WARN [protocol.ResponseProcessCookies] - Invalid cookie header: "Set-Cookie: sessionid=odi3ihlndcyv59hs1iw50bz9vlex8wfg; expires=Fri, 17 Feb 2023 10:18:18 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax". Invalid 'expires' attribute: Fri, 17 Feb 2023 10:18:18 GMT
2023-02-03 10:18:18,971 WARN [protocol.ResponseProcessCookies] - Invalid cookie header: "Set-Cookie: sessionid=4kwxavrtxtggd8we2lch7kh35nikkt9b; expires=Fri, 17 Feb 2023 10:18:18 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax". Invalid 'expires' attribute: Fri, 17 Feb 2023 10:18:18 GMT
2023-02-03 10:18:20,905 WARN [geofence.rest] - INVALIDATING CACHE
2023-02-03 10:18:20,905 WARN [geofence.cache] - Forcing cache invalidation
2023-02-03 10:18:21,119 WARN [geofence.rest] - INVALIDATING CACHE
2023-02-03 10:18:21,119 WARN [geofence.cache] - Forcing cache invalidation
2023-02-03 10:18:21,250 WARN [impl.RuleDAOImpl] -  ORIG: Rule[id:151 pri:166 srv:WFS req:TRANSACTION ws:geonode l:test4 acc:DENY]
2023-02-03 10:18:21,250 WARN [impl.RuleDAOImpl] -  DUP : Rule[id:null pri:170 srv:WFS req:TRANSACTION ws:geonode l:test4 acc:DENY]
2023-02-03 10:18:21,250 ERROR [geoserver.rest] - Duplicate Rule Rule[id:null pri:170 srv:WFS req:TRANSACTION ws:geonode l:test4 acc:DENY]
org.geoserver.geofence.core.dao.DuplicateKeyException: Duplicate Rule Rule[id:null pri:170 srv:WFS req:TRANSACTION ws:geonode l:test4 acc:DENY]`

**Comment by afabiani** [comment]
> > This happens whenever you try to edit a style with no workspace or one of the GeoServer default styles.
> 
> I agree with your remark, in my server setup the new dataset uses the default Geoserver style.
> 
> I have tried to reset my local geonode project by removing volumes, then starting again I remark that with each new dataset, a new style is created with an uuid name. which does not happen in my server setup, for an unknown reason may be the new style creation is not done.
> 
> idk if this could help, in the django side I see no errors, but in the server's geoserver side these are errors from the log :
> 
> `2023-02-03 10:18:21,283 WARN [impl.RuleDAOImpl] - ORIG: Rule[id:153 pri:168 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY] 2023-02-03 10:18:21,283 WARN [impl.RuleDAOImpl] - DUP : Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY] 2023-02-03 10:18:21,283 ERROR [geoserver.rest] - Duplicate Rule Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY] org.geoserver.geofence.core.dao.DuplicateKeyException: Duplicate Rule Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY]2023-02-03 10:18:21,283 WARN [impl.RuleDAOImpl] - ORIG: Rule[id:153 pri:168 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY] 2023-02-03 10:18:21,283 WARN [impl.RuleDAOImpl] - DUP : Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY] 2023-02-03 10:18:21,283 ERROR [geoserver.rest] - Duplicate Rule Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY] org.geoserver.geofence.core.dao.DuplicateKeyException: Duplicate Rule Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY]`
> 
> `2023-02-03 10:18:18,881 WARN [geofence.rest] - INVALIDATING CACHE 2023-02-03 10:18:18,881 WARN [geofence.cache] - Forcing cache invalidation 2023-02-03 10:18:18,958 WARN [protocol.ResponseProcessCookies] - Invalid cookie header: "Set-Cookie: sessionid=odi3ihlndcyv59hs1iw50bz9vlex8wfg; expires=Fri, 17 Feb 2023 10:18:18 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax". Invalid 'expires' attribute: Fri, 17 Feb 2023 10:18:18 GMT 2023-02-03 10:18:18,971 WARN [protocol.ResponseProcessCookies] - Invalid cookie header: "Set-Cookie: sessionid=4kwxavrtxtggd8we2lch7kh35nikkt9b; expires=Fri, 17 Feb 2023 10:18:18 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax". Invalid 'expires' attribute: Fri, 17 Feb 2023 10:18:18 GMT 2023-02-03 10:18:20,905 WARN [geofence.rest] - INVALIDATING CACHE 2023-02-03 10:18:20,905 WARN [geofence.cache] - Forcing cache invalidation 2023-02-03 10:18:21,119 WARN [geofence.rest] - INVALIDATING CACHE 2023-02-03 10:18:21,119 WARN [geofence.cache] - Forcing cache invalidation 2023-02-03 10:18:21,250 WARN [impl.RuleDAOImpl] - ORIG: Rule[id:151 pri:166 srv:WFS req:TRANSACTION ws:geonode l:test4 acc:DENY] 2023-02-03 10:18:21,250 WARN [impl.RuleDAOImpl] - DUP : Rule[id:null pri:170 srv:WFS req:TRANSACTION ws:geonode l:test4 acc:DENY] 2023-02-03 10:18:21,250 ERROR [geoserver.rest] - Duplicate Rule Rule[id:null pri:170 srv:WFS req:TRANSACTION ws:geonode l:test4 acc:DENY] org.geoserver.geofence.core.dao.DuplicateKeyException: Duplicate Rule Rule[id:null pri:170 srv:WFS req:TRANSACTION ws:geonode l:test4 acc:DENY]`
> 
> ` at java.base/java.lang.Thread.run(Thread.java:829) 2023-02-03 10:18:18,102 ERROR [config.impl] - Could not locate service of type interface org.geoserver.wps.WPSInfo, local workspace is null 2023-02-03 10:18:18,102 ERROR [config.impl] - Error occurred processing a configuration change listener java.lang.NullPointerException at org.geoserver.wps.WPSInitializer.initWPS(WPSInitializer.java:79)`

Uhm I don't think those warnings are related to your specific issue. It looks like a configuration or a security issue between GeoNode and GeoServer. It looks like GeoNode/MapStore is not able to finalize the style creation. I have seen something similar in the past also related to a GeoServer catalog misconfiguration.

Can you double check the admin username is correctly set on the env? And also that the security between GN and GS is working correctly (inparticular GS is able to retrieve the user roles from GN)?

**Comment by geogeek11** [comment]
> > > This happens whenever you try to edit a style with no workspace or one of the GeoServer default styles.
> > 
> > 
> > I agree with your remark, in my server setup the new dataset uses the default Geoserver style.
> > I have tried to reset my local geonode project by removing volumes, then starting again I remark that with each new dataset, a new style is created with an uuid name. which does not happen in my server setup, for an unknown reason may be the new style creation is not done.
> > idk if this could help, in the django side I see no errors, but in the server's geoserver side these are errors from the log :
> > `2023-02-03 10:18:21,283 WARN [impl.RuleDAOImpl] - ORIG: Rule[id:153 pri:168 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY] 2023-02-03 10:18:21,283 WARN [impl.RuleDAOImpl] - DUP : Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY] 2023-02-03 10:18:21,283 ERROR [geoserver.rest] - Duplicate Rule Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY] org.geoserver.geofence.core.dao.DuplicateKeyException: Duplicate Rule Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY]2023-02-03 10:18:21,283 WARN [impl.RuleDAOImpl] - ORIG: Rule[id:153 pri:168 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY] 2023-02-03 10:18:21,283 WARN [impl.RuleDAOImpl] - DUP : Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY] 2023-02-03 10:18:21,283 ERROR [geoserver.rest] - Duplicate Rule Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY] org.geoserver.geofence.core.dao.DuplicateKeyException: Duplicate Rule Rule[id:null pri:172 srv:WFS req:GETFEATUREWITHLOCK ws:geonode l:test4 acc:DENY]`
> > `2023-02-03 10:18:18,881 WARN [geofence.rest] - INVALIDATING CACHE 2023-02-03 10:18:18,881 WARN [geofence.cache] - Forcing cache invalidation 2023-02-03 10:18:18,958 WARN [protocol.ResponseProcessCookies] - Invalid cookie header: "Set-Cookie: sessionid=odi3ihlndcyv59hs1iw50bz9vlex8wfg; expires=Fri, 17 Feb 2023 10:18:18 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax". Invalid 'expires' attribute: Fri, 17 Feb 2023 10:18:18 GMT 2023-02-03 10:18:18,971 WARN [protocol.ResponseProcessCookies] - Invalid cookie header: "Set-Cookie: sessionid=4kwxavrtxtggd8we2lch7kh35nikkt9b; expires=Fri, 17 Feb 2023 10:18:18 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax". Invalid 'expires' attribute: Fri, 17 Feb 2023 10:18:18 GMT 2023-02-03 10:18:20,905 WARN [geofence.rest] - INVALIDATING CACHE 2023-02-03 10:18:20,905 WARN [geofence.cache] - Forcing cache invalidation 2023-02-03 10:18:21,119 WARN [geofence.rest] - INVALIDATING CACHE 2023-02-03 10:18:21,119 WARN [geofence.cache] - Forcing cache invalidation 2023-02-03 10:18:21,250 WARN [impl.RuleDAOImpl] - ORIG: Rule[id:151 pri:166 srv:WFS req:TRANSACTION ws:geonode l:test4 acc:DENY] 2023-02-03 10:18:21,250 WARN [impl.RuleDAOImpl] - DUP : Rule[id:null pri:170 srv:WFS req:TRANSACTION ws:geonode l:test4 acc:DENY] 2023-02-03 10:18:21,250 ERROR [geoserver.rest] - Duplicate Rule Rule[id:null pri:170 srv:WFS req:TRANSACTION ws:geonode l:test4 acc:DENY] org.geoserver.geofence.core.dao.DuplicateKeyException: Duplicate Rule Rule[id:null pri:170 srv:WFS req:TRANSACTION ws:geonode l:test4 acc:DENY]`
> > ` at java.base/java.lang.Thread.run(Thread.java:829) 2023-02-03 10:18:18,102 ERROR [config.impl] - Could not locate service of type interface org.geoserver.wps.WPSInfo, local workspace is null 2023-02-03 10:18:18,102 ERROR [config.impl] - Error occurred processing a configuration change listener java.lang.NullPointerException at org.geoserver.wps.WPSInitializer.initWPS(WPSInitializer.java:79)`
> 
> Uhm I don't think those warnings are related to your specific issue. It looks like a configuration or a security issue between GeoNode and GeoServer. It looks like GeoNode/MapStore is not able to finalize the style creation. I have seen something similar in the past also related to a GeoServer catalog misconfiguration.
> 
> Can you double check the admin username is correctly set on the env? And also that the security between GN and GS is working correctly (inparticular GS is able to retrieve the user roles from GN)?

Thanks a lot

**Comment by giohappy** [comment]
Closing as part of a repository cleanup: this issue was last updated before 2025-01-01. Not a judgment on the report itself — feel free to reopen or file a fresh issue against `main` if it's still relevant. Thanks for the report.
