### ISSUE TITLE
Not able to upload KML file

### ISSUE THREAD

**Issue by adjioev** [GeoNode/geonode#1066]
After switching uploader to:

```
UPLOADER = {
    'BACKEND' : 'geonode.importer',
    'OPTIONS' : {
        'TIME_ENABLED': False,
        'GEOGIT_ENABLED': False,
    }
}
```

geonode is throwing following  exception during KML upload:

```
Unexpected Error:,Please report the following code: 4eaeabc2-8f5b-42d6-bf04-b4324e41ec23 
```

Geonode log:

```
[Wed Aug 28 02:50:56 2013] [error] Unexpected error in upload step
[Wed Aug 28 02:50:56 2013] [error] Traceback (most recent call last):
[Wed Aug 28 02:50:56 2013] [error]   File "/usr/local/lib/python2.7/dist-packages/geonode/upload/views.py", line 582, in view
[Wed Aug 28 02:50:56 2013] [error]     resp = _steps[step](req, upload_session)
[Wed Aug 28 02:50:56 2013] [error]   File "/usr/local/lib/python2.7/dist-packages/geonode/upload/views.py", line 222, in save_step_view
[Wed Aug 28 02:50:56 2013] [error]     import_session = upload.save_step(req.user, name, base_file, overwrite=False)
[Wed Aug 28 02:50:56 2013] [error]   File "/usr/local/lib/python2.7/dist-packages/geonode/upload/upload.py", line 272, in save_step
[Wed Aug 28 02:50:56 2013] [error]     raise Exception('Could not save the layer %s, there was an upload error: %s' % (name, error_msg))
[Wed Aug 28 02:50:56 2013] [error] Exception: Could not save the layer KML_Samples, there was an upload error: No upload items found for task
```

Original thread: 
https://groups.google.com/forum/#!topic/geonode-users/ccWD2abRkq4

**Comment by jj0hns0n** [comment]
I think we are going to punt on KML issues until 2.5
