### ISSUE TITLE
Remote Services datasets do not have a thumbnail anymore

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#10685]
When creating a dataset from a Remote Service, the thumbnail won't be created on most of the cases

![image](https://user-images.githubusercontent.com/1278021/220876969-f71d4fa4-34eb-412c-b9b4-a06a54063943.png)

**Comment by afabiani** [comment]
Seems to be caused by the following exception from the https://github.com/GeoNode/geonode/blob/master/geonode/resource/utils.py#L135

```
 psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "base_hierarchicalkeyword_path_key"
DETAIL:  Key (path)=(004N) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/geonode/base/models.py", line 482, in add
    new_tag_obj = HierarchicalKeyword.add_root(name=new_tag)
  File "/usr/local/lib/python3.10/site-packages/treebeard/mp_tree.py", line 617, in add_root
    return MP_AddRootHandler(cls, **kwargs).process()
  File "/usr/local/lib/python3.10/site-packages/treebeard/mp_tree.py", line 313, in process
    return last_root.add_sibling('sorted-sibling', **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/treebeard/mp_tree.py", line 1098, in add_sibling
    return MP_AddSiblingHandler(self, pos, **kwargs).process()
  File "/usr/local/lib/python3.10/site-packages/treebeard/mp_tree.py", line 436, in process
    self.run_sql_stmts()
  File "/usr/local/lib/python3.10/site-packages/treebeard/mp_tree.py", line 145, in run_sql_stmts
    cursor.execute(sql, vals)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "base_hierarchicalkeyword_path_key"
DETAIL:  Key (path)=(004N) already exists.
```

**Comment by giohappy** [comment]
Closing as part of a repository cleanup: this issue was last updated before 2025-01-01. Not a judgment on the report itself — feel free to reopen or file a fresh issue against `main` if it's still relevant. Thanks for the report.
