### ISSUE TITLE
Deadlock in HierarchicalTagManager when creating tags

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#10859]
## Actual Behavior

Sometimes the log reports a DB deadlock when creating tags.

## Specifications

  - GeoNode version: 3.3.x, 4.x

## Details

<details>
  <summary>Log `tag_objs.update(existing)` --> `self._fetch_all()` </summary>

```
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/upload/upload.py", line 936, in final_step
    saved_layer = _update_layer_with_xml_info(saved_layer, xml_file, regions, keywords, vals)
  File "/usr/src/geonode/geonode/upload/upload.py", line 1075, in _update_layer_with_xml_info
    saved_layer = utils.KeywordHandler(saved_layer, keywords).set_keywords()
  File "/usr/src/geonode/geonode/upload/utils.py", line 669, in set_keywords
    self._set_free_keyword(keywords)
  File "/usr/src/geonode/geonode/upload/utils.py", line 711, in _set_free_keyword
    self.instance.keywords.add(*keywords)
  File "/usr/src/geonode/geonode/base/models.py", line 478, in add
    tag_objs.update(existing)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: deadlock detected
DETAIL:  Process 19352 waits for ShareLock on transaction 71406198; blocked by process 19188.
Process 19188 waits for ShareLock on transaction 71406498; blocked by process 15015.
Process 15015 waits for AccessExclusiveLock on tuple (23,57) of relation 40986 of database 37725; blocked by process 19352.
HINT:  See server log for query details.
CONTEXT:  while locking tuple (23,57) in relation "base_hierarchicalkeyword"
```
</details>

<details>
  <summary>Log `new_tag_obj = HierarchicalKeyword.add_root(name=new_tag)` </summary>

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/geonode/geonode/upload/upload.py", line 936, in final_step
    saved_layer = _update_layer_with_xml_info(saved_layer, xml_file, regions, keywords, vals)
  File "/usr/src/geonode/geonode/upload/upload.py", line 1075, in _update_layer_with_xml_info
    saved_layer = utils.KeywordHandler(saved_layer, keywords).set_keywords()
  File "/usr/src/geonode/geonode/upload/utils.py", line 669, in set_keywords
    self._set_free_keyword(keywords)
  File "/usr/src/geonode/geonode/upload/utils.py", line 711, in _set_free_keyword
    self.instance.keywords.add(*keywords)
  File "/usr/src/geonode/geonode/base/models.py", line 483, in add
    new_tag_obj = HierarchicalKeyword.add_root(name=new_tag)
  File "/usr/local/lib/python3.8/site-packages/treebeard/mp_tree.py", line 617, in add_root
    return MP_AddRootHandler(cls, **kwargs).process()
  File "/usr/local/lib/python3.8/site-packages/treebeard/mp_tree.py", line 313, in process
    return last_root.add_sibling('sorted-sibling', **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/treebeard/mp_tree.py", line 1098, in add_sibling
    return MP_AddSiblingHandler(self, pos, **kwargs).process()
  File "/usr/local/lib/python3.8/site-packages/treebeard/mp_tree.py", line 436, in process
    self.run_sql_stmts()
  File "/usr/local/lib/python3.8/site-packages/treebeard/mp_tree.py", line 145, in run_sql_stmts
    cursor.execute(sql, vals)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: deadlock detected
DETAIL:  Process 19188 waits for ShareLock on transaction 71406498; blocked by process 15015.
Process 15015 waits for AccessExclusiveLock on tuple (23,57) of relation 40986 of database 37725; blocked by process 19377.
Process 19377 waits for ShareLock on transaction 71406198; blocked by process 19188.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (6,55) in relation "base_hierarchicalkeyword"

```
</details>

**Comment by giohappy** [comment]
As we found out @etj the SELECT FOR UPDATE within the hierarchical model can raise deadlocks with concurrent updates. 
Removing the explicit lock [here](https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L406) is a workaround (whose effects must however be managed), but the proper solution is to review how the MP_Node is being used here.

**Comment by giohappy** [comment]
@mattiagiupponi where we are with this?

**Comment by mattiagiupponi** [comment]
We made a test in an environment and it looked like the `select_for_update()` is not needed. I didn't test it deeply yet on master and 4.1.x
I'll give some extra tests later and I'll open a pr for this

**Comment by mattiagiupponi** [comment]
PR open -> https://github.com/GeoNode/geonode/pull/10906

**Comment by giohappy** [comment]
The issue is rooted in the treebeard library, which is not robust with concurrent updates. The problem is probably caused by the calculation of node paths, which must be executed each time a new node is created, even in case of root nodes.

The problem has been reported in several places. The main issue is stale since years: https://github.com/django-treebeard/django-treebeard/issues/53

Notice that this was also quoted by @capooti in https://github.com/GeoNode/geonode/issues/5406 without a solution.

In the future we should probably consider if another solution should be implemented for the hierarchical keywords, and if haveing a hierarchical model is really worth it.
