### ISSUE TITLE
B/R of Geoserver catalog is broken with Geoserver 2.23.0

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#11081]
## Expected Behavior
GeoNode B/R procedure triggers Geoserver restore and the backup catalog is restored succesfully.

## Actual Behavior
Geoserver restore throws the following exception:

```
WARNING:javax.xml.transform.TransformerException: Can't transform a Source of type javax.xml.transform.stax.StAXSource
org.geoserver.catalog.CatalogException: javax.xml.transform.TransformerException: Can't transform a Source of type javax.xml.transform.stax.StAXSource
	at org.geoserver.backuprestore.BackupRestoreItem.logValidationExceptions(BackupRestoreItem.java:313)
	at org.geoserver.backuprestore.reader.CatalogFileReader.doRead(CatalogFileReader.java:271)
	at org.geoserver.backuprestore.reader.CatalogReader.read(CatalogReader.java:130)
	at org.geoserver.backuprestore.reader.CatalogMultiResourceItemReader.readFromDelegate(CatalogMultiResourceItemReader.java:151)
	at org.geoserver.backuprestore.reader.CatalogMultiResourceItemReader.readNextItem(CatalogMultiResourceItemReader.java:130)
	at org.geoserver.backuprestore.reader.CatalogMultiResourceItemReader.read(CatalogMultiResourceItemReader.java:119)
	at jdk.internal.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:137)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy168.read(Unknown Source)
	at org.springframework.batch.core.step.item.SimpleChunkProvider.doRead(SimpleChunkProvider.java:91)
	at org.springframework.batch.core.step.item.SimpleChunkProvider.read(SimpleChunkProvider.java:157)
	at org.springframework.batch.core.step.item.SimpleChunkProvider$1.doInIteration(SimpleChunkProvider.java:116)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
	at org.springframework.batch.core.step.item.SimpleChunkProvider.provide(SimpleChunkProvider.java:110)
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:69)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:271)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64)
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:67)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:134)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:306)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
	at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:286)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.xml.transform.TransformerException: Can't transform a Source of type javax.xml.transform.stax.StAXSource
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:419)
	at org.geoserver.backuprestore.reader.CatalogFileReader.unmarshal(CatalogFileReader.java:287)
	at org.geoserver.backuprestore.reader.CatalogFileReader.doRead(CatalogFileReader.java:256)
	... 43 more

WARNING:Can't transform a Source of type javax.xml.transform.stax.StAXSource
javax.xml.transform.TransformerException: Can't transform a Source of type javax.xml.transform.stax.StAXSource
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:419)
	at org.geoserver.backuprestore.reader.CatalogFileReader.unmarshal(CatalogFileReader.java:287)
	at org.geoserver.backuprestore.reader.CatalogFileReader.doRead(CatalogFileReader.java:256)
	at org.geoserver.backuprestore.reader.CatalogReader.read(CatalogReader.java:130)
	at org.geoserver.backuprestore.reader.CatalogMultiResourceItemReader.readFromDelegate(CatalogMultiResourceItemReader.java:151)
	at org.geoserver.backuprestore.reader.CatalogMultiResourceItemReader.readNextItem(CatalogMultiResourceItemReader.java:130)
	at org.geoserver.backuprestore.reader.CatalogMultiResourceItemReader.read(CatalogMultiResourceItemReader.java:119)
	at jdk.internal.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:137)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy168.read(Unknown Source)
	at org.springframework.batch.core.step.item.SimpleChunkProvider.doRead(SimpleChunkProvider.java:91)
	at org.springframework.batch.core.step.item.SimpleChunkProvider.read(SimpleChunkProvider.java:157)
	at org.springframework.batch.core.step.item.SimpleChunkProvider$1.doInIteration(SimpleChunkProvider.java:116)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
	at org.springframework.batch.core.step.item.SimpleChunkProvider.provide(SimpleChunkProvider.java:110)
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:69)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:271)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64)
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:67)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:134)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:306)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
	at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:286)
	at java.base/java.lang.Thread.run(Thread.java:829)

WARNING:File (not a directory) at gwc-layers
java.lang.IllegalStateException: File (not a directory) at gwc-layers
	at org.geoserver.platform.resource.FileSystemResourceStore$FileSystemResource.dir(FileSystemResourceStore.java:378)
	at org.geoserver.backuprestore.tasklet.CatalogBackupRestoreTasklet.restoreGwcLayers(CatalogBackupRestoreTasklet.java:1303)
	at org.geoserver.backuprestore.tasklet.CatalogBackupRestoreTasklet.restoreGWCSettings(CatalogBackupRestoreTasklet.java:1269)
	at org.geoserver.backuprestore.tasklet.CatalogBackupRestoreTasklet.restoreGwc(CatalogBackupRestoreTasklet.java:560)
	at org.geoserver.backuprestore.tasklet.CatalogBackupRestoreTasklet.hardRestore(CatalogBackupRestoreTasklet.java:489)
	at org.geoserver.backuprestore.tasklet.CatalogBackupRestoreTasklet.doRestore(CatalogBackupRestoreTasklet.java:396)
	at org.geoserver.backuprestore.tasklet.CatalogBackupRestoreTasklet.doExecute(CatalogBackupRestoreTasklet.java:108)
	at org.geoserver.backuprestore.tasklet.AbstractCatalogBackupRestoreTasklet$4.call(AbstractCatalogBackupRestoreTasklet.java:203)
	at org.geoserver.backuprestore.tasklet.AbstractCatalogBackupRestoreTasklet$4.call(AbstractCatalogBackupRestoreTasklet.java:199)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Maybe related to the issues that are being refactored in https://github.com/geoserver/geoserver/pull/6705

## Steps to Reproduce the Problem

  1. Execute backup of a GeoNode project `./myproject/br/backup.sh`
  2. Execute restore  `./myproject/br/restore.sh`

## Specifications

  - GeoNode version: master (4.1.0)
  - Installation type geonode-project:
  - Installation method: docker

**Comment by giohappy** [comment]
I could reproduce the error with a factory Geoserver build with:

`-T 4 clean install dependency:tree -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.count=100 -Djava.awt.headless=true -Dtest.maxHeapSize=256M -DskipTests -U -PsldService,printing,monitor,control-flow,wps,kmlppio,wps-download,excel,querylayer,gdal,authkey,css,ysld,importer,wmts-multi-dimensional,backup-restore,oauth2-geonode,oauth2-openid-connect,geofence-server,geofence-wps`

**Comment by afabiani** [comment]
PR on GeoServer available [here](https://github.com/geoserver/geoserver/pull/6850)

**Comment by giohappy** [comment]
fixed in https://github.com/geoserver/geoserver/commit/07ac17aa77b59df259ae338d3dfbc6957d239d1c
