### ISSUE TITLE
Uploading dataset fails

### ISSUE THREAD

**Issue by kaloyan13** [GeoNode/geonode#11203]
## Expected Behavior
Data from dataset is uploaded correctly.

## Actual Behavior
After upload we get an error popup with text  'tuple.indexx: x not in tuple'.

## Steps to Reproduce the Problem

  1. Install Geonode 4.1.0 or 4.1.x
  2. Download https://github.com/AcuGIS/GeoSuite/raw/main/data/neighborhoods.zip
  3. Try to upload from "Add Resource -> Upload dataset"

## Specifications

  - GeoNode version: 4.1.0/4.1.x
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): manual
  - Platform: ubuntu 22.04
  - Additional details:
First traceback shows errors due to missing GEODATABASE_URL in local_settings.py. I have pasted it only because it contains message from error popup "tuple.index(x): x not in tuple".
We were able to upload dataset through Geoserver, and after `geonode updatelayers` it was visible in Geonode.

```python
 Starting rollback for execid: 5bc6a15c-e15b-402e-979f-43fc5196391c resource published was: neighborhoods
 Rollback for execid: 5bc6a15c-e15b-402e-979f-43fc5196391c resource published was: neighborhoods completed
 'Settings' object has no attribute 'GEODATABASE_URL'
 tuple.index(x): x not in tuple. Request: 5bc6a15c-e15b-402e-979f-43fc5196391c. Request: 5bc6a15c-e15b-402e-979f-43fc5196391c
 Traceback (most recent call last):
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/handlers/common/vector.py", line 813, in import_with_ogr2ogr
     options = orchestrator.load_handler(handler_module_path).create_ogr2ogr_command(
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/handlers/shapefile/handler.py", line 143, in create_ogr2ogr_command
     base_command = BaseVectorFileHandler.create_ogr2ogr_command(files, original_name, ovverwrite_layer, alternate)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/handlers/common/vector.py", line 149, in create_ogr2ogr_command
     _uri = settings.GEODATABASE_URL.replace("postgis://", "")
   File "/opt/geonode/.venv/lib/python3.10/site-packages/django/conf/__init__.py", line 83, in __getattr__
     val = getattr(self._wrapped, name)
 AttributeError: 'Settings' object has no attribute 'GEODATABASE_URL'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/celery_tasks.py", line 148, in import_resource
     _datastore.start_import(execution_id, **kwargs)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/datastore.py", line 39, in start_import
     return self.handler().import_resource(self.files, execution_id,  **kwargs)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/handlers/common/vector.py", line 350, in import_resource
     raise e
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/handlers/common/vector.py", line 332, in import_resource
     workflow = chord(group_to_call)(
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/canvas.py", line 1377, in __call__
     return self.apply_async((), {'body': body} if body else {}, **options)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/canvas.py", line 1433, in apply_async
     return self.apply(args, kwargs,
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/canvas.py", line 1452, in apply
     args=(tasks.apply(args, kwargs).get(propagate=propagate),),
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/canvas.py", line 1123, in apply
     return app.GroupResult(group_id, [
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/canvas.py", line 1124, in <listcomp>
     sig.apply(args=args, kwargs=kwargs, **options) for sig, _, _ in tasks
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/canvas.py", line 186, in apply
     return self.type.apply(args, kwargs, **options)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/task.py", line 793, in apply
     ret = tracer(task_id, args, kwargs, request)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 468, in trace_task
     I, R, state, retval = on_error(task_request, exc, uuid)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
     R = retval = fun(*args, **kwargs)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/handlers/common/vector.py", line 840, in import_with_ogr2ogr
     raise Exception(e)
 Exception: 'Settings' object has no attribute 'GEODATABASE_URL'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/celery_tasks.py", line 89, in import_orchestrator
     orchestrator.perform_next_step(
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/orchestrator.py", line 157, in perform_next_step
     raise e
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/orchestrator.py", line 147, in perform_next_step
     importer_app.tasks.get(next_step).apply_async(task_params, kwargs)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/task.py", line 572, in apply_async
     return self.apply(args, kwargs, task_id=task_id or uuid(),
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/task.py", line 793, in apply
     ret = tracer(task_id, args, kwargs, request)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 468, in trace_task
     I, R, state, retval = on_error(task_request, exc, uuid)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
     R = retval = fun(*args, **kwargs)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/celery_tasks.py", line 732, in rollback
     handler.rollback(
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/handlers/common/vector.py", line 664, in rollback
     step_index = steps.index(rollback_from_step)
 ValueError: tuple.index(x): x not in tuple
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/celery_tasks.py", line 89, in import_orchestrator
     orchestrator.perform_next_step(
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/orchestrator.py", line 157, in perform_next_step
     raise e
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/orchestrator.py", line 147, in perform_next_step
     importer_app.tasks.get(next_step).apply_async(task_params, kwargs)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/task.py", line 572, in apply_async
     return self.apply(args, kwargs, task_id=task_id or uuid(),
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/task.py", line 793, in apply
     ret = tracer(task_id, args, kwargs, request)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 468, in trace_task
     I, R, state, retval = on_error(task_request, exc, uuid)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
     R = retval = fun(*args, **kwargs)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/celery_tasks.py", line 158, in import_resource
     call_rollback_function(
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/utils.py", line 47, in call_rollback_function
     import_orchestrator.apply_async(task_params, kwargs)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/task.py", line 572, in apply_async
     return self.apply(args, kwargs, task_id=task_id or uuid(),
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/task.py", line 793, in apply
     ret = tracer(task_id, args, kwargs, request)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 468, in trace_task
     I, R, state, retval = on_error(task_request, exc, uuid)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
     R = retval = fun(*args, **kwargs)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/celery_tasks.py", line 100, in import_orchestrator
     raise StartImportException(detail=error_handler(e, execution_id))
 importer.api.exception.StartImportException: tuple.index(x): x not in tuple. Request: 5bc6a15c-e15b-402e-979f-43fc5196391c
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/api/views.py", line 160, in create
     sig.apply_async()
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/canvas.py", line 219, in apply_async
     return _apply(args, kwargs, **options)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/task.py", line 572, in apply_async
     return self.apply(args, kwargs, task_id=task_id or uuid(),
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/task.py", line 793, in apply
     ret = tracer(task_id, args, kwargs, request)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 468, in trace_task
     I, R, state, retval = on_error(task_request, exc, uuid)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
     R = retval = fun(*args, **kwargs)
   File "/opt/geonode/.venv/lib/python3.10/site-packages/importer/celery_tasks.py", line 100, in import_orchestrator
     raise StartImportException(detail=error_handler(e, execution_id))
 importer.api.exception.StartImportException: tuple.index(x): x not in tuple. Request: 5bc6a15c-e15b-402e-979f-43fc5196391c. Request: 5bc6a15c-e15b-402e-979f-43fc5196391c
 Internal Server Error: /api/v2/uploads/upload

```

After that we get the following message in Apache error.log:
```python
The store does not exists: geonode_data creating...
error during publishing: Failed to publish feature type neighborhoods : 500, This is unexpected, the layer seems to be mis-configured
Starting rollback for execid: 0f4854f2-1fd6-49a0-9586-7f6672ea6096 resource published was: neighborhoods
Rollback for execid: 0f4854f2-1fd6-49a0-9586-7f6672ea6096 resource published was: neighborhoods completed
```

**Comment by mattiagiupponi** [comment]
Hi @kaloyan13 
Please be sure that the settings `GEODATABASE_URL` is present, to check if it is available please be sure that the env-var `DEFAULT_BACKEND_DATASTORE` is available (the settings are auto-populated if this variable is enabled)

Anyway @giohappy , here the error looks like how we extract the authority of the layer, we use [two possible approaches](https://github.com/GeoNode/geonode-importer/blob/6cb1137a61b27ac4a49b384a7c9f836d6aaa7efc/importer/handlers/common/vector.py#L247-L259) to extrapolate it and in both cases it return `None:None`

It need an analysis on how to improve the flow

**Comment by kaloyan13** [comment]
GEODATABASE_URL was present, when `error during publishing: Failed to publish feature type neighborhoods : 500, This is unexpected, the layer seems to be mis-configured` appeared.

**Comment by mattiagiupponi** [comment]
Hi @kaloyan13 
I have a potential fix ready, Can you please test it on your instance to see if it works as expected before merging and releasing a new version?

**Comment by kaloyan13** [comment]
Yes.

**Comment by mattiagiupponi** [comment]
Please install fromthis branch and restart geonode:
`pip install -e git+https://github.com/GeoNode/geonode-importer.git@ISSUE_11203#egg=geonode-importer`

**Comment by kaloyan13** [comment]
Fix works on v4.1.0

**Comment by mattiagiupponi** [comment]
Thanks @kaloyan13 i'm going to open the PR for the review and soon we will release a new version for the importer.
Please dont forget to update it in your instance, otherwise u will get an error

**Comment by ricardogsilva** [comment]
@mattiagiupponi 

cc @giohappy 

I was getting hit by the same error on a fresh manual install of geonode 4.1.3 on my dev machine.

After poking around the code, I think the problem, which still persists in the geonode-importer codebase, is that it simply assumes that `settings.GEODATABASE_URL` exists, while that may not be the case. See here:

https://github.com/GeoNode/geonode-importer/blob/c2a4c1e3114842bd79a6b0522dd02f53dfd485c4/importer/handlers/common/vector.py#L156

So geonode-importer tries to use `settings.GEODATABASE_URL`, expecting it to be defined.

However, looking at `geonode.settings` we see that `GEODATABASE_URL` is only defined if the `DEFAULT_BACKEND_DATASTORE` env variable exists:

https://github.com/GeoNode/geonode/blob/9d6a4ca0105db2f4bedab5b844fb7bf33b720dda/geonode/settings.py#L149

This means that it is possible to hit the aforementioned bug by simply not having the `DEFAULT_BACKEND_DATASTORE` environment variable set - which I did not have in my case. Also note that the error is pretty cryptic and gives little clue to what the problem actually is.

In my case I fixed it by defining `GEODATABASE_URL` from the contents of the `settings.DATABASES['datastore']` variable in my `local_settings.py` file, by doing this:

```python
# somewhere below the definition of the DATABASES value
GEODATABASE_URL=(
    f"postgis://{DATABASES['datastore']['USER']}:{DATABASES['datastore']['PASSWORD']}"
    f"@{DATABASES['datastore']['HOST']}:{DATABASES['datastore']['PORT']}/"
    f"{DATABASES['datastore']['NAME']}"
)
```

IMO this is a good fix because the `settings.DATABASES['datastore']` variable already exists and is expected to have a value.

I'm reopening this issue, since it seems to be easy to hit it. Not sure what would be the proper fix though, I guess some options would be:

- Modifying `geonode.settings` to provide a default value of the `GEODATABASE_URL` (similar to my fix above) if this variable is expected to exist by other parts of the code
- Modifying geonode-importer to not assume `GEODATABASE_URL` is defined

**Comment by giohappy** [comment]
hi @ricardogsilva. I agree, `DEFAULT_BACKEND_DATASTORE`  is rarely changed and in 99% of the cases it's assumed to be `datastore`. There are other several variables that could probably be given default values, but this is a good candidate.

It seems that it's only used for settings the settings in the block you mentioned
I would simply give a default value when getting the env var.

https://github.com/GeoNode/geonode/blob/9d6a4ca0105db2f4bedab5b844fb7bf33b720dda/geonode/settings.py#L148-L168

**Comment by giohappy** [comment]
anyway @ricardogsilva I'm going to close this since here there was a different problem that was fixed. 
Please create a new issue specific with your proposal

**Comment by ricardogsilva** [comment]
@giohappy  see #11615
