### ISSUE TITLE
Cannot create custom translation

### ISSUE THREAD

**Issue by syldor** [GeoNode/geonode#11227]
## Expected Behavior
Adding a new folder in locales and refering to it in LANGUAGES should make the language available.

## Actual Behavior
The new language is not available in the dropdown as it is not present in the settings.

![Selection_101](https://github.com/GeoNode/geonode/assets/4158062/7e0f1cd6-8370-46f2-8ada-2bc83605ae75)

## Steps to Reproduce the Problem
In Docker geonode I have a folder with a translation for Lao.

![Selection_095](https://github.com/GeoNode/geonode/assets/4158062/a2b1100f-2869-4f76-aa90-110681b4df04)

It's the english one moved under the name "la".

The command `django-admin compilemessages` shows that everything is compiled and the newly added files are found

 
![Selection_098](https://github.com/GeoNode/geonode/assets/4158062/b78a1fbc-2197-4298-a935-c811df0dc9ba)

The `LANGUAGES` variable is set to

(('en-us','English'),('la','Lao'))

![image](https://github.com/GeoNode/geonode/assets/4158062/d676f976-bfc0-4b0a-90c1-213403e5e775)

Now the dropdown does not show the second language lao. It seems it is removed from the settings.LANGUAGES list:

```
python manage.py diffsettings --all
```

shows that 

```
LANGUAGES = (('en-us', 'English'),)
```

![Selection_100](https://github.com/GeoNode/geonode/assets/4158062/d56061f2-e2b3-498c-938c-b8362aa77501)

Is there a way to have a local translation without relying on the official translations list? I'm willing to share my translations for lao later but I would like to start on a small amount of messages.

## Specifications

  - GeoNode version: 4.1.x
  - Installation type (vanilla, geonode-project): geonode-project
  - Installation method (manual, docker): docker
  - Platform: ubuntu 20.04
  - Additional details:

**Comment by chumano** [comment]
You maybe try to open **settings.py**, then modify as the following:

MAPSTORE_DEFAULT_LANGUAGES = (
        ("de-de", "Deutsch"),
        ("en-us", "English"),
        ("es-es", "Español"),
        ("fr-fr", "Français"),
        ("it-it", "Italiano"),
        # Add your language here <--------------
    )

**Comment by syldor** [comment]
I tried in `_DEFAULT_LANGUAGES` but even putting `('th', 'Thai')` which has a locale does not make it show up.

**Comment by syldor** [comment]
There was a bit of progress thanks to your pointer @chumano. Previously I was not able to use thai language even tough the `th` locale folder existed. Now I can see it, but I still cannot see the lao one. There must be something more to do :thinking: 

```
   MAPSTORE_DEFAULT_LANGUAGES = (
        ("de-de", "Deutsch"),
        ("en-us", "English"),
        ("es-es", "Español"),
        ("fr-fr", "Français"),
        ("it-it", "Italiano"),
        ("th-th", "Thai"),
        ("la-la", "Lao"),
    )
```

![image](https://github.com/GeoNode/geonode/assets/4158062/bcc1f704-dd43-4466-9d84-7629004ae926)

**Comment by syldor** [comment]
Thank you I could see the "Lao" in the dropdown. But when I select it I get 502 Error, there must be something else to update :thinking: 

```
LANGUAGES=(('en-us','English'),('th','Thai'),('it','Italian'),('la','Lao'))
```

![image](https://github.com/GeoNode/geonode/assets/4158062/27bcf4ea-de3c-4962-ace4-b16609ac2623)

![Selection_107](https://github.com/GeoNode/geonode/assets/4158062/a7079522-6359-421f-bcf2-583b1f98e6d8)

**Comment by chumano** [comment]
You should try i18n Locale Identifiers:
("lo-LA","Laos")
("th-TH","Thai") 

Then view log for more error details

**Comment by syldor** [comment]
@chumano logs for the container are empty. Are the usage logs somewhere else?

I do:
```
docker-compose logs -f django
```

![image](https://github.com/GeoNode/geonode/assets/4158062/6c04fa53-63d0-4382-befd-cb217fae8e39)

**Comment by chumano** [comment]
You go into docker container to view geonode log file at
/var/log/geonode.log

**Comment by syldor** [comment]
@chumano when changing the dropdown to Lao, the error seems totally unrelated:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 114, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 153, in handle_uncaught_exception
    return callback(request)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/defaults.py", line 97, in server_error
    return HttpResponseServerError(template.render())
  File "/usr/local/lib/python3.10/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/geonode_mapstore_client/templatetags/get_menu_json.py", line 127, in get_user_menu
    user = context.get('request').user
AttributeError: 'NoneType' object has no attribute 'user'
```

**Comment by chumano** [comment]
I tried to add the languages
![image](https://github.com/GeoNode/geonode/assets/3014969/f0eb89cb-ea6d-4c71-820e-5499adbafcc9)
![image](https://github.com/GeoNode/geonode/assets/3014969/f87e1beb-88d7-4fc9-a5a6-2be1fefee888)

Results:
![image](https://github.com/GeoNode/geonode/assets/3014969/8df14c2d-0db8-475c-ab82-fca6213e94a9)
![image](https://github.com/GeoNode/geonode/assets/3014969/4a8e9f1f-e46a-43ba-9a84-50c088268e4e)

**Comment by syldor** [comment]
@chumano thank you for your help on that.

I launched the container from geonode-project. In `requirements.txt`, I put my own fork of geonode where some translations are modified: https://github.com/1066-DC/geonode

![image](https://github.com/GeoNode/geonode/assets/4158062/64d52152-fd0a-40b0-bf91-a8e6f70d585e)

The locale files are compiled with:

```
django-admin compilemessages
```

I can see the `.mo` files being modified.

However when building the container, it's the old translations that are picked up and not the modifications.

What am I missing here?

On top of that I still have 502 error when modifying the cookie to be `lo-la`, while it's ok when I put `en-us` and even ok when I put a fake one `xx-yy`.
![Selection_125](https://github.com/GeoNode/geonode/assets/4158062/892f6fd6-c031-42aa-8e0c-e1a989269ec2)

![Selection_126](https://github.com/GeoNode/geonode/assets/4158062/b6b62a43-2ddf-4234-8825-0483ba015601)

![Selection_127](https://github.com/GeoNode/geonode/assets/4158062/a8f7b39c-eb89-4f4f-9a48-508a5671b46f)

**Comment by syldor** [comment]
It seems at least I can override the thai translations by putting them in my `geonode-project` and not in `geonode` :hot_face: .

**Comment by syldor** [comment]
Also has to put some translations in `geonode-mapstore-client` otherwise some things are missing:

Italian ok
![Selection_129](https://github.com/GeoNode/geonode/assets/4158062/f315b26e-58e7-49be-b18d-a874e9838d5f)


Thai not ok
![Selection_130](https://github.com/GeoNode/geonode/assets/4158062/3353d0b2-a33f-46d3-8bea-cf11efd921ea)
![Selection_131](https://github.com/GeoNode/geonode/assets/4158062/74abf6b6-634d-495f-9e5e-dcfda18156a0)

**Comment by chumano** [comment]
You should go into docker container then check the translations exist in the folders:
/mnt/volumes/statics/static/mapstore/gn-translations 
/mnt/volumes/statics/static/mapstore/ms-translations

**Comment by chumano** [comment]
> I tried to add the languages
> ![image](https://github.com/GeoNode/geonode/assets/3014969/f0eb89cb-ea6d-4c71-820e-5499adbafcc9)
> ![image](https://github.com/GeoNode/geonode/assets/3014969/f87e1beb-88d7-4fc9-a5a6-2be1fefee888)
> 
> Results:
> ![image](https://github.com/GeoNode/geonode/assets/3014969/8df14c2d-0db8-475c-ab82-fca6213e94a9)
> 
> ![image](https://github.com/GeoNode/geonode/assets/3014969/4a8e9f1f-e46a-43ba-9a84-50c088268e4e)
> 

You need to add "lo" to LANGUAGE_INFO. As I know that Django doesnt support Laos language

**Comment by syldor** [comment]
@chumano Thank you for your patient help, especially considering that I overlooked those 3 lines of codes that you provided in the screenshot and that were key to the solution:

```
import django.conf.locale
LANG_INFO = dict(django.conf.locale.LANG_INFO, **EXTRA_LANG_INFO)
django.conf.locale.LANG_INFO = LANG_INFO
```

Maybe it would be nice to be able to add extra languages in `geonode-project` instead of having to modify `geonode`, it seems to be a need as another issue was filled this week https://github.com/GeoNode/geonode/issues/11235

I'm closing down this issue if I'm allowed to.
