### ISSUE TITLE
docker.io/geonode:latest-ubuntu-22.10 pod not starting

### ISSUE THREAD

**Issue by rkhandha** [GeoNode/geonode#11326]
## Expected Behavior
- Pod to start and able to access goenode application

## Actual Behavior
- Pod fails to restart 

## Steps to Reproduce the Problem

  1. Deploy the image in Openshift docker.io/geonode:latest-ubuntu-22.10  pod has to run as non root user. 
  2. Pod does not start gives below errors 
  3.

## Specifications

  - GeoNode version:
  - Installation type (vanilla, geonode-project):  Docker version  docker.io/geonode:latest-ubuntu-22.10
  - Installation method (manual, docker):
  - Platform: Openshift
  - Additional details:
  - I am deploying the image in Openshift using Kubernetes deployment.  My Pod does not start and gives below error 
  
 * Starting periodic command scheduler cron
cron: can't open or create /var/run/crond.pid: Permission denied
   ...fail!
Restarting memcached: Only root wants to run start-memcached.
memcached.
\n\n\n
-----------------------------------------------------
STARTING DJANGO ENTRYPOINT Fri Aug  4 19:18:52 UTC 2023
-----------------------------------------------------
/usr/lib/python3/dist-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,

/usr/lib/python3/dist-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
**************************update geoip*******************************
/usr/local/bin/django-admin.py:17: RemovedInDjango40Warning: django-admin.py is deprecated in favor of django-admin.
  warnings.warn(
/usr/lib/python3/dist-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Traceback (most recent call last):
  - Traceback (most recent call last):
  File "/usr/local/bin/django-admin.py", line 21, in <module>
    management.execute_from_command_line()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/src/geonode/geonode/monitoring/management/commands/updategeoip.py", line 61, in handle
    r = requests.get(options['url'], stream=True, timeout=10, verify=False)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='build.geo-solutions.it', port=443): Max retries exceeded with url: /geonode/geoserver/latest/GeoLite2-City.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f552eb03850>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

https://github.com/GeoNode/geonode/issues/7852

**Comment by giohappy** [comment]
@rkhandha thanks for reporting this. We're aware of this issue, although it never blocked our deployments with Docker. 
There are plans to remove the geoip2 autoupdate, along with the refactoring of the monitoring module. This module is not reliable at the moment and it should be turned off.
Can you please try setting `MONITORING_ENABLED=False` in your dotenv file. This has been set to `False` everywhere except the default .env file which, by the way, will change soon (see [this PR](https://github.com/GeoNode/geonode/pull/11308/files#diff-d193984accad3db7674efa2ff485bcac11874023c56b7197de88a406a5288431L185) which is under review)

**Comment by giohappy** [comment]
Issue created https://github.com/GeoNode/geonode/issues/11332

**Comment by giohappy** [comment]
Monitoring disabled on 4.1.x https://github.com/GeoNode/geonode/pull/11334

**Comment by rkhandha** [comment]
Thank you very much that worked,  I do not see those errors.  Pod is still failing with below errors

- Cron error,  we have to run the container as nonroot. 

  * Restarting periodic command scheduler cron
  * Stopping periodic command scheduler cron
  ...done.
  * Starting periodic command scheduler cron
   cron: can't open or create /var/run/crond.pid: Permission denied
   ...fail!
   Restarting memcached: Only root wants to run start-memcached.
  memcached.
   \n\n\n

-  blowfish deprecated error and connections error  
- 
   [31m  Your models in app(s): 'ratings' have changes that are not yet reflected in a migration, and so won't be applied.[0m
[31m  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.[0m
/usr/lib/python3/dist-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Unknown command: 'rebuild_index'
Type 'manage.py help' for usage.
migrations tasks done
/usr/lib/python3/dist-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/docker/transport/unixconn.py", line 27, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/docker/transport/unixconn.py", line 27, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/geonode/tasks.py", line 470, in _docker_host_ip
    ip_list = client.containers.run(BOOTSTRAP_IMAGE_CHEIP, network_mode="host").split("\n")
  File "/usr/local/lib/python3.10/dist-packages/docker/models/containers.py", line 858, in run
    container = self.create(image=image, command=command,
  File "/usr/local/lib/python3.10/dist-packages/docker/models/containers.py", line 917, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/docker/api/container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
  File "/usr/local/lib/python3.10/dist-packages/docker/api/container.py", line 447, in create_container_from_config
    res = self._post_json(u, data=config, params=params)
  File "/usr/local/lib/python3.10/dist-packages/docker/api/client.py", line 296, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/docker/api/client.py", line 233, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

**Comment by rkhandha** [comment]
Sorry closed it by mistake

**Comment by rkhandha** [comment]
It seems this error is caused by invoke update in entrypoint.sh.  How do I fix this?

**Comment by giohappy** [comment]
The `update` task `[uses docker](https://github.com/GeoNode/geonode-demo/blob/development/src/tasks.py#L305)` to query the internal IP. Maybe your deployment/environment doesn't allow it?
In that case you have to replace that logic with something that works for you. As I said in https://github.com/GeoNode/geonode/issues/11388 GeoNode doesn't offer official support for k8s and OpenShift at the moment, but it would be great if anyone could make contributions on the topic.

**Comment by rkhandha** [comment]
Thank you for your response.  The above issue was combination of permission issue, I fixed it by giving rwx permission to the group on some of the directories.  And the pod name needed to be geonode don't understand that piece. 

 I have this up and running now and below is the log information.  So now next problem I am not able access geonde admin page.   
 I see Setting GeoServer Admin Password...
Response Code: 200
GeoServer admin password updated SUCCESSFULLY!
geoserverfixture tasks done
Executing UWSGI server uwsgi --ini /usr/src/geonode/uwsgi.ini for Production
-----------------------------------------------------
FINISHED DJANGO ENTRYPOINT --------------------------
-----------------------------------------------------
got command uwsgi --ini /usr/src/geonode/uwsgi.ini

Below is my configuration 

  SITEURL: https://geonode.xxx.com/
  ALLOWED_HOSTS: '[''geonode.xxx.com'', ]'  
  GEONODE_LB_HOST_IP: geonode.xxx.com
  GEONODE_LB_PORT: "8000"

I still have long way to go to see if this will work.  Any help is appreciated.

**Comment by rkhandha** [comment]
This got fixed by the new docker image  geonode/geonode:latest-ubuntu-22.10 and using .env_dev environment file.
