### ISSUE TITLE
`ProfileCreationForm.clean_username()` is broken, yet also useless

### ISSUE THREAD

**Issue by fvicent** [GeoNode/geonode#11381]
## Actual Behavior

When creating a new user at `/admin/people/profile/add/`, submitting an existing name raises an internal server error.

## Expected Behavior

The form should fail with a readable message:

![imagen](https://github.com/GeoNode/geonode/assets/26927473/9690478f-7bc7-4a14-a5f1-7ad35bea40c4)

## Steps to Reproduce the Problem

  1. Log in as admin
  2. Go to `/admin/people/profile/add/`
  3. Try to create a new user with an existing username (e.g., admin)

The full traceback is:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/src/geonode/./geonode/people/admin.py", line 153, in add_view
    return super().add_view(request, form_url, extra_context)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/options.py", line 1657, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/options.py", line 1579, in _changeform_view
    form_validated = form.is_valid()
  File "/usr/local/lib/python3.10/dist-packages/django/forms/forms.py", line 175, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.10/dist-packages/django/forms/forms.py", line 170, in errors
    self.full_clean()
  File "/usr/local/lib/python3.10/dist-packages/django/forms/forms.py", line 372, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.10/dist-packages/django/forms/forms.py", line 393, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()
  File "/usr/src/geonode/./geonode/people/forms.py", line 55, in clean_username
    self.error_messages["duplicate_username"],
KeyError: 'duplicate_username'
```

The problem is that `ProfileCreationForm` does not define this `"duplicate_username"` key:

https://github.com/GeoNode/geonode/blob/3fa9a8690f4aa27282cd815224014bb6cbc6fb00/geonode/people/forms.py#L41-L57

However, the `clean_username()` method is not required at all. It seems that Django is already able to produce a good error message as shown in the image above after removing this method. This might had some sense in older versions, I guess.

## Specifications

  - GeoNode version: 4.1.0-dev
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): docker
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
@fvicent good point. Could you open a PR with a fix?
