### ISSUE TITLE
Question: GeoServer importing

### ISSUE THREAD

**Issue by IceflowRE** [GeoNode/geonode#11740]
I try to import thousands of layers from a geoserver, with `python manage.py updatelayers -w geodata --remove-deleted --ignore-errors -v 3`

- ignore-errors is added because 
i get those errors while inspecting the available layers in GeoServer.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/geoserver/catalog.py", line 261, in parse_or_raise
    return XML(xml)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1342, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 38, column 45
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/geoserver/support.py", line 83, in getter
    self.fetch()
  File "/usr/local/lib/python3.10/dist-packages/geoserver/support.py", line 328, in fetch
    self.dom = self.catalog.get_xml(self.href)
  File "/usr/local/lib/python3.10/dist-packages/geoserver/catalog.py", line 277, in get_xml
    return parse_or_raise(content)
  File "/usr/src/geonode/geonode/geoserver/helpers.py", line 650, in <listcomp>
  File "/usr/src/geonode/geonode/geoserver/helpers.py", line 650, in <listcomp>
  File "/usr/src/geonode/geonode/geoserver/helpers.py", line 650, in <listcomp>
  File "/usr/src/geonode/geonode/geoserver/helpers.py", line 650, in <listcomp>
  File "/usr/src/geonode/geonode/geoserver/helpers.py", line 650, in <listcomp>
  File "/usr/src/geonode/geonode/geoserver/helpers.py", line 650, in <listcomp>
  File "/usr/src/geonode/geonode/geoserver/helpers.py", line 650, in <listcomp>
    resources_for_delete_compare = [k for k in resources_for_delete_compare if k.enabled in {"true", True}]
  File "/usr/src/geonode/geonode/geoserver/helpers.py", line 650, in <listcomp>
    resources_for_delete_compare = [k for k in resources_for_delete_compare if k.enabled in {"true", True}]
  File "/usr/src/geonode/geonode/geoserver/helpers.py", line 650, in <listcomp>
  File "/usr/src/geonode/geonode/geoserver/helpers.py", line 650, in <listcomp>
    resources_for_delete_compare = [k for k in resources_for_delete_compare if k.enabled in {"true", True}]
  File "/usr/local/lib/python3.10/dist-packages/geoserver/support.py", line 92, in getter
    raise AttributeError(e)
AttributeError: ('GeoServer gave non-XML response for [GET http://geoserver:8080/geoserver/rest/workspaces/geodata/datastores/geoportal_umwelt_sachsen_de_arcgis_services_geologie_rohstoffe_MapServer_WFSServer_/featuretypes/rohstoffe%3AKarbonatgesteine.xml]: <featureType>\n  <name>rohstoffe:Karbonatgesteine</name>\n  <nativeName>rohstoffe_Karbonatgesteine</nativeName>\n  <namespace>\n    <name>geodata</name>\n    <atom:link xmlns:atom="http://www.w3.org/2005/Atom" rel="alternate" href="http://geoserver:8080/geoserver/rest/namespaces/geodata.xml" type="application/xml"/>\n  </namespace>\n  <title>Karbonatgesteine</title>\n  <srs>EPSG:25833</srs>\n  <nativeBoundingBox>\n    <minx>271805.2692038624</minx>\n    <maxx>503019.93322461506</maxx>\n    <miny>5556538.181396301</miny>\n    <maxy>5732972.72581714</maxy>\n    <crs class="projected">EPSG:25833</crs>\n  </nativeBoundingBox>\n  <latLonBoundingBox>\n    <minx>11.697509664157439</minx>\n    <maxx>15.04374439744758</maxx>\n    <miny>50.11716668722052</miny>\n    <maxy>51.747650830287185</maxy>\n    <crs>EPSG:4326</crs>\n  </latLonBoundingBox>\n  <projectionPolicy>FORCE_DECLARED</projectionPolicy>\n  <enabled>true</enabled>\n  <store class="dataStore">\n    <name>geodata:geoportal_umwelt_sachsen_de_arcgis_services_geologie_rohstoffe_MapServer_WFSServer_</name>\n    <atom:link xmlns:atom="http://www.w3.org/2005/Atom" rel="alternate" href="http://geoserver:8080/geoserver/rest/workspaces/geodata/datastores/geoportal_umwelt_sachsen_de_arcgis_services_geologie_rohstoffe_MapServer_WFSServer_.xml" type="application/xml"/>\n  </store>\n  <serviceConfiguration>false</serviceConfiguration>\n  <maxFeatures>0</maxFeatures>\n  <numDecimals>0</numDecimals>\n  <padWithZeros>false</padWithZeros>\n  <forcedDecimal>false</forcedDecimal>\n  <overridingServiceSRS>false</overridingServiceSRS>\n  <skipNumberMatched>false</skipNumberMatched>\n  <circularArcPresent>false</circularArcPresent>\n  <attributesjava.net.SocketTimeoutException: Read timed out', ParseError('not well-formed (invalid token): line 38, column 45'))
```

Later on, while processing i get a lot of the following errors.

```
Error setting default style "mdhwfs:baustellen_sperrungen" for layer "mdhwfs:baustellen_sperrungen
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/geoserver/helpers.py", line 1160, in set_styles
    gs_catalog.save(gs_dataset)
  File "/usr/local/lib/python3.10/dist-packages/geoserver/catalog.py", line 302, in save
    data = obj.message()
  File "/usr/local/lib/python3.10/dist-packages/geoserver/support.py", line 309, in message
    self.serialize_all(builder)
  File "/usr/local/lib/python3.10/dist-packages/geoserver/support.py", line 304, in serialize_all
    self.serialize(builder)
  File "/usr/local/lib/python3.10/dist-packages/geoserver/support.py", line 294, in serialize
    writer(builder, val)
  File "/usr/local/lib/python3.10/dist-packages/geoserver/layer.py", line 103, in _write_default_style
    _write_style_element(builder, name)
  File "/usr/local/lib/python3.10/dist-packages/geoserver/layer.py", line 90, in _write_style_element
    ws, name = name.split(":") if ":" in name else (None, name)
ValueError: too many values to unpack (expected 2)
Could not clean style for layer mdhwfs:baustellen_sperrungen
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/geoserver/helpers.py", line 1135, in clean_styles
    gs_catalog.delete(style, purge=True, recurse=False)
  File "/usr/local/lib/python3.10/dist-packages/geoserver/catalog.py", line 240, in delete
    raise FailedRequestError(
geoserver.catalog.FailedRequestError: Failed to make DELETE request: 403, <!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:whi
te;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1><
hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Can&#39;t delete style referenced by existing layers.</p><p><b>Description</b> The server understood the request but refuses to authorize it.</p><hr class="line" /><h3>Apache Tomcat/9.0.82</h3></body></html>
Error 401 reading Style Filter Params GeoWebCache at http://geoserver:8080/geoserver/gwc/rest/layers/geodata:mdhwfs:baustellen_sperrungen.xml
```

Can those erros be ignored?
If the general import time per dataset is not around 45 seconds, those errors are slowing down a lot.

The dataset is not shown correctly in the end:
![grafik](https://github.com/GeoNode/geonode/assets/10883690/92e55dd9-47a2-4cd0-92f7-45cc990ce875)

If you need more informations feel open to ask.

**Comment by giohappy** [comment]
@IceflowRE which version of GeoNode? Is is vanilla GeoNode or a project?

**Comment by IceflowRE** [comment]
> @IceflowRE which version of GeoNode? Is is vanilla GeoNode or a project?

Vanilla GeoNode with Docker. But iam unable to assist further, my company went with a custom solution, which reduced the import time by 97%, and stepped back from GeoNode.
