### ISSUE TITLE
Broken parsing of options in backup script (3.3.x)

### ISSUE THREAD

**Issue by miceno** [GeoNode/geonode#11789]
## Expected Behavior

According to the documentation, you can create a backup that includes the raster and/or vector data from geoserver by configuring the ini file  by setting up keys "geoserver.dumpvectordata" and "geoserver.dumprasterdata".

While running a backup to include geoserver raster or vector data, the script includes in the backup the corresponding layers.

This is the settings file:
```ini
[database]
pgdump = pg_dump
pgrestore = pg_restore

[geoserver]
datadir = geoserver/data
# datadir_exclude_file_path = {comma separated list of paths to exclude from geoserver catalog} e.g.: /data,/data/geonode,/geonode
dumpvectordata = yes
dumprasterdata = yes
# data_dt_filter = {cmp_operator} {ISO8601} e.g. > 2019-04-05T24:00
# data_layername_filter = {comma separated list of layernames, optionally with glob syntax} e.g.: tuscany_*,
# data_layername_exclude_filter = {comma separated list of layernames, optionally with glob syntax} e.g.: tuscany_*,italy

```

For example:
```
python3 -W ignore manage.py backup --backup-dir /opt/geonode-3.3.x/backup -c /opt/geonode-3.3.x/geonode/br/management/commands/settings.ini --ignore-errors -f --dump-geoserver-vector-data --dump-geoserver-raster-data

Before proceeding with the Backup, please ensure that:
 1. The backend (DB or whatever) is accessible and you have rights
 2. The GeoServer is up and running and reachable from this machine
STARTED - 1/11
STARTED - 7/11
COMPLETED - 11/11
Dumping existing GeoServer Vectorial Data: ['XXX']
Dump Table: geonode_data:XXX
Saved Media Files from '/opt/geonode-3.3.x/geonode/uploaded'.
Saved Static Root from '/opt/geonode-3.3.x/geonode/static_root'.
Saved Static Files from '/opt/geonode-3.3.x/geonode/static'.
Saved Template Files from '/opt/geonode-3.3.x/geonode/templates'.
Backup Finished. Archive generated.
```

## Actual Behavior

An error arise on parsing the options:

```command
python3 -W ignore manage.py backup --backup-dir /opt/geonode-3.3.x/backup -c /opt/geonode-3.3.x/geonode/br/management/commands/settings.ini --ignore-errors -f --dump-geoserver-vector-data --dump-geoserver-raster-data
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/geonode/venv/geonode-3.3.x/lib64/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_
command_line
    utility.execute()
  File "/home/geonode/venv/geonode-3.3.x/lib64/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/geonode/venv/geonode-3.3.x/lib64/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/geonode/venv/geonode-3.3.x/lib64/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/geonode-3.3.x/geonode/br/management/commands/backup.py", line 111, in handle
    self.execute_backup(**options)
  File "/opt/geonode-3.3.x/geonode/br/management/commands/backup.py", line 122, in execute_backup
    config = utils.Config(options)
  File "/opt/geonode-3.3.x/geonode/br/management/commands/utils/utils.py", line 96, in __init__
    self.load_options(options)
  File "/opt/geonode-3.3.x/geonode/br/management/commands/utils/utils.py", line 113, in load_options
    self.config_parser['geoserver']['dumprasterdata'] = self.gs_dump_raster_data
  File "/usr/lib64/python3.8/configparser.py", line 1258, in __setitem__
    self._parser._validate_value_types(option=key, value=value)
  File "/usr/lib64/python3.8/configparser.py", line 1185, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
```

## Steps to Reproduce the Problem

  1. configure backup to include "geoserver.dumpvectordata" and "geoserver.dumprasterdata" set to "yes".
  2. run a backup with options "--dump-geoserver-vector-data" and "--dump-geoserver-raster-data"
  3. the backup fails.

## Specifications

  - GeoNode version: 3.3.x
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): manual
  - Platform: Linux Almalinux 8

**Comment by miceno** [comment]
The following patch solved the issue, but not quite sure if it is the right way to solve it:
```patch
diff --git a/geonode/br/management/commands/utils/utils.py b/geonode/br/management/commands/utils/utils.py
index e226c33..77a12c6 100644
--- a/geonode/br/management/commands/utils/utils.py
+++ b/geonode/br/management/commands/utils/utils.py
@@ -104,12 +104,12 @@ class Config:
         if options.get("dump_gs_vector_data", None) is not None:
             self.gs_dump_vector_data = options.get("dump_gs_vector_data")
             if self.config_parser:
-                self.config_parser['geoserver']['dumpvectordata'] = self.gs_dump_vector_data
+                self.config_parser['geoserver']['dumpvectordata'] = str(self.gs_dump_vector_data)
 
         if options.get("dump_gs_raster_data", None) is not None:
             self.gs_dump_raster_data = options.get("dump_gs_raster_data")
             if self.config_parser:
-                self.config_parser['geoserver']['dumprasterdata'] = self.gs_dump_raster_data
+                self.config_parser['geoserver']['dumprasterdata'] = str(self.gs_dump_raster_data)
 
     def load_settings(self, settings_path):
 
```

**Comment by giohappy** [comment]
version 3.3.x is not receiving support anymore.
