### ISSUE TITLE
Bad syntax on regular expression at proxy views on python 3.11

### ISSUE THREAD

**Issue by miceno** [GeoNode/geonode#11788]
## Expected Behavior

On a python 3.11 virtualenv, running command `python manage.py` should return the list of available commands:
```
(geonode-4-master-py311) [geonode@server geonode-src]$ python manage.py

Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

[account]
    account_unsetmultipleprimaryemails

...

[tastypie]
    backfill_api_keys

```

## Actual Behavior

An error rises when compiling a regular expression that does not use the new syntax for global flags [see here](https://docs.python.org/3/whatsnew/3.11.html#porting-to-python-3-11):
```command
(geonode-4-master-py311) [geonode@server geonode-src]$ python manage.py
Traceback (most recent call last):
  File "/home/geonode/geonode-src/manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/geonode/venv/geonode-4-master-py311/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/geonode/venv/geonode-4-master-py311/lib/python3.11/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/home/geonode/venv/geonode-4-master-py311/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/geonode/venv/geonode-4-master-py311/lib/python3.11/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/geonode/geonode-src/geonode/harvesting/apps.py", line 31, in ready
    from geonode.urls import urlpatterns
  File "/home/geonode/geonode-src/geonode/urls.py", line 33, in <module>
    import geonode.proxy.urls
  File "/home/geonode/geonode-src/geonode/proxy/urls.py", line 22, in <module>
    from . import views
  File "/home/geonode/geonode-src/geonode/proxy/views.py", line 70, in <module>
    ows_regexp = re.compile(r"^(?i)(version)=(\d\.\d\.\d)(?i)&(?i)request=(?i)(GetCapabilities)&(?i)service=(?i)(\w\w\w)$")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_parser.py", line 982, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_parser.py", line 457, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_parser.py", line 843, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 1

```

## Steps to Reproduce the Problem

  1. create a python 3.11 virtualenv
  2. install geonode on the new virtualenv
  3. run command `python manage.py`

## Specifications

  - GeoNode version: master (sha:a42f9f2426de444d51ab12046452893679d5803f)
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): manual
  - Platform: Almalinux 9.3

**Comment by miceno** [comment]
I have patched it temporarily to allow me to continue with the setup.

Here it is the patch:

```patch
diff --git a/geonode/proxy/views.py b/geonode/proxy/views.py
index fc49163f0..30e112b2a 100644
--- a/geonode/proxy/views.py
+++ b/geonode/proxy/views.py
@@ -23,6 +23,7 @@ import gzip
 import logging
 import traceback
 import zipstream
+import sys
 
 from hyperlink import URL
 from urllib.parse import urlparse, urlsplit, urljoin
@@ -63,7 +64,10 @@ LINK_TYPES = [L for L in _LT if L.startswith("OGC:")]
 logger = logging.getLogger(__name__)
 
 
-ows_regexp = re.compile(r"^(?i)(version)=(\d\.\d\.\d)(?i)&(?i)request=(?i)(GetCapabilities)&(?i)service=(?i)(\w\w\w)$")
+if sys.version_info > (3,10):
+   ows_regexp = re.compile(r"(?i)^(version)=(\d\.\d\.\d)&request=(GetCapabilities)&service=(\w\w\w)$")
+else:
+   ows_regexp = re.compile(r"^(?i)(version)=(\d\.\d\.\d)(?i)&(?i)request=(?i)(GetCapabilities)&(?i)service=(?i)(\w\w\w)$")
 
 
 @requires_csrf_token

```

**Comment by giohappy** [comment]
@miceno you didn't mention the version, but in master branch it's already fixed:

https://github.com/GeoNode/geonode/blob/a42f9f2426de444d51ab12046452893679d5803f/geonode/proxy/views.py#L65-L67
