### ISSUE TITLE
Paver sync: ModuleNotFoundError: No module named 'importer.handlers'

### ISSUE THREAD

**Issue by Junichi2000** [GeoNode/geonode#11860]
Installing Geonode 4.2.x on Winodws 10 using Ubuntu WSL referring 'https://docs.geonode.org/en/master/install/advanced/core/index.html' document.
Facing error on running '**./paver_local.sh sync**' command. Please see the steps I followed. How to fix this ?
++++++++++++++++++++++++++++++++++++++
Geoserver is running on 'localhost:8080'
- GDAL 3.4.1, released 2021/12/27
- Python 3.10.12
- Git Branch (Geonode version): * 4.2.x
- Installation method: manual (Not using Docker)

++++++++++++++++++++++++++++++++++++++
Initialize GeoNode
++++++++++++++++++++++++++++++++++++++
STEP 1:
(geonode) ubuntuadmin@DESKTOP-9PHKC8E:/opt/geonode$ chmod +x *.sh
++++++++++++++++++++++++++++++++++++++
STEP 2:
(geonode) ubuntuadmin@DESKTOP-9PHKC8E:/opt/geonode$ ./paver_local.sh reset
---> pavement.reset
---> pavement.stop
---> pavement.stop_geoserver
Stopping java (process number 268)
Stopping java (process number 268)
Stopping java (process number 268)

Captured Task Output:

---> pavement.reset
---> pavement.stop
---> pavement.stop_geoserver
Stopping java (process number 268)
Stopping java (process number 268)
Stopping java (process number 268)
Stopping java (process number 268)
Traceback (most recent call last):
  File "/home/ubuntuadmin/.virtualenvs/geonode/lib/python3.10/site-packages/paver/tasks.py", line 201, in _run_task
    return do_task()
  File "/home/ubuntuadmin/.virtualenvs/geonode/lib/python3.10/site-packages/paver/tasks.py", line 197, in do_task
    task()
  File "/home/ubuntuadmin/.virtualenvs/geonode/lib/python3.10/site-packages/paver/tasks.py", line 333, in __call__
    retval = environment._run_task(self.name, self.needs, self.func)
  File "/home/ubuntuadmin/.virtualenvs/geonode/lib/python3.10/site-packages/paver/tasks.py", line 219, in _run_task
    return do_task()
  File "/home/ubuntuadmin/.virtualenvs/geonode/lib/python3.10/site-packages/paver/tasks.py", line 197, in do_task
    task()
  File "/home/ubuntuadmin/.virtualenvs/geonode/lib/python3.10/site-packages/paver/tasks.py", line 333, in __call__
    retval = environment._run_task(self.name, self.needs, self.func)
  File "/home/ubuntuadmin/.virtualenvs/geonode/lib/python3.10/site-packages/paver/tasks.py", line 219, in _run_task
    return do_task()
  File "/home/ubuntuadmin/.virtualenvs/geonode/lib/python3.10/site-packages/paver/tasks.py", line 198, in do_task
    return func(**kw)
  File "pavement.py", line 457, in stop_geoserver
    kill("java", "geoserver")
  File "pavement.py", line 1075, in kill
    raise Exception(f"Could not stop {arg1}: " f"Running processes are\n{_procs}")
Exception: Could not stop java: Running processes are
b'tomcat       268  7.8 12.0 4875424 974584 ?      Sl   09:46   2:48 /usr/lib/jvm/java-11-openjdk-amd64//bin/java -Djava.util.logging.config.file=/opt/tomcat/apache-tomcat-9.0.83/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -server -Djava.awt.headless=true -Dorg.geotools.shapefile.datetime=false -DGS-SHAPEFILE-CHARSET=UTF-8 -XX:+UseParallelGC -XX:ParallelGCThreads=4 -Dfile.encoding=UTF8 -Duser.timezone=UTC -Xms512m -Xmx4096m -Djavax.servlet.request.encoding=UTF-8 -Djavax.servlet.response.encoding=UTF-8 -DGEOSERVER_CSRF_DISABLED=true -DPRINT_BASE_URL=http://localhost:8080/geoserver/pdf -DGEOSERVER_DATA_DIR=/opt/data/geoserver_data -Dgeofence.dir=/opt/data/geoserver_data/geofence -DGEOSERVER_LOG_LOCATION=/opt/data/geoserver_logs/geoserver.log -DGEOWEBCACHE_CACHE_DIR=/opt/data/gwc_cache_dir -Dgwc.context.suffix=gwc -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Xms512M -Xmx1024M -server -XX:+UseParallelGC -Dignore.endorsed.dirs= -classpath /opt/tomcat/apache-tomcat-9.0.83/bin/bootstrap.jar:/opt/tomcat/apache-tomcat-9.0.83/bin/tomcat-juli.jar -Dcatalina.base=/opt/tomcat/apache-tomcat-9.0.83 -Dcatalina.home=/opt/tomcat/apache-tomcat-9.0.83 -Djava.io.tmpdir=/opt/tomcat/apache-tomcat-9.0.83/temp org.apache.catalina.startup.Bootstrap start\n'
b'ubuntua+   71374  0.0  0.0   2900   984 pts/0    S+   10:22   0:00 /bin/sh -c ps aux | grep java\n'
b'ubuntua+   71376  0.0  0.0   4036  2104 pts/0    S+   10:22   0:00 grep java\n'
++++++++++++++++++++++++++++++++++++++
STEP 3:
(geonode) ubuntuadmin@DESKTOP-9PHKC8E:/opt/geonode$ ./paver_local.sh setup
---> pavement.setup
---> pavement.setup_geoserver
/home/ubuntuadmin/.virtualenvs/geonode/lib/python3.10/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'artifacts.geonode.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
161793KB [01:20, 2001.35KB/s]
/home/ubuntuadmin/.virtualenvs/geonode/lib/python3.10/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'repo1.maven.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
8880KB [00:03, 2375.79KB/s]
/home/ubuntuadmin/.virtualenvs/geonode/lib/python3.10/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'artifacts.geonode.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
167KB [00:00, 403.45KB/s]
GeoNode development environment successfully set up.If you have not set up an administrative account, please do so now. Use "paver start" to start up the server.
++++++++++++++++++++++++++++++++++++++
STEP 4:
(geonode) ubuntuadmin@DESKTOP-9PHKC8E:/opt/geonode$ ./paver_local.sh sync
---> pavement.sync
 python -W ignore manage.py makemigrations --noinput
Traceback (most recent call last):
  File "/opt/geonode/manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntuadmin/.virtualenvs/geonode/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/ubuntuadmin/.virtualenvs/geonode/lib/python3.10/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/home/ubuntuadmin/.virtualenvs/geonode/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntuadmin/.virtualenvs/geonode/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/ubuntuadmin/.virtualenvs/geonode/lib/python3.10/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
**ModuleNotFoundError: No module named 'importer.handlers'**

Captured Task Output:

---> pavement.sync
 python -W ignore manage.py makemigrations --noinput

Build failed running pavement.sync: Subprocess return code: 1
++++++++++++++++++++++++++++++++++++++
(geonode) ubuntuadmin@DESKTOP-9PHKC8E:/opt/geonode$ pip install handler
Requirement already satisfied: handler in

**Comment by mattiagiupponi** [comment]
`pip install geonode-importer==1.0.6` should fix the issue

**Comment by Junichi2000** [comment]
Thanks for reply. Still same issue.

(geonode) ubuntuadmin@DESKTOP-9PHKC8E:/opt/geonode$ pip install geonode-importer==1.0.6
Requirement already satisfied: geonode-importer==1.0.6 in /home/ubuntuadmin/.virtualenvs/geonode/src/geonode-importer (1.0.6)

**Comment by giohappy** [comment]
Closing as part of a repository cleanup: this issue was last updated before 2025-01-01. Not a judgment on the report itself — feel free to reopen or file a fresh issue against `main` if it's still relevant. Thanks for the report.
