### ISSUE TITLE
Unable to share layer with another user or group - geoserver could not find existing layer

### ISSUE THREAD

**Issue by vidlb** [GeoNode/geonode#11973]
## Expected Behavior
A layer should be visible by other users when shared with a user or group

## Actual Behavior
My layer is only visible for the user who uploaded it. Allowing view for the "registered members" group does not work, same thing if I create a rule to share with a specific user.

## Steps to Reproduce the Problem

  1. Upload a dataset
  2. Allow registered members to view
  3. Login with another user than the dataset owner, and try to query data
  4. Geoserver thow errors "could not find layer", even though it exists

First I thought this was due to https://github.com/GeoNode/geonode/issues/11447 but this is not working even after updating to latest.  
@giohappy any ideas ?

## Specifications

  - GeoNode version: 4.2.2
  - Installation type : geonode-project 
  - Installation method : docker
  - Platform: ubuntu
  - Additional details:

Geoserver log :  
```
geoserver4geonode_forcut    | 20 Feb 10:37:49 ERROR  [geoserver.ows] - 
geoserver4geonode_forcut    | org.geoserver.platform.ServiceException: Could not find layer geonode:tiles_clip_snap
geoserver4geonode_forcut    |   at org.geoserver.wms.map.GetMapKvpRequestReader.parseLayers(GetMapKvpRequestReader.java:1546)
geoserver4geonode_forcut    |   at org.geoserver.wms.map.GetMapKvpRequestReader.read(GetMapKvpRequestReader.java:361)
geoserver4geonode_forcut    |   at org.geoserver.wms.map.GetMapKvpRequestReader.read(GetMapKvpRequestReader.java:107)
geoserver4geonode_forcut    |   at org.geoserver.ows.Dispatcher.parseRequestKVP(Dispatcher.java:1509)
geoserver4geonode_forcut    |   at org.geoserver.ows.Dispatcher.dispatch(Dispatcher.java:682)
geoserver4geonode_forcut    |   at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:258)
geoserver4geonode_forcut    |   at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
geoserver4geonode_forcut    |   at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:51)
geoserver4geonode_forcut    |   at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
geoserver4geonode_forcut    |   at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
geoserver4geonode_forcut    |   at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
geoserver4geonode_forcut    |   at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
geoserver4geonode_forcut    |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
geoserver4geonode_forcut    |   at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
geoserver4geonode_forcut    |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
geoserver4geonode_forcut    |   at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
geoserver4geonode_forcut    |   at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:331)
geoserver4geonode_forcut    |   at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:158)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
geoserver4geonode_forcut    |   at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
geoserver4geonode_forcut    |   at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:73)
geoserver4geonode_forcut    |   at org.geoserver.monitor.MonitorFilter.doFilter(MonitorFilter.java:159)
geoserver4geonode_forcut    |   at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
geoserver4geonode_forcut    |   at org.geoserver.ows.HTTPHeadersCollector.doFilter(HTTPHeadersCollector.java:48)
geoserver4geonode_forcut    |   at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
geoserver4geonode_forcut    |   at org.geoserver.filters.HTTPMethodFilter.doFilter(HTTPMethodFilter.java:36)
geoserver4geonode_forcut    |   at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
geoserver4geonode_forcut    |   at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:194)
geoserver4geonode_forcut    |   at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
geoserver4geonode_forcut    |   at org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:89)
geoserver4geonode_forcut    |   at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
geoserver4geonode_forcut    |   at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:43)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
geoserver4geonode_forcut    |   at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:39)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
geoserver4geonode_forcut    |   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337)
geoserver4geonode_forcut    |   at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
geoserver4geonode_forcut    |   at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
geoserver4geonode_forcut    |   at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
geoserver4geonode_forcut    |   at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
geoserver4geonode_forcut    |   at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
geoserver4geonode_forcut    |   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
geoserver4geonode_forcut    |   at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
geoserver4geonode_forcut    |   at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
geoserver4geonode_forcut    |   at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
geoserver4geonode_forcut    |   at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
geoserver4geonode_forcut    |   at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
geoserver4geonode_forcut    |   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
geoserver4geonode_forcut    |   at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:53)
geoserver4geonode_forcut    |   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
geoserver4geonode_forcut    |   at org.geoserver.security.oauth2.GeoServerOAuthAuthenticationFilter.doFilter(GeoServerOAuthAuthenticationFilter.java:196)
geoserver4geonode_forcut    |   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
geoserver4geonode_forcut    |   at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
geoserver4geonode_forcut    |   at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:164)
geoserver4geonode_forcut    |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
geoserver4geonode_forcut    |   at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
geoserver4geonode_forcut    |   at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
geoserver4geonode_forcut    |   at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:81)
geoserver4geonode_forcut    |   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
geoserver4geonode_forcut    |   at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
geoserver4geonode_forcut    |   at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilterInternal(GeoServerSecurityContextPersistenceFilter.java:72)
geoserver4geonode_forcut    |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
geoserver4geonode_forcut    |   at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
geoserver4geonode_forcut    |   at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
geoserver4geonode_forcut    |   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
geoserver4geonode_forcut    |   at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)
geoserver4geonode_forcut    |   at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
geoserver4geonode_forcut    |   at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:142)
geoserver4geonode_forcut    |   at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
geoserver4geonode_forcut    |   at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
geoserver4geonode_forcut    |   at org.geoserver.filters.XFrameOptionsFilter.doFilter(XFrameOptionsFilter.java:77)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
geoserver4geonode_forcut    |   at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:48)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
geoserver4geonode_forcut    |   at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:49)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
geoserver4geonode_forcut    |   at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:42)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
geoserver4geonode_forcut    |   at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
geoserver4geonode_forcut    |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
nginx4geonode_forcut        | 193.48.189.101 - - [20/Feb/2024:10:37:49 +0000] "GET /geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=geonode%3Atiles_clip_snap&STYLES=geonode%3Atiles_clip_snap&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=true&_v_=1708424877540&access_token=nIWaHQEwH6KarXnc4rfei7RdW5J5jt&WIDTH=512&HEIGHT=512&BBOX=-313086.06785608083%2C5635549.221409474%2C1.1059455573558807e-9%2C5948635.289265555 HTTP/1.1" 200 308 "https://cbcf.teledetection.fr/catalogue/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
geoserver4geonode_forcut    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
geoserver4geonode_forcut    |   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
geoserver4geonode_forcut    |   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
geoserver4geonode_forcut    |   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
geoserver4geonode_forcut    |   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
geoserver4geonode_forcut    |   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
geoserver4geonode_forcut    |   at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
geoserver4geonode_forcut    |   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
geoserver4geonode_forcut    |   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
geoserver4geonode_forcut    |   at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
geoserver4geonode_forcut    |   at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
geoserver4geonode_forcut    |   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
geoserver4geonode_forcut    |   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
geoserver4geonode_forcut    |   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
geoserver4geonode_forcut    |   at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
geoserver4geonode_forcut    |   at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
geoserver4geonode_forcut    |   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
geoserver4geonode_forcut    |   at java.base/java.lang.Thread.run(Thread.java:829)
nginx4geonode_forcut        | 193.48.189.101 - - [20/Feb/2024:10:37:49 +0000] "GET /geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=geonode%3Atiles_clip_snap&STYLES=geonode%3Atiles_clip_snap&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=true&_v_=1708424877540&access_token=nIWaHQEwH6KarXnc4rfei7RdW5J5jt&WIDTH=512&HEIGHT=512&BBOX=-313086.06785608083%2C5322463.153553393%2C1.1059455573558807e-9%2C5635549.2214094745 HTTP/1.1" 200 308 "https://cbcf.teledetection.fr/catalogue/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"

```

**Comment by vidlb** [comment]
It seems to work if I remove the "0" rule where I'm supposed to set everything denied. Then removing view permission for anonymous.  
Is this part of the docs about the first geofence rule still valid ?

**Comment by vidlb** [comment]
It seems the "0" rule in geofence where everything is denied is a problem.

**Comment by kikislater** [comment]
@vidlb Could you please explain where in geoserver did you change: 

> I just changed the role from "*" to "ROLE_ANONYMOUS" and it's now working as expected

**Comment by kikislater** [comment]
Ok so you mean under Setup of the `GeoFence Server and Rules`, the `2. Check the GeoFence default Rules` from the docs: https://docs.geonode.org/en/master/advanced/components/index.html#setup-of-the-geofence-server-and-rules

You chande this rule to anonymous: 
![geofence rule](https://docs.geonode.org/en/master/_images/oauth029.png)


Screenshots are out of date from this page and some commands are not updated like in Troubleshooting and Advanced Features (api). So I wonder how reliable is ... and why in something replicable like docker the rule is not here

**Comment by vidlb** [comment]
Yes this is the one.
For sure if no rule is created, every dataset are visible by anyone.
In my case this was critical since our dataset cannot be public, for now.

I found out most people are using geonode as an open data platform, so this stuff about securing datasets may be outdated / less maintained indeed. It's especially true if you need to share via WFS / WMS, since there are no login mechanism for geonode integrated into QGIS, and you cannot use geonode logins to authenticate web services (you must create geoserver users for this).

**Comment by kikislater** [comment]
I don't have this rule (even the one said in docs than modified one you mentionned) in docker and layers are not public ... there are several issues with groups and permissions, it's a bit anoying

> there are no login mechanism for geonode integrated into QGIS, and you cannot use geonode login credentials to authenticate web services (you must create geoserver users for this).

You can use geonode plugin to do that, but I agree it's not convenient.

**Comment by vidlb** [comment]
I know about the plugin it's annoying because you cannot choose any parameter (in my case I want to query with TILED parameter and make use of GWC, but it's not possible, layers are added as plain WMS without tiling, so the tile cache isn't used)

**Comment by vidlb** [comment]
More over it is not maintained : it seems broken in my QGIS 3.34, the geonode section in providers disappeared

**Comment by vidlb** [comment]
> I don't have this rule (even the one said in docs than modified one you mentionned) in docker and layers are not public 

Are you sure about that ? They may not appear in geonode welcome page, but have you tried to query the layer ?

**Comment by vidlb** [comment]
Well I tried again after removing the rule and indeed, I got `Could not find layer` message, so I don't know if something changed or is it just I was testing this the wrong way ?  
Is it possible that my cookie / token was accessible while trying the query from a firefox private windows ?  

In that case I don't understand how unauthenticated requests are blocked, if not by geofence.
In any case, the docs needs to be updated

**Comment by kikislater** [comment]
For my understanding, rules are per layer. For example: 
![image](https://github.com/GeoNode/geonode/assets/13238064/3801d922-e0f2-4609-ac20-0d06daab4f14)

**Comment by vidlb** [comment]
What I mean is that the only "DENY" rules I got are for "download", all other are "ACCEPT" for "ROLE_AUTHENTICATED".  
So now that I removed the "DENY ALL" 0 rule I don't understand what is keeping me from accessing a layer via WMS while being anonymous.  
This is supposed to be the purpose of the DENY ALL rule from the (outdated) docs.

**Comment by giohappy** [comment]
Closing as part of a repository cleanup: this issue was last updated before 2025-01-01. Not a judgment on the report itself — feel free to reopen or file a fresh issue against `main` if it's still relevant. Thanks for the report.
