### ISSUE TITLE
Python3.11 re.error:  Global flags not at the start of the expression at position 1

### ISSUE THREAD

**Issue by imperialbeachca** [GeoNode/geonode#12010]
## Expected Behavior
Installed geonode.
Ran ./paver_local.sh sync to initialize Geonode.  Expected to run through initialization process properly.

## Actual Behavior
Captured Task Output:
pavement.sync
python -W ignore manage.py makemigrations --noinput
Build failed running pavement.sync:  Subprocess return code: 1

Traceback (most recent call last):
  File "/opt/geonode/manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.virtualenvs/geonode/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.virtualenvs/geonode/lib/python3.11/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/home/ubuntu/.virtualenvs/geonode/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/.virtualenvs/geonode/lib/python3.11/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/geonode/geonode/harvesting/apps.py", line 31, in ready
    from geonode.urls import urlpatterns
  File "/opt/geonode/geonode/urls.py", line 33, in <module>
    import geonode.proxy.urls
  File "/opt/geonode/geonode/proxy/urls.py", line 22, in <module>
    from . import views
  File "/opt/geonode/geonode/proxy/views.py", line 66, in <module>
    ows_regexp = re.compile(r"^(?i)(version)=(\d\.\d\.\d)(?i)&(?i)request=(?i)(GetCapabilities)&(?i)service=(?i)(\w\w\w)$")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 1

## Steps to Reproduce the Problem

# Get Geonode files
1. sudo mkdir -p /opt/geonode/; sudo usermod -a -G www-data $USER; sudo chown -Rf $USER:www-data /opt/geonode/; sudo chmod -Rf 775 /opt/geonode/
2. cd /opt; git clone https://github.com/GeoNode/geonode.git -b 4.2.x geonode

#Install Geonode file dependencies
3. cd geonode
4. pip install -r requirements.txt --upgrade
5. pip install -e . --upgrade
6. pip install pygdal=="`gdal-config --version`.*"

# Initialize Geonode
7. sudo chmod +x *.sh
8. sudo chmod -Rf 777 geonode/static_root/ geonode/uploaded/
9.  ./paver_local.sh sync

## Specifications

  - GeoNode version: 4.2.0
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): manual
  - Platform: ubuntu 22.04
  - Additional details:

**Comment by giohappy** [comment]
Closing as part of a repository cleanup: this issue was last updated before 2025-01-01. Not a judgment on the report itself — feel free to reopen or file a fresh issue against `main` if it's still relevant. Thanks for the report.
