### ISSUE TITLE
Cant upload dataset

### ISSUE THREAD

**Issue by nesangcode** [GeoNode/geonode#12344]
## Expected Behavior
Dataset uploaded

## Actual Behavior
return error "Check validity"
in `geonode.log`:
```
20 Jun 20:52:39 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 20:52:39 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 20:52:39 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 20:52:39 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 20:52:39 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 20:52:39 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 20:52:39 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
```
## Steps to Reproduce the Problem

  1. Follow all the installation steps
  2. Upload some `.kml` dataset

## Specifications

  - GeoNode version: 4.2.5
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): manual
  - Platform: Ubuntu Server 22.04
  - Additional details:

**Comment by etj** [comment]
@nesangcode the log is not related to the error.
Pls provide the proper log lines and/or the failing file.

**Comment by nesangcode** [comment]
Here it is.
```
20 Jun 21:13:06 WARN   [geoserver.config] - Error reading resource URL [jar:file:/opt/tomcat/apache-tomcat-9.0.90/webapps/geoserver/WEB-INF/lib/gs-geofence-server-2.24.2.jar!/geofence-default-override.properties]
java.io.FileNotFoundException: URL [jar:file:/opt/tomcat/apache-tomcat-9.0.90/webapps/geoserver/WEB-INF/lib/gs-geofence-server-2.24.2.jar!/geofence-default-override.properties] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/opt/tomcat/apache-tomcat-9.0.90/webapps/geoserver/WEB-INF/lib/gs-geofence-server-2.24.2.jar!/geofence-default-override.properties
        at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:217)
        at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:164)
        at org.springframework.core.io.UrlResource.getFile(UrlResource.java:241)
        at org.geoserver.config.SpringResourceAdaptor.relative(SpringResourceAdaptor.java:38)
        at org.geoserver.config.GeoServerPropertyOverrideConfigurer.setLocations(GeoServerPropertyOverrideConfigurer.java:49)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.beans.BeanWrapperImpl$BeanPropertyHandler.setValue(BeanWrapperImpl.java:332)
        at org.springframework.beans.AbstractNestablePropertyAccessor.processLocalProperty(AbstractNestablePropertyAccessor.java:463)
        at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:278)
        at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:266)
        at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:104)
        at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:79)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1740)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1452)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:171)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:748)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:399)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:278)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
        at org.geoserver.platform.GeoServerContextLoaderListener.contextInitialized(GeoServerContextLoaderListener.java:22)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4007)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4448)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:599)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:571)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:603)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1014)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1866)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:816)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:468)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1584)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:312)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:109)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:385)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:332)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:776)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:721)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1203)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1193)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:749)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:211)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:415)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:878)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:735)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
20 Jun 21:13:06 WARN   [geoserver.monitor] - monitoring storage memory not found, falling back to 'memory'
20 Jun 21:13:08 WARN   [ejb.Ejb3Configuration] - hibernate.connection.autocommit = false break the EJB3 specification
20 Jun 21:13:08 WARN   [cache.EhCacheProvider] - Could not find configuration [Rule]; using defaults.
20 Jun 21:13:08 WARN   [cache.EhCacheProvider] - Could not find configuration [RuleLimits]; using defaults.
20 Jun 21:13:08 WARN   [cache.EhCacheProvider] - Could not find configuration [usergroup]; using defaults.
20 Jun 21:13:08 WARN   [cache.EhCacheProvider] - Could not find configuration [GSUser]; using defaults.
20 Jun 21:13:08 WARN   [cache.EhCacheProvider] - Could not find configuration [GFUser]; using defaults.
20 Jun 21:13:08 WARN   [cache.EhCacheProvider] - Could not find configuration [gsinstance]; using defaults.
20 Jun 21:13:08 WARN   [cache.EhCacheProvider] - Could not find configuration [LayerDetails]; using defaults.
20 Jun 21:13:16 WARN   [gce.imagemosaic] - Unable to set ordering between tiff readers spi
20 Jun 21:13:16 WARN   [servlet.BaseMapServlet] - Cannot delete file:/opt/tomcat/apache-tomcat-9.0.90/work/Catalina/localhost/geoserver/wicket-filestore
20 Jun 21:13:17 WARN   [auth.GeoFenceAuthenticationProvider] - INIT FROM CONFIG
20 Jun 21:13:17 WARN   [protocol.ResponseProcessCookies] - Invalid cookie header: "Set-Cookie: sessionid=j5y27z76pa78r0lk6kozlmlxu2pgtq2z; expires=Thu, 04 Jul 2024 14:13:17 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax". Invalid 'expires' attribute: Thu, 04 Jul 2024 14:13:17 GMT
20 Jun 21:13:18 WARN   [protocol.ResponseProcessCookies] - Invalid cookie header: "Set-Cookie: sessionid=6wnkaqg4cgg4435l3cyp2sowhgptiy7h; expires=Thu, 04 Jul 2024 14:13:18 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax". Invalid 'expires' attribute: Thu, 04 Jul 2024 14:13:18 GMT
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - AcceptAllMatcher: unknown field 'dummy' with value 'true'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'maxLength' with value '100'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - ColumnsBlock: unknown field 'height' with value '500'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '420'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '420'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'maxLength' with value '1200'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '300'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '300'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '300'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '300'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '300'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '300'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '300'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '300'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - LastPage: unknown field 'rotation' with value 'true'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '300'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '300'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - LastPage: unknown field 'rotation' with value 'true'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - LastPage: unknown field 'rotation' with value 'true'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - TextBlock: unknown field 'width' with value '424'
20 Jun 21:13:18 WARN   [yaml.CustomBeanWrapper] - LastPage: unknown field 'rotation' with value 'true'
```

**Comment by mattiagiupponi** [comment]
Did you create the geofence db configuration as described here? https://docs.geonode.org/en/master/install/advanced/core/index.html#conifgure-the-geofence-db

**Comment by nesangcode** [comment]
Yes, the solution is I need to add `geonode_data` into GeoServer stores.
