### ISSUE TITLE
Database migration to `v4.4.x` fails with `KeyError: 'formats'`

### ISSUE THREAD

**Issue by ridoo** [GeoNode/geonode#12750]
## Expected Behavior
Data migrations works fine

## Actual Behavior
Migrating from `v4.3.x` to `v4.4.x` throws the following exception

```
django4geonode     | Running migrations:
django4geonode     |   Applying base.0092_migrate and_remove_resourcebase_files...Traceback (most recent call last):
django4geonode     |   File "/usr/src/geonode/manage.py", line 29, in <module>
django4geonode     |     execute_from_command_line(sys.argv)
django4geonode     |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
django4geonode     |     utility.execute()
django4geonode     |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 436, in execute
django4geonode     |     self.fetch_command(subcommand).run_from_argv(self.argv)
django4geonode     |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 412, in run_from_argv
django4geonode     |     self.execute(*args, **cmd_options)
django4geonode     |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 458, in execute
django4geonode     |     output = self.handle(*args, **options)
django4geonode     |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 106, in wrapper
django4geonode     |     res = handle_func(*args, **kwargs)
django4geonode     |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/migrate.py", line 356, in handle
django4geonode     |     post_migrate_state = executor.migrate(
django4geonode     |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 135, in migrate
django4geonode     |     state = self._migrate_all_forwards(
django4geonode     |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
django4geonode     |     state = self.apply_migration(
django4geonode     |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 252, in apply_migration
django4geonode     |     state = migration.apply(state, schema_editor)
django4geonode     |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/migration.py", line 132, in apply
django4geonode     |     operation.database_forwards(
django4geonode     |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
django4geonode     |     self.code(from_state.apps, schema_editor)
django4geonode     |   File "/usr/src/geonode/geonode/base/migrations/0092_migrate and_remove_resourcebase_files.py", line 63, in migrate_files
django4geonode     |     itertools.chain.from_iterable(y for y in [x["required_ext"] for x in filetype["formats"]])
django4geonode     | KeyError: 'formats'
```

## Steps to Reproduce the Problem

  1. Having `v4.3.x` database
  2. Start `v4.4.x` and run migrations

## Additional Information

The database migration 

https://github.com/GeoNode/geonode/blob/27476dcb8fb82e0ec0b398d549ceef4fdbe6ba38/geonode/base/migrations/0092_migrate%20and_remove_resourcebase_files.py#L60-L68

is missing the key `formats` which was [introduced in a later commit](https://github.com/GeoNode/geonode/commit/883f9333ef373bf4b939a7a1a42bf8f471fb7602#diff-600fe2fc072c2dc72eb3936671991dfe1057373233f45f9809d855f43f892c7aR1724). `v4.4.x` [currently does not map](https://github.com/GeoNode/geonode/blob/27476dcb8fb82e0ec0b398d549ceef4fdbe6ba38/geonode/utils.py#L1961) to the new format "required for FE" (whatever that means). Just compare it with the format mapping currently on `master`:

https://github.com/GeoNode/geonode/blob/993364a44c8afa1085dccd2366794789b36a2b39/geonode/utils.py#L1720-L1735

/cc @gannebamm 

## Specifications

  - GeoNode version: `v.4.4.x`
  - Installation type (vanilla, geonode-project):
  - Installation method (manual, docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
@ridoo the fix has been merged.
