### ISSUE TITLE
geonode-updateip hangs on a layer

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1279]
I have loaded some layers and then tried to change the ip and run sudo geonode-ip
the first layer is processed in no time and then it hangs indefinitely on the second one and this is the traceback on keyboard interrupt, it looks like it hangs on the wps statistics @tomkralidis an idea?

    Replacing SITEURL in /etc/geonode/local_settings.py
    Adding entry for local ip in /usr/share/geoserver/data//printing/config.yaml
      IP was already added to the printing whitelist.
    Replacing ALLOWED_HOSTS in /etc/geonode/local_settings.py
    Unknown command: 'fixsitename'
    Type 'django-admin help' for usage.
     * Restarting web server apache2                                                                                                               apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1 for ServerName
     ... waiting apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1 for ServerName
                                                                                                                                            [ OK ]
    [updated] Layer selected_basin (1/21)
    [updated] Layer sri_lanka_districts_admin_level_3 (2/21)
    ^CTraceback (most recent call last):
      File "/usr/bin/django-admin", line 5, in <module>
        management.execute_from_command_line()
      File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
        utility.execute()
      File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 222, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 255, in execute
        output = self.handle(*args, **options)
      File "/usr/local/lib/python2.7/dist-packages/geonode/layers/management/commands/updatelayers.py", line 68, in handle
        owner=owner, console=console, workspace=workspace, store=store, filter=filter, skip_unadvertised=skip_unadvertised)
      File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/helpers.py", line 306, in gs_slurp
        layer.save()
      File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 546, in save
        force_update=force_update, update_fields=update_fields)
      File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 664, in save_base
        update_fields=update_fields, raw=raw, using=using)
      File "/usr/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 170, in send
        response = receiver(signal=self, sender=sender, **named)
      File "/usr/local/lib/python2.7/dist-packages/geonode/layers/models.py", line 575, in geoserver_post_save
        set_attributes(instance)
      File "/usr/local/lib/python2.7/dist-packages/geonode/layers/models.py", line 711, in set_attributes
        result = get_attribute_statistics(layer.name, field)
      File "/usr/local/lib/python2.7/dist-packages/geonode/layers/models.py", line 634, in get_attribute_statistics
        return wps_execute_layer_attribute_statistics(layer_name, field)
      File "/usr/local/lib/python2.7/dist-packages/geonode/layers/ows.py", line 145, in wps_execute_layer_attribute_statistics
        response = http_post(url, request)
      File "/usr/lib/python2.7/dist-packages/owslib/util.py", line 270, in http_post
        up = urllib2.urlopen(r,timeout=timeout);
      File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
        return _opener.open(url, data, timeout)
      File "/usr/lib/python2.7/urllib2.py", line 400, in open
        response = self._open(req, data)
      File "/usr/lib/python2.7/urllib2.py", line 418, in _open
        '_open', req)
      File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 1207, in http_open
        return self.do_open(httplib.HTTPConnection, req)
      File "/usr/lib/python2.7/urllib2.py", line 1180, in do_open
        r = h.getresponse(buffering=True)
      File "/usr/lib/python2.7/httplib.py", line 1030, in getresponse
        response.begin()
      File "/usr/lib/python2.7/httplib.py", line 407, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
        line = self.fp.readline()
      File "/usr/lib/python2.7/socket.py", line 447, in readline
        data = self._sock.recv(self._rbufsize)
    KeyboardInterrupt

**Comment by jj0hns0n** [comment]
@vdeparday lets look into this at the sprint this week and close if possible.

**Comment by jj0hns0n** [comment]
I cant replicate this now. I dont the see statistics calculated at all, but it certainly doesnt hang. Going to go ahead and close and look at the stats generation in other tickets including #1412
