### ISSUE TITLE
timeout uploading files

### ISSUE THREAD

**Issue by batje** [GeoNode/geonode#1294]
When uploading of a very bad connection (welcome to Uganda), I get a timeout. Well, I see I have a timout in my apache.log, but on the client I only see the upload bar never finishes.

First step in fixing this would be to throw an error on the client when the server stops receiving data.

Second and better fix would be to allow for extending the timeout as a setting.

This is what is in the apache.log file:

```
[Wed Dec 04 13:09:37 2013] [warn] mod_wsgi: Runtime using Python/2.7.3.
[Wed Dec 04 13:09:37 2013] [notice] Apache/2.2.22 (Ubuntu) mod_wsgi/3.3 Python/2.7.3 configured -- resuming normal operations
[Wed Dec 04 13:13:06 2013] [error] [client 41.220.13.22] (70007)The timeout specified has expired: mod_wsgi (pid=30303): Unable to get bucket brigade for request., referer: http://geoclean.mountbatten.net/upload/
[Wed Dec 04 03:13:08 2013] [error] Internal Server Error: /layers/upload
[Wed Dec 04 03:13:08 2013] [error] Traceback (most recent call last):
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
[Wed Dec 04 03:13:08 2013] [error]     response = middleware_method(request, callback, callback_args, callback_kwargs)
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/middleware/csrf.py", line 185, in process_view
[Wed Dec 04 03:13:08 2013] [error]     request_csrf_token = request.POST.get('csrfmiddlewaretoken', '')
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 198, in _get_post
[Wed Dec 04 03:13:08 2013] [error]     self._load_post_and_files()
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/http/request.py", line 217, in _load_post_and_files
[Wed Dec 04 03:13:08 2013] [error]     self._post, self._files = self.parse_file_upload(self.META, data)
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/http/request.py", line 177, in parse_file_upload
[Wed Dec 04 03:13:08 2013] [error]     return parser.parse()
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/http/multipartparser.py", line 138, in parse
[Wed Dec 04 03:13:08 2013] [error]     for item_type, meta_data, field_stream in Parser(stream, self._boundary):
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/http/multipartparser.py", line 600, in __iter__
[Wed Dec 04 03:13:08 2013] [error]     for sub_stream in boundarystream:
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/utils/six.py", line 414, in next
[Wed Dec 04 03:13:08 2013] [error]     return type(self).__next__(self)
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/http/multipartparser.py", line 412, in __next__
[Wed Dec 04 03:13:08 2013] [error]     return LazyStream(BoundaryIter(self._stream, self._boundary))
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/http/multipartparser.py", line 438, in __init__
[Wed Dec 04 03:13:08 2013] [error]     unused_char = self._stream.read(1)
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/http/multipartparser.py", line 312, in read
[Wed Dec 04 03:13:08 2013] [error]     out = b''.join(parts())
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/http/multipartparser.py", line 305, in parts
[Wed Dec 04 03:13:08 2013] [error]     chunk = next(self)
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/utils/six.py", line 414, in next
[Wed Dec 04 03:13:08 2013] [error]     return type(self).__next__(self)
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/http/multipartparser.py", line 327, in __next__
[Wed Dec 04 03:13:08 2013] [error]     output = next(self._producer)
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/utils/six.py", line 414, in next
[Wed Dec 04 03:13:08 2013] [error]     return type(self).__next__(self)
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/http/multipartparser.py", line 388, in __next__
[Wed Dec 04 03:13:08 2013] [error]     data = self.flo.read(self.chunk_size)
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/http/request.py", line 243, in read
[Wed Dec 04 03:13:08 2013] [error]     return self._stream.read(*args, **kwargs)
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 104, in read
[Wed Dec 04 03:13:08 2013] [error]     result = self.buffer + self._read_limited(size - len(self.buffer))
[Wed Dec 04 03:13:08 2013] [error]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 92, in _read_limited
[Wed Dec 04 03:13:08 2013] [error]     result = self.stream.read(size)
[Wed Dec 04 03:13:08 2013] [error] IOError: request data read error
[Wed Dec 04 03:13:08 2013] [error] [client 41.220.13.22] mod_wsgi (pid=30111): Exception occurred processing WSGI script '/var/www/geonode/wsgi/geonode.wsgi'.
[Wed Dec 04 03:13:08 2013] [error] [client 41.220.13.22] IOError: failed to write data
```

**Comment by jj0hns0n** [comment]
This should get handled as part of new uploader work cc @ischneider

**Comment by ischneider** [comment]
@jj0hns0n This may have been fixed w/ 9b82d71d5740293c057e73bfcf259b09a878d6eb

**Comment by jj0hns0n** [comment]
@batje can you test this with the latest beta that includes the fix @ischneider mentioned.

**Comment by garnertb** [comment]
This can be fixed by adjusting the `RequestReadTimeout` in the Apache configuration. Without a pull request, I think the default settings are OK and this is up to the system administrator to fine-tune based on deployment limitations.

**Comment by jj0hns0n** [comment]
Going to go ahead and close. @batje please re-open or file a new issue if you encounter this same issue again.
