### ISSUE TITLE
Importlayers does not accept a relative filename

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#1759]
```
geonode importlayers data/buildings_osm_merapi.shp --traceback -v3

Verifying that GeoNode is running ...
Please pass a filename or a directory name as the "incoming" parameter, instead of data/buildings_osm_merapi.shp: <type 'str'>
None
Traceback (most recent call last):
  File "/usr/bin/django-admin", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/geonode/layers/management/commands/importlayers.py", line 95, in handle
    console=console)
  File "/usr/local/lib/python2.7/dist-packages/geonode/layers/utils.py", line 418, in upload
    raise GeoNodeException(msg)
geonode.GeoNodeException: Please pass a filename or a directory name as the "incoming" parameter, instead of data/buildings_osm_merapi.shp: <type 'str'>
```

**Comment by collaer** [comment]
verified with @jj0hns0n 

root@vagrant-ubuntu-trusty-64:/# geonode importlayers setup/Bat_Deval.shp
[created] Layer for 'setup/Bat_Deval.shp' (1/1)


Finished processing 1 layers in 14.0 seconds.

1 Created layers
0 Updated layers
0 Skipped layers
0 Failed layers
14.000000 seconds per layer

**Comment by jj0hns0n** [comment]
This seems to work both when using python manage.py and also with the geonode alias when installed from packages.

(geonode)scylax:geonode ortelius$ python manage.py importlayers scratch/tl_2013_06_tract.shp
[02/Feb/2015 06:00:42] "GET /layers/acls HTTP/1.1" 200 82
[02/Feb/2015 06:00:45] "GET /layers/acls HTTP/1.1" 200 653
[created] Layer for 'scratch/tl_2013_06_tract.shp' (1/1)


Finished processing 1 layers in 3.0 seconds.

1 Created layers
0 Updated layers
0 Skipped layers
0 Failed layers
3.000000 seconds per layer
(geonode)scylax:geonode ortelius$

**Comment by jj0hns0n** [comment]
@ingenieroariel ... closing, please reopen if you encounter this issue again.
