### ISSUE TITLE
2.4b10 fresh install/configure problems

### ISSUE THREAD

**Issue by vytj** [GeoNode/geonode#1937]
Hello,

Tried fresh install of GeoNode 2.4b10 on Ubuntu 14.04. Installation itself went without problems, but initial configuration failed:
  $ sudo geonode-updateip 127.0.0.1
  $ geonode createsuperuser
led to errors:

Replacing SITEURL in /etc/geonode/local_settings.py
Adding entry for local ip in /usr/share/geoserver/data/printing/config.yaml
Adding ALLOWED_HOSTS in /etc/geonode/local_settings.py
Traceback (most recent call last):
  File "/usr/bin/django-admin", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'geonode.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named kombu
 * Restarting web server apache2                                                AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
                                                                         [ OK ]
Traceback (most recent call last):
  File "/usr/bin/django-admin", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'geonode.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named kombu
Traceback (most recent call last):
  File "/usr/bin/django-admin", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'geonode.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named kombu

--------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/bin/django-admin", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'geonode.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named kombu

**Comment by collaer** [comment]
Seems django-kombu is not installed, related with the initial celery integration maybe ?
@garnertb

**Comment by garnertb** [comment]
This is definitely related to celery integration as kombu is a dependency of the celery python package.  I'll look into this.

**Comment by simod** [comment]
A quick workaround is to do sudo pip install celery django-celery.

Il venerdì 23 gennaio 2015, Tyler Garner <notifications@github.com> ha
scritto:

> This is definitely related to celery integration as kombu is a dependency
> of the celery python package. I'll look into this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/1937#issuecomment-71186568>.
>


-- 
Simone

**Comment by vytj** [comment]
Installed django-celery, got new errors:

$ sudo geonode-updateip 127.0.0.1
Replacing SITEURL in /etc/geonode/local_settings.py
Adding entry for local ip in /usr/share/geoserver/data/printing/config.yaml
  IP was already added to the printing whitelist.
Replacing ALLOWED_HOSTS in /etc/geonode/local_settings.py
Traceback (most recent call last):
  File "/usr/bin/django-admin", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/geonode/base/management/commands/fixsitename.py", line 19, in handle
    site = Site.objects.get_current()
  File "/usr/lib/python2.7/dist-packages/django/contrib/sites/models.py", line 47, in get_current
    current_site = self.get(pk=sid)
  File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 301, in get
    num = len(clone)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 710, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_site" does not exist
LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...
                                                             ^

 * Restarting web server apache2                                                AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
                                                                         [ OK ]
Traceback (most recent call last):
  File "/usr/bin/django-admin", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/management/commands/updatelayers.py", line 88, in handle
    owner = get_valid_user(user)
  File "/usr/local/lib/python2.7/dist-packages/geonode/people/utils.py", line 43, in get_valid_user
    theuser = get_default_user()
  File "/usr/local/lib/python2.7/dist-packages/geonode/people/utils.py", line 30, in get_default_user
    if superusers.count() > 0:
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 291, in count
    return self.query.get_count(using=self.db)
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 390, in get_count
    number = obj.get_aggregation(using=using)[None]
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 356, in get_aggregation
    result = query.get_compiler(using).execute_sql(SINGLE)
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "people_profile" does not exist
LINE 1: SELECT COUNT(*) FROM "people_profile" WHERE "people_profile"...
                             ^

Traceback (most recent call last):
  File "/usr/bin/django-admin", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/geonode/maps/management/commands/updatemaplayerip.py", line 31, in handle
    for maplayer in map_layers:
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 96, in __iter__
    self._fetch_all()
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 710, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "maps_maplayer" does not exist
LINE 1: ...er"."source_params", "maps_maplayer"."local" FROM "maps_mapl...
                                                             ^

**Comment by simod** [comment]
Apparently the installation process did not finish properly. Running geonode syncdb then geonode createsuperuser and geonode-updateip yourip should help. We'll try to fix it today.

**Comment by simod** [comment]
the b11 should be ready in one hour or so and should have a fix for this.

**Comment by vytj** [comment]
"geonode syncdb" created additional tables:

Creating table announcements_announcement
Creating table announcements_dismissal

You just installed Django's auth system, which means you don't have any superusers defined.
Would you like to create one now? (yes/no):

I chose "no", then ran createsuperuser and geonode-updateip.
Now i can see Geonode site and log in. However, /var/www/geonode/static folder is empty. Looks like installation went wrong more than once.

Anyway, let's try next beta. :)

**Comment by collaer** [comment]
just a last "geonode collectstatic" maybe :)

**Comment by vytj** [comment]
That did the trick :) Thanks!

**Comment by JamesLeonDufour** [comment]
same problems fixed, but got a basic 500 internal server error ?

**Comment by vytj** [comment]
In my case, i had fully updated fresh Ubuntu Server 14.04 64-bit install. To fix GeoNode, these commands were needed:

sudo pip install celery django-celery
sudo geonode syncdb
sudo geonode createsuperuser
sudo geonode-updateip <system IP>
sudo geonode collectstatic
(plus some entries in /var/geonode/local_settings.py to ALLOWED_HOSTS and PROXY_ALLOWED_HOSTS due to internal network specifics).

That's all, no more internal server error (500), can login with recently created user. Anyway, now next beta is available.

**Comment by JamesLeonDufour** [comment]
Fixed needed to run 

$ sudo pip install django-celery --upgrade

**Comment by vytj** [comment]
Confirmed with 2.4.b11, on fresh install still needed:
$ sudo pip install django-celery --upgrade 

Otherwise, you get "500 Internal Server Error"

**Comment by simod** [comment]
I saw that ubuntu 14.04 version of django-celery is 2.5.5 while we require the 3.1. So the option we have is to release a geonode-django-celery but I would prefer to avoid it. @garnertb any chance we can use the 2.5.5?

**Comment by simod** [comment]
update, the 2.5.5 seems to not be compatible with django 1.6

**Comment by collaer** [comment]
closed by #1962 (and beta 12) i think
