### ISSUE TITLE
2.4b11 importlayers additional options fails

### ISSUE THREAD

**Issue by vytj** [GeoNode/geonode#1953]
Hello,
Encountered permission issues while trying to upload layers from command line using *geonode importlayers*. GeoNode had 2 users - gnuser (default superuser) and T.User.

```
$ geonode importlayers -v 3 .
...
OSError: [Errno 13] Permission denied: '/var/www/geonode/uploaded/layers/test1.sld'
```
That's expected, because permissions for this folder are
drwxr-xr-x 2 www-data www-data 4096 Jan 28 11:53 layers

Running the same command as root and with options:
```
$ sudo geonode importlayers -v 3 --user=T.User --keywords=keyw1,keyw2 .

Verifying that GeoNode is running ...
Found 1 potential layers.
[failed] Layer for './test1.tif' (1/1)

Detailed report of failures:


./test1.tif
================
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geonode/layers/utils.py", line 472, in upload
    keywords=keywords,
  File "/usr/local/lib/python2.7/dist-packages/geonode/layers/utils.py", line 379, in file_upload
    defaults=defaults
  File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "/usr/lib/python2.7/dist-packages/modeltranslation/manager.py", line 341, in get_or_create
    return super(MultilingualQuerySet, self).get_or_create(**kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 378, in get_or_create
    obj = self.model(**params)
  File "/usr/lib/python2.7/dist-packages/modeltranslation/translator.py", line 213, in new_init
    old_init(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/modeltranslation/translator.py", line 213, in new_init
    old_init(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/polymorphic/polymorphic_model.py", line 163, in __init__
    super(PolymorphicModel, self).__init__(*args, ** kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 405, in __init__
    setattr(self, field.name, rel_obj)
  File "/usr/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 337, in __set__
    self.field.name, self.field.rel.to._meta.object_name))
ValueError: Cannot assign "'T.User'": "Layer.owner" must be a "Profile" instance.


Finished processing 1 layers in 0.0 seconds.

0 Created layers
0 Updated layers
0 Skipped layers
1 Failed layers
0.000000 seconds per layer
```
Leaving only keywords part:
```
$ sudo geonode importlayers -v 3  --keywords=keyw1,keyw2 .
Verifying that GeoNode is running ...
Found 1 potential layers.
[created] Layer for './test1.tif' (1/1)

Detailed report of failures:


Finished processing 1 layers in 7.0 seconds.

1 Created layers
0 Updated layers
0 Skipped layers
0 Failed layers
7.000000 seconds per layer
```
Layer is added, but without keywords. The same command in GeoNode 2.0.1 correctly adds both user and keywords.

**Comment by jj0hns0n** [comment]
Note the correct syntax is without the =

A valid version of the command is as follows

python manage.py importlayers -v 3 --user jeff --keywords testing,at,sprint ~/.virtualenvs/geonode/lib/python2.7/site-packages/gisdata/data/good/vector/

**Comment by vytj** [comment]
Tested with 2.4b19 - import command works. 
Should i open ticket to update documentation - it still displays old syntax (with "=")?

http://docs.geonode.org/en/latest/tutorials/admin/commands.html#commands
http://geonode.readthedocs.org/en/latest/tutorials/admin/commands.html
http://geonode.readthedocs.org/en/latest/tutorials/admin/data/importlayers.html

**Comment by jj0hns0n** [comment]
Yeah, or better yet, send a PR against the docs.
