### ISSUE TITLE
Installation of 2.4b20 requires pyshp

### ISSUE THREAD

**Issue by JJediny** [GeoNode/geonode#2061]
seems to require a new dependence in pyshp atleast in dev mode
`pip install pyshp` 
w/ paver stop --> paver start solved it for me

----
## Traceback
python manage.py syncdb --noinput
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 284, in execute
    self.validate()
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/usr/lib/python2.7/dist-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 78, in _populate
    self.load_app(app_name)
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/modeltranslation/models.py", line 84, in <module>
    handle_translation_registrations()
  File "/usr/local/lib/python2.7/dist-packages/modeltranslation/models.py", line 80, in handle_translation_registrations
    autodiscover()
  File "/usr/local/lib/python2.7/dist-packages/modeltranslation/models.py", line 31, in autodiscover
    import_module(module)
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/john/geonode/geonode/base/translation.py", line 2, in <module>
    from geonode.base.models import (TopicCategory, SpatialRepresentationType, Region,
  File "/home/john/geonode/geonode/base/models.py", line 25, in <module>
    from geonode.utils import bbox_to_wkt
  File "/home/john/geonode/geonode/utils.py", line 27, in <module>
    import shapefile
ImportError: No module named shapefile

**Comment by simod** [comment]
released b21, thanks!
