### ISSUE TITLE
Deleting Announcement from Form View causes 500 Error

### ISSUE THREAD

**Issue by JJediny** [GeoNode/geonode#2083]
![image](https://cloud.githubusercontent.com/assets/6350035/6317144/d0f032dc-ba11-11e4-9f8b-b2baa0c9fc2f.png)
Internal Server Error: /announcements/announcement/2/delete
 Traceback (most recent call last):
   File "/usr/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 206, in __call__
     response = self.get_response(request)
   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 194, in get_response
     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 236, in handle_uncaught_exception
     return callback(request, **param_dict)
   File "/usr/lib/python2.7/dist-packages/django/utils/decorators.py", line 99, in _wrapped_view
     response = view_func(request, *args, **kwargs)
   File "/usr/lib/python2.7/dist-packages/django/views/defaults.py", line 46, in server_error
     return http.HttpResponseServerError(template.render(Context({})))
   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
     return self._render(context)
   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
     return self.nodelist.render(context)
   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
     bit = self.render_node(node, context)
   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
     return node.render(context)
   File "/usr/lib/python2.7/dist-packages/django/template/loader_tags.py", line 53, in render
     result = self.nodelist.render(context)
   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
     bit = self.render_node(node, context)
   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
     return node.render(context)
   File "/usr/lib/python2.7/dist-packages/announcements/templatetags/announcements_tags.py", line 24, in render
     request = context["request"
   File "/usr/lib/python2.7/dist-packages/django/template/context.py", line 56, in __getitem__
     raise KeyError(key)
 KeyError: 'request'

**Comment by pjdufour** [comment]
@JJediny, should we close this issue?  It seems like it was fixed.  No errors on most recent build.
