### ISSUE TITLE
Error saving style back to server in IE

### ISSUE THREAD

**Issue by purpleplum** [GeoNode/geonode#2093]
I am using the current release version of geonode:  GeoNode version 2.0.1.  
Geonode always gave "the error saving style back to the server" error in IE (version 11.0.9600.17420).    The same operation would work fine in CHROME logged in as the same user. 
When I checked the geoserver log, I found the following error message:

           2015-03-04 22:24:36,848 ERROR [geoserver.rest] - 
            java.lang.RuntimeException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 95; The value of the attribute "prefix="xmlns",localpart="NS1",rawname="xmlns:NS1"" is invalid. Prefixed namespace bindings may not be empty.
	at org.geotools.styling.SLDParser.readXML(SLDParser.java:355)
         .....
          Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 95; The value of the attribute "prefix="xmlns",localpart="NS1",rawname="xmlns:NS1"" is invalid. Prefixed namespace bindings may not be empty.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at org.geotools.styling.SLDParser.readXML(SLDParser.java:351)
	... 91 more

 
I am wondering if someone can help out with this issue.
Thanks in advance!

**Comment by simod** [comment]
Hi thanks for reporting this. I can't test on IE but we have to make sure that this issue does not show up in 2.4.

**Comment by capooti** [comment]
Today I wanted to test this. Unluckily here at my office they have IE 8 as the supported one (if I am not wrong), and I cannot even reach the layer details page. This is how it looks the layers list page :(


![geonode_dont_like_explorer](https://cloud.githubusercontent.com/assets/148380/6618761/84de424a-c8c5-11e4-9838-f55f3656bacc.png)
