### ISSUE TITLE
LockFailed: failed to create /var/www/<hostname>.MainThread-<integer>

### ISSUE THREAD

**Issue by donaldbales** [GeoNode/geonode#2106]
When trying to upload files in Geonode/Layers after a fresh install using the Ubuntu geonode 2.4 beta 22 package, I get the following or similar error:

failed to create /var/www/foss-geonode01.Dummy-2-12596
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geonode/layers/views.py", line 163, in layer_upload
    title=form.cleaned_data["layer_title"],
  File "/usr/local/lib/python2.7/dist-packages/geonode/layers/utils.py", line 379, in file_upload
    defaults=defaults
  File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "/usr/lib/python2.7/dist-packages/modeltranslation/manager.py", line 341, in get_or_create
    return super(MultilingualQuerySet, self).get_or_create(**kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 380, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "/usr/lib/python2.7/dist-packages/polymorphic/polymorphic_model.py", line 90, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 582, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python2.7/dist-packages/geonode/social/signals.py", line 165, in notification_post_save_resource
    send_queued_notifications.delay()
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 452, in delay
    return self.apply_async(args, kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 546, in apply_async
    link=link, link_error=link_error, **options)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 727, in apply
    request=request, propagate=throw)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 315, in eager_trace_task
    uuid, args, kwargs, request)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 218, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/geonode/tasks/email.py", line 23, in send_queued_notifications
    send_all(*args)
  File "/usr/lib/python2.7/dist-packages/notification/engine.py", line 43, in send_all
    lock = acquire_lock(*args)
  File "/usr/lib/python2.7/dist-packages/notification/engine.py", line 31, in acquire_lock
    lock.acquire(LOCK_WAIT_TIMEOUT)
  File "/usr/lib/python2.7/dist-packages/notification/lockfile.py", line 249, in acquire
    raise LockFailed("failed to create %s" % self.unique_name)
LockFailed: failed to create /var/www/foss-geonode01.Dummy-2-12596
ERROR:geonode.layers.views:failed to create /var/www/foss-geonode01.Dummy-2-12596
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geonode/layers/views.py", line 163, in layer_upload
    title=form.cleaned_data["layer_title"],
  File "/usr/local/lib/python2.7/dist-packages/geonode/layers/utils.py", line 379, in file_upload
    defaults=defaults
  File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "/usr/lib/python2.7/dist-packages/modeltranslation/manager.py", line 341, in get_or_create
    return super(MultilingualQuerySet, self).get_or_create(**kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 380, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "/usr/lib/python2.7/dist-packages/polymorphic/polymorphic_model.py", line 90, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 582, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python2.7/dist-packages/geonode/social/signals.py", line 165, in notification_post_save_resource
    send_queued_notifications.delay()
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 452, in delay
    return self.apply_async(args, kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 546, in apply_async
    link=link, link_error=link_error, **options)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 727, in apply
    request=request, propagate=throw)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 315, in eager_trace_task
    uuid, args, kwargs, request)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 218, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/geonode/tasks/email.py", line 23, in send_queued_notifications
    send_all(*args)
  File "/usr/lib/python2.7/dist-packages/notification/engine.py", line 43, in send_all
    lock = acquire_lock(*args)
  File "/usr/lib/python2.7/dist-packages/notification/engine.py", line 31, in acquire_lock
    lock.acquire(LOCK_WAIT_TIMEOUT)
  File "/usr/lib/python2.7/dist-packages/notification/lockfile.py", line 249, in acquire
    raise LockFailed("failed to create %s" % self.unique_name)
LockFailed: failed to create /var/www/foss-geonode01.Dummy-2-12596

It appear the system is trying to create locks in /var/www.  So as a work-around, I modified the privileges to 777 on www.  Now it works.  But shouldn't these locks be created under /var/www/geonode?

**Comment by garnertb** [comment]
Add ```NOTIFICATION_LOCK_LOCATION='/var/www/geonode'```to your settings.

**Comment by donaldbales** [comment]
Thanks Tyler.
