### ISSUE TITLE
Error when trying to upload files with GeoNetwork as CSW backend.

### ISSUE THREAD

**Issue by cristianzamar** [GeoNode/geonode#2123]
I have version 2.4b24 installed from ppa:geonode/testing repository and have set GeoNetwork 2.10.4 as the CSW backend.
When I try to upload a doc or a layer I get the following error:

`File "/usr/local/lib/python2.7/dist-packages/geonode/catalogue/backends/generic.py", line 90, in login
doc = etree.fromstring(response.read())
File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src/lxml/lxml.etree.c:68106)
File "parser.pxi", line 1785, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102455)
File "parser.pxi", line 1673, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:101284)
File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:96466)
File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91275)
File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92461)
File "parser.pxi", line 622, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91757)
XMLSyntaxError: Opening and ending tag mismatch: link line 7 and head, line 12, column 9`

I also tried [this tweak](http://osgeo-org.1560.x6.nabble.com/XML-Login-Service-in-Geonetwork-2-10-td5064670.html) but it didn't work either. And using GN 2.8.0 I get this:

`File "/usr/local/lib/python2.7/dist-packages/geonode/catalogue/models.py", line 98, in catalogue_pre_save
msg = 'Could not connect to catalogue to save information for layer "%s"' % instance.name
AttributeError: 'Document' object has no attribute 'name'`

I commented that line as it was an error message and then I get this:
`File "/usr/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 185, in send
response = receiver(signal=self, sender=sender, **named)
File "/usr/local/lib/python2.7/dist-packages/geonode/catalogue/models.py", line 100, in catalogue_pre_save
raise err
HTTPError: HTTP Error 500: Error Interno del Servidor`

Any ideas on how to fix this?? 
I would be glad to participate as a tester and then maybe as a developer on this great project.

**Comment by tomkralidis** [comment]
I'll take a look. GeoNetwork now has different endpoints for discovery and publication, and we haven't updated GeoNode to support both, so I'm guessing the issue is rooted here.

**Comment by sefadolunay** [comment]
I am also getting a similar error when I try to upload a layer using Geonetwork as backend. My versions are;

- geonetwork: 3.2.1.0 (as for 02.05.17, latest stable)
- geonode: 2.6a1

Encountered error is:
```
Opening and ending tag mismatch: link line 18 and head, line 19, column 11 (line 19)
Traceback (most recent call last):
  File "/home/geonode/geonode/geonode/layers/views.py", line 168, in layer_upload
    metadata_uploaded_preserve=form.cleaned_data["metadata_uploaded_preserve"]
  File "/home/geonode/geonode/geonode/layers/utils.py", line 499, in file_upload
    defaults=defaults
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/modeltranslation/manager.py", line 389, in get_or_create
    return super(MultilingualQuerySet, self).get_or_create(**kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 407, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 439, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/lib/python2.7/site-packages/modeltranslation/manager.py", line 381, in create
    return super(MultilingualQuerySet, self).create(**kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/lib/python2.7/site-packages/polymorphic/models.py", line 72, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 758, in save_base
    update_fields=update_fields)
  File "/usr/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/geonode/geonode/geonode/catalogue/models.py", line 110, in catalogue_pre_save
    record = catalogue.get_record(instance.uuid)
  File "/home/geonode/geonode/geonode/catalogue/backends/generic.py", line 395, in get_record
    with self.catalogue:
  File "/home/geonode/geonode/geonode/catalogue/backends/generic.py", line 70, in __enter__
    self.login()
  File "/home/geonode/geonode/geonode/catalogue/backends/generic.py", line 90, in login
    doc = etree.fromstring(response.read())
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79010)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118341)
  File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117021)
  File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:111265)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105671)
XMLSyntaxError: Opening and ending tag mismatch: link line 18 and head, line 19, column 11 (line 19)
[02/May/2017 02:59:43] "POST /layers/upload HTTP/1.1" 400 3450
```

My local_settings.py;

```
CATALOGUE = {
    'default': {
        # The underlying CSW implementation
        # default is pycsw in local mode (tied directly to GeoNode Django DB)
        # 'ENGINE': 'geonode.catalogue.backends.pycsw_local',
        # pycsw in non-local mode
        # 'ENGINE': 'geonode.catalogue.backends.pycsw_http',
        # GeoNetwork opensource
        'ENGINE': 'geonode.catalogue.backends.geonetwork',
        # deegree and others
        # 'ENGINE': 'geonode.catalogue.backends.generic',

        # The FULLY QUALIFIED base url to the CSW instance for this GeoNode
        # 'URL': '%scatalogue/csw' % SITEURL,
        'URL': 'http://localhost:8080/geonetwork/srv/en/csw',
        # 'URL': 'http://localhost:8080/deegree-csw-demo-3.0.4/services',

        # login credentials (for GeoNetwork)
        'USER': 'admin',
        'PASSWORD': 'admin',
    }
}
```
