### ISSUE TITLE
Internal Server Error when deleting group  via admin panel in 2.4

### ISSUE THREAD

**Issue by rajanski** [GeoNode/geonode#2140]
Hi i keep getting an internal server error when deleting a group (in this cae "anonymous"  via the django admin panel:

apache.log says:

```shell
[Mon May 04 05:39:14.822648 2015] [:error] [pid 2025:tid 140618226833152] Internal Server Error: /admin/auth/group/
[Mon May 04 05:39:14.822701 2015] [:error] [pid 2025:tid 140618226833152] Traceback (most recent call last):
[Mon May 04 05:39:14.822713 2015] [:error] [pid 2025:tid 140618226833152]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
[Mon May 04 05:39:14.822724 2015] [:error] [pid 2025:tid 140618226833152]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Mon May 04 05:39:14.822734 2015] [:error] [pid 2025:tid 140618226833152]   File "/usr/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 461, in wrapper
[Mon May 04 05:39:14.822745 2015] [:error] [pid 2025:tid 140618226833152]     return self.admin_site.admin_view(view)(*args, **kwargs)
[Mon May 04 05:39:14.822755 2015] [:error] [pid 2025:tid 140618226833152]   File "/usr/lib/python2.7/dist-packages/django/utils/decorators.py", line 99, in _wrapped_view
[Mon May 04 05:39:14.822779 2015] [:error] [pid 2025:tid 140618226833152]     response = view_func(request, *args, **kwargs)
[Mon May 04 05:39:14.822791 2015] [:error] [pid 2025:tid 140618226833152]   File "/usr/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
[Mon May 04 05:39:14.822801 2015] [:error] [pid 2025:tid 140618226833152]     response = view_func(request, *args, **kwargs)
[Mon May 04 05:39:14.822811 2015] [:error] [pid 2025:tid 140618226833152]   File "/usr/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 198, in inner
[Mon May 04 05:39:14.822822 2015] [:error] [pid 2025:tid 140618226833152]     return view(request, *args, **kwargs)
[Mon May 04 05:39:14.822832 2015] [:error] [pid 2025:tid 140618226833152]   File "/usr/lib/python2.7/dist-packages/django/utils/decorators.py", line 29, in _wrapper
[Mon May 04 05:39:14.822842 2015] [:error] [pid 2025:tid 140618226833152]     return bound_func(*args, **kwargs)
[Mon May 04 05:39:14.822855 2015] [:error] [pid 2025:tid 140618226833152]   File "/usr/lib/python2.7/dist-packages/django/utils/decorators.py", line 99, in _wrapped_view
[Mon May 04 05:39:14.822865 2015] [:error] [pid 2025:tid 140618226833152]     response = view_func(request, *args, **kwargs)
[Mon May 04 05:39:14.822876 2015] [:error] [pid 2025:tid 140618226833152]   File "/usr/lib/python2.7/dist-packages/django/utils/decorators.py", line 25, in bound_func
[Mon May 04 05:39:14.822886 2015] [:error] [pid 2025:tid 140618226833152]     return func(self, *args2, **kwargs2)
[Mon May 04 05:39:14.822896 2015] [:error] [pid 2025:tid 140618226833152]   File "/usr/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1376, in changelist_view
[Mon May 04 05:39:14.822907 2015] [:error] [pid 2025:tid 140618226833152]     response = self.response_action(request, queryset=cl.get_queryset(request))
[Mon May 04 05:39:14.822917 2015] [:error] [pid 2025:tid 140618226833152]   File "/usr/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1113, in response_action
[Mon May 04 05:39:14.822927 2015] [:error] [pid 2025:tid 140618226833152]     response = func(self, request, queryset)
[Mon May 04 05:39:14.822938 2015] [:error] [pid 2025:tid 140618226833152]   File "/usr/lib/python2.7/dist-packages/django/contrib/admin/actions.py", line 48, in delete_selected
[Mon May 04 05:39:14.822950 2015] [:error] [pid 2025:tid 140618226833152]     queryset.delete()
[Mon May 04 05:39:14.822976 2015] [:error] [pid 2025:tid 140618226833152]   File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 465, in delete
[Mon May 04 05:39:14.822986 2015] [:error] [pid 2025:tid 140618226833152]     collector.delete()
[Mon May 04 05:39:14.822996 2015] [:error] [pid 2025:tid 140618226833152]   File "/usr/lib/python2.7/dist-packages/django/db/models/deletion.py", line 255, in delete
[Mon May 04 05:39:14.823005 2015] [:error] [pid 2025:tid 140618226833152]     sender=model, instance=obj, using=self.using
[Mon May 04 05:39:14.823015 2015] [:error] [pid 2025:tid 140618226833152]   File "/usr/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 185, in send
[Mon May 04 05:39:14.823025 2015] [:error] [pid 2025:tid 140618226833152]     response = receiver(signal=self, sender=sender, **named)
[Mon May 04 05:39:14.823035 2015] [:error] [pid 2025:tid 140618226833152]   File "/usr/local/lib/python2.7/dist-packages/geonode/groups/models.py", line 262, in group_pre_delete
[Mon May 04 05:39:14.823062 2015] [:error] [pid 2025:tid 140618226833152]     not permitted as will break the geonode permissions system')
[Mon May 04 05:39:14.823072 2015] [:error] [pid 2025:tid 140618226833152] Exception: Deletion of the anonymous group is         not permitted as will break the geonode permissions system
[Mon May 04 05:39:14.833620 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440] mod_wsgi (pid=2025): Exception occurred processing WSGI script '/var/www/geonode/wsgi/geonode.wsgi'.
[Mon May 04 05:39:14.833649 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440] Traceback (most recent call last):
[Mon May 04 05:39:14.833687 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 206, in __call__
[Mon May 04 05:39:14.833717 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]     response = self.get_response(request)
[Mon May 04 05:39:14.833735 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 194, in get_response
[Mon May 04 05:39:14.833776 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
[Mon May 04 05:39:14.833794 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 236, in handle_uncaught_exception
[Mon May 04 05:39:14.833818 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]     return callback(request, **param_dict)
[Mon May 04 05:39:14.833834 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]   File "/usr/lib/python2.7/dist-packages/django/utils/decorators.py", line 99, in _wrapped_view
[Mon May 04 05:39:14.833874 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]     response = view_func(request, *args, **kwargs)
[Mon May 04 05:39:14.833891 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]   File "/usr/lib/python2.7/dist-packages/django/views/defaults.py", line 46, in server_error
[Mon May 04 05:39:14.833915 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]     return http.HttpResponseServerError(template.render(Context({})))
[Mon May 04 05:39:14.833932 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
[Mon May 04 05:39:14.834004 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]     return self._render(context)
[Mon May 04 05:39:14.834275 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
[Mon May 04 05:39:14.834316 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]     return self.nodelist.render(context)
[Mon May 04 05:39:14.834341 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
[Mon May 04 05:39:14.834381 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]     bit = self.render_node(node, context)
[Mon May 04 05:39:14.834399 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
[Mon May 04 05:39:14.834421 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]     return node.render(context)
[Mon May 04 05:39:14.834438 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]   File "/usr/lib/python2.7/dist-packages/django/template/loader_tags.py", line 53, in render
[Mon May 04 05:39:14.834476 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]     result = self.nodelist.render(context)
[Mon May 04 05:39:14.834493 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
[Mon May 04 05:39:14.834515 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]     bit = self.render_node(node, context)
[Mon May 04 05:39:14.834532 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
[Mon May 04 05:39:14.834569 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]     return node.render(context)
[Mon May 04 05:39:14.834586 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]   File "/usr/lib/python2.7/dist-packages/announcements/templatetags/announcements_tags.py", line 24, in render
[Mon May 04 05:39:14.834610 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]     request = context["request"]
[Mon May 04 05:39:14.834626 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]   File "/usr/lib/python2.7/dist-packages/django/template/context.py", line 56, in __getitem__
[Mon May 04 05:39:14.834663 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440]     raise KeyError(key)
[Mon May 04 05:39:14.834684 2015] [:error] [pid 2025:tid 140618226833152] [remote 10.0.2.2:26440] KeyError: 'request'


```

**Comment by rajanski** [comment]
ah found it: 

```
Deletion of the anonymous group is         not permitted as will break the geonode permissions system
```
closed

**Comment by simod** [comment]
@rajanski you should really not the issue tracker for this kind of issues. If you have an error ask on the mailing lists. We will open a ticket only in the case the error you found would really be a bug.
