### ISSUE TITLE
Theming Issue

### ISSUE THREAD

**Issue by phyokyi** [GeoNode/geonode#2151]
Hello,
I'm just new to GeoNode. I just install geonode on Ubuntu 12.04 desktop i386.
As guide line from quick guideline
$ sudo add-apt-repository ppa:geonode/release
$ sudo apt-get update
$ sudo apt-get install geonode

After that i assign ip, and create superuser. it was done smoothly.

Since my job is to change theme of geonode, i trying to change theme.
I try to change base.html under template folder as guideline say.
Then I try to restart the geonode by using following command.
python manage.py restartserver.
it say it can't find manage.py. then i go to under following folder.
/usr/lib/python2.7/dist-packages/django/conf/project_template/
then i found manage.py, then try to restart.
but i got error after that....
/usr/lib/python2.7/dist-packages/django/conf/project_template# python manage.py restartserver
Traceback (most recent call last):
 File "manage.py", line 10, in <module>
   execute_from_command_line(sys.argv)
 File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
   utility.execute()
 File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
   self.fetch_command(subcommand).run_from_argv(self.argv)
 File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 263, in fetch_command
   app_name = get_commands()[subcommand]
 File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 109, in get_commands
   apps = settings.INSTALLED_APPS
 File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 53, in _getattr_
   self._setup(name)
 File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in _setup
   self._wrapped = Settings(settings_module)
 File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 134, in _init_
   raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings '{{ project_name }}.settings' (Is it on sys.path?): No module named {{ project_name }}.settings
root@sunny:/usr/lib/python2.7/dist-packages/django/conf/project_template#

How can I do? Please help me....

**Comment by simod** [comment]
Hi, I strongly suggest you to use the geonode_project to style your geonode https://github.com/GeoNode/geonode-project. For the templates there's no need to restart the server but in any case is apache that is running geonode so the command is $ sudo service apache2 restart.

Please use the users mailing list to ask for support geonode-users@lists.osgeo.org.

Hope this helps
