### ISSUE TITLE
Same file formats listed multiple times when downloading a layer

### ISSUE THREAD

**Issue by allspatial** [GeoNode/geonode#2197]
When clicking the "Download Layer" button the same file formats are listed repeatedly. This seems to occur only with raster layers:
![bug](https://cloud.githubusercontent.com/assets/12534211/8330021/635eeac2-1a8f-11e5-9e87-1d0896794bc8.png)
I am using GeoNode 2.4b25 on Ubuntu 14.04.

**Comment by capooti** [comment]
which version are you using?
this used to happen with GeoNode 2.0, when changing the SITE_URL setting.
With GeoNode 2.4 this should not happen as it has been fixed, anyway you can truncate the link table and run the updatelayers command and you should be fine.

**Comment by allspatial** [comment]
I am using GeoNode 2.4b25 on Ubuntu 14.04. Truncating the link table and running "geonode updatelayers" results in the error as follows:

Traceback (most recent call last):
  File "/usr/bin/django-admin", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/management/commands/updatelayers.py", line 108, in handle
    remove_deleted=remove_deleted)
  File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/helpers.py", line 444, in gs_slurp
    if not created and settings.SITEURL not in layer.link_set.metadata()[0].url:
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
Exception: ('Failed to process laplata_buildings', IndexError('list index out of range',))

  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
Exception: ('Failed to process laplata_buildings', IndexError('list index out of range',))

**Comment by capooti** [comment]
This was fixed here:
https://github.com/GeoNode/geonode/commit/5b9f07bbc074c0224b5b0c3682bb0388b27014d8#diff-c0e1c8cea0b01d04a691f88381580c4fR452

you may manually patch the file, sorry about it.
@simod may be the good time for 2.4b26

@allspatial is my idea correct that you changed the SITE_URL parameter to a new value? Just to try to replicate the bug

**Comment by allspatial** [comment]
I only used the "geonode-updateip" command to set the IP address to the one my server. And I will apply the patch mentioned.

**Comment by capooti** [comment]
yes, that command changes the SITE_URL setting. Thanks for the info, I will investigate into this.

**Comment by sbsimo** [comment]
I tested the issue both locally and on demo.geonode.org (version 2.4 rc2): it's not applicable anymore.
