### ISSUE TITLE
Object ImportError: No module named related

### ISSUE THREAD

**Issue by enricofer** [GeoNode/geonode#2330]
On a clean Ubuntu 14.04 setting up geonode with sudo geonode-updateip 127.0.0.1 I get exception:

Restarting web server apache2                                               AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the ServerName directive globally to suppress this message
                                                                        [ OK ]
Traceback (most recent call last):
  File "/usr/local/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/polymorphic/__init__.py", line 11, in <module>
    from .polymorphic_model import PolymorphicModel
  File "/usr/lib/python2.7/dist-packages/polymorphic/polymorphic_model.py", line 22, in <module>
    from .base import PolymorphicModelBase
  File "/usr/lib/python2.7/dist-packages/polymorphic/base.py", line 15, in <module>
    from .manager import PolymorphicManager
  File "/usr/lib/python2.7/dist-packages/polymorphic/manager.py", line 8, in <module>
    from polymorphic.query import PolymorphicQuerySet
  File "/usr/lib/python2.7/dist-packages/polymorphic/query.py", line 13, in <module>
    from .query_translate import translate_polymorphic_filter_definitions_in_kwargs, translate_polymorphic_filter_definitions_in_args
  File "/usr/lib/python2.7/dist-packages/polymorphic/query_translate.py", line 10, in <module>
    from django.db.models.related import RelatedObject
ImportError: No module named related
Traceback (most recent call last):
  File "/usr/local/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/polymorphic/__init__.py", line 11, in <module>
    from .polymorphic_model import PolymorphicModel
  File "/usr/lib/python2.7/dist-packages/polymorphic/polymorphic_model.py", line 22, in <module>
    from .base import PolymorphicModelBase
  File "/usr/lib/python2.7/dist-packages/polymorphic/base.py", line 15, in <module>
    from .manager import PolymorphicManager
  File "/usr/lib/python2.7/dist-packages/polymorphic/manager.py", line 8, in <module>
    from polymorphic.query import PolymorphicQuerySet
  File "/usr/lib/python2.7/dist-packages/polymorphic/query.py", line 13, in <module>
    from .query_translate import translate_polymorphic_filter_definitions_in_kwargs, translate_polymorphic_filter_definitions_in_args
  File "/usr/lib/python2.7/dist-packages/polymorphic/query_translate.py", line 10, in <module>
    from django.db.models.related import RelatedObject
ImportError: No module named related

**Comment by simod** [comment]
hi, you probably have the wrong django version, make sure to install the 1.6.11.

Ps please ask on the mailing lists before opening tickets here.

Regards

**Comment by enricofer** [comment]
You are right! I have django 1.8. Sorry!
