### ISSUE TITLE
Error uploading XML metadata

### ISSUE THREAD

**Issue by pmdias** [GeoNode/geonode#2385]
While uploading a shapefile with a metadata XML file and using the "preserve metadata xml" option, I'm getting the error

```
'constraints_use' is an invalid keyword argument for this function
```

and the complete traceback:
```
Traceback (most recent call last):
  File "/home/vagrant/development/geonode/geonode/layers/views.py", line 164, in layer_upload
    metadata_uploaded_preserve=form.cleaned_data["metadata_uploaded_preserve"]
  File "/home/vagrant/development/geonode/geonode/layers/utils.py", line 478, in file_upload
    defaults=defaults
  File "/home/vagrant/.venvs/localcatalogue/local/lib/python2.7/site-packages/django/db/models/manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "/home/vagrant/.venvs/localcatalogue/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 341, in get_or_create
    return super(MultilingualQuerySet, self).get_or_create(**kwargs)
  File "/home/vagrant/.venvs/localcatalogue/local/lib/python2.7/site-packages/django/db/models/query.py", line 381, in get_or_create
    obj = self.model(**params)
  File "/home/vagrant/.venvs/localcatalogue/local/lib/python2.7/site-packages/modeltranslation/translator.py", line 213, in new_init
    old_init(self, *args, **kwargs)
  File "/home/vagrant/.venvs/localcatalogue/local/lib/python2.7/site-packages/modeltranslation/translator.py", line 213, in new_init
    old_init(self, *args, **kwargs)
  File "/home/vagrant/.venvs/localcatalogue/local/lib/python2.7/site-packages/polymorphic/polymorphic_model.py", line 163, in __init__
    super(PolymorphicModel, self).__init__(*args, ** kwargs)
  File "/home/vagrant/.venvs/localcatalogue/local/lib/python2.7/site-packages/django/db/models/base.py", line 417, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'constraints_use' is an invalid keyword argument for this function
```

If I delete/comment out the following element from the metadata XML

```xml
<gmd:resourceConstraints>
  <gmd:MD_SecurityConstraints>
    <gmd:classification>
      <gmd:MD_ClassificationCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml#MD_ClassificationCode" codeListValue="topSecret">topSecret</gmd:MD_ClassificationCode>
    </gmd:classification>
  </gmd:MD_SecurityConstraints>
</gmd:resourceConstraints>
```
The error no longer shows up.

It seems that Geonode is trying to save the security constraints field into the database but that field doesn't exists in the models. I'm a bit confused by this error as the pycsw backend also defines a mapping to a `securityconstraints` field, but that field is missing.

**Comment by tomkralidis** [comment]
@pmdias thanks for the report.  In a GeoNode context we do not support `constraints_use` (not sure how this got in the code).  I've removed this from master so this is simply ignored.  Can you verify your upload use case now works?

**Comment by pmdias** [comment]
Thanks @tomkralidis , the upload is working now. I'm closing the issue as it seems that this is solved.
