### ISSUE TITLE
GeoNode 2.4 Install Problem in ubuntu 14.04

### ISSUE THREAD

**Issue by mingmingbaibai2015** [GeoNode/geonode#2439]
I have a ubuntu 14.04 server. I upgraded server from 12.04.
After I tried to install geonode 2.4 from ppa:geonode/stable repository.
But install operation failed with error.
So I tried to install geonode 2.4 from ppa:geonode/testing repository.
But also failed.
Error is equal with stable.
I tried to reinstall, but also equal error.
How I install geonode 2.4 in my server?
Please help me.

host# apt-get install geonode --reinstall
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 1 not upgraded.
1 not fully installed or removed.
Need to get 0 B/4,172 kB of archives.
After this operation, 0 B of additional disk space will be used.
Selecting previously unselected package geonode.
(Reading database ... 161950 files and directories currently installed.)
Preparing to unpack .../geonode_2.4.0+thefinal0_all.deb ...
Unpacking geonode (2.4.0+thefinal0) over (2.4.0+thefinal0) ...
Setting up geonode (2.4.0+thefinal0) ...
Sourcing /usr/share/geonode/config-post.sh as the configuration file
	Step: 'post specified
Running GeoNode postinstall ...
Not enabling BingMaps base layer as a BING_API_KEY is not defined in local_settings.py file.
Traceback (most recent call last):
  File "/usr/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 284, in execute
    self.validate()
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/usr/lib/python2.7/dist-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/modeltranslation/models.py", line 84, in <module>
    handle_translation_registrations()
  File "/usr/lib/python2.7/dist-packages/modeltranslation/models.py", line 80, in handle_translation_registrations
    autodiscover()
  File "/usr/lib/python2.7/dist-packages/modeltranslation/models.py", line 31, in autodiscover
    import_module(module)
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/geonode/base/translation.py", line 25, in <module>
    translator.register(TopicCategory, TopicCategoryTranslationOptions)
  File "/usr/lib/python2.7/dist-packages/modeltranslation/translator.py", line 398, in register
    for related_obj in model._meta.get_all_related_objects():
  File "/usr/lib/python2.7/dist-packages/django/db/models/options.py", line 454, in get_all_related_objects
    include_proxy_eq=include_proxy_eq)]
  File "/usr/lib/python2.7/dist-packages/django/db/models/options.py", line 466, in get_all_related_objects_with_model
    self._fill_related_objects_cache()
  File "/usr/lib/python2.7/dist-packages/django/db/models/options.py", line 489, in _fill_related_objects_cache
    for klass in get_models(include_auto_created=True, only_installed=False):
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 232, in get_models
    self._populate()
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/announcements/models.py", line 13, in <module>
    User = get_user_model()
  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 127, in get_user_model
    user_model = get_model(app_label, model_name)
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 271, in get_model
    self._populate()
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/actstream/models.py", line 22, in <module>
    User = get_user_model()
  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 127, in get_user_model
    user_model = get_model(app_label, model_name)
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 271, in get_model
    self._populate()
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/geonode/upload/models.py", line 28, in <module>
    from geonode.geoserver.helpers import gs_uploader, ogc_server_settings
  File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/helpers.py", line 1587, in <module>
    ogc_server_settings = OGC_Servers_Handler(settings.OGC_SERVER)['default']
  File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/helpers.py", line 1376, in __getitem__
    self.ensure_valid_configuration(alias)
  File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/helpers.py", line 1346, in ensure_valid_configuration
    raise ImproperlyConfigured("The PRINTNG_ENABLED setting has been removed, use 'PRINT_NG_ENABLED' instead.")
django.core.exceptions.ImproperlyConfigured: The PRINTNG_ENABLED setting has been removed, use 'PRINT_NG_ENABLED' instead.
Not enabling BingMaps base layer as a BING_API_KEY is not defined in local_settings.py file.
Site 000-default already disabled
Considering dependency proxy for proxy_http:
Module proxy already enabled
Module proxy_http already enabled
ERROR: Site geonode does not exist!
 * Restarting web server apache2                                                                         [ OK ] 
 * Stopping Tomcat servlet engine tomcat7                                                                [ OK ] 
 * Starting Tomcat servlet engine tomcat7                                                                [ OK ] 
 * Restarting web server apache2                                                                         [ OK ] 

host# geonode createsuperuser
Not enabling BingMaps base layer as a BING_API_KEY is not defined in local_settings.py file.
Traceback (most recent call last):
  File "/usr/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 76, in load_command_class
    return module.Command()
  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/management/commands/createsuperuser.py", line 26, in __init__
    self.UserModel = get_user_model()
  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 127, in get_user_model
    user_model = get_model(app_label, model_name)
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 271, in get_model
    self._populate()
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/modeltranslation/models.py", line 84, in <module>
    handle_translation_registrations()
  File "/usr/lib/python2.7/dist-packages/modeltranslation/models.py", line 80, in handle_translation_registrations
    autodiscover()
  File "/usr/lib/python2.7/dist-packages/modeltranslation/models.py", line 31, in autodiscover
    import_module(module)
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/geonode/base/translation.py", line 25, in <module>
    translator.register(TopicCategory, TopicCategoryTranslationOptions)
  File "/usr/lib/python2.7/dist-packages/modeltranslation/translator.py", line 398, in register
    for related_obj in model._meta.get_all_related_objects():
  File "/usr/lib/python2.7/dist-packages/django/db/models/options.py", line 454, in get_all_related_objects
    include_proxy_eq=include_proxy_eq)]
  File "/usr/lib/python2.7/dist-packages/django/db/models/options.py", line 466, in get_all_related_objects_with_model
    self._fill_related_objects_cache()
  File "/usr/lib/python2.7/dist-packages/django/db/models/options.py", line 489, in _fill_related_objects_cache
    for klass in get_models(include_auto_created=True, only_installed=False):
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 232, in get_models
    self._populate()
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/announcements/models.py", line 13, in <module>
    User = get_user_model()
  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 127, in get_user_model
    user_model = get_model(app_label, model_name)
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 271, in get_model
    self._populate()
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/actstream/models.py", line 22, in <module>
    User = get_user_model()
  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 127, in get_user_model
    user_model = get_model(app_label, model_name)
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 271, in get_model
    self._populate()
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/usr/lib/python2.7/dist-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/geonode/upload/models.py", line 28, in <module>
    from geonode.geoserver.helpers import gs_uploader, ogc_server_settings
  File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/helpers.py", line 1587, in <module>
    ogc_server_settings = OGC_Servers_Handler(settings.OGC_SERVER)['default']
  File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/helpers.py", line 1376, in __getitem__
    self.ensure_valid_configuration(alias)
  File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/helpers.py", line 1346, in ensure_valid_configuration
    raise ImproperlyConfigured("The PRINTNG_ENABLED setting has been removed, use 'PRINT_NG_ENABLED' instead.")
django.core.exceptions.ImproperlyConfigured: The PRINTNG_ENABLED setting has been removed, use 'PRINT_NG_ENABLED' instead.

**Comment by simod** [comment]
Please @mingmingbaibai2015 use the mailing list geonode-users@lists.osgeo.org to ask for support.
