### ISSUE TITLE
Geonode importlayers error when metadata XML is present

### ISSUE THREAD

**Issue by dvictori** [GeoNode/geonode#2469]
Trying to populate a new geonode instance (v2.4) with some shapefiles from another geonode (v2.4).

I've placed all the shapefiles in a directory along with the metadata downloaded from the former geonode instance (ISO format, XML file, renamed to match the shapefile).
The importlayers command fails with the following message
```python
./par_a01_2013_inventoryplotsubplot.shp
  ================
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geonode/layers/utils.py", line 588, in upload
    title=title
  File "/usr/local/lib/python2.7/dist-packages/geonode/layers/utils.py", line 429, in file_upload
    vals, regions, keywords = set_metadata(xml_file.read())
  File "/usr/local/lib/python2.7/dist-packages/geonode/layers/metadata.py", line 62, in set_metadata
    vals, regions, keywords = dc2dict(exml)
  File "/usr/local/lib/python2.7/dist-packages/geonode/layers/metadata.py", line 198, in dc2dict
    vals['date'] = sniff_date(mdata.modified)
  File "/usr/local/lib/python2.7/dist-packages/geonode/layers/metadata.py", line 222, in sniff_date
    return datetime.datetime.strptime(datestr.strip(), dfmt)
AttributeError: 'NoneType' object has no attribute 'strip'
```
-------------
I attached the offending metadata XML file (renamed to txt sisnce GitHub did not like xml extension), just in case
[par_a01_2013_las_boundary.txt](https://github.com/GeoNode/geonode/files/216257/par_a01_2013_las_boundary.txt)

**Comment by tomkralidis** [comment]
Fixed in master and 2.4.x.
