### ISSUE TITLE
GeoNode installation fails with EOFError

### ISSUE THREAD

**Issue by sarasafavi** [GeoNode/geonode#2579]
The change introduced in this commit (https://github.com/GeoNode/geonode/commit/ea2b2925056a4660dfc4896b26ca95dd95180772) throws an error which causes automated provisioning/build processes to fail:

```
You are trying to change the nullable field 'layer' on attribute to non-nullable without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
1) Provide a one-off default now (will be set on all existing rows)
2) Ignore for now, and let me handle existing rows with NULL myself (e.g. because you added a RunPython or RunSQL operation to handle NULL values in a previous data migration)
3) Quit, and let me add a default in models.py
Select an option: Please select a valid option: 
Traceback (most recent call last):
  File "/vagrant/manage.py", line 30, in <module>
    
execute_from_command_line(sys.argv)
  File "/vagrant/.venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    
utility.execute()
  File "/vagrant/.venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    
self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/vagrant/.venv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    
self.execute(*args, **cmd_options)
  File "/vagrant/.venv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    
output = self.handle(*args, **options)
  File "/vagrant/.venv/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 125, in handle
    
migration_name=self.migration_name,
  File "/vagrant/.venv/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 43, in changes
    
changes = self._detect_changes(convert_apps, graph)
  File "/vagrant/.venv/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 186, in _detect_changes
    
self.generate_altered_fields()
  File "/vagrant/.venv/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 865, in generate_altered_fields
    
new_default = self.questioner.ask_not_null_alteration(field_name, model_name)
  File "/vagrant/.venv/lib/python2.7/site-packages/django/db/migrations/questioner.py", line 153, in ask_not_null_alteration
    
"Quit, and let me add a default in models.py",
  File "/vagrant/.venv/lib/python2.7/site-packages/django/db/migrations/questioner.py", line 99, in _choice_input
    
result = input("Please select a valid option: ")
EOFError
: 
EOF when reading a line
```

In the future we may want to consider restricting committing directly into master without going through a PR process; at minimum Travis CI should be allowed to sanity check things like build-fails etc (even if no additional human eyes are available to review).

**Comment by sarasafavi** [comment]
A reversion commit has been raised (#2583): if @afabiani or someone else can chime in with the intended effect of that original commit, we can work on a replacement implements the desired functionality without the bug above.

**Comment by jj0hns0n** [comment]
@sarasafavi @afabiani can you guys update us on the status of this one?

**Comment by sarasafavi** [comment]
@jj0hns0n https://github.com/GeoNode/geonode/pull/2583 (in master now) reverted the breaking commit, so installs no longer fail; closing.
