### ISSUE TITLE
Hypermap/Registry fails to discover services/layers from ArcGIS MapServer

### ISSUE THREAD

**Issue by emerkle826** [GeoNode/geonode#2639]
There's 2 parts to this issue.

Issue #1.
When adding https://services.arcgisonline.com/arcgis/rest/services/NGS_Topo_US_2D/MapServer as an Endpoint, I see the following error in the Celery logs:

> [2016-08-31 10:49:05,606: ERROR/Worker-4] local variable 'service_to_process' referenced before assignment
Traceback (most recent call last):
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/hypermap/aggregator/utils.py", line 308, in create_services_from_endpoint
    service_to_process = get_single_service(esri, url, endpoint)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/hypermap/aggregator/utils.py", line 344, in get_single_service
    return service_to_process
UnboundLocalError: local variable 'service_to_process' referenced before assignment
[2016-08-31 10:49:05,628: INFO/MainProcess] Task hypermap.aggregator.tasks.update_endpoint[00027c4a-aa00-4787-911b-2d050f7b4907] succeeded in 1.523003477s: None

Issue #2
After modifying utils.py above to initialize `service_to_process`, Registry is still unable to discover layers/servcies from:

https://services.arcgisonline.com/arcgis/rest/services/NGS_Topo_US_2D/MapServer

> [2016-08-31 11:11:51,782: INFO/MainProcess] Received task: hypermap.aggregator.tasks.update_endpoint[1da46561-2ea3-467b-bb7d-9ad344f19458]
[2016-08-31 11:11:52,063: INFO/Worker-3] Starting new HTTPS connection (1): services.arcgisonline.com
[2016-08-31 11:11:52,373: INFO/Worker-3] Starting new HTTPS connection (1): services.arcgisonline.com
[2016-08-31 11:11:52,642: INFO/Worker-3] Starting new HTTPS connection (1): services.arcgisonline.com
[2016-08-31 11:11:52,927: INFO/Worker-3] Starting new HTTPS connection (1): services.arcgisonline.com
[2016-08-31 11:11:53,695: INFO/MainProcess] Task hypermap.aggregator.tasks.update_endpoint[1da46561-2ea3-467b-bb7d-9ad344f19458] succeeded in 1.910557994s: None

**Comment by ingenieroariel** [comment]
Thanks @emerkle826.

I moved this to the cga-harvard/HHypermap repository as it is not GeoNode related: https://github.com/cga-harvard/HHypermap/issues/189
