### ISSUE TITLE
Error in running geonode via docker

### ISSUE THREAD

**Issue by sindile** [GeoNode/geonode#2686]
I am trying to run geonode via docker (this is my first attempt on using docker)

have done the following:
1. cloned the master repo
2. docker-compose build
3. docker-compose up

have ran into errors:

**geonode/django      "celery worker --app="   35 minutes ago      Exited (1) 35 minutes ago**

ran docker logs "container id"

Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/celery/**main**.py", line 30, in main
    main()
  File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/usr/local/lib/python2.7/site-packages/celery/bin/base.py", line 465, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/usr/local/lib/python2.7/site-packages/celery/bin/base.py", line 485, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/usr/local/lib/python2.7/site-packages/celery/app/utils.py", line 229, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/usr/local/lib/python2.7/site-packages/celery/bin/base.py", line 488, in symbol_by_name
    return symbol_by_name(name, imp=imp)
  File "/usr/local/lib/python2.7/site-packages/kombu/utils/**init**.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/usr/local/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
ImportError: No module named celeryapp

**geonode/geoserver   "/usr/local/tomcat/tm"   35 minutes ago      Exited (1) 35 minutes ago**

ran docker logs "container id"

cp: cannot stat ‘/geoserver_data/data/security/auth/geonodeAuthProvider/config.xml’: No such file or directory

**Comment by harts-boundless** [comment]
The `No module named celeryapp` may relate to #2682 

`config.xml` is often updated as part of a Geoserver install (e.g. as described in `docs/tutorials/install_and_admin/geonode_install/install_geoserver_application:98`, `docs/tutorials/admin/install/custom_install.txt:516` and `geonode/contrib/geosites/README.md:184` and as edited in a couple places in `scripts/cloud/fabfile.py`)

in Exchange's dev setup there is a Dockerfile for GeoServer in here: https://github.com/boundlessgeo/exchange/tree/master/docker/geoserver with an ugly inline command which does the same. (We end up basing on the tomcat image because we have to use a particular WAR file for GeoServer).

**Comment by francbartoli** [comment]
I think this is no longer happening with the latest updates so I'm going to close it
