### ISSUE TITLE
'Request bounding box has zero area' when replacing a layer or re-uploading a deleted layer

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#2717]
Geonode 2.4 on Ubuntu 16.04:

Layer > Edit Layer > Layer: Replace
Layer Info: Map extent is world. Layer not drawn.

Exit to Layers: Thumbnail image is broken.

'Open image in new tab' gives WMS error:

> The request bounding box has zero area: ReferencedEnvelope[0.0 : -1.0, 0.0 : -1.0]

Same happens if I:

1. Layer > Edit Layer > Remove
2. Layers > Upload Layers > upload the same shapefile again

Workaround:

Restart Tomcat after removing layer and before uploading again.

**Comment by jondoig** [comment]
Seems to be the same error [reported by isralopez in June](http://osgeo-org.1560.x6.nabble.com/Geoserver-upload-failed-tt5271932.html#none).

**Comment by capooti** [comment]
I cannot replicate this.

**Comment by davekennewell** [comment]
+1

I've experienced the same behaviour using geonode 2.4 on ubuntu 14.04. I haven't yet tried the "restart tomcat" workaround, but I did check write permissions for the uploaded files and this didn't seem to be the problem.

**Comment by simod** [comment]
I can replicate, it happens in production and the layer has to be replaced twice in order to show up again.

**Comment by capooti** [comment]
I tested with GN master, and the development server. In such a scenario I do not experience it

**Comment by capooti** [comment]
So it could be a problem of GN 2.4?

**Comment by jondoig** [comment]
From psql I can see that deleting the layer removes its table from geonode_data, and removes its row from geonode.layers_layer. I also see the shapefile is gone from uploaded/layers.

However on attempting to re-upload the same shapefile, the first error I see in tomcat log is:

```
23 Feb 17:19:35 ERROR [geoserver.importer] - Error occured during import
java.lang.IllegalArgumentException: Schema 'test11' already exists
        at org.geotools.jdbc.JDBCDataStore.createSchema(JDBCDataStore.java:735)
        at org.geotools.jdbc.JDBCDataStore.createSchema(JDBCDataStore.java:144)
        at org.geoserver.importer.Importer.loadIntoDataStore(Importer.java:1181)
        at org.geoserver.importer.Importer.doIndirectImport(Importer.java:960)
        at org.geoserver.importer.Importer.run(Importer.java:817)
        at org.geoserver.importer.Importer.run(Importer.java:767)
        at org.geoserver.importer.Importer$5.call(Importer.java:850)
        at org.geoserver.importer.Importer$5.call(Importer.java:844)
        at org.geoserver.importer.job.Job.call(Job.java:16)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
