### ISSUE TITLE
Error happened when upload shp files as a layer

### ISSUE THREAD

**Issue by xqx930807** [GeoNode/geonode#2951]
[15/Mar/2017 02:39:21] "GET / HTTP/1.1" 200 17297
[15/Mar/2017 02:39:21] "GET /jsi18n/ HTTP/1.1" 200 13512
[15/Mar/2017 02:39:21] "GET /lang.js HTTP/1.1" 200 10016
[15/Mar/2017 02:39:21] "GET /api/featured/ HTTP/1.1" 200 68
[15/Mar/2017 02:39:39] "GET /layers/upload HTTP/1.1" 200 30363
[15/Mar/2017 02:39:39] "GET /jsi18n/ HTTP/1.1" 200 13512
[15/Mar/2017 02:39:39] "GET /lang.js HTTP/1.1" 200 10016
[15/Mar/2017 02:39:39] "GET /static/geonode/js/upload/cookie.js HTTP/1.1" 404 1685
[15/Mar/2017 02:39:40] "GET /static/geonode/js/upload/cookie.js HTTP/1.1" 404 1685
[15/Mar/2017 02:40:02] "GET /upload/progress HTTP/1.1" 200 17
[15/Mar/2017 02:40:02] "GET /catalogue/csw?outputFormat=application%2Fxml&service=CSW&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&request=GetRecordById&version=2.0.2&elementsetname=full&id=997db35a-0952-11e7-8603-eca86baee997 HTTP/1.1" 302 0
[15/Mar/2017 02:40:02] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:02] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:02] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:02] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:02] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:02] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:02] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:02] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:02] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:02] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:02] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:02] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:02] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:02] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:03] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:03] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:03] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:03] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:03] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:03] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:03] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:03] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:03] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:03] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:03] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:03] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:03] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:03] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:03] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:03] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:03] "GET /layers/acls HTTP/1.1" 200 82
[15/Mar/2017 02:40:04] "GET /catalogue/csw?outputFormat=application%2Fxml&service=CSW&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&request=GetRecordById&version=2.0.2&elementsetname=full&id=997db35a-0952-11e7-8603-eca86baee997 HTTP/1.1" 302 0
[15/Mar/2017 02:40:04] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:04] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:04] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:04] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:04] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:04] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:04] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:04] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:04] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:04] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:04] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /upload/progress HTTP/1.1" 200 17
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "POST /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:05] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:06] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:06] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:06] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:06] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:06] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:06] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:06] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:06] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:06] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:06] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:06] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:06] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:06] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:06] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:06] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:06] "GET /catalogue/csw HTTP/1.1" 302 0
[15/Mar/2017 02:40:06] "GET /catalogue/csw HTTP/1.1" 302 0
'TooManyRedirects' object has no attribute 'reason'
Traceback (most recent call last):
  File "/home/xqx/2.4.x/geonode/layers/views.py", line 160, in layer_upload
    title=form.cleaned_data["layer_title"],
  File "/home/xqx/2.4.x/geonode/layers/utils.py", line 470, in file_upload
    defaults=defaults
  File "/home/xqx/venvs/local/lib/python2.7/site-packages/django/db/models/manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "/home/xqx/venvs/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 341, in get_or_create
    return super(MultilingualQuerySet, self).get_or_create(**kwargs)
  File "/home/xqx/venvs/local/lib/python2.7/site-packages/django/db/models/query.py", line 383, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "/home/xqx/venvs/local/lib/python2.7/site-packages/polymorphic/polymorphic_model.py", line 90, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/home/xqx/venvs/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/xqx/venvs/local/lib/python2.7/site-packages/django/db/models/base.py", line 582, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/xqx/venvs/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/xqx/2.4.x/geonode/catalogue/models.py", line 50, in catalogue_post_save
    if err.reason.errno == errno.ECONNREFUSED:
AttributeError: 'TooManyRedirects' object has no attribute 'reason'
[15/Mar/2017 02:40:06] "POST /layers/upload HTTP/1.1" 400 12047

The environment is on Ubuntu14.04.5 ,postgressql9.3postgis2.1.python2.7 virtualenv.
I have tested on GeoNode 2.6.x or 2.4.x .The error logs are similiar.

**Comment by simod** [comment]
hi, did you see any errors during the installation? it should be a setup issue as geonode has been tested a lot, especially the 2.4.

ps, do you mind moving this to geonode-users@lists.osgeo.org?

**Comment by xqx930807** [comment]
okay, I have subscribed to the geonode maillist just now.

however,  during the installation there is no errors to report.
