### ISSUE TITLE
Upload Layer Issue

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2975]
I'm getting the following issue when uploading a shapefile using webui and importlayers.  Django will create a layer object, but a layer won't be created in GeoServer.  Looks like a geofence sync issue.

```
2017-03-27 20:34:45.050:WARN:oejs.ServletHandler:/geoserver/geofence/rest/rules
org.geoserver.geofence.core.dao.DuplicateKeyException: Duplicate Rule Rule[id:null pri:0 ws:geonode l:nepal_tracks acc:ALLOW]
	at org.geoserver.geofence.core.dao.impl.RuleDAOImpl.persist(RuleDAOImpl.java:55)
	at org.geoserver.geofence.core.dao.impl.RuleDAOImpl.persist(RuleDAOImpl.java:31)
	at sun.reflect.GeneratedMethodAccessor292.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy58.persist(Unknown Source)
	at org.geoserver.geofence.services.RuleAdminServiceImpl.insert(RuleAdminServiceImpl.java:63)
	at org.geoserver.geofence.rest.RulesRestController.insert(RulesRestController.java:134)
	at sun.reflect.GeneratedMethodAccessor291.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

```

**Comment by simod** [comment]
@pjdufour I guess you are on master. It requires rabbitmq at the moment in order to load the layers. That gs warning is not a big deal I think

**Comment by afabiani** [comment]
Please have a look at

https://github.com/GeoNode/geonode/pull/3032
