### ISSUE TITLE
Stores with Spaces in the name cause problems

### ISSUE THREAD

**Issue by smaranh** [GeoNode/geonode#303]
smaranh@ignatius:~$ geonode updatelayers
Inspecting the available layers in GeoServer ...
Traceback (most recent call last):
  File "/var/lib/geonode/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/var/lib/geonode/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 429, in execute_from_command_line
    utility.execute()
  File "/var/lib/geonode/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/django/core/management/base.py", line 218, in execute
    output = self.handle(_args, *_options)
  File "/var/lib/geonode/src/GeoNodePy/geonode/maps/management/commands/updatelayers.py", line 21, in handle
    output = Layer.objects.slurp(ignore_errors, verbosity)
  File "/var/lib/geonode/src/GeoNodePy/geonode/maps/models.py", line 607, in slurp
    resources = cat.get_resources()
  File "/var/lib/geonode/src/gsconfig.py/src/geoserver/catalog.py", line 353, in get_resources
    resources.extend(self.get_resources(workspace=ws))
  File "/var/lib/geonode/src/gsconfig.py/src/geoserver/catalog.py", line 349, in get_resources
    resources.extend(self.get_resources(store))
  File "/var/lib/geonode/src/gsconfig.py/src/geoserver/catalog.py", line 345, in get_resources
    return store.get_resources()
  File "/var/lib/geonode/src/gsconfig.py/src/geoserver/store.py", line 46, in get_resources
    xml = self.catalog.get_xml(res_url)
  File "/var/lib/geonode/src/gsconfig.py/src/geoserver/catalog.py", line 120, in get_xml
    raise FailedRequestError("Tried to make a GET request to %s but got a %d status code: \n%s" % (url, response.status, content))
geoserver.catalog.FailedRequestError: Tried to make a GET request to http://ignatius.iplantcollaborative.org/geoserver/rest/workspaces/geonode/datastores/Davis Species/featuretypes.xml but got a 404 status code: 
No such datastore: geonode,Davis

**Comment by besufikad** [comment]
why GeoNode store shape  files in GeoNode database

**Comment by besufikad** [comment]
python : can't open file manage.py
