### ISSUE TITLE
Create Group Fail if exist Group Category with special char

### ISSUE THREAD

**Issue by federicogodan** [GeoNode/geonode#3204]
Hi, if a Group Category name has a special char (as á,é,í, etc.) when try to create a group the next error is throw:
```
Traceback (most recent call last):
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/federicogodan/Workspace/geodata/geonode/geonode/groups/views.py", line 77, in group_create
    }, context_instance=RequestContext(request))
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/debug.py", line 89, in render
    output = self.filter_expression.resolve(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 675, in resolve
    new_obj = func(obj, *arg_vals)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django_forms_bootstrap/templatetags/bootstrap_tags.py", line 28, in as_bootstrap
    return template.render(c)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/loader_tags.py", line 159, in render
    return template.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 212, in render
    return self._render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/template/debug.py", line 92, in render
    output = force_text(output)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/utils/encoding.py", line 92, in force_text
    s = six.text_type(s)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/utils/html.py", line 390, in <lambda>
    klass.__unicode__ = lambda self: mark_safe(klass_unicode(self))
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/forms/forms.py", line 537, in __str__
    return self.as_widget()
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/forms/forms.py", line 593, in as_widget
    return force_text(widget.render(name, self.value(), attrs=attrs))
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/forms/widgets.py", line 585, in render
    options = self.render_options(choices, value)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/forms/widgets.py", line 539, in render_options
    for option_value, option_label in chain(self.choices, choices):
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/forms/models.py", line 1108, in __iter__
    yield self.choice(obj)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/forms/models.py", line 1115, in choice
    return (self.field.prepare_value(obj), self.field.label_from_instance(obj))
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/forms/models.py", line 1186, in label_from_instance
    return smart_text(obj)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/utils/encoding.py", line 56, in smart_text
    return force_text(s, encoding, strings_only, errors)
  File "/home/federicogodan/.virtualenvs/geonode_python2/lib/python2.7/site-packages/django/utils/encoding.py", line 94, in force_text
    s = six.text_type(bytes(s), encoding, errors)
  File "/home/federicogodan/Workspace/geodata/geonode/geonode/groups/models.py", line 49, in __str__
    return 'Category: {}'.format(self.name)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 7: ordinal not in range(128)
```
Checked in branch master and 2.7.x

**Comment by federicogodan** [comment]
```python
    def __str__(self):
        return 'Category: {}'.format(self.name)
```
This fixes the issue but may be occurring elsewhere in the code
