### ISSUE TITLE
error in development installation: ImportError: cannot import name GroupCategory

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#3218]
This is happening when installing GN with development setup.

How to replicate it (in ubuntu 16.04):

$ virtualenv --no-site-packages env
$ . env/bin/activate
$ git clone https://github.com/GeoNode/geonode.git
$ cd geonode
$ git checkout -b 2.6.x tags/2.6.x
$ pip install pygdal==1.10.1
$ pip install -e .
$ ./manage.py syncdb
Traceback (most recent call last):
  File "./manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/env_261/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/env_261/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/vagrant/env_261/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/env_261/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/vagrant/env_261/local/lib/python2.7/site-packages/modeltranslation/apps.py", line 11, in ready
    handle_translation_registrations()
  File "/home/vagrant/env_261/local/lib/python2.7/site-packages/modeltranslation/models.py", line 81, in handle_translation_registrations
    autodiscover()
  File "/home/vagrant/env_261/local/lib/python2.7/site-packages/modeltranslation/models.py", line 32, in autodiscover
    import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/geonode/geonode/geonode/groups/translation.py", line 23, in <module>
ImportError: cannot import name GroupCategory

**Comment by capooti** [comment]
I had a wrong setup. closing it

**Comment by francbartoli** [comment]
For anybody who is having this error the procedure to remove all .pyc files is below:

`paver reset_hard`
