### ISSUE TITLE
NoReverseMatch at / login as admin

### ISSUE THREAD

**Issue by sindile** [GeoNode/geonode#3467]
Environment:

Request Method: GET
Request URL: http://172.17.0.1/

Django Version: 1.8.18
Python Version: 2.7.9
Installed Applications:
('modeltranslation',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.sitemaps',
 'django.contrib.staticfiles',
 'django.contrib.messages',
 'django.contrib.humanize',
 'django.contrib.gis',
 'pagination',
 'taggit',
 'treebeard',
 'friendlytagloader',
 'geoexplorer',
 'leaflet',
 'django_extensions',
 'autocomplete_light',
 'mptt',
 'storages',
 'floppyforms',
 'pinax_theme_bootstrap',
 'django_forms_bootstrap',
 'account',
 'avatar',
 'dialogos',
 'agon_ratings',
 'announcements',
 'actstream',
 'user_messages',
 'tastypie',
 'polymorphic',
 'guardian',
 'oauth2_provider',
 'corsheaders',
 'geonode.contrib.metadataxsl',
 'geonode.contrib.api_basemaps',
 'geonode.people',
 'geonode.base',
 'geonode.layers',
 'geonode.maps',
 'geonode.proxy',
 'geonode.security',
 'geonode.social',
 'geonode.catalogue',
 'geonode.documents',
 'geonode.api',
 'geonode.groups',
 'geonode.services',
 'geonode.geoserver',
 'geonode.upload',
 'geonode.tasks',
 'geonode.messaging',
 'pinax.notifications')
Installed Middleware:
('corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'pagination.middleware.PaginationMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'oauth2_provider.middleware.OAuth2TokenMiddleware')

Template error:
In template /usr/src/app/geonode/templates/base.html, error at line 101
   Reverse for 'account_invite_user' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

   91 :               <ul class="dropdown-menu">

   92 :                 <li><a href="{% url "profile_browse" %}">{% trans "People" %}</a></li>

   93 :                 <li><a href="{% url "group_list" %}">{% trans "Groups" %}</a></li>

   94 :                 <li><a href="{% url "group_category_list" %}">{% trans "Group Categories" %}</a></li>

   95 :                 {% if perms.announcements.can_manage %}

   96 :                 <li><a href="{% url "announcements_list" %}">{% trans "Announcements" %}</a></li>

   97 :                 {% endif %}

   98 :                 {% if user.is_superuser %}

   99 :                 <li role="separator" class="divider"></li>

   100 :                 <li><a href="/admin/people/profile/add/">{% trans "Add User" %}</a></li>

   101 :                 <li><a href=" {% url "account_invite_user" %} ">{% trans "Invite User" %}</a></li>

   102 :                 <li><a href="{% url "group_create" %}">{% trans "Create Group" %}</a></li>

   103 :                 {% endif %}

   104 :               </ul>

   105 :             </li>

   106 : 

   107 : 	        {% block extra_tab %}

   108 :             {% endblock %}

   109 :             {% endblock %}

   110 :           </ul>

   111 : 	      <ul class="nav navbar-nav navbar-right">

Traceback:
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  164.                 response = response.render()
File "/usr/local/lib/python2.7/site-packages/django/template/response.py" in render
  158.             self.content = self.rendered_content
File "/usr/local/lib/python2.7/site-packages/django/template/response.py" in rendered_content
  135.         content = template.render(context, self._request)
File "/usr/local/lib/python2.7/site-packages/django/template/backends/django.py" in render
  74.         return self.template.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in render
  210.                     return self._render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in _render
  202.         return self.nodelist.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in render
  905.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/site-packages/django/template/debug.py" in render_node
  79.             return node.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py" in render
  135.         return compiled_parent._render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in _render
  202.         return self.nodelist.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in render
  905.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/site-packages/django/template/debug.py" in render_node
  79.             return node.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py" in render
  135.         return compiled_parent._render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in _render
  202.         return self.nodelist.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in render
  905.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/site-packages/django/template/debug.py" in render_node
  79.             return node.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py" in render
  65.                 result = block.nodelist.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in render
  905.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/site-packages/django/template/debug.py" in render_node
  79.             return node.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py" in render
  65.                 result = block.nodelist.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in render
  905.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/site-packages/django/template/debug.py" in render_node
  79.             return node.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py" in render
  329.                 return nodelist.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in render
  905.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/site-packages/django/template/debug.py" in render_node
  79.             return node.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py" in render
  507.                         six.reraise(*exc_info)
File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py" in render
  493.             url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py" in reverse
  578.     return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py" in _reverse_with_prefix
  495.                              (lookup_view_s, args, kwargs, len(patterns), patterns))

Exception Type: NoReverseMatch at /
Exception Value: Reverse for 'account_invite_user' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

**Comment by sindile** [comment]
I also see that there is a similar issue - https://github.com/GeoNode/geonode/issues/3172

**Comment by afabiani** [comment]
To solve the issue please do te following:

```
pip uninstall django-user-accounts -y
pip uninstall geonode-user-accounts -y

pip install django-user-accounts --no-cache
pip install geonode-user-accounts --no-cache

paver sync
```

**Comment by afabiani** [comment]
P.S.: this will be fixed when https://github.com/GeoNode/geonode/pull/3461 is merged

**Comment by sindile** [comment]
tried running the commands in my container - Build failed running pavement.sync: Subprocess return code: 1 - and here is the output:

root@ea4448e3d621:/usr/src/app# pip uninstall django-user-accounts -y
Uninstalling django-user-accounts-2.0.3:
  Successfully uninstalled django-user-accounts-2.0.3
root@ea4448e3d621:/usr/src/app# pip uninstall geonode-user-accounts -y
Uninstalling geonode-user-accounts-1.0.15:
  Successfully uninstalled geonode-user-accounts-1.0.15
root@ea4448e3d621:/usr/src/app# pip install django-user-accounts --no-cache
Collecting django-user-accounts
  Downloading django_user_accounts-2.0.3-py2.py3-none-any.whl (106kB)
    100% |████████████████████████████████| 112kB 966kB/s 
Requirement already satisfied: Django>=1.8 in /usr/local/lib/python2.7/site-packages (from django-user-accounts)
Requirement already satisfied: django-appconf>=1.0.1 in /usr/local/lib/python2.7/site-packages (from django-user-accounts)
Requirement already satisfied: pytz>=2015.6 in /usr/local/lib/python2.7/site-packages (from django-user-accounts)
Installing collected packages: django-user-accounts
Successfully installed django-user-accounts-2.0.3
root@ea4448e3d621:/usr/src/app# pip install geonode-user-accounts --no-cache
Collecting geonode-user-accounts
  Downloading geonode_user_accounts-1.0.15-py2.py3-none-any.whl (113kB)
    100% |████████████████████████████████| 122kB 795kB/s 
Requirement already satisfied: django-appconf>=1.0.1 in /usr/local/lib/python2.7/site-packages (from geonode-user-accounts)
Requirement already satisfied: pytz>=2015.6 in /usr/local/lib/python2.7/site-packages (from geonode-user-accounts)
Installing collected packages: geonode-user-accounts
Successfully installed geonode-user-accounts-1.0.15
root@ea4448e3d621:/usr/src/app# paver sync
---> pavement.sync
python manage.py makemigrations --noinput
Migrations for 'account':
  0007_signupcode_username.py:
    - Add field username to signupcode
python manage.py migrate --noinput
Operations to perform:
  Synchronize unmigrated apps: tasks, floppyforms, modeltranslation, django_extensions, polymorphic, treebeard, corsheaders, django_forms_bootstrap, catalogue, humanize, geoserver, api_basemaps, storages, mptt, friendlytagloader, staticfiles, metadataxsl, geoexplorer, sitemaps, proxy, gis, pinax_theme_bootstrap, pagination, autocomplete_light, messages, leaflet, api, social, messaging, security
  Apply all migrations: dialogos, people, tastypie, agon_ratings, documents, actstream, sites, maps, contenttypes, announcements, user_messages, layers, sessions, guardian, auth, base, pinax_notifications, groups, services, oauth2_provider, account, admin, upload, avatar, taggit
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying account.0007_signupcode_username... OK
python manage.py loaddata sample_admin.json
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/modeltranslation/management/commands/loaddata.py", line 61, in handle
    return super(Command, self).handle(*fixture_labels, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 100, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 157, in load_label
    obj.save(using=self.using)
  File "/usr/local/lib/python2.7/site-packages/django/core/serializers/base.py", line 173, in save
    models.Model.save_base(self.object, using=using, raw=True)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: Problem installing fixture '/usr/src/app/geonode/people/fixtures/sample_admin.json': Could not load people.Profile(pk=1000): duplicate key value violates unique constraint "people_profile_username_key"
DETAIL:  Key (username)=(admin) already exists.



Captured Task Output:
---------------------

---> pavement.sync
python manage.py makemigrations --noinput
python manage.py migrate --noinput
python manage.py loaddata sample_admin.json

Build failed running pavement.sync: Subprocess return code: 1

**Comment by sindile** [comment]
I am still getting the same error when login as user admin

**Comment by afabiani** [comment]
Just to do a quick test, can you please try to change on 

 /usr/src/app/geonode/templates/base.html

The line 

`<a href=" {% url "account_invite_user" %} ">{% trans "Invite User" %}`

with the line

`<a href=" {% url "invitations:send-invite" %} ">{% trans "Invite User" %}`

**Comment by sindile** [comment]
Did make the change and I get the following error:

 Environment:


Request Method: GET
Request URL: http://172.17.0.1/

Django Version: 1.8.18
Python Version: 2.7.9
Installed Applications:
('modeltranslation',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.sitemaps',
 'django.contrib.staticfiles',
 'django.contrib.messages',
 'django.contrib.humanize',
 'django.contrib.gis',
 'pagination',
 'taggit',
 'treebeard',
 'friendlytagloader',
 'geoexplorer',
 'leaflet',
 'django_extensions',
 'autocomplete_light',
 'mptt',
 'storages',
 'floppyforms',
 'pinax_theme_bootstrap',
 'django_forms_bootstrap',
 'account',
 'avatar',
 'dialogos',
 'agon_ratings',
 'announcements',
 'actstream',
 'user_messages',
 'tastypie',
 'polymorphic',
 'guardian',
 'oauth2_provider',
 'corsheaders',
 'geonode.contrib.metadataxsl',
 'geonode.contrib.api_basemaps',
 'geonode.people',
 'geonode.base',
 'geonode.layers',
 'geonode.maps',
 'geonode.proxy',
 'geonode.security',
 'geonode.social',
 'geonode.catalogue',
 'geonode.documents',
 'geonode.api',
 'geonode.groups',
 'geonode.services',
 'geonode.geoserver',
 'geonode.upload',
 'geonode.tasks',
 'geonode.messaging',
 'pinax.notifications')
Installed Middleware:
('corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'pagination.middleware.PaginationMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'oauth2_provider.middleware.OAuth2TokenMiddleware')


Template error:
In template /usr/src/app/geonode/templates/base.html, error at line 101
   Reverse for 'account_invite_user' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

   91 :               <ul class="dropdown-menu">



   92 :                 <li><a href="{% url "profile_browse" %}">{% trans "People" %}</a></li>



   93 :                 <li><a href="{% url "group_list" %}">{% trans "Groups" %}</a></li>



   94 :                 <li><a href="{% url "group_category_list" %}">{% trans "Group Categories" %}</a></li>



   95 :                 {% if perms.announcements.can_manage %}



   96 :                 <li><a href="{% url "announcements_list" %}">{% trans "Announcements" %}</a></li>



   97 :                 {% endif %}



   98 :                 {% if user.is_superuser %}



   99 :                 <li role="separator" class="divider"></li>



   100 :                 <li><a href="/admin/people/profile/add/">{% trans "Add User" %}</a></li>



   101 :                 <li><a href=" {% url "account_invite_user" %} ">{% trans "Invite User" %}</a></li>



   102 :                 <li><a href="{% url "group_create" %}">{% trans "Create Group" %}</a></li>



   103 :                 {% endif %}



   104 :               </ul>



   105 :             </li>



   106 : 



   107 : 	        {% block extra_tab %}



   108 :             {% endblock %}



   109 :             {% endblock %}



   110 :           </ul>



   111 : 	      <ul class="nav navbar-nav navbar-right">


Traceback:
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  164.                 response = response.render()
File "/usr/local/lib/python2.7/site-packages/django/template/response.py" in render
  158.             self.content = self.rendered_content
File "/usr/local/lib/python2.7/site-packages/django/template/response.py" in rendered_content
  135.         content = template.render(context, self._request)
File "/usr/local/lib/python2.7/site-packages/django/template/backends/django.py" in render
  74.         return self.template.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in render
  210.                     return self._render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in _render
  202.         return self.nodelist.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in render
  905.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/site-packages/django/template/debug.py" in render_node
  79.             return node.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py" in render
  135.         return compiled_parent._render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in _render
  202.         return self.nodelist.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in render
  905.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/site-packages/django/template/debug.py" in render_node
  79.             return node.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py" in render
  135.         return compiled_parent._render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in _render
  202.         return self.nodelist.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in render
  905.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/site-packages/django/template/debug.py" in render_node
  79.             return node.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py" in render
  65.                 result = block.nodelist.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in render
  905.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/site-packages/django/template/debug.py" in render_node
  79.             return node.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py" in render
  65.                 result = block.nodelist.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in render
  905.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/site-packages/django/template/debug.py" in render_node
  79.             return node.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py" in render
  329.                 return nodelist.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/base.py" in render
  905.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/site-packages/django/template/debug.py" in render_node
  79.             return node.render(context)
File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py" in render
  507.                         six.reraise(*exc_info)
File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py" in render
  493.             url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py" in reverse
  578.     return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py" in _reverse_with_prefix
  495.                              (lookup_view_s, args, kwargs, len(patterns), patterns))

Exception Type: NoReverseMatch at /
Exception Value: Reverse for 'account_invite_user' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

**Comment by afabiani** [comment]
mumble ... from your log I still see the old code

101 :

<a href=" {% url "account_invite_user" %} ">{% trans "Invite User" %}

**Comment by afabiani** [comment]
Sent a fix here https://github.com/GeoNode/geonode/pull/3487

it will be available as soon it is merged
