### ISSUE TITLE
CSV upload with column named "location" fails

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#3557]
Tested on Geonode 2.4: in layers/upload, trying to upload a CSV file with a column named 'location' either fails with the message 'BAD REQUEST' in the page, or appears to hang and never finish uploading.

E.g. upload a CSV file containing just 1 record:
```
location,longitude,latitude
Atherton,145.48586,-17.26608
```

Geoserver.log explains that PostgreSQL is failing to create another 'location' column:

> 2018-01-11 04:52:54,792 ERROR [geoserver.importer] - Error occured during import
> java.io.IOException: Error occurred creating table
>         at org.geotools.jdbc.JDBCDataStore.createSchema(JDBCDataStore.java:757)
>         at org.geotools.jdbc.JDBCDataStore.createSchema(JDBCDataStore.java:144)
>         at org.geoserver.importer.Importer.loadIntoDataStore(Importer.java:1181)
>         at org.geoserver.importer.Importer.doIndirectImport(Importer.java:960)
>         at org.geoserver.importer.Importer.run(Importer.java:817)
>         at org.geoserver.importer.Importer.run(Importer.java:767)
>         at org.geoserver.importer.Importer$5.call(Importer.java:850)
>         at org.geoserver.importer.Importer$5.call(Importer.java:844)
>         at org.geoserver.importer.job.Job.call(Job.java:16)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: org.postgresql.util.PSQLException: ERROR: column "location" specified more than once
>         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2062)
>         at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1795)
>         at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
>         at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:479)
>         at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:353)
>         at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:345)
>         at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
>         at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
>         at org.geotools.jdbc.JDBCDataStore.createSchema(JDBCDataStore.java:749)
>         ... 12 more
>

**Comment by jondoig** [comment]
One option would be to check for that column name and gracefully exit with a message like:

> The attribute name ‘location’ is reserved. Please rename this attribute in your data before uploading again.
