### ISSUE TITLE
Conflicting 'emailaddress' models in application 'account' after installing latest commits

### ISSUE THREAD

**Issue by karakostis** [GeoNode/geonode#3606]
After installing the latest commits in my local GeoNode environment, I get the following error (on python manage.py runserver..): 

```
Traceback (most recent call last):
  File "/vagrant/env/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/vagrant/env/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 107, in inner_run
    autoreload.raise_last_exception()
  File "/vagrant/env/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 252, in raise_last_exception
    six.reraise(*_exception)
  File "/vagrant/env/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/vagrant/env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/vagrant/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/vagrant/env/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/vagrant/geonode/geonode/people/__init__.py", line 27, in <module>
    from . import signals
  File "/vagrant/geonode/geonode/people/signals.py", line 34, in <module>
    from .adapters import get_data_extractor
  File "/vagrant/geonode/geonode/people/adapters.py", line 34, in <module>
    from allauth.socialaccount.adapter import DefaultSocialAccountAdapter
  File "/vagrant/env/local/lib/python2.7/site-packages/allauth/socialaccount/adapter.py", line 10, in <module>
    from ..account.models import EmailAddress
  File "/vagrant/env/local/lib/python2.7/site-packages/allauth/account/models.py", line 20, in <module>
    class EmailAddress(models.Model):
  File "/vagrant/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 309, in __new__
    new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
  File "/vagrant/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 221, in register_model
    (model_name, app_label, app_models[model_name], model))
RuntimeError: Conflicting 'emailaddress' models in application 'account': <class 'account.models.EmailAddress'> and <class 'allauth.account.models.EmailAddress'>.
```

Somehow this must be related with the django-allauth app. Is anyone else facing similar error? @afabiani I think the error is related with [this commit](https://github.com/GeoNode/geonode/commit/fa9a892acbbe9a0075377233904c1aa0083ef064)

**Comment by afabiani** [comment]
You have to uninstall both 

```
django-user-accounts
geonode-user-accounts
```

and redo

```
pip install -r requirements.txt
pip install -e .
```

Also make sure your `local_settings `have been updated with latest `settings `updates
(see `local_settings.py.geoserver.sample` for reference)
