### ISSUE TITLE
Make sync error

### ISSUE THREAD

**Issue by Fanevanjanahary** [GeoNode/geonode#3647]
Hello,
I'm trying to run geonode used Docker, I followed the readme.
I have this error when I execute the commande "make sync".

```
docker-compose exec django django-admin.py migrate --noinput
Traceback (most recent call last):
  File "/usr/local/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/pinax/notifications/models.py", line 14, in <module>
    from .compat import GenericForeignKey
  File "/usr/local/lib/python2.7/site-packages/pinax/notifications/compat.py", line 17, in <module>
    from account.decorators import login_required
  File "/usr/local/lib/python2.7/site-packages/account/decorators.py", line 9, in <module>
    from account.utils import handle_redirect_to_login
  File "/usr/local/lib/python2.7/site-packages/account/utils.py", line 18, in <module>
    from .models import PasswordHistory
  File "/usr/local/lib/python2.7/site-packages/account/models.py", line 259, in <module>
    class EmailAddress(models.Model):
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 309, in __new__
    new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 221, in register_model
    (model_name, app_label, app_models[model_name], model))
RuntimeError: Conflicting 'emailaddress' models in application 'account': <class 'allauth.account.models.EmailAddress'> and <class 'account.models.EmailAddress'>.
Makefile:10: recipe for target 'sync' failed
make: *** [sync] Error 1

```

**Comment by francbartoli** [comment]
@Fanevanjanahary are you running from master?

**Comment by Fanevanjanahary** [comment]
Hi @francbartoli,
Yeah

**Comment by francbartoli** [comment]
If you have a look at branch 2.6.x it is no longer needed to use make command, porting that to master is a WIP, please catch the related pr

**Comment by Fanevanjanahary** [comment]
2.6.x is the stable version? I couldn't migrate database, and there are other error on nginx. I use 2.6.x

**Comment by Fanevanjanahary** [comment]
I have this on log when i execute docker-compose up

```
geoserver4geonode | 27 Feb 06:46:02 INFO [org.geoserver.ows.OWSHandlerMapping] - Mapped URL path [/wms] onto handler 'dispatcher'
geoserver4geonode | 27 Feb 06:46:02 INFO [org.geoserver.ows.OWSHandlerMapping] - Mapped URL path [/wms/*] onto handler 'dispatcher'
geoserver4geonode | 27 Feb 06:46:03 INFO [org.geoserver.ows.OWSHandlerMapping] - Mapped URL path [/animate/*] onto handler 'dispatcher'
geoserver4geonode | 27 Feb 06:46:03 INFO [org.geoserver.ows.OWSHandlerMapping] - Mapped URL path [/animate] onto handler 'dispatcher'
geoserver4geonode | 27 Feb 06:46:03 DEBUG [org.geoserver.geofence] - Not limiting styles
geoserver4geonode | 27 Feb 06:46:03 DEBUG [org.geoserver.geofence] - Not limiting styles
geoserver4geonode | 27 Feb 06:46:03 DEBUG [org.geoserver.geofence] - Not limiting styles
geoserver4geonode | 27 Feb 06:46:03 DEBUG [org.geoserver.geofence] - Not limiting styles
geoserver4geonode | 27 Feb 06:46:03 DEBUG [org.geoserver.geofence] - Not limiting styles
geoserver4geonode | 27 Feb 06:46:03 INFO [org.geoserver] - GeoServer configuration lock is enabled
geoserver4geonode | 27 Feb 06:46:05 INFO [org.geoserver.ows.OWSHandlerMapping] - Mapped URL path [/TestWfsPost] onto handler 'wfsTestServlet'
geoserver4geonode | 27 Feb 06:46:05 INFO [org.geoserver.ows.OWSHandlerMapping] - Mapped URL path [/wfs/*] onto handler 'dispatcher'
geoserver4geonode | 27 Feb 06:46:05 INFO [org.geoserver.ows.OWSHandlerMapping] - Mapped URL path [/wfs] onto handler 'dispatcher'
geoserver4geonode | 27 Feb 06:46:11 INFO [org.geoserver.ows.OWSHandlerMapping] - Mapped URL path [/kml] onto handler 'dispatcher'
geoserver4geonode | 27 Feb 06:46:11 INFO [org.geoserver.ows.OWSHandlerMapping] - Mapped URL path [/kml/*] onto handler 'dispatcher'
geoserver4geonode | 27 Feb 06:46:11 INFO [org.geoserver.ows.OWSHandlerMapping] - Mapped URL path [/kml/icon/**/*] onto handler 'kmlIconService'
django4geonode exited with code 1

```

The nginx log is 
```
nginx4geonode    | 2018/02/27 06:48:35 [error] 7#7: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.20.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.20.0.7:8000/", host: "localhost"
nginx4geonode    | 172.20.0.1 - - [27/Feb/2018:06:48:35 +0000] "GET / HTTP/1.1" 502 173 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "-"

```

**Comment by francbartoli** [comment]
@Fanevanjanahary did you follow this guide http://docs.geonode.org/en/master/tutorials/install_and_admin/running_docker/index.html?

GeoNode has to be opened at ip address of docker0 interface. Can you check it?

**Comment by Fanevanjanahary** [comment]
I see, maybe this is django error, I used docker0 ip to run geoserver and this is work. but not with ip:8000. 

Executing docker ps I couldn't see a django container, is it normaly?

```
celery4geonode   | Traceback (most recent call last):
celery4geonode   |   File "/usr/local/bin/invoke", line 11, in <module>
celery4geonode   |     sys.exit(program.run())
celery4geonode   |   File "/usr/local/lib/python2.7/site-packages/invoke/program.py", line 293, in run
celery4geonode   |     self.execute()
celery4geonode   |   File "/usr/local/lib/python2.7/site-packages/invoke/program.py", line 414, in execute
celery4geonode   |     executor.execute(*self.tasks)
celery4geonode   |   File "/usr/local/lib/python2.7/site-packages/invoke/executor.py", line 129, in execute
celery4geonode   |     result = call.task(*args, **call.kwargs)
celery4geonode   |   File "/usr/local/lib/python2.7/site-packages/invoke/tasks.py", line 115, in __call__
celery4geonode   |     result = self.body(*args, **kwargs)
celery4geonode   |   File "/usr/src/app/tasks.py", line 25, in update
celery4geonode   |     pub_port = _geonode_public_port()
celery4geonode   |   File "/usr/src/app/tasks.py", line 149, in _geonode_public_port
celery4geonode   |     os.getenv('GEONODE_INSTANCE_NAME', 'geonode')
celery4geonode   |   File "/usr/src/app/tasks.py", line 101, in _container_exposed_port
celery4geonode   |     ) if '{0}'.format(instname) in c.name][0]
celery4geonode   | IndexError: list index out of range
celery4geonode   | DATABASE_URL=postgres://geonode:geonode@db:5432/geonode
celery4geonode   | GEODATABASE_URL=postgis://geonode_data:geonode_data@db:5432/geonode_data
celery4geonode   | waitfordbs task done
celery4geonode   | DATABASE_URL=postgres://geonode:geonode@db:5432/geonode
```

**Comment by francbartoli** [comment]
Can you start from scratch by cleaning of the available images related to geonode? Also be careful that geonode is server through a nginx proxy so the port where to open the application is 80 unless you set the variable GEONODE_LB_PORT which would override the default

**Comment by francbartoli** [comment]
Hi @Fanevanjanahary, as already said above that command is not needed anymore.
After cleaning up you have to run just:

docker-compose up --build

Migrations are automated internally within the django container.
