### ISSUE TITLE
Geonode Installation in Oracle Linux

### ISSUE THREAD

**Issue by juliermegeotube** [GeoNode/geonode#3659]
I am running python 2.7.5 and installing geonode in a Oracle Linux machine. I am following the installation manual and I execute the command:

python manage.py migrate

I got the following error

```
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/apps/geonode/geonode/geonode/base/models.py", line 56, in <module>
    from geonode.utils import bbox_to_wkt
  File "/opt/apps/geonode/geonode/geonode/utils.py", line 31, in <module>
    from slugify import Slugify
  File "/usr/lib/python2.7/site-packages/slugify/__init__.py", line 1, in <module>
    from slugify.main import Slugify, UniqueSlugify
ImportError: No module named main
```

Any tip on how to solve this issue?

Sorry if this issue has been discussed here before
Thank you for your time in advance

**Comment by ewsterrenburg** [comment]
I fixed this by installing awesome-slugify master branch from git ([https://github.com/dimka665/awesome-slugify](https://github.com/dimka665/awesome-slugify)

**Comment by juliermegeotube** [comment]
Thank you @ewsterrenburg  and @simod. I got it fixed.
