### ISSUE TITLE
paver setup.py - .ContextualVersionConflic- during installation Ubuntu 16.04.2

### ISSUE THREAD

**Issue by DarnelleF** [GeoNode/geonode#3664]
Been installing/following a installtion guide on a new vm Ubuntu 16.04.2

(geonode) geonode@sling:~/my_geonode$ paver setup
```
---> pavement.setup
---> pavement.setup_geoserver
rmtree path('geoserver/data')
---> pavement.setup_qgis_server
---> pavement.updategeoip
 python manage.py updategeoip -o
Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/home/geonode/Envs/geonode/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/geonode/Envs/geonode/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/geonode/Envs/geonode/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/geonode/Envs/geonode/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/geonode/Envs/geonode/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/geonode/Envs/geonode/local/lib/python2.7/site-packages/polymorphic/__init__.py", line 13, in <module>
    __version__ = pkg_resources.require("django-polymorphic")[0].version
  File "/home/geonode/Envs/geonode/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/geonode/Envs/geonode/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Django 1.8.18 (/home/geonode/Envs/geonode/lib/python2.7/site-packages), Requirement.parse('Django>=1.11'), set(['django-polymorphic']))


Captured Task Output:
---------------------

---> pavement.setup
---> pavement.setup_geoserver
rmtree path('geoserver/data')
---> pavement.setup_qgis_server
---> pavement.updategeoip
 python manage.py updategeoip -o

Build failed running pavement.setup: Subprocess return code: 1
(geonode) geonode@sling:~/my_geonode$ ^C

```

**Comment by DarnelleF** [comment]
been sick for a week just returning with a fresh head, instruction guide needs updating 
just needed django 1.11
