### ISSUE TITLE
update layers error

### ISSUE THREAD

**Issue by hishamkaram** [GeoNode/geonode#3920]
update layers command raise an error
`$ python manage.py updatelayer`
error:
```
Inspecting the available layers in GeoServer ...
Found 1 layers, starting processing
Stopping process because --ignore-errors was not set and an error was found.
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/hishamkaram/virtual_envs/geonode/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/hishamkaram/virtual_envs/geonode/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/hishamkaram/virtual_envs/geonode/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/hishamkaram/virtual_envs/geonode/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/hishamkaram/Projects-Active/geonode/geonode/geoserver/management/commands/updatelayers.py", line 124, in handle
    execute_signals=True)
  File "/Users/hishamkaram/Projects-Active/geonode/geonode/geoserver/helpers.py", line 633, in gs_slurp
    layer.set_permissions(perm_spec)
  File "/Users/hishamkaram/Projects-Active/geonode/geonode/security/models.py", line 201, in set_permissions
    sync_geofence_with_guardian(self.layer, perms, user=geofence_user)
  File "/Users/hishamkaram/Projects-Active/geonode/geonode/decorators.py", line 44, in wrapper
    return func(*args, **kwargs)
  File "/Users/hishamkaram/Projects-Active/geonode/geonode/security/utils.py", line 333, in sync_geofence_with_guardian
    _update_geofence_rule(layer.name, layer.workspace, service, user=user.username)
Exception: ('Failed to process other_healthcare_60cfefd3', AttributeError("'str' object has no attribute 'username'",))
```

**Comment by hishamkaram** [comment]
this PR https://github.com/GeoNode/geonode/pull/3919 fix this issue
