### ISSUE TITLE
Document Upload Succeeds but Django Error is Shown

### ISSUE THREAD

**Issue by mikefedak** [GeoNode/geonode#3980]
On the 2.8.x branch, Geoserver 2.12.2

Uploading documents succeeds but Django displays the following Error:

> DoesNotExist at /documents/upload
> Layer matching query does not exist.

This is the output of error.log:
```
[Tue Oct 09 21:41:03.090447 2018] [wsgi:error] [pid 26713] Internal Server Error: /documents/upload
[Tue Oct 09 21:41:03.090479 2018] [wsgi:error] [pid 26713] Traceback (most recent call last):
[Tue Oct 09 21:41:03.090483 2018] [wsgi:error] [pid 26713]   File "/home/gnode/gndev/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
[Tue Oct 09 21:41:03.090487 2018] [wsgi:error] [pid 26713]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Oct 09 21:41:03.090491 2018] [wsgi:error] [pid 26713]   File "/home/gnode/gndev/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
[Tue Oct 09 21:41:03.090495 2018] [wsgi:error] [pid 26713]     return view_func(request, *args, **kwargs)
[Tue Oct 09 21:41:03.090499 2018] [wsgi:error] [pid 26713]   File "/home/gnode/gndev/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
[Tue Oct 09 21:41:03.090503 2018] [wsgi:error] [pid 26713]     return self.dispatch(request, *args, **kwargs)
[Tue Oct 09 21:41:03.090506 2018] [wsgi:error] [pid 26713]   File "/home/gnode/gndev/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
[Tue Oct 09 21:41:03.090510 2018] [wsgi:error] [pid 26713]     return handler(request, *args, **kwargs)
[Tue Oct 09 21:41:03.090514 2018] [wsgi:error] [pid 26713]   File "/home/gnode/gndev/lib/python2.7/site-packages/django/views/generic/edit.py", line 249, in post
[Tue Oct 09 21:41:03.090518 2018] [wsgi:error] [pid 26713]     return super(BaseCreateView, self).post(request, *args, **kwargs)
[Tue Oct 09 21:41:03.090521 2018] [wsgi:error] [pid 26713]   File "/home/gnode/gndev/lib/python2.7/site-packages/django/views/generic/edit.py", line 215, in post
[Tue Oct 09 21:41:03.090525 2018] [wsgi:error] [pid 26713]     return self.form_valid(form)
[Tue Oct 09 21:41:03.090529 2018] [wsgi:error] [pid 26713]   File "/home/gnode/geonode_dev/geonode/geonode/documents/views.py", line 215, in form_valid
[Tue Oct 09 21:41:03.090532 2018] [wsgi:error] [pid 26713]     self.object.set_permissions(form.cleaned_data['permissions'])
[Tue Oct 09 21:41:03.090536 2018] [wsgi:error] [pid 26713]   File "/home/gnode/geonode_dev/geonode/geonode/security/models.py", line 201, in set_permissions
[Tue Oct 09 21:41:03.090540 2018] [wsgi:error] [pid 26713]     sync_geofence_with_guardian(self.layer, perms, user=geofence_user)
[Tue Oct 09 21:41:03.090543 2018] [wsgi:error] [pid 26713]   File "/home/gnode/gndev/lib/python2.7/site-packages/polymorphic/models.py", line 159, in accessor_function
[Tue Oct 09 21:41:03.090547 2018] [wsgi:error] [pid 26713]     attr = model.base_objects.get(pk=self.pk)
[Tue Oct 09 21:41:03.090551 2018] [wsgi:error] [pid 26713]   File "/home/gnode/gndev/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
[Tue Oct 09 21:41:03.090554 2018] [wsgi:error] [pid 26713]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[Tue Oct 09 21:41:03.090558 2018] [wsgi:error] [pid 26713]   File "/home/gnode/gndev/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
[Tue Oct 09 21:41:03.090562 2018] [wsgi:error] [pid 26713]     self.model._meta.object_name
[Tue Oct 09 21:41:03.090565 2018] [wsgi:error] [pid 26713] DoesNotExist: Layer matching query does not exist.
```

**Comment by mikefedak** [comment]
Nope, this was never solved.

**Comment by capooti** [comment]
I have just uploaded a document to my dev box and looks to work. Can you specify the steps to reproduce the issue? Thanks

**Comment by jgrocha** [comment]
Thanks @capooti for testing. 

I login as an admin user. I do:
1. Upload Document
1. Open explorer; select a file
1. Title is filled automatically with filename and extension
1. I select one layer I've already uploaded
1. I don't change default permissions (_Anyone can view_ it and _Anyone can download_ it)
1. Click Upload button

Details of the error:
```
Environment:


Request Method: POST
Request URL: https://geocolabora.sig.cm-agueda.pt/documents/upload

Django Version: 1.11.15
Python Version: 2.7.12
Installed Applications:
('modeltranslation',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.sitemaps',
 'django.contrib.staticfiles',
 'django.contrib.messages',
 'django.contrib.humanize',
 'django.contrib.gis',
 'dj_pagination',
 'taggit',
 'treebeard',
 'geoexplorer',
 'leaflet',
 'bootstrap3_datetime',
 'django_extensions',
 'django_basic_auth',
 'autocomplete_light',
 'mptt',
 'storages',
 'floppyforms',
 'pinax_theme_bootstrap',
 'django_forms_bootstrap',
 'avatar',
 'dialogos',
 'agon_ratings',
 'announcements',
 'actstream',
 'user_messages',
 'tastypie',
 'polymorphic',
 'guardian',
 'oauth2_provider',
 'corsheaders',
 'invitations',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'rest_framework',
 'geonode',
 'geonode.api',
 'geonode.base',
 'geonode.layers',
 'geonode.maps',
 'geonode.documents',
 'geonode.security',
 'geonode.catalogue',
 'geonode.people',
 'geonode.client',
 'geonode.proxy',
 'geonode.social',
 'geonode.groups',
 'geonode.services',
 'geonode.geoserver',
 'geonode.upload',
 'geonode.tasks',
 'geonode.messaging',
 'geonode.chart',
 'geonode.hook',
 'geonode.contrib.metadataxsl',
 'geonode.contrib.api_basemaps',
 'geonode.contrib.ows_api',
 'pinax.notifications',
 'mapstore2_adapter',
 'geonode_mapstore_client',
 'osgeo_importer',
 <Celery geonode at 0x7f346fdeddd0>)
Installed Middleware:
('corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'dj_pagination.middleware.PaginationMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'oauth2_provider.middleware.OAuth2TokenMiddleware',
 'django.middleware.security.SecurityMiddleware')



Traceback:

File "/home/pda/geocolaborav2/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/home/pda/geocolaborav2/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/home/pda/geocolaborav2/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/home/pda/geocolaborav2/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/pda/geocolaborav2/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/home/pda/geocolaborav2/env/local/lib/python2.7/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/home/pda/geocolaborav2/env/local/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/home/pda/geocolaborav2/env/local/lib/python2.7/site-packages/django/views/generic/edit.py" in post
  217.         return super(BaseCreateView, self).post(request, *args, **kwargs)

File "/home/pda/geocolaborav2/env/local/lib/python2.7/site-packages/django/views/generic/edit.py" in post
  183.             return self.form_valid(form)

File "/home/pda/geocolaborav2/geonode/geonode/documents/views.py" in form_valid
  215.         self.object.set_permissions(form.cleaned_data['permissions'])

File "/home/pda/geocolaborav2/geonode/geonode/security/models.py" in set_permissions
  171.             purge_geofence_layer_rules(self.get_self_resource())

File "/home/pda/geocolaborav2/geonode/geonode/decorators.py" in wrapper
  44.                 return func(*args, **kwargs)

File "/home/pda/geocolaborav2/geonode/geonode/security/utils.py" in purge_geofence_layer_rules
  277.     workspace = _get_layer_workspace(resource.layer)

File "/home/pda/geocolaborav2/env/local/lib/python2.7/site-packages/polymorphic/models.py" in accessor_function
  174.                 attr = model.base_objects.get(pk=self.pk)

File "/home/pda/geocolaborav2/env/local/lib/python2.7/site-packages/django/db/models/manager.py" in manager_method
  85.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/home/pda/geocolaborav2/env/local/lib/python2.7/site-packages/django/db/models/query.py" in get
  380.                 self.model._meta.object_name

Exception Type: DoesNotExist at /documents/upload
Exception Value: Layer matching query does not exist.
```

**Comment by jgrocha** [comment]
This [instance](https://geocolabora.sig.cm-agueda.pt) is online and still in beta. It can be used for testing without problem.

**Comment by capooti** [comment]
OK I didn't notice you are on 2.8. On master this is working, you may change this block in geonode/security/models.py like this (didn't test it - later I may post a PR with the backport):

```python
if GEOFENCE_SECURITY_ENABLED:
                    set_geofence_owner(self, username=geofence_user,
                                       view_perms=has_view_perms,
                                       download_perms=has_download_perms)

```

```python
if GEOFENCE_SECURITY_ENABLED::
        if self.polymorphic_ctype.name == 'layer':
                        sync_geofence_with_guardian(self.layer, perms, user=geofence_user)
```

**Comment by jgrocha** [comment]
Thanks @capooti 
I was able to upload documents with your support.

I'm running a copy from master, with a few commits behind. This was the difference between the current (master) `models.py` and my `models.py`:
```diff
72,174c170,171
<         if self.__class__.__name__ == 'Layer':
<             if settings.OGC_SERVER['default'].get("GEOFENCE_SECURITY_ENABLED", False):
<                 purge_geofence_layer_rules(self.get_self_resource())
---
>         if settings.OGC_SERVER['default'].get("GEOFENCE_SECURITY_ENABLED", False):
>             purge_geofence_layer_rules(self.get_self_resource())
```

So, I've just checkout the last `models.py` with the additional ` self.__class__.__name__ == 'Layer'` test, and the uploads are working!

You've been very helpful.

The ticket can remain closed.

**Comment by afabiani** [comment]
https://github.com/GeoNode/geonode/commit/4bc434ce91c45d5a81d6e051d9adf6de17ab5636

**Comment by frafra** [comment]
Still happening on master:
```
[2019-03-27 13:44:26,701: ERROR/ForkPoolWorker-2] Task geonode.geoserver.tasks.thumbnail_task[c7edf30c-6a9a-40ff-8e86-9ed354df2247] raised unexpected: DoesNotExist('Layer matching query does not exist.',),
Traceback (most recent call last):,
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task,
    R = retval = fun(*args, **kwargs),
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__,
    return self.run(*args, **kwargs),
  File "/spcgeonode/geonode/geoserver/tasks.py", line 43, in thumbnail_task,
    instance = Layer.objects.get(id=instance_id),
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method,
    return getattr(self.get_queryset(), name)(*args, **kwargs),
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get,
    self.model._meta.object_name,
Exception: Layer matching query does not exist.
```

**Comment by simod** [comment]
looks to be solved
