### ISSUE TITLE
Recurring User 'None' Error Geofence/Geoserver

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#3984]
I am using the latest 2.8.x branch with Geoserver 2.12.2 and I keep receiving the following error when attempting to run the updatelayers command (Below). 

I am also having trouble with users not being sync'd with geoserver. I have gone through the documentation for security configuration, and checked that the geonode role/user apis are accessible to geoserver. As far as I can tell, nothing is blocking either geonode from reaching geofence or vice-versa. 

Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/gnode/gndev/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/gnode/gndev/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/gnode/gndev/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/gnode/gndev/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/gnode/geonode_dev/geonode/geonode/geoserver/management/commands/updatelayers.py", line 124, in handle
    execute_signals=True)
  File "/home/gnode/geonode_dev/geonode/geonode/geoserver/helpers.py", line 636, in gs_slurp
    layer.set_permissions(perm_spec)
  File "/home/gnode/geonode_dev/geonode/geonode/security/models.py", line 216, in set_permissions
    sync_geofence_with_guardian(self.layer, perms, group=group)
  File "/home/gnode/geonode_dev/geonode/geonode/decorators.py", line 44, in wrapper
    return func(*args, **kwargs)
  File "/home/gnode/geonode_dev/geonode/geonode/security/utils.py", line 393, in sync_geofence_with_guardian
    _update_geofence_rule(layer.name, layer.workspace, service)
  File "/home/gnode/geonode_dev/geonode/geonode/security/utils.py", line 564, in _update_geofence_rule
    raise RuntimeError(msg)
Exception: ('Failed to process lprca_ws_boundarywgs84', RuntimeError("Could not ADD GeoServer User None Rule for Layer u'lprca_ws_boundarywgs84'",))

---------------------
And also getting an error (Error updating permissions) when trying to add groups to layer permissions; although the permission change is still successful.  

---------------------
And finally, document uploads throws an error but the upload is still successful.

**Comment by mikefedak** [comment]
Thanks Alessio, this fixes the issue with documents, however; I am still experiencing the same errors with updatelayers and with sync_geofence. 

> updatelayers throws the following:


Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/gnode/gndev/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/gnode/gndev/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/gnode/gndev/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/gnode/gndev/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/gnode/geonode_dev/geonode/geonode/geoserver/management/commands/updatelayers.py", line 124, in handle
    execute_signals=True)
  File "/home/gnode/geonode_dev/geonode/geonode/geoserver/helpers.py", line 636, in gs_slurp
    layer.set_permissions(perm_spec)
  File "/home/gnode/geonode_dev/geonode/geonode/security/models.py", line 218, in set_permissions
    sync_geofence_with_guardian(self.layer, perms, group=group)
  File "/home/gnode/geonode_dev/geonode/geonode/decorators.py", line 44, in wrapper
    return func(*args, **kwargs)
  File "/home/gnode/geonode_dev/geonode/geonode/security/utils.py", line 393, in sync_geofence_with_guardian
    _update_geofence_rule(layer.name, layer.workspace, service)
  File "/home/gnode/geonode_dev/geonode/geonode/security/utils.py", line 566, in _update_geofence_rule
    raise RuntimeError(msg)
Exception: ('Failed to process lprca_ws_boundarywgs84', RuntimeError("Could not ADD GeoServer User None Rule for Layer u'lprca_ws_boundarywgs84'",))

**sync_geofence throws the following:**

('Unexpected error:', <type 'exceptions.RuntimeError'>)
perm_spec is {u'users': {u'AnonymousUser': [u'view_resourcebase', u'download_resourcebase'], u'lprca': [u'view_resourcebase', u'download_resourcebase', u'change_resourcebase_metadata', u'change_resourcebase', u'delete_resourcebase', u'change_resourcebase_permissions', u'publish_resourcebase', u'change_layer_data', u'change_layer_style']}, u'groups': {u'anonymous': [u'view_resourcebase', u'download_resourcebase']}}

**Comment by mikefedak** [comment]
Yes, I see that error in my geoserver log. I also receive an error when i try and change user permissions via the geonode GUI (but the change is still registered).

**Comment by jgrocha** [comment]
I still have problems uploading documents. Is it possible to reopen this issue?

```text
DoesNotExist at /documents/upload

Layer matching query does not exist.

Request Method: 	POST
Request URL: 	https://geocolabora.sig.cm-agueda.pt/documents/upload
Django Version: 	1.11.15
Exception Type: 	DoesNotExist
```

**Comment by afabiani** [comment]
Hi, please take a look at this commit to fix the issue

https://github.com/GeoNode/geonode/commit/4bc434ce91c45d5a81d6e051d9adf6de17ab5636

**Comment by kabredramany** [comment]
I want to configure on my ubuntu server 18.04:
pip
paver setup
pave sync
But its not working!

**Comment by Mibrahim333** [comment]
@afabiani how did you resolve this error . when i upload a shapefile having records more than one 1k hundred (100000) ,geonode throw this error "
Unexpected error! - 502 Bad Gateway. This error is usually due to improperly configured proxy servers. The first step in resolving the issue is to clear the client's cache.
"
Upon checking the geoserver log file . the error shows there is the same as urs "Duplicate Rule Rule[id:null pri:150 srv:WPS ws:geonode l:relief_san_andres acc:Deny]"
My error is "2022-06-02 07:32:11,539 WARN [impl.RuleDAOImpl] -  ORIG: Rule[id:2167 pri:2518 srv:WFS req:LOCKFEATURE ws:geonode l:Geonames88k acc:DENY]
2022-06-02 07:32:11,539 WARN [impl.RuleDAOImpl] -  DUP : Rule[id:null pri:2522 srv:WFS req:LOCKFEATURE ws:geonode l:Geonames88k acc:DENY]
2022-06-02 07:32:11,540 ERROR [geoserver.rest] - Duplicate Rule Rule[id:null pri:2522 srv:WFS req:LOCKFEATURE ws:geonode l:Geonames88k acc:DENY]
org.geoserver.geofence.core.dao.DuplicateKeyException: Duplicate Rule Rule[id:null pri:2522 srv:WFS req:LOCKFEATURE ws:geonode l:Geonames88k acc:DENY]"
Kindly look into this and give me the solution

**Comment by pierreyvesturquin** [comment]
> Hi, please take a look at this commit to fix the issue
> 
> [4bc434c](https://github.com/GeoNode/geonode/commit/4bc434ce91c45d5a81d6e051d9adf6de17ab5636)

I'm using Geoserver 2.20.6 and I have this error message, how to fix it ?
