### ISSUE TITLE
Running manage.py updatelayers results in AttributeError: 'NoneType' object has no attribute 'sld_body'

### ISSUE THREAD

**Issue by sindile** [GeoNode/geonode#4014]
I am running into this issue - Exception: ('Failed to process rams_roads', AttributeError("'NoneType' object has no attribute 'sld_body'",)) with GeoNode version 2.9.dev20180529160544

Here is the entire stack trace - System check identified some issues:

WARNINGS:
?: (urls.W002) Your URL pattern '^/?$' [name='home'] has a regex beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.
Inspecting the available layers in GeoServer ...
Found 1 layers, starting processing
/usr/local/lib/python2.7/site-packages/owslib/iso.py:117: FutureWarning: the .identification and .serviceidentification properties will merge into .identification beinga list of properties. This is currently implemented in .identificationinfo. Please see geopython/OWSLib#38 for more information
FutureWarning)
/usr/local/lib/python2.7/site-packages/owslib/iso.py:482: FutureWarning: The .keywords and .keywords2 properties will merge into the .keywords property in the future, with .keywords becoming a list of MD_Keywords instances. This is currently implemented in .keywords2. Please see geopython/OWSLib#301 for more information
FutureWarning)
Exception while publishing message: Traceback (most recent call last):
File "/usr/src/geonode/geonode/messaging/producer.py", line 68, in sync_if_local_memory
worker.run(timeout=broker_sockettimeout)
File "/usr/local/lib/python2.7/site-packages/kombu/mixins.py", line 170, in run
for in self.consume(limit=None, kwargs):
File "/usr/local/lib/python2.7/site-packages/kombu/mixins.py", line 192, in consume
conn.drain_events(timeout=safety_interval)
File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 301, in drain_events
return self.transport.drain_events(self.connection, kwargs)
File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 961, in drain_events
get(self._deliver, timeout=timeout)
File "/usr/local/lib/python2.7/site-packages/kombu/utils/scheduling.py", line 56, in get
return self.fun(resource, callback, kwargs)
File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 999, in _drain_channel
return channel.drain_events(callback=callback, timeout=timeout)
File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 745, in drain_events
return self._poll(self.cycle, callback, timeout=timeout)
File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 402, in _poll
return cycle.get(callback)
File "/usr/local/lib/python2.7/site-packages/kombu/utils/scheduling.py", line 56, in get
return self.fun(resource, callback, kwargs)
File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 406, in _get_and_deliver
callback(message, queue)
File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 981, in _deliver
callback(message)
File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 633, in _callback
return callback(message)
File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 624, in _receive_callback
return on_m(message) if on_m else self.receive(decoded, message)
File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 590, in receive
[callback(body, message) for callback in callbacks]
File "/usr/src/geonode/geonode/messaging/consumer.py", line 104, in on_geoserver_messages
geoserver_post_save_local(layer)
File "/usr/src/geonode/geonode/geoserver/signals.py", line 215, in geoserver_post_save_local
sld = instance.default_style.sld_body
AttributeError: 'NoneType' object has no attribute 'sld_body'

Stopping process because --ignore-errors was not set and an error was found.
Traceback (most recent call last):
File "manage.py", line 31, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python2.7/site-packages/django/core/management/init.py", line 364, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python2.7/site-packages/django/core/management/init.py", line

The sld was created using QGIS 3.2.3.
I had to modify the field name used to symbolize in the SLD from being upper case to lower case.
I am able to preview the layer in Geoserver.

**Comment by ikzte** [comment]
@sindile could you solve this already or test it with an updated GeoNode version? If not could you provide some test data?
