### ISSUE TITLE
Regression with uploading a shapefile with no ascii characters

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#4025]
Using master I cannot upload this shapefile, which a few months could be uploaded: 

[ming_female_1.zip](https://github.com/GeoNode/geonode/files/2515642/ming_female_1.zip)

The error is:
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfd in position 1437: invalid start byte

This is happening in the upload.models.update_from_session() when the session is saved (self.save()).

I believe this can happen to any shapefile with sends some non-ascii character in the unicode_session and it can't be encoded/decoded. @afabiani any hint on this?

**Comment by afabiani** [comment]
taking a look

**Comment by capooti** [comment]
thanks @afabiani 
Using the geoserver importer the shapefile is correctly imported.

**Comment by capooti** [comment]
I realized it is not a regression, I tried the method as it was one year ago before your PR with mosaics and there is the same error. It could be that when I uploaded it correctly it was using geonode.rest vs geonode.importer (which I am currently using)

**Comment by afabiani** [comment]
hi @capooti indeed there is an issue, which should be handled somehow.

However, in your specific use case I'm getting an error from GeoServer Importer, not being able to ingest the layer

```
java.io.IOException: Error occurred creating table
	at org.geotools.jdbc.JDBCDataStore.createSchema(JDBCDataStore.java:795)
	at org.geotools.jdbc.JDBCDataStore.createSchema(JDBCDataStore.java:150)
	at org.geoserver.importer.Importer.loadIntoDataStore(Importer.java:1334)
	at org.geoserver.importer.Importer.doIndirectImport(Importer.java:1105)
	at org.geoserver.importer.Importer.run(Importer.java:928)
	at org.geoserver.importer.Importer.run(Importer.java:891)
	at org.geoserver.importer.Importer$5.callInternal(Importer.java:962)
	at org.geoserver.importer.Importer$5.callInternal(Importer.java:1)
	at org.geoserver.importer.Importer$SecurityContextCopyingJob.call(Importer.java:993)
	at org.geoserver.importer.job.Job.call(Job.java:16)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERRORE: la colonna "__" è stata specificata più di una volta
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2476)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2189)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:260)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at org.geotools.jdbc.JDBCDataStore.createSchema(JDBCDataStore.java:787)
	... 13 more
```

**Comment by capooti** [comment]
Which GeoServer version are you using? I am with 2.14.x, and this is what I see in log:

```
2018-10-25 17:35:48,864 TRACE [importer.format] - Error reading file as json
java.lang.RuntimeException: Unexpected character (G) at position 0.
	at org.geotools.geojson.feature.FeatureJSON$FeatureCollectionIterator.readNext(FeatureJSON.java:725)
	at org.geotools.geojson.feature.FeatureJSON$FeatureCollectionIterator.hasNext(FeatureJSON.java:710)
	at org.geoserver.importer.format.GeoJSONFormat.sniff(GeoJSONFormat.java:116)
	at org.geoserver.importer.format.GeoJSONFormat.canRead(GeoJSONFormat.java:106)
	at org.geoserver.importer.DataFormat.lookup(DataFormat.java:50)
	at org.geoserver.importer.Directory.prepare(Directory.java:192)
	at org.geoserver.importer.Importer.addTasks(Importer.java:472)
	at org.geoserver.importer.Importer.update(Importer.java:457)
	at org.geoserver.importer.rest.ImportTaskController.acceptData(ImportTaskController.java:277)
	at org.geoserver.importer.rest.ImportTaskController.taskPost(ImportTaskController.java:178)
```

Furthermore I can successfully import the shapefile with the GeoServer importer from GeoServer admin site. Thanks!

**Comment by capooti** [comment]
I definitely think is a regression. I have downloaded a few shapefiles from our GeoNode instance - which were successfully uploaded with GeoNode 2.7.x and which have Chinese field names and now they all fail to upload.

**Comment by afabiani** [comment]
@capooti can you give a try to this patch here?

https://github.com/GeoNode/geonode/pull/4026
