### ISSUE TITLE
geonode importlayers: srid1 is empty

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#4140]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geonode/base/models.py", line 1313, in resourcebase_post_save
    poly1 = GEOSGeometry(wkt1, srid=int(srid1[0]))
IndexError: list index out of range
```

**Comment by frafra** [comment]
That is what happens when I try to open the layer:

```
Internal Server Error: /layers/geonode:lulc_trondheim_v1
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/geonode/layers/views.py", line 354, in layer_detail
    target_srid=int(srs.split(":")[1]))[:4])
  File "/usr/local/lib/python2.7/dist-packages/geonode/utils.py", line 201, in bbox_to_projection
    source_srid = int(proj.split(":")[1])
ValueError: invalid literal for int() with base 10: 'None'
```

**Comment by t-book** [comment]
Does this only happen with some specific layer?

**Comment by frafra** [comment]
Yes, exactly.
That is what I am trying to upload: http://geodata.nina.no/static/internal/frank.tar.xz

**Comment by t-book** [comment]
Might be connect to to EPSG:3035. 

```
$ ogrinfo -so -al  /Users/ts/Downloads/frank/LULC_Trondheim_V1.shp 
INFO: Open of `/Users/ts/Downloads/frank/LULC_Trondheim_V1.shp'
      using driver `ESRI Shapefile' successful.

Layer name: LULC_Trondheim_V1
Metadata:
  DBF_DATE_LAST_UPDATE=2018-12-20
Geometry: 3D Polygon
Feature Count: 228484
Extent: (4321177.296856, 4448941.272014) - (4359546.590839, 4490409.045088)
Layer SRS WKT:
PROJCS["ETRS89 / LAEA Europe",
```

Can you try if it work when reprojecting to f.e. 4326?

**Comment by frafra** [comment]
I am able to upload the reprojected version and this time I can load it via WMS, but I still get the original error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geonode/base/models.py", line 1313, in resourcebase_post_save
    poly1 = GEOSGeometry(wkt1, srid=int(srid1[0]))
IndexError: list index out of range
```

I think that there are two different issue here: one is related to this "srid1", the other is with EPSG:3035 (I opened a different issue #4146).

**Comment by t-book** [comment]
ehm, not really into this projection issues other might definitly know better but can you check bounding boxes of this layer in geoserver?

**Comment by frafra** [comment]
They look fine to me, nothing strange, just some rounding errors.

**Comment by t-book** [comment]
Another Idea, I think srid1[0] deals with bounding box. maybe something odd with Geometry: 3D Polygon

**Comment by frafra** [comment]
That is a nice idea. I will check it having the same data without the third coordinate will work, thank you.

**Comment by t-book** [comment]
@frafra any updates on this? – Is it possible that the third coordinate caused this?
