### ISSUE TITLE
geonode importlayers: paths with spaces do not work

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#4141]
```bash
geonode importlayers -u $user "path with spaces/" # does not work
(cd "path with spaces/" && geonode importlayers -u $user .) # does work
```

Error:

```python-traceback
Please pass a filename or a directory name as the "incoming" parameter, instead of Sentinel4Nature: <type 'str'>
None
Traceback (most recent call last):
  File "/usr/bin/django-admin", line 9, in <module>
    load_entry_point('Django==1.8.19', 'console_scripts', 'django-admin')()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/geonode/layers/management/commands/importlayers.py", line 210, in handle
    charset=charset)
  File "/usr/local/lib/python2.7/dist-packages/geonode/layers/utils.py", line 711, in upload
    raise GeoNodeException(msg)
geonode.GeoNodeException: Please pass a filename or a directory name as the "incoming" parameter, instead of Sentinel4Nature: <type 'str'>
```

**Comment by t-book** [comment]
will it work when you escape the blank ?
`geonode importlayers -u $user "path\ with\ spaces/" `
