### ISSUE TITLE
Error with importer

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#4155]
Importer fails with .kml with the following error:

```
Could not open /tmp/tmpkeUFKg/cities_to_visit.kml
spatial_files: [<SpatialFile base_file=/tmp/tmpkeUFKg/cities_to_visit.kml file_type=<FileType kml> aux=[] sld=[] xml=[]>]
Error creating import session
Traceback (most recent call last):
  File "/home/ubuntu/geonode/geonode/upload/upload.py", line 363, in save_step
    target_store=None
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/client.py", line 103, in upload_files
    session.upload_task(files, use_url, intial_opts)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/api.py", line 421, in upload_task
    tasks = parse_response( resp )
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/api.py", line 48, in parse_response
    return Task(resp['task'], parent=parent)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/api.py", line 72, in __init__
    self._bind_json(json)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/api.py", line 104, in _bind_json
    val = binding.binding(val, parent=self)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/api.py", line 72, in __init__
    self._bind_json(json)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/api.py", line 200, in _bind_json
    super(Target, self)._bind_json(repr)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/api.py", line 99, in _bind_json
    self._binding_failed('expected val for %s', binding.name)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/api.py", line 113, in _binding_failed
    raise BindingFailed('[%s] %s' % (type(self), msg % args))
BindingFailed: [<class 'gsimporter.api.Target'>] expected val for type
Unexpected error in upload step
Traceback (most recent call last):
  File "/home/ubuntu/geonode/geonode/upload/views.py", line 648, in view
    resp = _steps[step](req, upload_session)
  File "/home/ubuntu/geonode/geonode/upload/views.py", line 191, in save_step_view
    time_presentation_reference_value=form.cleaned_data['time_presentation_reference_value']
  File "/home/ubuntu/geonode/geonode/upload/upload.py", line 405, in save_step
    raise e
BindingFailed: [<class 'gsimporter.api.Target'>] expected val for type
Traceback (most recent call last):
  File "/home/ubuntu/geonode/geonode/upload/views.py", line 648, in view
    resp = _steps[step](req, upload_session)
  File "/home/ubuntu/geonode/geonode/upload/views.py", line 191, in save_step_view
    time_presentation_reference_value=form.cleaned_data['time_presentation_reference_value']
  File "/home/ubuntu/geonode/geonode/upload/upload.py", line 405, in save_step
    raise e
BindingFailed: [<class 'gsimporter.api.Target'>] expected val for type
```

This happens only in production, while in my dev box seems working properly. I wonder how this could be caused.

**Comment by jondoig** [comment]
Same for me with just-completed 2.8 build for development created per [this doco](http://docs.geonode.org/en/master/tutorials/install_and_admin/geonode_install/index.html).

In my case uploading a simple shapefile ([TM_WORLD_BORDERS_SIMPL-0.3](http://thematicmapping.org/downloads/TM_WORLD_BORDERS_SIMPL-0.3.zip) from [ThematicMapping](http://thematicmapping.org/downloads/world_borders.php)) fails with console message:
```
Unable to usecom.vividsolutions.jts.geom.impl.CoordinateArraySequenceFactory@2f663d0 to produce CoordinateSequence with dimension 2
```

and the Apache error.log says:
```
Could not open /tmp/tmpxk7jzr/TM_WORLD_BORDERS_SIMPL-0.3.prj
```

The folder `/tmp/tmpxk7jzr` is owned by www-data and has permissions 700 (only owner can access), so maybe that's the issue.

**Comment by jondoig** [comment]
I have a similar issue with my just-completed 2.8 build for development created per [this doco](http://docs.geonode.org/en/master/tutorials/install_and_admin/geonode_install/index.html).

In my case uploading a simple shapefile ([TM_WORLD_BORDERS_SIMPL-0.3](http://thematicmapping.org/downloads/TM_WORLD_BORDERS_SIMPL-0.3.zip) fails with console message:
```
Unable to usecom.vividsolutions.jts.geom.impl.CoordinateArraySequenceFactory@2f663d0 to produce CoordinateSequence with dimension 2
```

and the Apache error.log says:
```
Could not open /tmp/tmpxk7jzr/TM_WORLD_BORDERS_SIMPL-0.3.prj
```

I noticed the folder `/tmp/tmpxk7jzr` is owned by www-data and has permissions 700 (only owner can access). This is created in [layers/forms.py](https://github.com/GeoNode/geonode/blob/2.8.x/geonode/layers/forms.py#L210) with `tempfile.mkdtemp()` which specifically creates a directory "readable, writable, and searchable only by the creating user ID".

So maybe the issue in my case is that the geoserver code that needs to access this folder is running as a user other than www-data???

**Comment by jondoig** [comment]
Back on this job. Thanks @afabiani I tested [http://master.demo.geonode.org](master) - upload of [same data](http://thematicmapping.org/downloads/TM_WORLD_BORDERS_SIMPL-0.3.zip "TM_WORLD_BORDERS_SIMPL_0_3") is fine: no error. The problem is with my 2.8.x dev install.

One change from [this doco](http://docs.geonode.org/en/master/tutorials/install_and_admin/geonode_install/index.html) is I'm running as ubuntu, there's no geo user. But what's that got to do with www-data....

**Comment by t-book** [comment]
@jondoig  please see https://github.com/GeoNode/geonode/issues/3960 might be outdated geotools.
