### ISSUE TITLE
layer upload with celery

### ISSUE THREAD

**Issue by hishamkaram** [GeoNode/geonode#4166]
layer upload fail if celery enabled: 
```
ERROR 2019-01-22 16:00:59,092 views 1 140208880506624 'Layer' object has no attribute '_remote_service_cache'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geonode/layers/views.py", line 211, in layer_upload
    metadata_upload_form=form.cleaned_data["metadata_upload_form"])
  File "/usr/local/lib/python2.7/site-packages/geonode/layers/utils.py", line 595, in file_upload
    defaults=defaults
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 413, in get_or_create
    return super(MultilingualQuerySet, self).get_or_create(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 500, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 405, in create
    return super(MultilingualQuerySet, self).create(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/site-packages/polymorphic/models.py", line 82, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 848, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python2.7/site-packages/geonode/decorators.py", line 44, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geonode/geoserver/signals.py", line 92, in geoserver_post_save
    producer.geoserver_upload_layer(payload)
  File "<decorator-gen-3>", line 2, in geoserver_upload_layer
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 748, in save
    getattr(self, field.get_cache_name())
AttributeError: 'Layer' object has no attribute '_remote_service_cache'
ERROR 2019-01-22 16:00:59,092 views 1 140208880506624 'Layer' object has no attribute '_remote_service_cache'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geonode/layers/views.py", line 211, in layer_upload
    metadata_upload_form=form.cleaned_data["metadata_upload_form"])
  File "/usr/local/lib/python2.7/site-packages/geonode/layers/utils.py", line 595, in file_upload
    defaults=defaults
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 413, in get_or_create
    return super(MultilingualQuerySet, self).get_or_create(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 500, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 405, in create
    return super(MultilingualQuerySet, self).create(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/site-packages/polymorphic/models.py", line 82, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 848, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python2.7/site-packages/geonode/decorators.py", line 44, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geonode/geoserver/signals.py", line 92, in geoserver_post_save
    producer.geoserver_upload_layer(payload)
  File "<decorator-gen-3>", line 2, in geoserver_upload_layer
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 748, in save
    getattr(self, field.get_cache_name())
AttributeError: 'Layer' object has no attribute '_remote_service_cache'
ERROR 2019-01-22 16:00:59,092 views 1 140208880506624 'Layer' object has no attribute '_remote_service_cache'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geonode/layers/views.py", line 211, in layer_upload
    metadata_upload_form=form.cleaned_data["metadata_upload_form"])
  File "/usr/local/lib/python2.7/site-packages/geonode/layers/utils.py", line 595, in file_upload
    defaults=defaults
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 413, in get_or_create
    return super(MultilingualQuerySet, self).get_or_create(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 500, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 405, in create
    return super(MultilingualQuerySet, self).create(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/site-packages/polymorphic/models.py", line 82, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 848, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python2.7/site-packages/geonode/decorators.py", line 44, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geonode/geoserver/signals.py", line 92, in geoserver_post_save
    producer.geoserver_upload_layer(payload)
  File "<decorator-gen-3>", line 2, in geoserver_upload_layer
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 748, in save
    getattr(self, field.get_cache_name())
AttributeError: 'Layer' object has no attribute '_remote_service_cache'
Internal Server Error: /layers/upload
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geonode/layers/views.py", line 294, in layer_upload
    out[_k] = out[_k].decode(saved_layer.charset).encode("utf-8")
AttributeError: 'NoneType' object has no attribute 'charset'
ERROR 2019-01-22 16:00:59,104 exception 1 140208880506624 Internal Server Error: /layers/upload
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geonode/layers/views.py", line 294, in layer_upload
    out[_k] = out[_k].decode(saved_layer.charset).encode("utf-8")
AttributeError: 'NoneType' object has no attribute 'charset'
```
geonode version: 2.10.x

**Comment by afabiani** [comment]
Very strange. Do you have some dataset to test against

http://master.demo.geonode.org

or

http://dev.geonode.geo-solutions.it/

**Comment by hishamkaram** [comment]
@afabiani 
celery log:
```
[2019-01-25 14:07:50,291: WARNING/MainProcess] Received and deleted unknown message.  Wrong destination?!?

The full contents of the message body was: body: {u'keywords': u'<QuerySet []>', u'rating': u'0', u'constraints_other': u'None', u'bbox_x0': u'32.449047100000001', u'csw_mdsource': u'local', u'constraints_other_en': u'None', u'csw_schema': u'http://www.isotc211.org/2005/gmd', u'csw_typename': u'gmd:MD_Metadata', u'date_type': u'publication', u'srid': u'EPSG:4326', u'bbox_x1': u'33.979071300000001', u'edition': u'None', u'featured': u'False', u'owner': 1000, u'has_time': u'False', u'detail_url': u'/layers/geonode:veterinary_78a4c72d_1', u'id': 242, u'category': u'None', u'license': 1, u'spatial_representation_type': u'None', u'uuid': u'981af2cc-20aa-11e9-9240-0242ac1b0005', u'title': u'veterinary_78a4c72d', u'alternate': u'geonode:veterinary_78a4c72d_1', u'name': u'veterinary_78a4c72d_1', u'regions': u'[<Region: Global>, <Region: Africa>, <Region: Central Africa>, <Region: North Africa>, <Region: Asia>, <Region: East Asia>, <Region: South Asia>, <Region: Europe>, <Region: Cyprus>, <Region: Middle East>, <Region: Pacific>]', u'thumbnail_url':... (2270b)
{content_type:'application/json' content_encoding:'utf-8'
  delivery_info:{u'consumer_tag': u'None4', u'redelivered': False, u'routing_key': u'geonode.geoserver', u'delivery_tag': 1, u'exchange': u'geonode'} headers={}}


[2019-01-25 14:07:50,292: WARNING/MainProcess] Received and deleted unknown message.  Wrong destination?!?

The full contents of the message body was: body: {u'keywords': u'<QuerySet []>', u'rating': u'0', u'constraints_other': u'None', u'bbox_x0': u'32.449047100000001', u'csw_mdsource': u'local', u'constraints_other_en': u'None', u'csw_schema': u'http://www.isotc211.org/2005/gmd', u'csw_typename': u'gmd:MD_Metadata', u'date_type': u'publication', u'srid': u'EPSG:4326', u'bbox_x1': u'33.979071300000001', u'edition': u'None', u'featured': u'False', u'owner': 1000, u'has_time': u'False', u'detail_url': u'/layers/geonode:veterinary_78a4c72d_1', u'id': 242, u'category': u'None', u'license': 1, u'spatial_representation_type': u'None', u'uuid': u'981af2cc-20aa-11e9-9240-0242ac1b0005', u'title': u'veterinary_78a4c72d', u'alternate': u'geonode:veterinary_78a4c72d_1', u'name': u'veterinary_78a4c72d_1', u'regions': u'[<Region: Global>, <Region: Africa>, <Region: Central Africa>, <Region: North Africa>, <Region: Asia>, <Region: East Asia>, <Region: South Asia>, <Region: Europe>, <Region: Cyprus>, <Region: Middle East>, <Region: Pacific>]', u'thumbnail_url':... (2270b)
{content_type:'application/json' content_encoding:'utf-8'
  delivery_info:{u'consumer_tag': u'None14', u'redelivered': False, u'routing_key': u'geonode.geoserver', u'delivery_tag': 2, u'exchange': u'geonode'} headers={}}
```
rabbitmq log:
```
=INFO REPORT==== 25-Jan-2019::14:06:48 ===
Starting RabbitMQ 3.6.16 on Erlang 20.3.4
Copyright (C) 2007-2018 Pivotal Software, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/

              RabbitMQ 3.6.16. Copyright (C) 2007-2018 Pivotal Software, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: tty
  ######  ##        tty
  ##########
              Starting broker...

=INFO REPORT==== 25-Jan-2019::14:06:48 ===
node           : rabbit@27eb72ca66da
home dir       : /var/lib/rabbitmq
config file(s) : /etc/rabbitmq/rabbitmq.config
cookie hash    : 6t1REP0OKjHAZuNfYSI60g==
log            : tty
sasl log       : tty
database dir   : /var/lib/rabbitmq/mnesia/rabbit@27eb72ca66da

=INFO REPORT==== 25-Jan-2019::14:06:52 ===
Memory high watermark set to 20127 MiB (21105041408 bytes) of 50318 MiB (52762603520 bytes) total

=INFO REPORT==== 25-Jan-2019::14:06:52 ===
Enabling free disk space monitoring

=INFO REPORT==== 25-Jan-2019::14:06:52 ===
Disk free limit set to 50MB

=INFO REPORT==== 25-Jan-2019::14:06:52 ===
Limiting to approx 1048476 file handles (943626 sockets)

=INFO REPORT==== 25-Jan-2019::14:06:52 ===
FHC read buffering:  OFF
FHC write buffering: ON

=INFO REPORT==== 25-Jan-2019::14:06:52 ===
Waiting for Mnesia tables for 30000 ms, 9 retries left

=INFO REPORT==== 25-Jan-2019::14:06:52 ===
Waiting for Mnesia tables for 30000 ms, 9 retries left

=INFO REPORT==== 25-Jan-2019::14:06:52 ===
Priority queues enabled, real BQ is rabbit_variable_queue

=INFO REPORT==== 25-Jan-2019::14:06:52 ===
Starting rabbit_node_monitor

=INFO REPORT==== 25-Jan-2019::14:06:52 ===
msg_store_transient: using rabbit_msg_store_ets_index to provide index

=INFO REPORT==== 25-Jan-2019::14:06:52 ===
msg_store_persistent: using rabbit_msg_store_ets_index to provide index

=INFO REPORT==== 25-Jan-2019::14:06:52 ===
started TCP Listener on [::]:5672
 completed with 0 plugins.

=INFO REPORT==== 25-Jan-2019::14:06:52 ===
Server startup complete; 0 plugins started.

=INFO REPORT==== 25-Jan-2019::14:06:53 ===
accepting AMQP connection <0.369.0> (172.27.0.7:33088 -> 172.27.0.3:5672)

=INFO REPORT==== 25-Jan-2019::14:06:53 ===
connection <0.369.0> (172.27.0.7:33088 -> 172.27.0.3:5672): user 'guest' authenticated and granted access to vhost '/'

=INFO REPORT==== 25-Jan-2019::14:06:53 ===
accepting AMQP connection <0.377.0> (172.27.0.7:33090 -> 172.27.0.3:5672)

=INFO REPORT==== 25-Jan-2019::14:06:53 ===
connection <0.377.0> (172.27.0.7:33090 -> 172.27.0.3:5672): user 'guest' authenticated and granted access to vhost '/'

=INFO REPORT==== 25-Jan-2019::14:06:53 ===
accepting AMQP connection <0.394.0> (172.27.0.7:33092 -> 172.27.0.3:5672)

=INFO REPORT==== 25-Jan-2019::14:06:53 ===
connection <0.394.0> (172.27.0.7:33092 -> 172.27.0.3:5672): user 'guest' authenticated and granted access to vhost '/'

=INFO REPORT==== 25-Jan-2019::14:07:50 ===
accepting AMQP connection <0.445.0> (172.27.0.5:52792 -> 172.27.0.3:5672)

=INFO REPORT==== 25-Jan-2019::14:07:50 ===
connection <0.445.0> (172.27.0.5:52792 -> 172.27.0.3:5672): user 'guest' authenticated and granted access to vhost '/'

=INFO REPORT==== 25-Jan-2019::14:07:50 ===
accepting AMQP connection <0.455.0> (172.27.0.5:52794 -> 172.27.0.3:5672)

=INFO REPORT==== 25-Jan-2019::14:07:50 ===
connection <0.455.0> (172.27.0.5:52794 -> 172.27.0.3:5672): user 'guest' authenticated and granted access to vhost '/'

=WARNING REPORT==== 25-Jan-2019::14:07:50 ===
closing AMQP connection <0.455.0> (172.27.0.5:52794 -> 172.27.0.3:5672, vhost: '/', user: 'guest'):
client unexpectedly closed TCP connection

=ERROR REPORT==== 25-Jan-2019::14:09:53 ===
closing AMQP connection <0.394.0> (172.27.0.7:33092 -> 172.27.0.3:5672):
missed heartbeats from client, timeout: 60s
```
