### ISSUE TITLE
Unicode error with a shapefile which is correctly exported to GeoJSON with GDAL

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#4184]
Error stack:

```
Traceback (most recent call last):
  File "/home/ubuntu/geonode/geonode/upload/views.py", line 648, in view
    resp = _steps[step](req, upload_session)
  File "/home/ubuntu/geonode/geonode/upload/views.py", line 415, in check_step_view
    import_session.tasks[0].layer, upload_session=upload_session)
  File "/home/ubuntu/geonode/geonode/upload/utils.py", line 543, in layer_eligible_for_time_dimension
    layer_values = values or _get_layer_values(layer, upload_session, expand=0)
  File "/home/ubuntu/geonode/geonode/upload/utils.py", line 526, in _get_layer_values
    feat_values = json_loads_byteified(feat.ExportToJson()).get('properties')
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/osgeo/ogr.py", line 3118, in ExportToJson
    output = simplejson.dumps(output)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/simplejson/__init__.py", line 382, in dumps
    return _default_encoder.encode(obj)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/simplejson/encoder.py", line 291, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/simplejson/encoder.py", line 373, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa1 in position 0: invalid start byte
```

Looking at this line which is causing the error:
feat_values = json_loads_byteified(feat.ExportToJson()).get('properties')

If I export the shapefile to GeoJSON using ogr2ogr that works. Wondering why this is happening.

Find attached the shapefile to reproduce the issue. You need to unzip it before uploading it otherwise you will get a different error (Only one shapefile per zip is allowed).

[test.zip](https://github.com/GeoNode/geonode/files/2797001/test.zip)

@afabiani any ideas on this?

**Comment by t-book** [comment]
@capooti

 have you seen that your bio col has non utf-8 characters?
![bildschirmfoto 2019-01-28 um 11 33 05](https://user-images.githubusercontent.com/20478652/51831178-c4755f80-22f1-11e9-8a5d-ec4a3032ba15.png)

 When converting your shape to GB18030 and choosing it  for upload/charset it works without problems. Unsure if this is really an issue with geonode or just of your source data.

**Comment by capooti** [comment]
Sorry, you are correct @t-book . I used a bad shapefile. Thanks for taking the time to help ;)
closing this.
