### ISSUE TITLE
Delayed Security Sync Task seems causing issues with sqlite queries

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#4219]
Users reported the following stack trace on vanilla GeoNode using sqlite and DELAYED_SECURITY_SIGNALS

```
  . geonode_tmpl_work.celeryapp.debug_task

[2019-02-11 09:44:28,062: ERROR/Beat] Task geonode.security.tasks.synch_guardian[87816ff8-25d7-429f-aa9e-6258a46e7187] raised unexpected: OperationalError('disk I/O error',)
Traceback (most recent call last):
  File "/Users/ts/Documents/github/envs/t-geonode/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/ts/Documents/github/envs/t-geonode/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/ts/Documents/github/envs/t-geonode/src/geonode/geonode/security/tasks.py", line 44, in synch_guardian
    if dirty_resources and dirty_resources.count() > 0:
  File "/Users/ts/Documents/github/envs/t-geonode/lib/python2.7/site-packages/django/db/models/query.py", line 258, in __nonzero__
    return type(self).__bool__(self)
  File "/Users/ts/Documents/github/envs/t-geonode/lib/python2.7/site-packages/django/db/models/query.py", line 254, in __bool__
    self._fetch_all()
  File "/Users/ts/Documents/github/envs/t-geonode/lib/python2.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/ts/Documents/github/envs/t-geonode/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/Users/ts/Documents/github/envs/t-geonode/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
OperationalError: disk I/O error
```

**Comment by t-book** [comment]
checked:

- Tested celerybeat-schedule database is writeable
- no hints it´s the filesystem
