### ISSUE TITLE
NameError: name 'strtobool' is not defined

### ISSUE THREAD

**Issue by rli-rms** [GeoNode/geonode#4412]
Hello,

I was trying to build Geonode project with docker and got this error:

```
django4my_geonode | Traceback (most recent call last):
django4my_geonode |   File "manage.py", line 31, in <module>
django4my_geonode |     execute_from_command_line(sys.argv)
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
django4my_geonode |     utility.execute()
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
django4my_geonode |     settings.INSTALLED_APPS
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
django4my_geonode |     self._setup(name)
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
django4my_geonode |     self._wrapped = Settings(settings_module)
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
django4my_geonode |     mod = importlib.import_module(self.SETTINGS_MODULE)
django4my_geonode |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
django4my_geonode |     __import__(name)
django4my_geonode |   File "/usr/src/my_geonode/my_geonode/settings.py", line 75, in <module>
django4my_geonode |     UNOCONV_ENABLE = strtobool(os.getenv('UNOCONV_ENABLE', 'True'))
django4my_geonode | NameError: name 'strtobool' is not defined
````

It never happened before, but started to occur since this morning (US time). I tried on multiple machines and can confirm that it persists. Was the geonode settings.py accidentally damaged in the last update?

**Comment by rli-rms** [comment]
I was able to build geonode successfully until this issue occurred a few hours ago

**Comment by rli-rms** [comment]
OK, I checked the latest commit #4408 , it seems that "strtobool" was replaced by "ast.literal_eval". @afabiani  could you also fix the docker installation accordingly?  It still requests the old "strtobool". Thanks!

**Comment by afabiani** [comment]
@rli-rms you should add this to my_geonode settings in order to fix the error

from distutils.util import strtobool

however I will leave the import on geonode settings too in order to avoid similar issues in the future
