### ISSUE TITLE
"ImportError: No module named contrib" when building Geonode

### ISSUE THREAD

**Issue by rli-rms** [GeoNode/geonode#4439]
I have been experiencing an issue for Geonode project running on docker. When using `local_settings.py` instead of `settings.py`, the Geonode cannot be built successfully.

I have reproduced this on a freshly started Geonode project. Here are the steps I took:
1. git clone https://github.com/GeoNode/geonode-project.git -b master
2. Start a new geonode project: `
django-admin startproject --template=./geonode-project -e py,rst,json,yml,ini,env,sample -n Dockerfile my_gdp`
3.  Copy `local_settings.py.sample` and rename it into `local_settings.py`
4.  In `wsgi.py`, apply the change: `os.environ.setdefault("DJANGO_SETTINGS_MODULE", "my_gdp.local_settings")`
5. Run: `docker-compose -f docker-compose.yml -f docker-compose.override.yml up --build`

After that, you'll see the error message as below:
```
celery4my_gdp    | running migrations
django4my_gdp    | **************************migrations*******************************
django4my_gdp    | Traceback (most recent call last):
django4my_gdp    |   File "manage.py", line 31, in <module>
django4my_gdp    |     execute_from_command_line(sys.argv)
django4my_gdp    |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
django4my_gdp    |     utility.execute()
django4my_gdp    |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
django4my_gdp    |     django.setup()
django4my_gdp    |   File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
django4my_gdp    |     apps.populate(settings.INSTALLED_APPS)
django4my_gdp    |   File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
django4my_gdp    |     app_config = AppConfig.create(entry)
django4my_gdp    |   File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 120, in create
django4my_gdp    |     mod = import_module(mod_path)
django4my_gdp    |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
django4my_gdp    |     __import__(name)
django4my_gdp    | ImportError: No module named contrib
celery4my_gdp    | **************************migrations*******************************
celery4my_gdp    | Traceback (most recent call last):
celery4my_gdp    |   File "manage.py", line 31, in <module>
celery4my_gdp    |     execute_from_command_line(sys.argv)
celery4my_gdp    |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
celery4my_gdp    |     utility.execute()
celery4my_gdp    |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
celery4my_gdp    |     django.setup()
celery4my_gdp    |   File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
celery4my_gdp    |     apps.populate(settings.INSTALLED_APPS)
celery4my_gdp    |   File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
celery4my_gdp    |     app_config = AppConfig.create(entry)
celery4my_gdp    |   File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 120, in create
celery4my_gdp    |     mod = import_module(mod_path)
celery4my_gdp    |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
celery4my_gdp    |     __import__(name)
celery4my_gdp    | ImportError: No module named contrib
```
The Geonode cannot be built successfully due to the above error. 
I suspect it is a bug. Please investigate.

**Comment by francbartoli** [comment]
@rli-rms I think it is a bug in the geonode-project repo. Can you open this issue in there, I'm going to close it here. Thanks!
