### ISSUE TITLE
OperationalError: could not receive data from server: Bad file descriptor

### ISSUE THREAD

**Issue by bkhezry** [GeoNode/geonode#4466]
I used docker & this repo to develop Geonode.
After uploading some shapefile or Geotiff, I want to remove them.
during remove, this error happens:

```
celery4geonode   | [2019-06-08 21:13:23,800: ERROR/ForkPoolWorker-3] Task geonode.layers.tasks.update.delete_layer[20e266e2-0b11-47e2-9972-057609f680ae] raised unexpected: OperationalError('could not receive data from server: Bad file descriptor\n',)
celery4geonode   | Traceback (most recent call last):
celery4geonode   |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
celery4geonode   |     R = retval = fun(*args, **kwargs)
celery4geonode   |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
celery4geonode   |     return self.run(*args, **kwargs)
celery4geonode   |   File "/usr/local/lib/python2.7/site-packages/celery/app/base.py", line 467, in run
celery4geonode   |     return task._orig_run(*args, **kwargs)
celery4geonode   |   File "/usr/src/app/geonode/layers/tasks.py", line 40, in delete_layer
celery4geonode   |     layer = Layer.objects.get(id=layer_id)
celery4geonode   |   File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
celery4geonode   |     return getattr(self.get_queryset(), name)(*args, **kwargs)
celery4geonode   |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 374, in get
celery4geonode   |     num = len(clone)
celery4geonode   |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __len__
celery4geonode   |     self._fetch_all()
celery4geonode   |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
celery4geonode   |     self._result_cache = list(self._iterable_class(self))
celery4geonode   |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
celery4geonode   |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
celery4geonode   |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
celery4geonode   |     raise original_exception
celery4geonode   | OperationalError: could not receive data from server: Bad file descriptor
celery4geonode   | 
```

**Comment by sjohn-atenekom** [comment]
@bkhezry 
I tested adding layers and deleting them and I didn't face this issue.
Can you give more information about your setup?
- Which branch did you checkout?
- How does your command look like, to start GeoNode?

**Comment by bkhezry** [comment]
@sjohn-atenekom 

- A commit from 3 weeks ago.
- `docker-compose -f docker-compose.yml -f docker-compose.override.localhost.yml up --build`

I will be close to this issue & update my source from the last commit. If it happens again I will comment again.
