### ISSUE TITLE
importlayers: Profile matching query does not exist

### ISSUE THREAD

**Issue by wimpeelaerts** [GeoNode/geonode#4638]
## Expected Behavior
Importing layers to Geonode via 
python manage.py importlayers
python manage.py updatelayers

## Actual Behavior
All seems to be created but the Django db is not updated with the new entries due to user profiles that can’t be found. So the layer doesn't show up in the layer list.

```console
root@1b5916cc815e:/usr/src/app# python manage.py importlayers -n layername -u import_user -o -v 3 /geoserver_data/data/geonode/data_manual_upload/map.tif
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/src/app/geonode/layers/management/commands/importlayers.py", line 160, in handle
    user = get_valid_user(username)
  File "/usr/src/app/geonode/people/utils.py", line 46, in get_valid_user
    theuser = get_user_model().objects.get(username=user)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
geonode.people.models.DoesNotExist: Profile matching query does not exist.
```

## Steps to Reproduce the Problem

  1. Setup Geonode via Docker compose
  2. (Setup user authentication via LDAP)
  3. Copy a file to the geonode container filesystem 
  4. Run: python manage.py importlayers -n layername -u import_user -o  /geoserver_data/data/geonode/data_manual_upload/map.tif

## Specifications

  - GeoNode version: version 2.10rc5
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker compose
  - Platform: Debian Linux version 4.9.0-6-amd64 
  - Additional details:

**Comment by wimpeelaerts** [comment]
Leaving the user out of the command lets GeoNode fallback to a default (first) superuser. Running that leads to more success. The GeoServer layer is created but the database is still not updated so the new layer doesn't show in webplatform.

```console
root@1b5916cc815e:/usr/src/app#python -m django importlayers -n layername-o -v 3 /geoserver_data/data/geonode/data_manual_upload/map.tif
Verifying that GeoNode is running ...

Found 1 potential layers.

/usr/local/lib/python2.7/site-packages/owslib/iso.py:117: FutureWarning: the .identification and .serviceidentification properties will merge into .identification being a list of properties.  This is currently implemented in .identificationinfo.  Please see https://github.com/geopython/OWSLib/issues/38 for more information
  FutureWarning)
/usr/local/lib/python2.7/site-packages/owslib/iso.py:495: FutureWarning: The .keywords and .keywords2 properties will merge into the .keywords property in the future, with .keywords becoming a list of MD_Keywords instances. This is currently implemented in .keywords2. Please see https://github.com/geopython/OWSLib/issues/301 for more information
  FutureWarning)
>>> Step 2. Make sure we are not trying to overwrite a existing resource named [nitrogen_dioxide_Flanders_2016] with the wrong type
geonode/geoserver/helpers.py:1373: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  if store:
>>> Step 3. Identifying if [map] is vector or raster and gathering extra files
>>> Step 4. Starting upload of [map] to GeoServer...
>>> Step 5. Generating the metadata for [map] after successful import to GeoSever
>>> Step 6. Making sure [map] has a valid projection
>>> Step 7. Creating style for [map]
>>> Step 10. Creating Django record for [map]
/usr/local/lib/python2.7/site-packages/geoserver/style.py:73: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  if not user_style:
/usr/local/lib/python2.7/site-packages/geoserver/style.py:77: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  if user_style:
[created] Layer for '/geoserver_data/data/geonode/data_manual_upload/map.tif' (1/1)


Detailed report of failures:


Finished processing 1 layers in 31.0 seconds.

1 Created layers
0 Updated layers
0 Skipped layers
0 Failed layers
31.000000 seconds per layer
```

**Comment by t-book** [comment]
A short in the dark, do you have pending migrations for people app?

**Comment by t-book** [comment]
Further what happens if you define a user where you're sure a profile exists (--user=USER) ?

**Comment by wimpeelaerts** [comment]
Thanks for the advice. I'm really looking forward to promote GeoNode in our organisation. But first need to get it full functional. 

No pending migrations:
```
root@1b5916cc815e:/usr/src/app# python manage.py migrate
Operations to perform:
  Apply all migrations: account, actstream, admin, agon_ratings, announcements, auth, avatar, base, contenttypes, dialogos, documents, favorite, geonode_client, geonode_themes, groups, guardian, invitations, layers, maps, mapstore2_adapter, monitoring, oauth2_provider, people, pinax_notifications, services, sessions, sites, socialaccount, taggit, tastypie, upload, user_messages
Running migrations:
  No migrations to apply.
root@1b5916cc815e:/usr/src/app#
root@1b5916cc815e:/usr/src/app# python manage.py makemigrations
No changes detected
root@1b5916cc815e:/usr/src/app#
```

I'm not a Django expert but when I look into the DB the people_profile table contains 3 users. This is consistent with the People->Users list in the admin panel. newly added users via the application show up in this table. 
But when I debug the people/utils.py function get_valid_user(user=None)
the get_user_model() returns an other list of users. e.g. updater and data_importer, which are not part of the user list in the people_profile table. 

apparently, not supplying a user falls back to the updater user (get_default_user()) which is not part of the user list in the people_profile table. Seems odd but I'm not an expert... 

How can I make sure a profile exists for a user?

**Comment by t-book** [comment]
@wimpeelaerts How did you setup geonode? It looks you do not have a virtualenv in use 

> root@1b5916cc815e:/usr/src/app# python manage.py importlayers -n layername -u import_user -o -v 3 /geoserver_data/data/geonode/data_manual_upload/map.tif


Further can you try to pass in the correct settings file:

`DJANGO_SETTINGS_MODULE=your_geonode.local_settings ./manage.py importlayers ...`

**Comment by wimpeelaerts** [comment]
Well spotted!
I used the docker compose setup which spins up a django4geonode container. 
I'm using the Python interpreter installed in this container. So no virtual env. I'll try passing in the settings file I found here (/usr/src/app/package/support/geonode.local_settings).

This  provides me with a new error:
```console
root@1b5916cc815e:/usr/src/app# export DJANGO_SETTINGS_MODULE=/usr/src/app/package/support/geonode.local_settings
root@1b5916cc815e:/usr/src/app#  python manage.py updatelayers -u user
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/django/__main__.py", line 9, in <module>
    management.execute_from_command_line()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: Import by filename is not supported.
root@1b5916cc815e:/usr/src/app#
```

I'll check the documentation for that error.

**Comment by wimpeelaerts** [comment]
Explicitly pushing in the settings returns the same error 
```console 
root@1b5916cc815e:/usr/src/app# python manage.py importlayers --settings geonode.settings -n map -u user -o -v 3 /geoserver_data/data/geonode/data_manual_upload/map.tif
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/src/app/geonode/layers/management/commands/importlayers.py", line 160, in handle
    user = get_valid_user(username)
  File "/usr/src/app/geonode/people/utils.py", line 52, in get_valid_user
    theuser = get_user_model().objects.get(username=user)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
geonode.people.models.DoesNotExist: Profile matching query does not exist.
```

**Comment by t-book** [comment]
A guess: I think inside docker you need to respect some env variables. Can you log into your django container and try something like:

```
    source $HOME/.override_env; \
    echo DATABASE_URL=$DATABASE_URL; \
    echo GEODATABASE_URL=$GEODATABASE_URL; \
    echo SITEURL=$SITEURL; \
    echo ALLOWED_HOSTS=$ALLOWED_HOSTS; \
    echo GEOSERVER_PUBLIC_LOCATION=$GEOSERVER_PUBLIC_LOCATION; \
    django-admin importlayers ...
```

**Comment by wimpeelaerts** [comment]
@t-book, You have now been promoted to hero status. Still experiencing some other issues but the "Profile matching query" error is gone and the layer was created in the application! 
Thanks!!

**Comment by t-book** [comment]
:)) Great to hear! So can we close here and you open another issue for 

>  Still experiencing some other issues

**Comment by deviirmr** [comment]
> A guess: I think inside docker you need to respect some env variables. Can you log into your django container and try something like:
> 
> ```
>     source $HOME/.override_env; \
>     echo DATABASE_URL=$DATABASE_URL; \
>     echo GEODATABASE_URL=$GEODATABASE_URL; \
>     echo SITEURL=$SITEURL; \
>     echo ALLOWED_HOSTS=$ALLOWED_HOSTS; \
>     echo GEOSERVER_PUBLIC_LOCATION=$GEOSERVER_PUBLIC_LOCATION; \
>     django-admin importlayers ...
> ```

I have also the same issue but it's gone after @t-book suggestion. But I am wondering why it is not the default set in the container.

**Comment by t-book** [comment]
My guess: Every terminal session has its own context hence env vars from the initial starting process are not present for you. Unsure if it would work to make them permanent f.e. by use of bash_profile.
