### ISSUE TITLE
Unable to see a newly added layer in Geoserver in Geonode

### ISSUE THREAD

**Issue by vijayr1912** [GeoNode/geonode#4718]
## Actual Behavior
I uploaded a layer to GeoServer using the following curl command
```
curl -u admin:geoserver -H "Content-type: application/zip" -T /Users/rvijay/Desktop/Geonode-ScratchPad/pointlands.zip http://localhost:8080/geoserver/rest/workspaces/geonode/datastores/pointlands/file.shp
```

After executing this command, I am able to see the new pointlands layer in the GeoServer Layers page

![Screen Shot 2019-08-02 at 5 41 44 pm](https://user-images.githubusercontent.com/14032490/62353087-23d85480-b54d-11e9-8976-5aba942143ad.png)

I have made changes to the GeoFence Data Rules by creating new rules for the services (GWC, WMS, *, WPS, WFS), see the last 5 entries in the table below.

![Screen Shot 2019-08-02 at 5 45 41 pm](https://user-images.githubusercontent.com/14032490/62353207-70bc2b00-b54d-11e9-8bf5-30329b58c623.png)

Despite this I am not able to see this layer on GeoNode 'Explore Layers' option. It only shows the other layers that were added manually from GeoNode GUI Upload Layers option.

Restarting the GeoNode and GeoServer made no change to the above observations

## Steps to Reproduce the Problem

  1. Install GeoNode and GeoServer using the Vagrant box as in http://www.paolocorti.net/foss4g_2017_geonode_solr/
  2. Add a new layer to the Geoserver using curl command - 
```
curl -u admin:geoserver -H "Content-type: application/zip" -T /Users/rvijay/Desktop/Geonode-ScratchPad/pointlands.zip http://localhost:8080/geoserver/rest/workspaces/geonode/datastores/pointlands/file.shp
```

  3. Allow the services (GWC, WMS, *, WPS and WFS) from the GeoFence Data Rules of GeoServer.

4. The newly added layer,pointlands, comes in GeoServer search.

5. It does not show in GeoNode Layer search despite restarting the server.

## Specifications

  - GeoNode version: 2.10.1
   - GeoServer version: 2.15.2
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Manual using Vagrant.
Steps are as in the link - http://www.paolocorti.net/foss4g_2017_geonode_solr/00_setup_the_workshop_environment.html
  - Platform: Ubuntu Linux 18.04
  - Additional details: Had followed the instructions in a Geospatial workshop, the proceedings of which are shared at - http://www.paolocorti.net/foss4g_2017_geonode_solr/

**Comment by t-book** [comment]
@vijayr1912 Layers from geoserver need to be imported to geonode before they show up. You can use the `python manage.py importlayers` management command for it. Be sure to use correct settings file.

**Comment by vijayr1912** [comment]
Hi

Tried to run the following command - 
```
python manage.py updatelayers --skip-geonode-registered --skip-geonode-registered
```

It gives output as -
Finished processing 0 layers in 0.0 seconds.

0 Created layers
0 Updated layers
0 Skipped layers
0 Failed layers

Should i check the geonode/settings.py to check for correct setting parameters.

The OGC dictionary parameters are as follows
``` Python
OGC_SERVER = {
    'default': {
        'BACKEND': 'geonode.geoserver',
        'LOCATION': GEOSERVER_LOCATION,
        'WEB_UI_LOCATION': GEOSERVER_WEB_UI_LOCATION,
        'LOGIN_ENDPOINT': 'j_spring_oauth2_geonode_login',
        'LOGOUT_ENDPOINT': 'j_spring_oauth2_geonode_logout',
        # PUBLIC_LOCATION needs to be kept like this because in dev mode
        # the proxy won't work and the integration tests will fail
        # the entire block has to be overridden in the local_settings
        'PUBLIC_LOCATION': GEOSERVER_PUBLIC_LOCATION,
        'USER': OGC_SERVER_DEFAULT_USER,
        'PASSWORD': OGC_SERVER_DEFAULT_PASSWORD,
        'MAPFISH_PRINT_ENABLED': ast.literal_eval(os.getenv('MAPFISH_PRINT_ENABLED', 'True')),
        'PRINT_NG_ENABLED': ast.literal_eval(os.getenv('PRINT_NG_ENABLED', 'True')),
        'GEONODE_SECURITY_ENABLED': ast.literal_eval(os.getenv('GEONODE_SECURITY_ENABLED', 'True')),
        'GEOFENCE_SECURITY_ENABLED': GEOFENCE_SECURITY_ENABLED,
        'GEOFENCE_URL': os.getenv('GEOFENCE_URL', 'internal:/'),
        'WMST_ENABLED': ast.literal_eval(os.getenv('WMST_ENABLED', 'False')),
        'BACKEND_WRITE_ENABLED': ast.literal_eval(os.getenv('BACKEND_WRITE_ENABLED', 'True')),
        'WPS_ENABLED': ast.literal_eval(os.getenv('WPS_ENABLED', 'True')),
        'LOG_FILE': '%s/geoserver/data/logs/geoserver.log'
        % os.path.abspath(os.path.join(PROJECT_ROOT, os.pardir)),
        # Set to name of database in DATABASES dictionary to enable
        # 'datastore',
        'DATASTORE': os.getenv('DEFAULT_BACKEND_DATASTORE', ''),
        'TIMEOUT': int(os.getenv('OGC_REQUEST_TIMEOUT', '20')),
        'MAX_RETRIES': int(os.getenv('OGC_REQUEST_MAX_RETRIES', '5')),
        'BACKOFF_FACTOR': float(os.getenv('OGC_REQUEST_BACKOFF_FACTOR', '0.3')),
        'POOL_MAXSIZE': int(os.getenv('OGC_REQUEST_POOL_MAXSIZE', '10')),
        'POOL_CONNECTIONS': int(os.getenv('OGC_REQUEST_POOL_CONNECTIONS', '10')),
    }
}
```

**Comment by afabiani** [comment]
@vijayr1912 hi, try to specify also the workspace by using the "-w" option.

**Comment by vijayr1912** [comment]
> @vijayr1912 hi, try to specify also the workspace by using the "-w" option.

Thanks..:)

specifying the workspace option worked. The layer is now available in Geonode search.

``` python
$ python manage.py updatelayers --skip-geonode-registered -w geonode
```

**Comment by guilvinec** [comment]
Hi,
I tried using the updatelayers function to Update the GeoNode application with the GeoServer data. I used python manage.py updatelayers, but I do not understand why it does not work. I have attached the errors displayed. Can you please help me to find out what's wrong? Thank you in advance, truthfully yours,

![Capture](https://user-images.githubusercontent.com/58708228/70474553-1cb0ec80-1ad3-11ea-8e43-8efd7d0f2f7d.PNG)

**Comment by geo-data-co** [comment]
@afabiani Hi, I am having the same problem, but I'm not a Django expert and have to follow detailed instructions.  I followed those to install Geonode Core and Geonode Project with Docker but with this error, and checking instructions for not dockerized installation I feel I'm missing configuration of my settings.py.  Instructions online about this changes (to local_settings.py.sample) are for previous versions of Geonode and I am unable to assimilate them to current ones.

The error I am getting:

$ python manage.py updatelayers --skip-geonode-registered -w geonode
Traceback (most recent call last):
  File "/home/geonode/dev/.venvs/biogeodata/lib/python3.8/site-packages/django/core/management/__init__.py", line 237, in fetch_command
    app_name = commands[subcommand]
KeyError: 'updatelayers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/geonode_custom/biogeodata/biogeodata/settings.py", line 33, in <module>
    from biogeodata.local_settings import *
ModuleNotFoundError: No module named 'biogeodata.local_settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/home/geonode/dev/.venvs/biogeodata/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/geonode/dev/.venvs/biogeodata/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/geonode/dev/.venvs/biogeodata/lib/python3.8/site-packages/django/core/management/__init__.py", line 244, in fetch_command
    settings.INSTALLED_APPS
  File "/home/geonode/dev/.venvs/biogeodata/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/geonode/dev/.venvs/biogeodata/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/geonode/dev/.venvs/biogeodata/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/geonode_custom/biogeodata/biogeodata/settings.py", line 36, in <module>
    from geonode.settings import *
ModuleNotFoundError: No module named 'geonode'

**Comment by geo-data-co** [comment]
@afabiani Hi, I am having the same problem, but I'm not a Django expert and have to follow detailed instructions.  I followed those to install Geonode Core and Geonode Project with Docker but with this error, and checking instructions for not dockerized installation I feel I'm missing configuration of my settings.py.  Instructions online about this changes (to local_settings.py.sample) are for previous versions of Geonode and I am unable to assimilate them to current ones.

The error I am getting:

`$ python manage.py updatelayers --skip-geonode-registered -w geonode
Traceback (most recent call last):
  File "/home/geonode/dev/.venvs/biogeodata/lib/python3.8/site-packages/django/core/management/__init__.py", line 237, in fetch_command
    app_name = commands[subcommand]
KeyError: 'updatelayers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/geonode_custom/biogeodata/biogeodata/settings.py", line 33, in <module>
    from biogeodata.local_settings import *
ModuleNotFoundError: No module named 'biogeodata.local_settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/home/geonode/dev/.venvs/biogeodata/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/geonode/dev/.venvs/biogeodata/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/geonode/dev/.venvs/biogeodata/lib/python3.8/site-packages/django/core/management/__init__.py", line 244, in fetch_command
    settings.INSTALLED_APPS
  File "/home/geonode/dev/.venvs/biogeodata/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/geonode/dev/.venvs/biogeodata/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/geonode/dev/.venvs/biogeodata/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/geonode_custom/biogeodata/biogeodata/settings.py", line 36, in <module>
    from geonode.settings import *
ModuleNotFoundError: No module named 'geonode'`
