### ISSUE TITLE
ImproperlyConfigured celery error when running tests with docker

### ISSUE THREAD

**Issue by travislbrundage** [GeoNode/geonode#5295]
## Expected Behavior
I expect to be able to run unit tests when using GeoNode's docker installation.

## Actual Behavior
Tests are blocked by failures related to celery, reporting an `ImproperlyConfigured` error. Full stack trace:
```
======================================================================
ERROR: test_initial_behavior (geonode.base.tests.ThumbnailTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/Documents/Development/Git/geonode-community/geonode/geonode/base/tests.py", line 31, in setUp
    super(ThumbnailTests, self).setUp()
  File "/home/travis/Documents/Development/Git/geonode-community/geonode/geonode/tests/base.py", line 79, in setUp
    self.get_obj_ids = create_models(type=self.get_type)
  File "/home/travis/Documents/Development/Git/geonode-community/geonode/geonode/base/populate_test_data.py", line 230, in create_models
    m.save()
  File "/home/travis/Documents/Development/Git/geonode-community/geonode-env/local/lib/python2.7/site-packages/polymorphic/models.py", line 93, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/home/travis/Documents/Development/Git/geonode-community/geonode-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/travis/Documents/Development/Git/geonode-community/geonode-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 848, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/home/travis/Documents/Development/Git/geonode-community/geonode-env/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/home/travis/Documents/Development/Git/geonode-community/geonode/geonode/documents/models.py", line 211, in create_thumbnail
    create_document_thumbnail.delay(object_id=instance.id)
  File "/home/travis/Documents/Development/Git/geonode-community/geonode-env/local/lib/python2.7/site-packages/celery/app/task.py", line 408, in delay
    return self.apply_async(args, kwargs)
  File "/home/travis/Documents/Development/Git/geonode-community/geonode-env/local/lib/python2.7/site-packages/celery/app/task.py", line 519, in apply_async
    link=link, link_error=link_error, **options)
  File "/home/travis/Documents/Development/Git/geonode-community/geonode-env/local/lib/python2.7/site-packages/celery/app/task.py", line 734, in apply
    propagate=throw, app=self._get_app(),
  File "/home/travis/Documents/Development/Git/geonode-community/geonode-env/local/lib/python2.7/site-packages/celery/app/trace.py", line 295, in build_tracer
    backend = task.backend
  File "/home/travis/Documents/Development/Git/geonode-community/geonode-env/local/lib/python2.7/site-packages/celery/app/task.py", line 992, in backend
    return self.app.backend
  File "/home/travis/Documents/Development/Git/geonode-community/geonode-env/local/lib/python2.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/travis/Documents/Development/Git/geonode-community/geonode-env/local/lib/python2.7/site-packages/celery/app/base.py", line 1196, in backend
    return self._get_backend()
  File "/home/travis/Documents/Development/Git/geonode-community/geonode-env/local/lib/python2.7/site-packages/celery/app/base.py", line 915, in _get_backend
    return backend(app=self, url=url)
  File "/home/travis/Documents/Development/Git/geonode-community/geonode-env/local/lib/python2.7/site-packages/celery/backends/filesystem.py", line 55, in __init__
    self._do_directory_test(b'.fs-backend-' + uuid().encode(encoding))
  File "/home/travis/Documents/Development/Git/geonode-community/geonode-env/local/lib/python2.7/site-packages/celery/backends/filesystem.py", line 70, in _do_directory_test
    raise ImproperlyConfigured(E_PATH_INVALID)
ImproperlyConfigured: The configured path for the file-system backend does not
work correctly, please make sure that it exists and has
the correct permissions.
```

## Steps to Reproduce the Problem

  1. Clone geonode master
  2. Start GeoNode's docker container as specified in documentation. `docker-compose -f docker-compose.async.yml -f docker-compose.development.yml up -d`.
  3. Attempt to run some unit tests, such as: `coverage run --branch --source=geonode manage.py test geonode.base.tests --noinput`.

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker, SPCGeoNode Docker
  - Platform: Ubuntu 18.04
  - Additional details: This was previously not running into this error. Previously I was receiving the error in https://github.com/GeoNode/geonode/issues/5196 , but this began happening around Oct. 31, 2019.

For now I have switched to using the local setup as described in the documentation, and tests run successfully that way. However, I have not been able to get working tests with any docker installation. The installation otherwise works fine and GeoNode appears to be usable, it just cannot run tests.

**Comment by afabiani** [comment]
This is tipically a problem with the ".celery-results" folder permissions.

The httpd server should be able to write here too.
