### ISSUE TITLE
Django fails to start up in Docker instances

### ISSUE THREAD

**Issue by nilsnolde** [GeoNode/geonode#5327]
## Expected Behavior

Successful startup of Geonode and this in the Django logs:
```
...
789 static files copied to '/mnt/volumes/statics/static'.
static data refreshed
Executing UWSGI server uwsgi --ini /usr/src/app/uwsgi.ini for Production
[uWSGI] getting INI configuration from /usr/src/app/uwsgi.ini
```

## Actual Behavior

Django docker container keeps restarting due to failure, from logs:

```
IS_CELERY=false
DATABASE_URL=postgres://geonode:geonode@db:5432/geonode
GEODATABASE_URL=postgis://geonode_data:geonode_data@db:5432/geonode_data
SITEURL=http://localhost:80/
ALLOWED_HOSTS=['localhost', 'localhost', 'localhost:80', 'django', 'geonode']
GEOSERVER_PUBLIC_LOCATION=http://localhost:80/geoserver/
GEOSERVER_WEB_UI_LOCATION=http://localhost:80/geoserver/
waitfordbs task done
migrations task done
DOCKER_ENV=production
**************************init file********************************
initialized
refresh static data
**************************migrations*******************************
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/src/app/geonode/upload/models.py", line 30, in <module>
    from geonode.geoserver.helpers import gs_uploader, ogc_server_settings
  File "/usr/src/app/geonode/geoserver/helpers.py", line 1885, in <module>
    backoff_factor=ogc_server_settings.BACKOFF_FACTOR)
TypeError: __init__() got an unexpected keyword argument 'retries'
```

## Steps to Reproduce the Problem

  1. Follow the [installation guide for Docker](http://docs.geonode.org/en/2.10.x/install/core/index.html#deploy-a-vanilla-geonode-2-10-with-docker)
  2. `docker logs django4geonode`

## Specifications

  - GeoNode version: latest Docker release (2.10.1?)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): [Docker](http://docs.geonode.org/en/2.10.x/install/core/index.html#deploy-a-vanilla-geonode-2-10-with-docker)
  - Platform: Ubuntu 18.04
  - Additional details:

**Comment by GeoTob** [comment]
I have checked and managed to start the server without issues:

```
# Reset git to 2.10.1
git checkout 0cb7360
# Start the geonode
docker-compose -f docker-compose.yml -f docker-compose.override.localhost.yml up
```
Given that the error above mentions `ogc_server_settings` I wonder if either your Geoserver didn't come up clean or there's a networking issue ?

**Comment by nilsnolde** [comment]
Thanks, I'll have a look trmw. Is there any port that needs to be open on a server other than 80?

**Comment by nilsnolde** [comment]
Nothing changed, but somehow it started working today. So I guess it was networking.
