### ISSUE TITLE
Problem installing fixture '/usr/src/app/geonode/base/fixtures/initial_data.json': Invalid model identifier: 'base.menuplaceholder'

### ISSUE THREAD

**Issue by tom110** [GeoNode/geonode#5452]
## Actual Behavior
I find this wrong:
Traceback (most recent call last):
File "/usr/local/bin/django-admin.py", line 5, in
management.execute_from_command_line()
File "/usr/local/lib/python2.7/site-packages/django/core/management/init.py", line 364, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python2.7/site-packages/django/core/management/init.py", line 356, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
output = self.handle(*args, **options)
File "/usr/local/lib/python2.7/site-packages/modeltranslation/management/commands/loaddata.py", line 61, in handle
return super(Command, self).handle(*fixture_labels, **options)
File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
self.loaddata(fixture_labels)
File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 109, in loaddata
self.load_label(fixture_label)
File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 166, in load_label
for obj in objects:
File "/usr/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 88, in Deserializer
six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
File "/usr/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 82, in Deserializer
for obj in PythonDeserializer(objects, **options):
File "/usr/local/lib/python2.7/site-packages/django/core/serializers/python.py", line 99, in Deserializer
Model = _get_model(d["model"])
File "/usr/local/lib/python2.7/site-packages/django/core/serializers/python.py", line 194, in _get_model
raise base.DeserializationError("Invalid model identifier: '%s'" % model_identifier)
django.core.serializers.base.DeserializationError: Problem installing fixture '/usr/src/app/geonode/base/fixtures/initial_data.json': Invalid model identifier: 'base.menuplaceholder'
I use this http://docs.geonode.org/en/2.10.x/install/core/index.html#docker
my os is centos7

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - GeoNode version:
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by t-book** [comment]
@tom110 which branch did you use ?
