### ISSUE TITLE
python haystack in requirements.txt

### ISSUE THREAD

**Issue by leohoy** [GeoNode/geonode#5461]
## Expected Behavior
Clean install

## Actual Behavior
Error pops up

## Steps to Reproduce the Problem
http://docs.geonode.org/en/2.10.x/install/project/index.html

## Specifications

  - Installation method: geonode-project
  - Platform: ubuntu 18
  - Additional details: replaced djanog-haystack with python-django-haystack

**Comment by t-book** [comment]
Hi @leohoy can you kindly post the error that pops up here?

**Comment by leohoy** [comment]
sure....


    ERROR: Command errored out with exit status 1:
     command: /home/geonode/.virtualenvs/my_geonode/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fj0M0A/django-haystack/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fj0M0A/django-haystack/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-fj0M0A/django-haystack/pip-egg-info
         cwd: /tmp/pip-install-fj0M0A/django-haystack/
    Complete output (44 lines):
    DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
    WARNING: The directory '/home/geonode/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    ERROR: Exception:
    Traceback (most recent call last):
      File "/home/geonode/.virtualenvs/my_geonode/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
        status = self.run(options, args)
      File "/home/geonode/.virtualenvs/my_geonode/local/lib/python2.7/site-packages/pip/_internal/commands/wheel.py", line 158, in run
        resolver.resolve(requirement_set)
      File "/home/geonode/.virtualenvs/my_geonode/local/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
        self._resolve_one(requirement_set, req)
      File "/home/geonode/.virtualenvs/my_geonode/local/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
        abstract_dist = self._get_abstract_dist_for(req_to_install)
      File "/home/geonode/.virtualenvs/my_geonode/local/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 311, in _get_abstract_dist_for
        req.populate_link(self.finder, upgrade_allowed, self.require_hashes)
      File "/home/geonode/.virtualenvs/my_geonode/local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 232, in populate_link
        supported_tags=supported_tags,
      File "/home/geonode/.virtualenvs/my_geonode/local/lib/python2.7/site-packages/pip/_internal/cache.py", line 239, in get
        supported_tags=supported_tags,
      File "/home/geonode/.virtualenvs/my_geonode/local/lib/python2.7/site-packages/pip/_internal/cache.py", line 171, in get
        for wheel_name in self._get_candidates(link, package_name):
      File "/home/geonode/.virtualenvs/my_geonode/local/lib/python2.7/site-packages/pip/_internal/cache.py", line 95, in _get_candidates
        return os.listdir(root)
    OSError: [Errno 13] Permission denied: '/home/geonode/.cache/pip/wheels/3c/ec/4c/647aab3df2c8150a5eb36a6d9feaaef1dcc8869256fef6c233'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fj0M0A/django-haystack/setup.py", line 71, in <module>
        setup_requires=['setuptools_scm'],
      File "/home/geonode/.virtualenvs/my_geonode/local/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/geonode/.virtualenvs/my_geonode/local/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/geonode/.virtualenvs/my_geonode/local/lib/python2.7/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/geonode/.virtualenvs/my_geonode/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "/home/geonode/.virtualenvs/my_geonode/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "/home/geonode/.virtualenvs/my_geonode/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1069, in obtain
        return installer(requirement)
      File "/home/geonode/.virtualenvs/my_geonode/local/lib/python2.7/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/geonode/.virtualenvs/my_geonode/local/lib/python2.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/home/geonode/.virtualenvs/my_geonode/bin/python2', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpRRGmDI', '--quiet', 'setuptools_scm']' returned non-zero exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by leohoy** [comment]
If I execute sudo pip install django-haystack, it works...

**Comment by leohoy** [comment]
okay I found the error. It is actually in the tutorial of the GeoNode Project. It misses all the sudos in the section: http://docs.geonode.org/en/2.10.x/install/project/index.html#geonode-project-installation
