### ISSUE TITLE
default url (maxmind) for GeoIP DB in updategeoip closed

### ISSUE THREAD

**Issue by sjohn-atenekom** [GeoNode/geonode#5483]
## Expected Behavior
Running management command updategeoip updates file located at GEOIP_PATH.

## Actual Behavior
Maxmind has closed their public download under http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz due to new data privacy regulations. Therefore, the database cannot be download and django container does not start properly.
```
Traceback (most recent call last):
  File "manage.py", line 48, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/geonode/base/management/commands/updategeoip.py", line 73, in handle
    r = requests.get(options['url'], stream=True, timeout=10, verify=False)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='geolite.maxmind.com', port=80): Max retries exceeded with url: /download/geoip/database/GeoLite2-City.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33467c0e90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

## Steps to Reproduce the Problem

  1. run `python manage.py updategeoip --overwrite`
  2.
  3.

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker
  - Platform: Ubuntu
  - Additional details: more information from maxmind: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/
https://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by t-book** [comment]
Hi @sjohn-atenekom please see this PR: https://gitter.im/GeoNode/general?at=5df39e21ac14cc652c78946a

**Comment by sjohn-atenekom** [comment]
Thanks, @t-book. I didn't see that!
