### ISSUE TITLE
Geonode 3.0 Send Email Error: ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by mehmadi** [GeoNode/geonode#5907]
Installed Geonode 3.0 with settings below to send email during registration for account activation:

```
EMAIL_BACKEND = os.getenv('DJANGO_EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('DJANGO_EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = os.getenv('DJANGO_EMAIL_PORT', 587)
EMAIL_HOST_USER = os.getenv('DJANGO_EMAIL_HOST_USER', 'USER@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('DJANGO_EMAIL_HOST_PASSWORD', 'PASS')
EMAIL_USE_TLS = ast.literal_eval(os.getenv('DJANGO_EMAIL_USE_TLS', 'True'))
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'GeoNode <USER@gmail.com>')
```

## Expected Behavior
Receive email for account activation.

## Actual Behavior
Geonode shows message that email is sent. But, no email is received and the following error is seen in `geonode.log`:
`ConnectionRefusedError: [Errno 111] Connection refused`

I tried to see if I can send email from python with the same email as settings in the same machine, it worked with no problem.

Additional details from `geonode.log`:
```
Mon Mar 23 15:53:16 2020 - SIGINT/SIGQUIT received...killing workers...
Mon Mar 23 15:53:17 2020 - [deadlock-detector] a process holding a robust mutex died. recovering...
Mon Mar 23 15:53:18 2020 - worker 1 buried after 2 seconds
Mon Mar 23 15:53:18 2020 - worker 2 buried after 2 seconds
Mon Mar 23 15:53:18 2020 - worker 3 buried after 2 seconds
Mon Mar 23 15:53:18 2020 - worker 4 buried after 2 seconds
Mon Mar 23 15:53:18 2020 - goodbye to uWSGI.
Mon Mar 23 15:53:18 2020 - VACUUM: unix socket /run/uwsgi/app/geonode/socket removed.
Mon Mar 23 15:53:18 2020 - *** Starting uWSGI 2.0.15-debian (64bit) on [Mon Mar 23 15:53:18 2020] ***
Mon Mar 23 15:53:18 2020 - compiled with version: 7.3.0 on 28 September 2018 15:41:15
Mon Mar 23 15:53:18 2020 - os: Linux-4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018
Mon Mar 23 15:53:18 2020 - nodename: ulsdi
Mon Mar 23 15:53:18 2020 - machine: x86_64
Mon Mar 23 15:53:18 2020 - clock source: unix
Mon Mar 23 15:53:18 2020 - pcre jit disabled
Mon Mar 23 15:53:18 2020 - detected number of CPU cores: 2
Mon Mar 23 15:53:18 2020 - current working directory: /
Mon Mar 23 15:53:18 2020 - writing pidfile to /run/uwsgi/app/geonode/pid
Mon Mar 23 15:53:18 2020 - detected binary path: /usr/bin/uwsgi-core
Mon Mar 23 15:53:18 2020 - dropping root privileges as early as possible
Mon Mar 23 15:53:18 2020 - setgid() to 33
Mon Mar 23 15:53:18 2020 - set additional group 27 (sudo)
Mon Mar 23 15:53:18 2020 - setuid() to 1000
Mon Mar 23 15:53:18 2020 - chdir() to /opt/geonode
Mon Mar 23 15:53:18 2020 - your processes number limit is 23744
Mon Mar 23 15:53:18 2020 - your memory page size is 4096 bytes
Mon Mar 23 15:53:18 2020 -  *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
Mon Mar 23 15:53:18 2020 - detected max file descriptor number: 1024
Mon Mar 23 15:53:18 2020 - lock engine: pthread robust mutexes
Mon Mar 23 15:53:18 2020 - thunder lock: enabled
Mon Mar 23 15:53:18 2020 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/geonode/socket fd 3
Mon Mar 23 15:53:18 2020 - uwsgi socket 1 bound to TCP address 0.0.0.0:8000 fd 5
Mon Mar 23 15:53:18 2020 - dropping root privileges after socket binding
Mon Mar 23 15:53:18 2020 - Python version: 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
Mon Mar 23 15:53:18 2020 - Set PythonHome to /home/geonode/.virtualenvs/geonode
Mon Mar 23 15:53:18 2020 - Python main interpreter initialized at 0x5645197f94b0
Mon Mar 23 15:53:18 2020 - dropping root privileges after plugin initialization
Mon Mar 23 15:53:18 2020 - python threads support enabled
Mon Mar 23 15:53:18 2020 - your server socket listen backlog is limited to 100 connections
Mon Mar 23 15:53:18 2020 - your mercy for graceful operations on workers is 60 seconds
Mon Mar 23 15:53:18 2020 - mapped 702080 bytes (685 KB) for 8 cores
Mon Mar 23 15:53:18 2020 - *** Operational MODE: preforking+threaded ***
Mon Mar 23 15:53:22 2020 - WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x5645197f94b0 pid: 11714 (default app)
Mon Mar 23 15:53:22 2020 - dropping root privileges after application loading
Mon Mar 23 15:53:22 2020 - *** uWSGI is running in multiple interpreter mode ***
Mon Mar 23 15:53:22 2020 - spawned uWSGI master process (pid: 11714)
Mon Mar 23 15:53:22 2020 - spawned uWSGI worker 1 (pid: 11734, cores: 2)
Mon Mar 23 15:53:22 2020 - spawned uWSGI worker 2 (pid: 11736, cores: 2)
Mon Mar 23 15:53:22 2020 - spawned uWSGI worker 3 (pid: 11738, cores: 2)
Mon Mar 23 15:53:22 2020 - spawned uWSGI worker 4 (pid: 11740, cores: 2)
Internal Server Error: /account/signup/
Traceback (most recent call last):
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/allauth/account/views.py", line 215, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/allauth/account/views.py", line 81, in dispatch
    **kwargs)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/allauth/account/views.py", line 193, in dispatch
    **kwargs)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/allauth/account/views.py", line 104, in post
    response = self.form_valid(form)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/allauth/account/views.py", line 236, in form_valid
    self.get_success_url())
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/allauth/account/utils.py", line 192, in complete_signup
    signal_kwargs=signal_kwargs)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/allauth/account/utils.py", line 152, in perform_login
    send_email_confirmation(request, user, signup=signup)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/allauth/account/utils.py", line 323, in send_email_confirmation
    signup=signup)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/allauth/account/models.py", line 58, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/allauth/account/models.py", line 163, in send
    get_adapter(request).send_confirmation_mail(request, self, signup)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/allauth/account/adapter.py", line 450, in send_confirmation_mail
    ctx)
  File "./geonode/people/adapters.py", line 154, in send_mail
    msg.send()
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/django/core/mail/message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/home/geonode/.virtualenvs/geonode/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[pid: 11734|app: 0|req: 1/1] xxx.xxx.xxx.xxx () {52 vars in 1057 bytes} [Mon Mar 23 15:54:30 2020] POST /account/signup/ => generated 8765 bytes in 385 msecs (HTTP/1.1 500) 8 headers in 324 bytes (1 switches on core 0)
[pid: 11734|app: 0|req: 2/2] xxx.xxx.xxx.xxx () {46 vars in 789 bytes} [Mon Mar 23 15:54:31 2020] GET /jsi18n/ => generated 3223 bytes in 5 msecs (HTTP/1.1 200) 7 headers in 281 bytes (1 switches on core 1)

```

## Specifications

  - GeoNode version: 3.0
  - Installation method (manual):
  - Platform: Ubuntu 18.04
  - Additional details: NA

**Comment by giohappy** [comment]
Are you sure you're able to send emails through your gmail account, without any double-factor or oauth2 authorization?
Google replies with this if I try to send email from django smtp account.

![image](https://user-images.githubusercontent.com/571129/77344559-9cd22980-6d33-11ea-88e0-1ae82b2c458e.png)

**Comment by t-book** [comment]
> I tried to see if I can send email from python with the same email as settings in the same machine, it worked with no problem.

In the same virtualenv? I do remember that now py 3.7 is required for master you use 3.6

**Comment by t-book** [comment]
@mehmadi one more thing which would make sense: The 111 indicates that gmail refuses your smtp helo. Look at your settings. In case some environment variables exist your credentials/settings will change. Either try to remove the os.gentenv or check current variables with printenv in a terminal session similar to the process which started django ...

**Comment by giohappy** [comment]
btw I don't know how gmail can accpet your emails from python too. Did you reduce you security settings for your account? Otherwise it shouldn't accept unsecure apps (i.e. clients trying to user simple username/password authn)

**Comment by t-book** [comment]
good point @giohappy gmail fooled my several times with it's settings

**Comment by mehmadi** [comment]
> Are you sure you're able to send emails through your gmail account, without any double-factor or oauth2 authorization?
> Google replies with this if I try to send email from django smtp account.
> 
> ![image](https://user-images.githubusercontent.com/571129/77344559-9cd22980-6d33-11ea-88e0-1ae82b2c458e.png)

I already authorized my gmail to send emails from another app by reducing security settings for the account. So, I didn't get this error.

I will try to repeat sending emails from within the virtualenv with python 3.7. I hope it helps to figure out the problem.

**Comment by mehmadi** [comment]
BTW, I thought there might be a problem with allauth

**Comment by giohappy** [comment]
I don't think it's a problem with allauth. You can test sending emails from django shell, without interacting with the other pieces:

```
#python manage.py shell
from django.core.mail.message import EmailMessage

message = EmailMessage(from_email="sender@gmail.com",to=["recipient@gmail.com"],subject="Test from Django",body="Hi!")
message.send()
```

**Comment by t-book** [comment]
... and double-check to use correct settings with `manage.py shell` ;)

**Comment by mehmadi** [comment]
https://github.com/GeoNode/geonode/issues/5907#issuecomment-602772796
I tried this and email was sent without any problem.

HOWEVER, I just figured out the issue is because of `ACCOUNT_APPROVAL_REQUIRED`. No matter if `EMAIL_ENABLE` is `True` or `False`, when I set `ACCOUNT_APPROVAL_REQUIRED` to be `False`, geonode throws this error (https://github.com/GeoNode/geonode/issues/5907#issue-586339364). It is strange!

Any ideas?
