### ISSUE TITLE
Error while generating PDF: java.lang.NoClassDefFoundError: Could not initialize class org.apache.batik.bridge.CursorManager

### ISSUE THREAD

**Issue by lazyfahim** [GeoNode/geonode#5939]
## Expected Behavior:
While print a map. It should print a map and generate a pdf file. 

## Actual Behavior
But the loader from map printing is rounding for unlimited time and the console give me this error:
`Forbidden: /api/o/v4/tokeninfo/
"POST /api/o/v4/tokeninfo/ HTTP/1.1" 403 13
Error while generating PDF:
java.lang.NoClassDefFoundError: Could not initialize class org.apache.batik.bridge.CursorManager
	at org.apache.batik.bridge.BridgeContext.<init>(BridgeContext.java:1162)
	at org.apache.batik.bridge.BridgeContext.<init>(BridgeContext.java:292)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.createBridgeContext(SVGAbstractTranscoder.java:336)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.createBridgeContext(SVGAbstractTranscoder.java:312)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:194)
	at org.apache.batik.transcoder.print.PrintTranscoder.transcode(PrintTranscoder.java:159)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)`

## Steps to Reproduce the Problem

  1. paver start the project
  2.goto: any map.
  3.then print the map with include legend

## Specifications

  - GeoNode version: 3.0
  - Installation method (manual):
  - Platform: ubuntu 18.04
  - Additional details:

**Comment by gannebamm** [comment]
Reproduced a different printing error on SPC: https://gist.github.com/gannebamm/ecadb4e9015b8423e1a6ff8c28928d22

Will test a paver setup tomorrow

**Comment by tigreped** [comment]
Had the same issue as gannebamm, related to JAR on geonode 3.1 docker customized from geonode-project. Should we open an issue? Any hints?

**Comment by villa101101** [comment]
I am facing a similar issue now on version 3.2. Manual installation. The error occurred when I used A4, portrait, including legend
