### ISSUE TITLE
No module named 'geonode': paver command not working

### ISSUE THREAD

**Issue by iamtekson** [GeoNode/geonode#6050]
## Expected Behavior
I am following [the official tutorial for geonode installation on ubuntu 18.04](https://docs.geonode.org/en/master/install/core/index.html). When I tried to setup the paver (`paver setup`), it gets following error,
```
Traceback (most recent call last):
  File "/home/geonode/.virtualenvs/geonode/bin/paver", line 8, in <module>
    sys.exit(main())
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/paver/tasks.py", line 890, in main
    _launch_pavement(args)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/paver/tasks.py", line 858, in _launch_pavement
    exec(compile(source, environment.pavement_file, 'exec'), mod.__dict__)
  File "pavement.py", line 58, in <module>
    from geonode.settings import (
ModuleNotFoundError: No module named 'geonode'
```

## Steps to Reproduce the Problem

  1. As mentioned in tutorial, I have done all the steps accordingly upto `paver setup`. I was curious to check the geonode on my own machine. Before setup paver, I tried these two command which are not mentioned in tutorial, 
```
python manage.py makemigrations
python manage.py migrate
```

  2. And I checked the site by using `python manage.py runserver`. It is working fine. 

I thought that I do not need paver command anymore. But later at this section (__Update the settings in order to use the PostgreSQL Database__), I need paver and tried these commands
```
# Initialize GeoNode
DJANGO_SETTINGS_MODULE=geonode.local_settings paver reset
DJANGO_SETTINGS_MODULE=geonode.local_settings paver setup
DJANGO_SETTINGS_MODULE=geonode.local_settings paver sync
DJANGO_SETTINGS_MODULE=geonode.local_settings python manage.py collectstatic --noinput
``` 
I again got the the same error message. Anyone have any idea? how to solve this issue?

## Specifications

  - GeoNode version: 2.1.3
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: geonode
  - Additional details:

**Comment by t-book** [comment]
Have you enabled the virtualenv when running paver?

**Comment by iamtekson** [comment]
Yes, I activate the virtualenv as suggested in document and also installed the required packages. My site is working fine. But when I tried `DJANGO_SETTINGS_MODULE=geonode.local_settings paver reset`, It shows the above error message.

**Comment by JorgeMartinezG** [comment]
@iamtekson was possible to see the landing page of geonode after running `python manage.py runserver`? 

Please, make sure that even with your venv activated, you have installed geonode within the venv. You can check this by writing `pip freeze`or `pip list`

If not, `pip install -e .` might work. You need to be within the project folder

**Comment by iamtekson** [comment]
I already installed the required packages inside my venv. I have the following packages,
```
(geonode) geonode@geonode:/opt/geonode$ pip freeze

amqp==2.5.2
appdirs==1.4.3
attrs==19.3.0
Automat==20.2.0
beautifulsoup4==4.9.0
billiard==3.6.3.0
boto3==1.12.47
botocore==1.15.48
CacheControl==0.12.6
celery==4.4.2
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
click==7.1.2
colorama==0.4.3
constantly==15.1.0
contextlib2==0.6.0
coverage==5.1
cryptography==2.9.2
decorator==4.4.2
defusedxml==0.6.0
Deprecated==1.2.9
distlib==0.3.0
distro==1.4.0
dj-database-url==0.5.0
dj-pagination==2.4.0
Django==2.2.12
-e git+https://github.com/justquick/django-activity-stream.git@8d38fd45b4bef1f7137fb8185b04ee0d8cdb5e3b#egg=django_activity_stream
django-allauth==0.41.0
django-appconf==1.0.4
django-autocomplete-light==3.5.1
django-bootstrap3-datetimepicker-2==2.8.2
django-celery-beat==2.0.0
django-celery-monitor==1.1.2
django-contrib-comments==1.9.2
django-cors-headers==3.2.1
django-downloadview==1.10
django-filter==2.2.0
django-floppyforms==1.8.0
django-forms-bootstrap==3.1.0
django-geonode-client==1.0.9
django-geonode-mapstore-client==2.0.4
django-guardian==1.4.9
django-haystack==2.8.1
django-imagekit==4.0.2
django-invitations==1.9.3
django-ipware==2.1.0
django-js-asset==1.2.2
django-jsonfield==1.4.0
django-jsonfield-compat==0.4.4
django-leaflet==0.26.0
django-mapstore-adapter==2.0.3.1
django-modeltranslation==0.15
django-mptt==0.11.0
django-polymorphic==2.1.2
django-recaptcha==2.0.6
django-storages==1.9.1
django-taggit==1.2.0
django-tastypie==0.14.3
django-timezone-field==4.0
django-treebeard==4.3.1
djangorestframework==3.11.0
docker==4.2.0
docutils==0.15.2
elasticsearch==7.6.0
entrypoints==0.3
factory-boy==2.12.0
Faker==4.0.3
flake8==3.7.9
future==0.18.2
geoip2==3.0.0
geolinks==0.2.0
geonode-announcements==2.0.2
geonode-avatar==5.0.2
geonode-dialogos==3.0.1
geonode-django-activity-stream==0.9.0
geonode-oauth-toolkit==1.1.5.1
geonode-user-messages==2.0.0
geoserver-restconfig==2.0.2
gisdata==0.5.4
glob2==0.7
gn-arcrest==10.5
gn-gsimporter==2.0.0
gunicorn==20.0.4
html5lib==1.0.1
httplib2==0.17.3
hyperlink==19.0.0
idna==2.8
incremental==17.5.0
inflection==0.4.0
invoke==1.4.1
ipaddr==2.2.0
ipython==5.8.0
ipython-genutils==0.2.0
jdcal==1.4.1
jmespath==0.9.5
jsonfield==2.0.2
jwcrypto==0.7
kombu==4.6.8
lockfile==0.12.2
lxml==4.5.0
Mako==1.1.2
Markdown==2.6.11
MarkupSafe==1.1.1
maxminddb==1.5.2
mccabe==0.6.1
mercantile==1.1.3
mock==4.0.2
more-itertools==8.2.0
msgpack==0.6.2
numpy==1.18.4
oauthlib==3.1.0
OWSLib==0.19.1
packaging==20.3
parse==1.15.0
parse-type==0.5.2
Paver==1.3.4
pep517==0.8.2
pexpect==4.8.0
pickleshare==0.7.5
pilkit==2.0
Pillow==7.1.2
pinax-notifications==5.0.3
pinax-ratings==3.0.3
pluggy==0.13.1
progress==1.5
prompt-toolkit==1.0.18
psutil==5.7.0
psycopg2==2.8.5
ptyprocess==0.6.0
py==1.8.1
pycodestyle==2.5.0
pycountry==19.8.18
pycparser==2.20
pycsw==2.4.2
pyflakes==2.1.1
pygdal==3.0.4.6
Pygments==2.6.1
PyHamcrest==2.0.2
pyOpenSSL==19.1.0
pyparsing==2.4.6
pyproj==2.6.0
pytest==5.4.1
pytest-bdd==3.3.0
pytest-django==3.9.0
pytest-splinter==2.0.1
python-crontab==2.4.2
python-dateutil==2.8.1
python-memcached==1.59
python-mimeparse==1.6.0
python-resize-image==1.1.19
python-slugify==4.0.0
python3-openid==3.1.0
pytoml==0.1.21
pytz==2019.3
PyYAML==5.3.1
requests==2.23.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
retrying==1.3.3
s3transfer==0.3.3
selenium==3.141.0
Shapely==1.7.0
simplegeneric==0.8.1
six==1.12.0
soupsieve==2.0
splinter==0.13.0
SQLAlchemy==1.3.16
sqlparse==0.3.1
text-unidecode==1.3
timeout-decorator==0.4.1
tqdm==4.45.0
traitlets==4.3.3
Twisted==20.3.0
ua-parser==0.10.0
urllib3==1.25.9
user-agents==2.1
uWSGI==2.0.18
vine==1.3.0
wcwidth==0.1.9
webencodings==0.5.1
websocket-client==0.57.0
wrapt==1.12.1
xmljson==0.2.1
xmltodict==0.12.0
zope.interface==5.1.0
```

**Comment by iamtekson** [comment]
This is the import error. I think the problem is in `__init__.py` file inside geonode folder. But I didn't change anything to this file. Any help?

**Comment by JorgeMartinezG** [comment]
@iamtekson I do not see GeoNode module installed given the pip freeze. Could you run pip install -e . ?

**Comment by iamtekson** [comment]
In the official documentation, The installation process is written as,
```
# Install the Python packages
cd /opt/geonode
pip install -r requirements.txt --upgrade --no-cache --no-cache-dir
pip install -e . --upgrade
```
I did the exact same. This above installation did not work for me. But as your suggestion, I again run `pip install -e .` only (exclude the `--upgrade` tag), now it is working fine. What do you think, this is a bug or something else? 
But anyway Thank you very much for your help.
