### ISSUE TITLE
Installation Documentation - pip install requirements - error

### ISSUE THREAD

**Issue by bermud** [GeoNode/geonode#6067]
When running `pip3 install -r requirements.txt`, following the [latest documentation](https://docs.geonode.org/en/master/install/project/#install-dep-proj), I get the following error:

```
(my_geonode) root@b002f37e6e6a:/opt/geonode_custom/my_geonode# pip install -r requirements.txt --upgrade --no-cache --no-cache-dir
Obtaining GeoNode from git+https://github.com/GeoNode/geonode.git#egg=GeoNode (from -r requirements.txt (line 4))
  Cloning https://github.com/GeoNode/geonode.git to /root/.virtualenvs/my_geonode/src/geonode
  Running command git clone -q https://github.com/GeoNode/geonode.git /root/.virtualenvs/my_geonode/src/geonode
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /root/.virtualenvs/my_geonode/bin/python3 /root/.virtualenvs/my_geonode/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpvzfb8if2
       cwd: /root/.virtualenvs/my_geonode/src/geonode
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/root/.virtualenvs/my_geonode/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/root/.virtualenvs/my_geonode/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/root/.virtualenvs/my_geonode/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-0th4zxp8/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 148, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-0th4zxp8/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 128, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-0th4zxp8/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 143, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 58, in <module>
      long_description=open("README.md").read(),
    File "/root/.virtualenvs/my_geonode/lib/python3.6/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2067: ordinal not in range(128)
  ----------------------------------------
ERROR: Command errored out with exit status 1: /root/.virtualenvs/my_geonode/bin/python3 /root/.virtualenvs/my_geonode/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpvzfb8if2 Check the logs for full command output.
(my_geonode) root@b002f37e6e6a:/opt/geonode_custom/my_geonode# 


```

  - GeoNode version: the latest from GtiHub :4635e4b 
  - Installation method: manual installation 
  - Platform: Ubuntu image (18.04)
  - Additional details: Ubuntu image  is inside Docker

**Comment by t-book** [comment]
@bermud This might be caused by your encoding language of your shell.

Try to add following to your docker file:

```
ENV LC_CTYPE en_US.UTF-8
ENV LANG en_US.UTF-8
```

or try following in your shell before running the command

```
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8
```

**Comment by t-book** [comment]
@bermud Is this still an issue or can we close here?
