### ISSUE TITLE
error on updatelayers for docker installation

### ISSUE THREAD

**Issue by geo-studio** [GeoNode/geonode#6386]
## Expected Behavior
running python manage.py updatelayers -w geonode on the django4geonode container shell should return log like described on point number 9, Geonode documentation, administering, geonode management commands, loading data into geonode, management command ([here](https://docs.geonode.org/en/2.10/admin/mgmt_commands/index.html#management-command-updatelayers))

## Actual Behavior
manage.py updatelayers -w geonode returns the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: people_profile

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/src/app/geonode/geoserver/management/commands/updatelayers.py", line 97, in handle
    owner = get_valid_user(user)
  File "/usr/src/app/geonode/people/utils.py", line 46, in get_valid_user
    theuser = get_default_user()
  File "/usr/src/app/geonode/people/utils.py", line 33, in get_default_user
    if superusers.count() > 0:
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 392, in count
    return self.query.get_count(using=self.db)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 504, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 489, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: people_profile

## Steps to Reproduce the Problem

  1. Deploy the docker images
  2. Go to geoserver and import a layer direcly from postgis (in my case, a remote postgis server), then publish on geonode workspace
  3. Access to django4geonode shell
  4. Run manage.py updatelayers -w geonode

## Specifications

  - GeoNode version: 2.10.4
  - Installation method (GeoNode Docker):
  - Platform: Ubuntu 18.04
  - Additional details: This is an on premise server so Ports for remote access were changed on docker-compose.yml and docker-compose.override.localhost.yml files before deployment

**Comment by t-book** [comment]
@geo-studio 
The error message sqlite3.OperationalError: no such table: people_profile indicates you're missing env variables when running the command! Hence sqlite is used over postgis where the table does not exist. You could try something similar to here: https://gitter.im/GeoNode/general?at=5c17d90cb4c74555cce1a29b

**Comment by gannebamm** [comment]
I think this can be closed. The error was identified and a solution posted. If the OP still has issues, please reopen.

**Comment by imperialbeachca** [comment]
Hi,
I am running into this same issue.  I am using the current version of Genode, installed on Ubuntu.  I would love to use the gitter link and find the solution there, however that link no longer works, and threads prior to 2021 are not available.  Can you point me to another solution for this issue?
Thanks,
Russell
