### ISSUE TITLE
The backup command is not working 

### ISSUE THREAD

**Issue by iamtekson** [GeoNode/geonode#6617]
## Expected Behavior
I tried to backup my geonode using following command

```shell
cd opt/geonode/

python manage.py backup --backup-dir=/opt/geonode --config=/opt/geonode/geonode/br/management/commands/settings_sample.ini 
```

I want to backup everything from geonode, so i didn't changed anything with `settings_sample.ini` file. I follow this docs: https://docs.geonode.org/en/master/intermediate/backup/

## Actual Behavior
But the command throw the following error,

```
Traceback (most recent call last):
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: base_configuration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/geonode/geonode/br/management/commands/backup.py", line 96, in handle
    config = Configuration.load()
  File "/opt/geonode/geonode/singleton.py", line 41, in load
    obj, created = cls.objects.get_or_create(pk=1)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: base_configuration
```

## Specifications

  - GeoNode version: geonode master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): 18.04 core installation
  - Platform:
  - Additional details:

**Comment by gannebamm** [comment]
Hi, could you check if in your admin panel the base/configuration is listed:
http(s)://your.geonode.xyz/en/admin/base/configuration/

**Comment by iamtekson** [comment]
Actually, I forgot to mention the option `--settings=geonode.local_settings` in command, that's why this error occurs. Now I am facing the permission error,

```
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/geonode/geonode/br/management/commands/backup.py", line 106, in handle
    self.execute_backup(**options)
  File "/opt/geonode/geonode/br/management/commands/backup.py", line 141, in execute_backup
    self.create_geoserver_backup(config, settings, target_folder, ignore_errors)
  File "/opt/geonode/geonode/br/management/commands/backup.py", line 378, in create_geoserver_backup
    os.chmod(geoserver_bk_file, _permissions)
PermissionError: [Errno 1] Operation not permitted: '/opt/geonode/2020-11-06_074840/geoserver_catalog.zip'
```
The `admin/base/configuration/` URL looks like this. Is it ok?

![image](https://user-images.githubusercontent.com/39838116/98341770-fa588380-2041-11eb-82d9-9a7a31e78707.png)

**Comment by gannebamm** [comment]
The admin panel looks ok. The old stacktrace showed sqlite3 as database backend, you do not use sqlite but a postgresql database?

About the `PermissionError: [Errno 1] Operation not permitted: '/opt/geonode/2020-11-06_074840/geoserver_catalog.zip'` you seem to not have appropriate rights as geonode user to write to this folder. I would create a dedicated backup folder somewhere and give your geonode user permissions to it. You shall change it in the `--backup-dir=/opt/geonode` parameter if running a backup.

**Comment by iamtekson** [comment]
Yes, I used the Postgres database. I already created a folder called `backup` inside `/opt/geonode/`. The command `ls -la` shows the user and group of this folder to `geonode` user. I already tried `--backup-dir=/tmp` and `--backup-dir=/opt/geonode/backup` as well. But it still throws the `permission error`. Is there something missing from the `backup.py` file?


![image](https://user-images.githubusercontent.com/39838116/98345000-a13f1e80-2046-11eb-8787-4805eef8bef4.png)

**Comment by gannebamm** [comment]
ok, my guess is that you **do not** run the command as geonode user, but as your local user. If you created a virtual env please be sure that:
* you enabled it
* use the manage.py command with the geonode user

The mentioned line in the stacktrace actually checks if the current user has the permissions to write in the directory.

**Comment by iamtekson** [comment]
I am running the code with `geonode` user and I already activate the virtual env named as `geonode` as shown in the below code. And I am gettings this kind of error after completion of the dumping process of geonode. I found this strange and still can't figure out. 

```shell
(geonode) geonode@gic-HP:/opt/geonode$
(geonode) geonode@gic-HP:/opt/geonode$ python manage.py backup --backup-dir=/tmp --config=/opt/geonode/geonode/br/management/commands/settings_sample.ini --settings=geonode.local_settings
Before proceeding with the Backup, please ensure that:
 1. The backend (DB or whatever) is accessible and you have rights
 2. The GeoServer is up and running and reachable from this machine
You want to proceed? [n]|y: y
Dumping 'GeoServer Catalog [http://localhost:8080/geoserver/]' into '/tmp/2020-11-09_095809/geoserver_catalog.zip'.
STARTED - 1/11
STARTED - 7/11
COMPLETED - 11/11
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/geonode/geonode/br/management/commands/backup.py", line 106, in handle
    self.execute_backup(**options)
  File "/opt/geonode/geonode/br/management/commands/backup.py", line 141, in execute_backup
    self.create_geoserver_backup(config, settings, target_folder, ignore_errors)
  File "/opt/geonode/geonode/br/management/commands/backup.py", line 378, in create_geoserver_backup
    os.chmod(geoserver_bk_file, _permissions)
PermissionError: [Errno 1] Operation not permitted: '/tmp/2020-11-09_095809/geoserver_catalog.zip'
(geonode) geonode@gic-HP:/opt/geonode$
```

**Comment by iamtekson** [comment]
Hi @gannebamm, I again checked today about this issue. I found the generated backup file (geoserver_catalog.zip) has user and group both are `tomcat`. That's why it was sending me the permission error. Do you have any idea how to change the generated backup file to has default user as `geonode`?

**Comment by gannebamm** [comment]
Since GeoServer is managed and served by tomcat the folders to get the backup from are most likely also belonging to `tomcat`. What happens if you add the `geonode` user to the group `tomcat` with `sudo usermod -aG tomcat geonode`?

**Comment by iamtekson** [comment]
I added the geonode user to the tomcat group. Now the error is coming from [this line](https://github.com/GeoNode/geonode/blob/master/geonode/br/management/commands/backup.py#L379).

**Comment by gannebamm** [comment]
Ok, I see it wants to set/get `0o777` rights. Will this help:
```
sudo mkdir /tmp/geonode_backups
sudo chown geonode:tomcat /tmp/geonode_backups -R
sudo chmod 777 /tmp/geonode_backups -R
python manage.py backup --backup-dir=/tmp/tmp/geonode_backups --config=/opt/geonode/geonode/br/management/commands/settings_sample.ini --settings=geonode.local_settings
```

Just to sort out permissions issues.

**Comment by iamtekson** [comment]
Thank you very much @gannebamm, The `-R` command in `chown` and `chmod` did work for me. Thank you very much.
