### ISSUE TITLE
Can't load local_settings.py

### ISSUE THREAD

**Issue by naub1n** [GeoNode/geonode#6618]
## Expected Behavior
Django load local_settings.py

## Actual Behavior
Django container stopping with exit code 1 and log stay to "waitfordbs task done"

## Steps to Reproduce the Problem

  1. Create file local_settings.py in /usr/src/app/geonode/local_settings.py

  2. Add this code
```
# -*- coding: utf-8 -*-
#########################################################################
#
# My conf
#
#########################################################################

import os

try:
    # import geonode settings
    from geonode.settings import *
except ImportError:
    pass
```

  3. Restart container with this environment variable
`DJANGO_SETTINGS_MODULE=geonode.local_settings`

## Specifications

  - GeoNode version: 3.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker
  - Platform: Linux (CentOS)
  - Additional details:
      Work with GeoNode 3.0 and local_settings.py ( `DJANGO_SETTINGS_MODULE=geonode.local_settings` )
      Work with GeoNode 3.1 and settings.py ( `DJANGO_SETTINGS_MODULE=geonode.settings` )

**Comment by naub1n** [comment]
I tried, pulling new image geonode/geonode:3.1
(geonode/geonode:3.1@sha256:cb384aeaacdf143c4fae08d01d6fcc4d2950f4aaa204446800bb81564e898b92)

This is container log:
```
Restarting periodic command scheduler: cronStopping periodic command scheduler: cron.
Starting periodic command scheduler: cron.
DATABASE_URL=postgres://geonode:geonode@db:5432/geonode
GEODATABASE_URL=postgis://geonode_data:geonode_data@db:5432/geonode_data
SITEURL=http://geonode-dev.aesn.fr/
ALLOWED_HOSTS=['django', '*', 'geonode-dev.aesn.fr', 'geonode-dev.aesn.fr:None', 'geonode', 'django']
GEOSERVER_PUBLIC_LOCATION=http://geonode-dev.aesn.fr/geoserver/
MONITORING_ENABLED=True
MONITORING_HOST_NAME=geonode
MONITORING_SERVICE_NAME=local-geonode
MONITORING_DATA_TTL=7
```
File geonode.log doesn't exist.
Container doesn't stop.

I don't know where i can find more debug info

**Comment by naub1n** [comment]
I tried with new geonode image:
`geonode/geonode:3.1@sha256:cb384aeaacdf143c4fae08d01d6fcc4d2950f4aaa204446800bb81564e898b92`
In geonode container log, the problem seems to be in migration process :

```
Restarting periodic command scheduler: cronStopping periodic command scheduler: cron.
Starting periodic command scheduler: cron.
DATABASE_URL=postgres://geonode:geonode@db:5432/geonode
GEODATABASE_URL=postgis://geonode_data:geonode_data@db:5432/geonode_data
SITEURL=http://geonode-dev.aesn.fr/
ALLOWED_HOSTS=['django', '*', 'geonode-dev.aesn.fr', 'geonode-dev.aesn.fr:None', 'geonode', 'django']
GEOSERVER_PUBLIC_LOCATION=http://geonode-dev.aesn.fr/geoserver/
MONITORING_ENABLED=True
MONITORING_HOST_NAME=geonode
MONITORING_SERVICE_NAME=local-geonode
MONITORING_DATA_TTL=7
waitfordbs task done
running migrations
```
This is the `invoke.log` file
```
                                      List of databases
       Name       |  Owner   | Encoding |  Collate   |   Ctype    |     Access privileges     
------------------+----------+----------+------------+------------+---------------------------
 geonode          | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =Tc/postgres             +
                  |          |          |            |            | postgres=CTc/postgres    +
                  |          |          |            |            | geonode=CTc/postgres
 geonode_data     | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =Tc/postgres             +
                  |          |          |            |            | postgres=CTc/postgres    +
                  |          |          |            |            | geonode_data=CTc/postgres
 postgres         | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0        | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres              +
                  |          |          |            |            | postgres=CTc/postgres
 template1        | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres              +
                  |          |          |            |            | postgres=CTc/postgres
 template_postgis | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
(6 rows)

GeoNode databases are up - executing command
**************************migrations*******************************
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 387, in check
    all_issues = self._run_checks(
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/model_checks.py", line 16, in check_all_models
    models = apps.get_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 178, in get_models
    self.check_models_ready()
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 140, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 336, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 219, in close_all
    for alias in self:
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 213, in __iter__
    return iter(self.databases)
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 147, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'geonode.local_settings'
```

**Comment by singh-atenekom** [comment]
I could reproduce the same error. 

There is an small bug in `docker-compose.override.localhost.yml`. The volumes mapping is wrong. instead of `.:/usr/src/app` it should be `'.:/usr/src/geonode'`. It works with correct volume mapping.

**Comment by singh-atenekom** [comment]
@afabiani  this ticket has label Bug. Volume mapping is not correct in `docker-compose.override.localhost.yml`.  instead of `.:/usr/src/app` it should be `.:/usr/src/geonode`

**Comment by ThemisCol** [comment]
**WARNING: First commit or stash your current changes, or you will lose them.**

1. add file setting.py into .gitignore.
2. git rm -r --cached .
3. git add .
4. git commit -m "fixed untracked files"
