### ISSUE TITLE
[SPCGeonode][Docker] Multilanguage site Container django don't restart after changes 

### ISSUE THREAD

**Issue by jonnyforestGIS** [GeoNode/geonode#6654]
## Expected Behavior
Rebuild docker-compose without problems in a multilanguage SPCGeonode instance.

## Actual Behavior
After the first fresh build, Django Container enter in restart mode (un-healthy)

## Steps to Reproduce the Problem
There are two ways to test this problem:
First way:
  1. Create a fresh install SPCGeonode using docker-compose -f docker-compose.yml up -d --build
  2. Change the settings and add a new language in VARIABLES of MODELTRANSLATION_LANGUAGES and MODELTRANSLATION_FALLBACK_LANGUAGE and save
  3. Run again using docker-compose -f docker-compose.yml up -d --build
  4. After rebuilding the container of Django stays unhealthy and starts to restart.

Second way:
1. With a fresh install using a 2 language in VARIABLES of MODELTRANSLATION_LANGUAGES and MODELTRANSLATION_FALLBACK_LANGUAGE and running using docker-compose -f docker-compose.yml up -d --build
2. Change a random VARIABLE or don't change anything
3. Run again using docker-compose -f docker-compose.yml up -d --build
4. After rebuilding the container of Django stays unhealthy and starts to restart.

For both cases if check the log of Django container I have the following error:
```python

No changes detected

Operations to perform:

Apply all migrations: account, actstream, admin, announcements, auth, avatar, base, br, contenttypes, dialogos, documents, favorite, geonode_client, geonode_themes, groups, guardian, invitations, layers, maps, mapstore2_adapter, monitoring, oauth2_provider, people, pinax_notifications, ratings, services, sessions, sites, socialaccount, taggit, tastypie, upload, user_messages


Running migrations:
Traceback (most recent call [last):]([url](url))
File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateColumn: column "description_pt" of relation "base_license" already exists

````
and

```python

The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "scripts/spcgeonode/django/initialize.py", line 63, in <module>

call_command('migrate', '--noinput')

```

So what I understand when Django try to do the migrations he tries to do recreate the second language in my case "pt" when already have.

## Specifications

  - GeoNode version: 3.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): SPCGeoNode
  - Platform: Windows 10 64x
  - Additional details: 
[spcgeonode_django.log](https://github.com/GeoNode/geonode/files/5565732/spcgeonode_django.log)

**Comment by jonnyforestGIS** [comment]
Probably related with the start of this file? https://github.com/GeoNode/geonode/blob/40623c718ca65548d4e423d9f466fd6973d84a8d/scripts/spcgeonode/django/initialize.py#L63

I search and found this can be related with necessary of using the Django command manage.py migrate --fake

**Comment by jonnyforestGIS** [comment]
If I change initialize.py:

```python

 call_command('migrate', '--noinput')
 ```

to 

```python

 call_command('migrate', '--fake')
 ```
and do the docker-compose -f docker-compose.yml up -d --build - Everything stays fine
