### ISSUE TITLE
ModuleNotFoundError: No module named 'geonode.local_settings'

### ISSUE THREAD

**Issue by cabelq** [GeoNode/geonode#6757]
Hi  I'm installing geonode in Ubuntu 20.04
I followed the steps in this guide, but I have an error when I want to install the webserver (Step 6)

https://docs.geonode.org/en/master/install/advanced/core/index.html#postgis-database-setup

Traceback (most recent call last):
  File "./geonode/wsgi.py", line 30, in <module>
    application = get_wsgi_application()
  File "/home/xrdpuser/.virtualenvs/geonode/lib/python3.8/site-packages/django>
    django.setup(set_prefix=False)
  File "/home/xrdpuser/.virtualenvs/geonode/lib/python3.8/site-packages/django>
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/xrdpuser/.virtualenvs/geonode/lib/python3.8/site-packages/django>
    self._setup(name)
  File "/home/xrdpuser/.virtualenvs/geonode/lib/python3.8/site-packages/django>
    self._wrapped = Settings(settings_module)
  File "/home/xrdpuser/.virtualenvs/geonode/lib/python3.8/site-packages/django>
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'geonode.local_settings'

What am I doing wrong?

This is my geonode.ini is the same as that of the guide by changing this
virtualenv = /home/xrdpuser/.virtualenvs/geonode

Thank you

Regards

Abel Quesi

**Comment by ChiaraSammarco** [comment]
I had the same problem. Reading [this issue](https://github.com/GeoNode/geonode/issues/6618), I figured out that it is looking for a `local_settings.py` under `geonode` folder.

I solved the problem by renaming the file `local_settings.py.geoserver.sample` in `geonode` folder into `local_settings.py ` 
Maybe it's not the best solution, but it seems to work so far. 

Btw I was working on Ubuntu 20.04 (geonode - branch 3.2.x)
