### ISSUE TITLE
EXIF data will not get read

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#6774]
## Expected Behavior
If I upload a picture with EXIF data and EXIF is enabled the EXIF information will be read and saved as part of the photo.

## Actual Behavior

If I upload a photo with EXIF the EXIF data will not be used to fill metadata fields. It will fail silently. After checking the logs and debugging I see the following error:

```
Traceback (most recent call last):
  File "/home/geonode/.virtualenvs/geonodev3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-147058952c6e>", line 1, in <module>
    exif_extract_metadata_doc(self.object)
  File "/home/geonode/PycharmProjects/geonode/geonode/documents/exif/utils.py", line 180, in exif_extract_metadata_doc
    lat = convertExifLocationToDecimalDegrees(gpsinfo["GPSLatitude"], gpsinfo.get('GPSLatitudeRef', 'N'))
  File "/home/geonode/PycharmProjects/geonode/geonode/documents/exif/utils.py", line 54, in convertExifLocationToDecimalDegrees
    dd += float(d[0]) / float(d[1])
TypeError: 'IFDRational' object is not subscriptable
Exif extraction failed.
```

See https://github.com/GeoNode/geonode/blob/master/geonode/documents/exif/utils.py#L54

As example the attached picture will result in `location = (51.0, 47.0, 55.788)`

![grafik](https://user-images.githubusercontent.com/6172324/103645925-1486e300-4f59-11eb-9c96-0f221ec89952.png)

## Steps to Reproduce the Problem

  1. enable EXIF by `EXIF_ENABLED=True` in the settings/ .env file
  2. upload a photo with EXIF data, e.g. [this](https://drive.google.com/file/d/1IRidmA9mA9pFa5_qx7hue9C3m3vj8JGU/view?usp=sharing)

## Specifications

  - GeoNode version: 3.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): paver setup + postgis
  - Platform: Ubuntu 20.04
  - Additional details:

I do not understand why the getitem is needed here:

```py
dd += float(d[0]) / float(d[1])
```

changing these line to

```py
    if location:
        dd = 0.0
        d, m, s = location
        dd += float(d)
        dd += float(m) / 60.0
        dd += float(s) / 3600.0
```

should work well. Is my example picture an edge case?

**Comment by gannebamm** [comment]
I just tested my idea above

```py
def convertExifLocationToDecimalDegrees(location, direction):
    if location:
        dd = 0.0
        d, m, s = location
        dd += float(d)
        dd += float(m) / 60.0
        dd += float(s) / 3600.0
```

Does work for my EXIF photos.

**Comment by gannebamm** [comment]
On master the above fails with:

```
  File "/home/geonode/PycharmProjects/geonode_upstream/geonode/documents/views.py", line 273, in form_valid
    bbox = BBOXHelper.from_xy(bbox)
  File "/home/geonode/PycharmProjects/geonode_upstream/geonode/base/bbox_utils.py", line 41, in from_xy
    xy[1], xy[2] = xy[2], xy[1]
TypeError: 'tuple' object does not support item assignment
```

Looking at the code in geonode/base/bbox_utils.py

```py
    def from_xy(cls, xy):
        """
        Constructs a `BBOXHelper` instance from coordinates in "xy" format.

        :param xy: collection of coordinates as [xmin, xmax, ymin, ymax]
        """
        xy[1], xy[2] = xy[2], xy[1]   # << why do we do this?
        return cls(xy)
```

With the above-mentioned code changes the delivered EXIF xy is already perfectly suited for creating a bbox by `cls(xy)`. @afabiani  Do you know why the strange  xy[1], xy[2] = xy[2], xy[1]?

Anyways, I see the method (from_xy) is used all over the codebase and will not change that. Instead creating the bbox as list instead a tuple will do the trick:

geonode/documents/exif/utils.py:179 ++
```py
            if "GPSLatitude" in gpsinfo and "GPSLongitude" in gpsinfo:
                lat = convertExifLocationToDecimalDegrees(gpsinfo["GPSLatitude"], gpsinfo.get('GPSLatitudeRef', 'N'))
                lon = convertExifLocationToDecimalDegrees(gpsinfo["GPSLongitude"], gpsinfo.get('GPSLongitudeRef', 'E'))
                bbox = [lon, lon, lat, lat] # < switch to list instead tuple (lon, lon, lat, lat)
```

Nonetheless, the search by extent does not work as expected for the images and I will take a look at `geonode.base.bbox_utils.filter_bbox()` now.
