### ISSUE TITLE
uploading a shapefile with paver setup (and spc) does not work

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#6780]
## Expected Behavior

I can use the paver setup to create a simple working GeoNode instance and as a development environment. In this setup I am able to upload a shapefile through the GUI. If I upload the file it will get registered as GeoServer layer and imported into the backend.

## Actual Behavior

The upload will create a Django layer but it fails to create a GeoServer layer and will not get ingested into the backend.

This was tested with and without PostgreSQL as backend.

## Steps to Reproduce the Problem

  1. Use `paver setup, sync, start`
  2. Upload a shapefile

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): paver + PostgreSQL DBMS / SPC docker

  - Additional details: 
  
  I can see lots of requests during the upload. It seems like the async upload code changes do interfere with non-async setups. The docker-compose setup does work. SPC is maybe broken because the currently used async way (Memcached, rabbitMQ?) is set up in a different way in GeoNode docker than SPC docker?

**Comment by obersupermega** [comment]
I have the problem too. I have just pulled a git checkout. And when I upload a layer it stays up forever and ever: "Layer not ready yet. Still finalizing layer ingestion..."
I use docker as SPC Docker. Nothing changes even if I set "ASYNC_SIGNALS=False" or True in the docker-compose.yml.

For me the Geoserver layer will created, but Geonode Layer have a broken extent/BBOX. (see screenshot)

Steps to reproduce: git clone and ../scripts/spcgeonode$: docker-compose -f docker-compose.yml up --build

![Bildschirmfoto von 2021-01-07 12-35-44](https://user-images.githubusercontent.com/47182599/103889198-5002e800-50e6-11eb-92bc-64a027bc5c7f.png)

**Comment by t-book** [comment]
This is the celery queue from docker. There it's working. Comparing it to paver setups startup could help. Maybe the task is not registered there?

```
celery4geonode   |  -------------- worker1@b1f797e40fe4 v5.0.2 (singularity)
celery4geonode   | --- ***** ----- 
celery4geonode   | -- ******* ---- Linux-5.4.39-linuxkit-x86_64-with-glibc2.2.5 2021-01-07 17:44:06
celery4geonode   | - *** --- * --- 
celery4geonode   | - ** ---------- [config]
celery4geonode   | - ** ---------- .> app:         geonode:0x7f3b1c5c9190
celery4geonode   | - ** ---------- .> transport:   amqp://guest:**@rabbitmq:5672//
celery4geonode   | - ** ---------- .> results:     rpc://
celery4geonode   | - *** --- * --- .> concurrency: 10 (prefork)
celery4geonode   | -- ******* ---- .> task events: ON
celery4geonode   | --- ***** ----- 
celery4geonode   |  -------------- [queues]
celery4geonode   |                 .> all.geoserver    exchange=geonode(topic) key=geoserver.#
celery4geonode   |                 .> broadcast        exchange=geonode(topic) key=#
celery4geonode   |                 .> cleanup          exchange=default(direct) key=cleanup
celery4geonode   |                 .> default          exchange=default(direct) key=default
celery4geonode   |                 .> email            exchange=default(direct) key=email
celery4geonode   |                 .> email.events     exchange=geonode(topic) key=email
celery4geonode   |                 .> geonode          exchange=default(direct) key=geonode
celery4geonode   |                 .> geonode.layer.viewer exchange=geonode(topic) key=geonode.viewer
celery4geonode   |                 .> geoserver.catalog exchange=geonode(topic) key=geoserver.catalog
celery4geonode   |                 .> geoserver.data   exchange=geonode(topic) key=geoserver.catalog
celery4geonode   |                 .> geoserver.events exchange=geonode(topic) key=geonode.geoserver
celery4geonode   |                 .> notifications.events exchange=geonode(topic) key=notifications
celery4geonode   |                 .> update           exchange=default(direct) key=update
celery4geonode   | 
celery4geonode   | [tasks]
celery4geonode   |   . geonode.br.tasks.restore_notification
celery4geonode   |   . geonode.documents.tasks.create_document_thumbnail
celery4geonode   |   . geonode.documents.tasks.delete_orphaned_document_files
celery4geonode   |   . geonode.documents.tasks.delete_orphaned_thumbnails
celery4geonode   |   . geonode.geoserver.tasks.geoserver_cascading_delete
celery4geonode   |   . geonode.geoserver.tasks.geoserver_post_save_layers
celery4geonode   |   . geonode.geoserver.tasks.geoserver_update_layers
celery4geonode   |   . geonode.layers.tasks.delete_layer
celery4geonode   |   . geonode.maps.tasks.delete_map
celery4geonode   |   . geonode.monitoring.tasks.collect_metrics
celery4geonode   |   . geonode.security.tasks.synch_guardian
celery4geonode   |   . geonode.services.tasks.harvest_resource
celery4geonode   |   . geonode.services.tasks.probe_services
celery4geonode   |   . geonode.tasks.email.send_mail
celery4geonode   |   . geonode.tasks.layers.set_permissions
celery4geonode   |   . geonode.tasks.notifications.send_queued_notifications
```

**Comment by gannebamm** [comment]
@obersupermega 

```
  celery:
    << : *default-common-django
    container_name: celery4${COMPOSE_PROJECT_NAME}
    environment:
      - IS_CELERY=True
    entrypoint: ["/usr/src/geonode/entrypoint.sh"]
    command: "celery -A geonode.celery_app:app worker -B -E --statedb=/mnt/volumes/statics/worker.state -s /mnt/volumes/statics/celerybeat-schedule --loglevel=INFO --concurrency=2 -n worker1@%h -f /var/log/celery.log"
```

Could you test to incorporate the above `docker-compose.yml` config line to the SPC celery service? It currently is slightly different. Maybe this will fix the issue.

**Comment by obersupermega** [comment]
@gannebamm Unfortunately. But that did not help.

On the one hand, there is no entrypoint: ["/usr/src/geonode/entrypoint.sh"]. But even if I omit that, I get the following in the log:
celery4port80geonode exited with code 139
celery4port80geonode | basic_ios::clear: iostream error
celery4port80geonode | Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x7fd6b48dec50>> raised: WKBReadingError('Could not create geometry because of errors while reading input.')
celery4port80geonode | Traceback (most recent call last):
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/celery/utils/dispatch/signal.py", line 276, in send
celery4port80geonode |     response = receiver(signal=self, sender=sender, **named)
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/celery/fixups/django.py", line 82, in on_import_modules
celery4port80geonode |     self.worker_fixup.validate_models()
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/celery/fixups/django.py", line 120, in validate_models
celery4port80geonode |     self.django_setup()
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/celery/fixups/django.py", line 116, in django_setup
celery4port80geonode |     django.setup()
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
celery4port80geonode |     apps.populate(settings.INSTALLED_APPS)
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
celery4port80geonode |     app_config.ready()
celery4port80geonode |   File "/src/django-mapstore-adapter/mapstore2_adapter/apps.py", line 34, in ready
celery4port80geonode |     run_setup_hooks()
celery4port80geonode |   File "/src/django-mapstore-adapter/mapstore2_adapter/apps.py", line 17, in run_setup_hooks
celery4port80geonode |     from geonode.urls import urlpatterns
celery4port80geonode |   File "/spcgeonode/geonode/urls.py", line 110, in <module>
celery4port80geonode |     url(r'^catalogue/', include('geonode.catalogue.urls')),
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
celery4port80geonode |     urlconf_module = import_module(urlconf_module)
celery4port80geonode |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
celery4port80geonode |     return _bootstrap._gcd_import(name[level:], package, level)
celery4port80geonode |   File "/spcgeonode/geonode/catalogue/urls.py", line 22, in <module>
celery4port80geonode |     from . import views
celery4port80geonode |   File "/spcgeonode/geonode/catalogue/views.py", line 29, in <module>
celery4port80geonode |     from pycsw import server
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/pycsw/server.py", line 49, in <module>
celery4port80geonode |     from pycsw.ogc.csw import csw2, csw3
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/pycsw/ogc/csw/csw2.py", line 43, in <module>
celery4port80geonode |     from pycsw.core import config, log, metadata, util
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/pycsw/core/metadata.py", line 41, in <module>
celery4port80geonode |     from shapely.geometry import MultiPolygon
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
celery4port80geonode |     from .base import CAP_STYLE, JOIN_STYLE
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/shapely/geometry/base.py", line 183, in <module>
celery4port80geonode |     EMPTY = deserialize_wkb(a2b_hex(b'010700000000000000'))
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/shapely/geometry/base.py", line 123, in deserialize_wkb
celery4port80geonode |     "Could not create geometry because of errors while reading input.")
celery4port80geonode | shapely.errors.WKBReadingError: Could not create geometry because of errors while reading input.
celery4port80geonode | [Errno 2] No such file or directory: 'spatialite': 'spatialite'
celery4port80geonode | Traceback (most recent call last):
celery4port80geonode |   File "/usr/local/bin/celery", line 8, in <module>
celery4port80geonode |     sys.exit(main())
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/celery/__main__.py", line 15, in main
celery4port80geonode |     sys.exit(_main())
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/celery/bin/celery.py", line 213, in main
celery4port80geonode |     return celery(auto_envvar_prefix="CELERY")
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
celery4port80geonode |     return self.main(*args, **kwargs)
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
celery4port80geonode |     rv = self.invoke(ctx)
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
celery4port80geonode |     return _process_result(sub_ctx.command.invoke(sub_ctx))
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
celery4port80geonode |     return ctx.invoke(self.callback, **ctx.params)
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
celery4port80geonode |     return callback(*args, **kwargs)
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
celery4port80geonode |     return f(get_current_context(), *args, **kwargs)
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/celery/bin/base.py", line 132, in caller
celery4port80geonode |     return f(ctx, *args, **kwargs)
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/celery/bin/worker.py", line 326, in worker
celery4port80geonode |     **kwargs)
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 94, in __init__
celery4port80geonode |     self.app.loader.init_worker()
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/celery/loaders/base.py", line 111, in init_worker
celery4port80geonode |     self.import_default_modules()
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/celery/loaders/base.py", line 105, in import_default_modules
celery4port80geonode |     raise response
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/celery/utils/dispatch/signal.py", line 276, in send
celery4port80geonode |     response = receiver(signal=self, sender=sender, **named)
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/celery/fixups/django.py", line 82, in on_import_modules
celery4port80geonode |     self.worker_fixup.validate_models()
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/celery/fixups/django.py", line 120, in validate_models
celery4port80geonode |     self.django_setup()
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/celery/fixups/django.py", line 116, in django_setup
celery4port80geonode |     django.setup()
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
celery4port80geonode |     apps.populate(settings.INSTALLED_APPS)
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
celery4port80geonode |     app_config.ready()
celery4port80geonode |   File "/src/django-mapstore-adapter/mapstore2_adapter/apps.py", line 34, in ready
celery4port80geonode |     run_setup_hooks()
celery4port80geonode |   File "/src/django-mapstore-adapter/mapstore2_adapter/apps.py", line 17, in run_setup_hooks
celery4port80geonode |     from geonode.urls import urlpatterns
celery4port80geonode |   File "/spcgeonode/geonode/urls.py", line 110, in <module>
celery4port80geonode |     url(r'^catalogue/', include('geonode.catalogue.urls')),
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
celery4port80geonode |     urlconf_module = import_module(urlconf_module)
celery4port80geonode |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
celery4port80geonode |     return _bootstrap._gcd_import(name[level:], package, level)
celery4port80geonode |   File "/spcgeonode/geonode/catalogue/urls.py", line 22, in <module>
celery4port80geonode |     from . import views
celery4port80geonode |   File "/spcgeonode/geonode/catalogue/views.py", line 29, in <module>
celery4port80geonode |     from pycsw import server
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/pycsw/server.py", line 49, in <module>
celery4port80geonode |     from pycsw.ogc.csw import csw2, csw3
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/pycsw/ogc/csw/csw2.py", line 43, in <module>
celery4port80geonode |     from pycsw.core import config, log, metadata, util
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/pycsw/core/metadata.py", line 41, in <module>
celery4port80geonode |     from shapely.geometry import MultiPolygon
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
celery4port80geonode |     from .base import CAP_STYLE, JOIN_STYLE
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/shapely/geometry/base.py", line 183, in <module>
celery4port80geonode |     EMPTY = deserialize_wkb(a2b_hex(b'010700000000000000'))
celery4port80geonode |   File "/usr/local/lib/python3.7/site-packages/shapely/geometry/base.py", line 123, in deserialize_wkb
celery4port80geonode |     "Could not create geometry because of errors while reading input.")
celery4port80geonode | shapely.errors.WKBReadingError: Could not create geometry because of errors while reading input.
celery4port80geonode exited with code 139
django_1          | [pid: 32|app: 0|req: 13/41] 127.0.0.1 () {28 vars in 294 bytes} [Fri Jan  8 09:08:46 2021] GET / => generated 26986 bytes in 135 msecs (HTTP/1.1 200) 9 headers in 560 bytes (1 switches on core 0)

**Comment by obersupermega** [comment]
Ich habe es wieder auf die alte Variante zurückgestellt. Und habe mir das Logfile beim build angeshen.
Da sieht man folgendes: 
celery_1          | [2021-01-08 09:23:07,471: INFO/ForkPoolWorker-3] geonode.geoserver.tasks.geoserver_post_save_layers[d169b865-84f5-4563-a24c-0d8eac206e99]: Using 'MEMCACHED-LOCAL-CONTEXT' lock type.
celery_1          | [2021-01-08 09:23:07,504: INFO/ForkPoolWorker-2] geonode.geoserver.tasks.geoserver_finalize_upload[06689cab-83f6-43c2-b307-6a77e49c4c45]: Using 'MEMCACHED-LOCAL-CONTEXT' lock type.

Then when you upload a shapefile, this is what comes up:
celery_1          | [2021-01-08 09:26:09,207: INFO/ForkPoolWorker-3] geonode.geoserver.tasks.geoserver_post_save_layers[647cc381-c04d-4866-b633-bd5a2d9c2a4a]: Using 'MEMCACHED-LOCAL-CONTEXT' lock type.
nginx_1           | 172.18.0.1 - - [08/Jan/2021:09:26:09 +0000] "GET /upload/final?id=3 HTTP/1.1" 200 179 "http://127.0.0.1/layers/upload" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
celery_1          | [2021-01-08 09:26:09,253: INFO/ForkPoolWorker-2] geonode.geoserver.tasks.geoserver_finalize_upload[f52633b1-defa-461b-9fa4-2d3057534353]: Using 'MEMCACHED-LOCAL-CONTEXT' lock type.
celery_1          | [2021-01-08 09:26:09,258: INFO/ForkPoolWorker-3] geonode.geoserver.tasks.geoserver_finalize_upload[f52633b1-defa-461b-9fa4-2d3057534353]: Using 'MEMCACHED-LOCAL-CONTEXT' lock type.
celery_1          | [2021-01-08 09:26:10,190: INFO/ForkPoolWorker-3] geonode.geoserver.tasks.geoserver_post_save_layers[647cc381-c04d-4866-b633-bd5a2d9c2a4a]: Using 'MEMCACHED-LOCAL-CONTEXT' lock type.
celery_1          | [2021-01-08 09:26:10,191: INFO/ForkPoolWorker-2] geonode.geoserver.tasks.geoserver_post_save_layers[647cc381-c04d-4866-b633-bd5a2d9c2a4a]: Using 'MEMCACHED-LOCAL-CONTEXT' lock type.
celery_1          | [2021-01-08 09:26:10,205: INFO/ForkPoolWorker-3] geonode.geoserver.tasks.geoserver_post_save_layers[647cc381-c04d-4866-b633-bd5a2d9c2a4a]: Using 'MEMCACHED-LOCAL-CONTEXT' lock type.
celery_1          | [2021-01-08 09:26:10,206: INFO/ForkPoolWorker-2] geonode.geoserver.tasks.geoserver_post_save_layers[647cc381-c04d-4866-b633-bd5a2d9c2a4a]: Using 'MEMCACHED-LOCAL-CONTEXT' lock type.
celery_1          | [2021-01-08 09:26:10,229: INFO/ForkPoolWorker-3] geonode.geoserver.tasks.geoserver_post_save_layers[647cc381-c04d-4866-b633-bd5a2d9c2a4a]: Using 'MEMCACHED-LOCAL-CONTEXT' lock type.
celery_1          | [2021-01-08 09:26:10,236: INFO/ForkPoolWorker-2] geonode.geoserver.tasks.geoserver_post_save_layers[647cc381-c04d-4866-b633-bd5a2d9c2a4a]: Using 'MEMCACHED-LOCAL-CONTEXT' lock type.

Whether that helps - I don't know.

**Comment by obersupermega** [comment]
And this is what the postgis container logs during upload:
2021-01-08 09:54:39.982 UTC [180] ERROR:  relation "gt_pk_metadata" does not exist at character 15
2021-01-08 09:54:39.982 UTC [180] STATEMENT:  SELECT * FROM GT_PK_METADATA WHERE 1 = 0

**Comment by gannebamm** [comment]
This also applies for a manual setup without async tasks it seems.

**Comment by afabiani** [comment]
It looks like a blocker... will try to take a look ASAP.

**Comment by AWeissMotz** [comment]
It's the same here I took the master from 8.1.2020 via spcgeonode docker deployment. The uploaded shapes are available on Geoserver but not on Geonodes Layer Overview Page. So on Geonode the data is available under */layers/geonode_data:geonode:point_test but when I click on an element in the Geonode Layer Page it redirects to */layers/:geonode:

**Comment by afabiani** [comment]
@AWeissMotz that means the async is not properly configured.

Take a look at the `rabbitmq` container and `celery` logs, you might need to remove the rabbit volume and let celery recreate the queues.

**Comment by stefmec** [comment]
During a discussion with gannebamm we noticed that the shapefile upload still works on my dev VM.
It was created by following the geonode 2020 workshop tutorial (setup without docker) and uses the master branch from 2020-12-04; the last included commit is af7183a5

**Comment by afabiani** [comment]
Can someone please give a try to https://github.com/GeoNode/geonode/pull/6816

**Comment by t-book** [comment]
@afabiani will test paver

**Comment by obersupermega** [comment]
@afabiani I will test the SPC variant.

**Comment by obersupermega** [comment]
So. The good news is it works. The bad news is it is now quite slow. I uploaded 2 shapefiles which each had only one feature using drag and drop. The layers pretty quickly said they uploaded successfully. However, when I switched to layer list, it took up to a minute for the layers to stop showing the "still working" message.

The thumnails and legends images do not come either. But I think that has other reasons. (I just did a checkout of the branch and started directly without customization).

![Bildschirmfoto von 2021-01-14 10-22-07](https://user-images.githubusercontent.com/47182599/104573764-92cc3f00-5655-11eb-9da4-f146b606c8da.png)

**Comment by afabiani** [comment]
I currently tested both and they seem working fine here.

Notice that the celery command **must** include the additional options in order to work properly:

`--without-gossip --without-mingle -Ofair`

from the `docker-compose.yml` and/or `docker-compose.override.yml`

**Comment by stefmec** [comment]
I tried paver setup and both sqlite and postgres. The upload works, but I always get 4 geoserver exceptions related with the new layer (here "vg2500_sta__00.shp") Maybe this makes it slow? 

```
Jan 15, 2021 5:20:11 PM org.geowebcache.rest.controller.RestExceptionHandler handleRestException
SEVERE: Unknown layer: geonode:vg2500_sta__00
org.geowebcache.rest.exception.RestException 404 NOT_FOUND: Unknown layer: geonode:vg2500_sta__00
        at org.geowebcache.rest.controller.GWCController.findTileLayer(GWCController.java:45)
        at org.geowebcache.rest.controller.TileLayerController.layerGet(TileLayerController.java:66)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        ....

Jan 15, 2021 5:20:11 PM org.geowebcache.rest.controller.RestExceptionHandler handleRestException
SEVERE: Unknown layer: geonode:vg2500_sta__00
org.geowebcache.rest.exception.RestException 404 NOT_FOUND: Unknown layer: geonode:vg2500_sta__00
        at org.geowebcache.rest.controller.GWCController.findTileLayer(GWCController.java:45)
        at org.geowebcache.rest.controller.TileLayerController.layerGet(TileLayerController.java:66)
        at sun.reflect.GeneratedMethodAccessor506.invoke(Unknown Source)
		....

Jan 15, 2021 5:20:11 PM org.geowebcache.rest.controller.RestExceptionHandler handleRestException
SEVERE: Unknown layer: geonode:vg2500_sta__00
org.geowebcache.rest.exception.RestException 404 NOT_FOUND: Unknown layer: geonode:vg2500_sta__00
        at org.geowebcache.rest.controller.GWCController.findTileLayer(GWCController.java:45)
        at org.geowebcache.rest.controller.TileLayerController.layerGet(TileLayerController.java:66)
        at sun.reflect.GeneratedMethodAccessor506.invoke(Unknown Source)
        ....

Jan 15, 2021 5:20:12 PM org.geowebcache.rest.controller.RestExceptionHandler handleRestException
SEVERE: Unknown layer: geonode:vg2500_sta__00
org.geowebcache.rest.exception.RestException 404 NOT_FOUND: Unknown layer: geonode:vg2500_sta__00
        at org.geowebcache.rest.controller.GWCController.findTileLayer(GWCController.java:45)
        at org.geowebcache.rest.controller.TileLayerController.layerGet(TileLayerController.java:66)
        at sun.reflect.GeneratedMethodAccessor506.invoke(Unknown Source)
        ....
```

**Comment by gannebamm** [comment]
This looks like something is off with the GWC (geowebcache). We had some GeoServer GWC issues with one of the jetty paver setups, do you remember @stefmec ? The main URL for geoserver did point to the GWC subsite. Maybe there is something off in the build config @afabiani ?

@stefmec could you try with the latest build https://build.geo-solutions.it/geonode/geoserver/latest/geoserver-2.18.1.war ? 
You will have to change those two lines in the dev_config.yml:
https://github.com/GeoNode/geonode/blob/master/dev_config.yml#L2-L3

To point to the 2.18.1 GeoServer .war **AND** the data-dir:

* https://build.geo-solutions.it/geonode/geoserver/latest/geoserver-2.18.1.war
* https://build.geo-solutions.it/geonode/geoserver/latest/data-2.18.1.zip

**Comment by afabiani** [comment]
@gannebamm that depends on this file from the `GEOSERVER_DATA_DIR` basically

https://github.com/GeoNode/geoserver-geonode-ext/blob/2.17.x/geoserver/data/geonode_v217x/geofence/geofence-server.properties

please, check that is present and contains that information above. Then, restart GeoServer

**Comment by stefmec** [comment]
@gannebamm : I think that's a seperate thing and I'v created a new issue for that #6830 

The `org.geowebcache.rest.exception.RestException`s disappear with geoserver 2.17.4 or 2.18.1 but instead I get:

```
Error while trying to save resource named <geoserver.layer.Layer object at 0x7fd3d5d06d00> in GeoServer, try to use: "Failed to save to Geoserver catalog: 500, Ambiguous handler methods mapped for '/geoserver/rest/layers/grid_3x3_25832__004.xml': {public org.springframework.http.ResponseEntity org.geowebcache.rest.controller.TileLayerController.layerPut(org.geowebcache.layer.TileLayer,java.lang.String) throws org.geowebcache.GeoWebCacheException,org.geowebcache.rest.exception.RestException,java.io.IOException, public void org.geoserver.rest.catalog.LayerController.layerPut(org.geoserver.catalog.LayerInfo,java.lang.String,java.lang.String)}"
Traceback (most recent call last):
  File "/home/geonode/PycharmProjects/geonode_master2/geonode/geoserver/upload.py", line 262, in geoserver_upload
    cat.save(publishing)
  File "/home/geonode/PycharmProjects/geonode_master2/venv/lib/python3.8/site-packages/geoserver/catalog.py", line 302, in save
    raise FailedRequestError('Failed to save to Geoserver catalog: {}, {}'.format(resp.status_code, resp.text))
geoserver.catalog.FailedRequestError: Error while trying to save resource named <geoserver.layer.Layer object at 0x7fd3d5d06d00> in GeoServer, try to use: "Failed to save to Geoserver catalog: 500, Ambiguous handler methods mapped for '/geoserver/rest/layers/grid_3x3_25832__004.xml': {public org.springframework.http.ResponseEntity org.geowebcache.rest.controller.TileLayerController.layerPut(org.geowebcache.layer.TileLayer,java.lang.String) throws org.geowebcache.GeoWebCacheException,org.geowebcache.rest.exception.RestException,java.io.IOException, public void org.geoserver.rest.catalog.LayerController.layerPut(org.geoserver.catalog.LayerInfo,java.lang.String,java.lang.String)}"
Failed to save to Geoserver catalog: 500, Ambiguous handler methods mapped for '/geoserver/rest/layers/grid_3x3_25832__004.xml': {public org.springframework.http.ResponseEntity org.geowebcache.rest.controller.TileLayerController.layerPut(org.geowebcache.layer.TileLayer,java.lang.String) throws org.geowebcache.GeoWebCacheException,org.geowebcache.rest.exception.RestException,java.io.IOException, public void org.geoserver.rest.catalog.LayerController.layerPut(org.geoserver.catalog.LayerInfo,java.lang.String,java.lang.String)}
Traceback (most recent call last):
  File "/home/geonode/PycharmProjects/geonode_master2/geonode/geoserver/tasks.py", line 638, in geoserver_post_save_layers
    set_styles(instance, gs_catalog)
  File "/home/geonode/PycharmProjects/geonode_master2/geonode/geoserver/helpers.py", line 1124, in set_styles
    gs_catalog.save(gs_layer)
  File "/home/geonode/PycharmProjects/geonode_master2/venv/lib/python3.8/site-packages/geoserver/catalog.py", line 302, in save
    raise FailedRequestError('Failed to save to Geoserver catalog: {}, {}'.format(resp.status_code, resp.text))
geoserver.catalog.FailedRequestError: Failed to save to Geoserver catalog: 500, Ambiguous handler methods mapped for '/geoserver/rest/layers/grid_3x3_25832__004.xml': {public org.springframework.http.ResponseEntity org.geowebcache.rest.controller.TileLayerController.layerPut(org.geowebcache.layer.TileLayer,java.lang.String) throws org.geowebcache.GeoWebCacheException,org.geowebcache.rest.exception.RestException,java.io.IOException, public void org.geoserver.rest.catalog.LayerController.layerPut(org.geoserver.catalog.LayerInfo,java.lang.String,java.lang.String)}
Error 404 reading Style Filter Params GeoWebCache at http://localhost:8080/geoserver/gwc/rest/layers/geonode:grid_3x3_25832__004.xml
The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.
The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.
The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.
The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.
Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space
Traceback (most recent call last):
  File "/home/geonode/PycharmProjects/geonode_master2/geonode/geoserver/helpers.py", line 2071, in _render_thumbnail
    raise Exception(content)
Exception: Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space
Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space
Traceback (most recent call last):
  File "/home/geonode/PycharmProjects/geonode_master2/geonode/geoserver/helpers.py", line 2315, in _prepare_thumbnail_body_from_opts
    image = _render_thumbnail(_img_request_template, width=width, height=height)
  File "/home/geonode/PycharmProjects/geonode_master2/geonode/geoserver/helpers.py", line 2091, in _render_thumbnail
    raise e
  File "/home/geonode/PycharmProjects/geonode_master2/geonode/geoserver/helpers.py", line 2071, in _render_thumbnail
    raise Exception(content)
Exception: Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space
Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space
Traceback (most recent call last):
  File "/home/geonode/PycharmProjects/geonode_master2/geonode/layers/utils.py", line 1039, in create_thumbnail
    image = _prepare_thumbnail_body_from_opts(request_body)
  File "/home/geonode/PycharmProjects/geonode_master2/geonode/geoserver/helpers.py", line 2319, in _prepare_thumbnail_body_from_opts
    raise e
  File "/home/geonode/PycharmProjects/geonode_master2/geonode/geoserver/helpers.py", line 2315, in _prepare_thumbnail_body_from_opts
    image = _render_thumbnail(_img_request_template, width=width, height=height)
  File "/home/geonode/PycharmProjects/geonode_master2/geonode/geoserver/helpers.py", line 2091, in _render_thumbnail
    raise e
  File "/home/geonode/PycharmProjects/geonode_master2/geonode/geoserver/helpers.py", line 2071, in _render_thumbnail
    raise Exception(content)
Exception: Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space
```

**Comment by stefmec** [comment]
Indeed `geofence-server.propertie`s was empty with the latest geoserver versions. Downloading the file from github into `geonode/geoserver/data/geofence` removes the python exceptions but recovers the org.geowebcache.rest.exception.RestException.

**Comment by stefmec** [comment]
The exceptions are triggered from geonode/layers/utils.py:L687 `(layer = Layer.objects.create( ...))` und can be forced by accessing `http://127.0.0.1:8080/geoserver/gwc/rest/layers/geonode:AnyBogusLayerName.xml`. So this might be a geoserver issue?

**Comment by stefmec** [comment]
With a complete fresh venv from today I get a bunch of exceptions. In the end the upload works but takes ~ 60 seconds.
```
The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.
The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.
The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.
The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.
The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.
Internal Server Error: /api/o/v4/tokeninfo/
Traceback (most recent call last):
  File "/home/geonode/PycharmProjects/geonode_master/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/geonode/PycharmProjects/geonode_master/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked
```

**Comment by gannebamm** [comment]
The listed errors (and upload times?) are bound to sqlite3. It is a known limitation and we can not change anything there, except advising PostgreSQL as database if possible for development.

As described by @stefmec the upload and development environment will work but SQLite complains about locked connections most likely due to parallel async requests.

**Comment by gannebamm** [comment]
The last time I checked this in my local paver dev it was working.
See: #6816 and #7014 

I will close this. If the error persists It can get reopened.
