### ISSUE TITLE
Error on layer replace

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7392]
When a layer is replaced GeoNode returns the following error:

```
Some error occurred while trying to access the uploaded schema: Please ensure the name is consistent with the file you are trying to replace.
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/layers/utils.py", line 1131, in validate_input_source
    raise Exception(
Exception: Please ensure the name is consistent with the file you are trying to replace.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/geonode/geonode/layers/views.py", line 1338, in layer_replace
    saved_layer = file_upload(
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/src/geonode/geonode/layers/utils.py", line 462, in file_upload
    validate_input_source(layer, filename, files, gtype, action_type='replace')
  File "/usr/src/geonode/geonode/layers/utils.py", line 1164, in validate_input_source
    raise Exception(
Exception: Some error occurred while trying to access the uploaded schema: Please ensure the name is consistent with the file you are trying to replace.
Bad Request: /layers/geonode:Reg01012019_g_WGS847/replace
```

This log comes from master demo. It can be replicated on any layer.

**Comment by mattiagiupponi** [comment]
PR for fix the issue are opened,
master:  https://github.com/GeoNode/geonode/pull/7395
backport: https://github.com/GeoNode/geonode/pull/7396
Friendly reminder that the name of the layer should match the name of the uploaded files
![immagine](https://user-images.githubusercontent.com/51856725/116206190-d6e3db00-a73e-11eb-8384-58b127b5f427.png)
