### ISSUE TITLE
'OAuth2Backend' validator interferes with DRF authenticators

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#7560]
`OAuth2Backend` backend could be useful whenever we would like to authenticate on GeoNode by using an `access_token` instead of the Django session or basic auth.

Currently such authentication is not supported by GeoNoder and therefore the backend is not used by any of the internal GeoNode components or clients and.

Moreover, when trying to hit a REST endpoint its validator interfers with the `auhtenticate` method throwing the following exception

```
Internal Server Error: /api/v2/uploads/upload
Traceback (most recent call last):
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/jwcrypto/jws.py", line 383, in deserialize
    djws = json_decode(raw_jws)
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/jwcrypto/common.py", line 45, in json_decode
    return json.loads(string)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/jwcrypto/jws.py", line 403, in deserialize
    raise InvalidJWSObject('Unrecognized representation')
jwcrypto.jws.InvalidJWSObject: Invalid JWS Object [Unrecognized representation]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/rest_framework/views.py", line 410, in initial
    self.perform_authentication(request)
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/rest_framework/request.py", line 220, in user
    self._authenticate()
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/rest_framework/request.py", line 373, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/rest_framework/authentication.py", line 83, in authenticate
    return self.authenticate_credentials(userid, password, request)
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/rest_framework/authentication.py", line 94, in authenticate_credentials
    user = authenticate(request=request, **credentials)
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/mnt/d/work/code/python/django-oauth-lib/geonode-oauth-toolkit/oauth2_provider/backends.py", line 17, in authenticate
    valid, r = OAuthLibCore.verify_request(request, scopes=[])
  File "/mnt/d/work/code/python/django-oauth-lib/geonode-oauth-toolkit/oauth2_provider/oauth2_backends.py", line 213, in verify_request
    valid, r = self.server.verify_request(uri, http_method, body, headers, scopes=scopes)
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 116, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/endpoints/resource.py", line 75, in verify_request
    return token_type_handler.validate_request(request), request
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/oauthlib/openid/connect/core/tokens.py", line 46, in validate_request
    return self.request_validator.validate_jwt_bearer_token(
  File "/mnt/d/work/code/python/django-oauth-lib/geonode-oauth-toolkit/oauth2_provider/oauth2_validators.py", line 798, in validate_jwt_bearer_token
    return self.validate_id_token(token, scopes, request)
  File "/mnt/d/work/code/python/django-oauth-lib/geonode-oauth-toolkit/oauth2_provider/oauth2_validators.py", line 807, in validate_id_token
    id_token = self._load_id_token(token)
  File "/mnt/d/work/code/python/django-oauth-lib/geonode-oauth-toolkit/oauth2_provider/oauth2_validators.py", line 822, in _load_id_token
    key = self._get_key_for_token(token)
  File "/mnt/d/work/code/python/django-oauth-lib/geonode-oauth-toolkit/oauth2_provider/oauth2_validators.py", line 838, in _get_key_for_token
    unverified_token.deserialize(token)
  File "/home/afabiani/.virtualenvs/geonode-3.x/lib/python3.8/site-packages/jwcrypto/jws.py", line 414, in deserialize
    raise InvalidJWSObject('Invalid format', repr(e))
jwcrypto.jws.InvalidJWSObject: Invalid JWS Object [Invalid format] {InvalidJWSObject('Invalid JWS Object [Unrecognized representation]')}
"PUT /api/v2/uploads/upload HTTP/1.1" 500 57633
```

Let's remove this one from the default settings.

**Comment by giohappy** [comment]
@afabiani the Oauth2 provider is used (and will be used more and more) by external clients like QGIS.
Rather then moving it away I would spend some time to fix it.

**Comment by afabiani** [comment]
@giohappy not this specific backend, this one is not used by external clients, unless they want to get authenticated into GeoNode by providing a valid access_token as a request parameter.

**Comment by giohappy** [comment]
ok then, I trust you!
