### ISSUE TITLE
importlayers command not working

### ISSUE THREAD

**Issue by nikipapadatou** [GeoNode/geonode#7582]
Hello, I am having an issue with importing layers into geonode, as explained below. The importlayers command most of the times is not working. 
Is anybody else having the same issue? 

Thanks in advance!

## Expected Behavior
$ python manage.py importlayers [options] [path] : This command should be used to import layers to geonode.

## Actual Behavior
Sometimes layers are imported as expected, but most of the times they don't. When the shapefiles are not imported correctly, it says 'Layer not ready yet. Still finalizing layer ingestion...' and a red questionmark appears on the 'view layer' page next to the name of the layer. Although the listing exists on geonode (missing the spatial information obvisously), the shapefile is not imported into geoserver. Also, I have checked it with the postgres container, and the layer is not imported into the database as well. 
There is nothing to do with the shapefiles themselves, as the same layer some times are imported correctly, and other times not. The same shapefiles are properly imported through UI. 
I have tried many different combinations with the command line and its options, as removing some/all of them, renaming the shapefiles and the containing folders, providing only the basic files, ignoring the sld etc, but nothing seemed to be a solution.

## Specifications

  - GeoNode version: 3.4
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Geonode Docker
  - Platform: tested on ubuntu and MacOSX
  - Additional details:

**Comment by d3netxer** [comment]
where is the code in the repo for the importlayers command?

**Comment by t-book** [comment]
> where is the code in the repo for the importlayers command?

https://github.com/GeoNode/geonode/blob/3.2.x/geonode/layers/management/commands/importlayers.py

**Comment by nikipapadatou** [comment]
I have followed the code and it seems that the problem occurs somewhere in this function:
https://github.com/GeoNode/geonode/blob/6d9c186fe8c9deb045825ebec61d475b8e7bf501/geonode/geoserver/tasks.py#L326

I have seen the logs from the geoserver container as follows:
>>>>>>
geoserver access log: /usr/local/tomcat/logs/localhost_access_log.2021-05-31.txt
172.27.0.8 - - [31/May/2021:20:37:14 +0000] "PUT /geoserver/rest/workspaces/geonode/datastores/geonode_data/file.shp?update=overwrite&charset=UTF-8&filename=l06.zip&target=shp HTTP/1.1" 201 -
172.27.0.8 - - [31/May/2021:20:37:19 +0000] "GET /geoserver/rest/workspaces/geonode/coveragestores/l06.xml HTTP/1.1" 404 77
172.27.0.8 - - [31/May/2021:20:37:19 +0000] "GET /geoserver/rest/workspaces/geonode/wmsstores/l06.xml HTTP/1.1" 404 72
172.27.0.8 - - [31/May/2021:20:37:22 +0000] "GET /geoserver/rest/workspaces/geonode/datastores/l06.xml HTTP/1.1" 404 72
>>>>>


Also the logs from the celery container is:
>>>>>
[2021-05-31 20:37:26,698: ERROR/ForkPoolWorker-8] Task geonode.geoserver.tasks.geoserver_post_save_layers[2db5f53f-697a-4cbe-8189-03096c14fb28] raised unexpected: GeoNodeException('An exception occurred loading data to PostGIS- 1 ')
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/geoserver/helpers.py", line 1400, in _create_db_featurestore
    assert resource is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 405, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 697, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/autoretry.py", line 54, in run
    ret = task.retry(exc=exc, **retry_kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 703, in retry
    raise_with_context(exc)
  File "/usr/local/lib/python3.8/site-packages/celery/app/autoretry.py", line 34, in run
    return task._orig_run(*args, **kwargs)
  File "/usr/src/geonode/geonode/geoserver/tasks.py", line 461, in geoserver_post_save_layers
    gs_name, workspace, values, gs_resource = geoserver_upload(
  File "/usr/src/geonode/geonode/geoserver/upload.py", line 124, in geoserver_upload
    store, gs_resource = create_store_and_resource(
  File "/usr/src/geonode/geonode/geoserver/helpers.py", line 1411, in _create_db_featurestore
    raise GeoNodeException(msg)
geonode.GeoNodeException: An exception occurred loading data to PostGIS- 1
>>>>>
