### ISSUE TITLE
Style Editor: Mark url image not displayed for layer

### ISSUE THREAD

**Issue by WernerRaath** [GeoNode/geonode#7724]
## Expected Behavior
When opening the style editor, clicking on `Selected layer style settings` -> `Style` -> `MyStyle` -> `Edit selected style` -> `Switch to text editor` and entering the following CSS, I expect the layer to display as icons.
```
@mode 'Flat';
@styleTitle 'Tower icon';

* {
  mark: url('https://iconarchive.com/download/i90297/icons8/windows-8/City-Water-Tower.ico');
  mark-opacity: 1;
  mark-size: 14;
  mark-rotation: 0;
}
```
Hence each point should be displayed as ![marker](https://iconarchive.com/download/i90297/icons8/windows-8/City-Water-Tower.ico)

## Actual Behavior
Instead of GeoServer rendering tiles with that icon as the marker, I see the following:
![Screenshot from 2021-06-29 13-45-50](https://user-images.githubusercontent.com/5022650/123791939-5a0ce300-d8e0-11eb-97db-ea549600cf22.png)

As well as the following **Geoserver exception**:
```
29 Jun 11:42:42 DEBUG [renderer.style] - Error occurred evaluating external graphic
 java.lang.IllegalArgumentException: Argument "value" should not be null.
 	at org.geotools.util.SoftValueHashMap.ensureNotNull(SoftValueHashMap.java:120)
 	at org.geotools.util.SoftValueHashMap.put(SoftValueHashMap.java:252)
 	at java.util.Collections$SynchronizedMap.put(Collections.java:2590)
 	at org.geotools.renderer.style.ImageGraphicFactory.getIcon(ImageGraphicFactory.java:76)
 	at org.geotools.renderer.style.SLDStyleFactory.getIcon(SLDStyleFactory.java:1319)
 	at org.geotools.renderer.style.SLDStyleFactory.getGraphicStyle(SLDStyleFactory.java:1238)
 	at org.geotools.renderer.style.SLDStyleFactory.createPointStyle(SLDStyleFactory.java:571)
 	at org.geotools.renderer.style.SLDStyleFactory.createPointStyle(SLDStyleFactory.java:463)
 	at org.geotools.renderer.style.SLDStyleFactory.createStyleInternal(SLDStyleFactory.java:318)
 	at org.geotools.renderer.style.SLDStyleFactory.createStyle(SLDStyleFactory.java:281)
 	at org.geotools.renderer.style.SLDStyleFactory.createStyle(SLDStyleFactory.java:254)
 	at org.geotools.renderer.lite.StreamingRenderer.processSymbolizers(StreamingRenderer.java:2997)
 	at org.geotools.renderer.lite.StreamingRenderer.processFeature(StreamingRenderer.java:2879)
 	at org.geotools.renderer.lite.StreamingRenderer.drawPlain(StreamingRenderer.java:2651)
 	at org.geotools.renderer.lite.StreamingRenderer.processStylers(StreamingRenderer.java:2272)
 	at org.geotools.renderer.lite.StreamingRenderer.paint(StreamingRenderer.java:902)
 	at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:606)
 	at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:269)
 	at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:129)
 	at org.geoserver.wms.GetMap.executeInternal(GetMap.java:749)
 	at org.geoserver.wms.GetMap.run(GetMap.java:300)
 	at org.geoserver.wms.GetMap.run(GetMap.java:123)
 	at org.geoserver.wms.DefaultWebMapService.getMap(DefaultWebMapService.java:246)
 	at sun.reflect.GeneratedMethodAccessor526.invoke(Unknown Source)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
 	at org.geoserver.kml.WebMapServiceKmlInterceptor.invoke(WebMapServiceKmlInterceptor.java:38)
 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
 	at org.geoserver.gwc.wms.CacheSeedingWebMapService.invoke(CacheSeedingWebMapService.java:55)
 	at org.geoserver.gwc.wms.CacheSeedingWebMapService.invoke(CacheSeedingWebMapService.java:31)
 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
 	at org.geoserver.gwc.wms.CachingWebMapService.invoke(CachingWebMapService.java:67)
 	at org.geoserver.gwc.wms.CachingWebMapService.invoke(CachingWebMapService.java:41)
 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
 	at org.geoserver.ows.util.RequestObjectLogger.invoke(RequestObjectLogger.java:50)
 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
 	at com.sun.proxy.$Proxy169.getMap(Unknown Source)
 	at sun.reflect.GeneratedMethodAccessor483.invoke(Unknown Source)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at org.geoserver.ows.Dispatcher.execute(Dispatcher.java:877)
 	at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:265)
 	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 	at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:26)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:69)
 	at org.geoserver.monitor.MonitorFilter.doFilter(MonitorFilter.java:142)
 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
 	at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:70)
 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
 	at org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:89)
 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
 	at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:41)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 	at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:37)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 	at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:51)
 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 	at org.geoserver.security.oauth2.GeoServerOAuthAuthenticationFilter.doFilter(GeoServerOAuthAuthenticationFilter.java:172)
 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
 	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
 	at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:81)
 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 	at org.geoserver.security.GeoServerAuthenticationKeyFilter.doFilter(GeoServerAuthenticationKeyFilter.java:100)
 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
 	at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:52)
 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
 	at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:142)
 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 	at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:101)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 	at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:47)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 	at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:46)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 	at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:42)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1839)
 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
 	at java.lang.Thread.run(Thread.java:748)
  ```

## Steps to Reproduce the Problem

  1. Create a new Point Layer and add some points to it
  2. Open Style Editor
  3. Click on the first layer and select `Selected layer style settings`
  4. Click on the `Style` tab
  5. Select `Create new style`
  6. Select `Base CSS`
  7. Click the plus button or `Add selected template to list of styles` and call it `Towers` and `Save`.
  8. Click on `Towers` in the style list and select `Edit selected style`
  9. Select the `Switch to text editor`button
  10. Enter the above mentioned CSS into the TextArea
  11. See the grey blocks popping up

## Specifications

  - GeoNode version: 3.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):GeoNode Project
  - Platform: Ubuntu
  - Additional details:

**Comment by AlexGacon** [comment]
In the geoserver CSS cookbook, there is no quotes around the image : could it be a solution? Did you try with another image format?

**Comment by WernerRaath** [comment]
Trying the same thing with the following PNG as the icon still causes the problem: https://cdn.iconscout.com/icon/free/png-512/network-tower-2031082-1714461.png

**Comment by t-book** [comment]
might be something with your symbol (see: https://stable.demo.geonode.org/layers/geonode:test_dbqg0/style_edit#/):
Try:
```
@mode 'Flat';
@styleTitle 'Base CSS';

* {
  mark: url('http://geomap.arpa.veneto.it/static/img/ico/antenna-with-signal-transmission.png');
  mark-opacity: 1;
  mark-size: 80;
  mark-rotation: 0;
}
```

**Comment by WernerRaath** [comment]
Ah okay so I got that to work. I wonder what causes the failure for my former PNG link. I also guess this is more of a GeoServer issue than GeoNode

**Comment by AlexGacon** [comment]
If you look at https://docs.geoserver.org/stable/en/user/styling/workshop/css/css.html#css-style, the parameter of url has not quotes.
