### ISSUE TITLE
Error in handling favorite

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#7882]
## Expected Behavior
`api/v2/layers` should work when `FAVORITE_ENABLED=False`

## Actual Behavior
If `FAVORITE_ENABLED=False` authenticated calls to `api/v2/layers` fail with HTTP code 500.

## Steps to Reproduce the Problem

  1. Set `FAVORITE_ENABLED=False`
  2. Make a call to `api/v2/layers` also with filters etc
  3. You'll get a 500 error

## Specifications

  - GeoNode version: at least 3.2.x

This in `settings.py` at https://github.com/GeoNode/geonode/blob/3.2.1/geonode/settings.py#L1354-L1359:

```py
# Settings for FAVORITE plugin
FAVORITE_ENABLED = ast.literal_eval(os.getenv('FAVORITE_ENABLED', 'True'))

if FAVORITE_ENABLED:
    if 'geonode.favorite' not in INSTALLED_APPS:
        INSTALLED_APPS += ('geonode.favorite',)
```

This is the serializer code at  https://github.com/GeoNode/geonode/blob/3.2.1/geonode/base/api/serializers.py#L342:
```py
            if not request.user.is_anonymous:
                favorite = Favorite.objects.filter(user=request.user, object_id=instance.pk).count()
```

Since the `geonode.favorite` app has not been added, the ORM does not know how to create the table name, so it raises an error of the kind `relation "geonode_favorite" does not exist`.

This is the stack trace:
```
/usr/local/lib/python3.8/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'geonode.layers.models.Layer'> MultilingualPolymorphicQuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
Internal Server Error: /api/v2/layers
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "geonode_favorite" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "geonode_favorite" WHERE (...
                                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/usr/local/lib/python3.8/site-packages/dynamic_rest/bases.py", line 21, in wrapper
    self._resettable_cached_properties[func.__name__] = func(self)
  File "/usr/local/lib/python3.8/site-packages/dynamic_rest/serializers.py", line 90, in data
    data = super(DynamicListSerializer, self).data
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 760, in data
    ret = super().data
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.8/site-packages/dynamic_rest/serializers.py", line 69, in to_representation
    return [self.child.to_representation(item) for item in iterable]
  File "/usr/local/lib/python3.8/site-packages/dynamic_rest/serializers.py", line 69, in <listcomp>
    return [self.child.to_representation(item) for item in iterable]
  File "/usr/local/lib/python3.8/site-packages/geonode/base/api/serializers.py", line 342, in to_representation
    favorite = Favorite.objects.filter(user=request.user, object_id=instance.pk).count()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 392, in count
    return self.query.get_count(using=self.db)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 504, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 489, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "geonode_favorite" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "geonode_favorite" WHERE (...
               
```

The condition at https://github.com/GeoNode/geonode/blob/3.2.1/geonode/base/api/serializers.py#L342 should also check if the `FAVORITE_ENABLED` setting is `True`.

**Comment by giohappy** [comment]
@etj let's forward this to 3.3.x and master
