### ISSUE TITLE
Bad Gateway on Advanced installation Ubuntu 20.04

### ISSUE THREAD

**Issue by Calvitox** [GeoNode/geonode#8021]
I am going through the installation process, and when i reach the step 6.3 Update OAuth2 configuration in order to hit the new hostname.

> sudo PYTHONWARNINGS=ignore VIRTUAL_ENV=$VIRTUAL_ENV DJANGO_SETTINGS_MODULE=geonode.settings GEONODE_ETC=/opt/geonode/geonode GEOSERVER_DATA_DIR=/opt/data/geoserver_data TOMCAT_SERVICE="service tomcat" APACHE_SERVICE="service nginx" geonode_updateip -l localhost -p csdc.immap.org

I got this errors related to database:

```
Traceback (most recent call last):
  File "/home/geonode/.virtualenvs/geonode/bin/django-admin", line 8, in <module>
    sys.exit(execute_from_command_line())
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/geonode/geonode/base/management/commands/fixsitename.py", line 39, in handle
    site = Site.objects.get_current()
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/contrib/sites/models.py", line 58, in get_current
    return self._get_site_by_id(site_id)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/contrib/sites/models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_site
```

I could see it is refered to sqlite3, so i try the next steps to keep updating the ip, nginx, uwsgi an tomcat process are running and geoserver URL works perfect, but accesing geonode URL, i alway got 502 Bad Gateway error.

uwsgi geonode.log:

```
Mon Aug 30 19:47:37 2021 - *** Operational MODE: preforking ***
Mon Aug 30 19:47:37 2021 - *** no app loaded. going in full dynamic mode ***
Mon Aug 30 19:47:37 2021 - *** uWSGI is running in multiple interpreter mode ***
Mon Aug 30 19:47:37 2021 - !!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!
Mon Aug 30 19:47:37 2021 - no request plugin is loaded, you will not be able to manage requests.
Mon Aug 30 19:47:37 2021 - you may need to install the package for your language of choice, or simply load it with --plugin.
Mon Aug 30 19:47:37 2021 - !!!!!!!!!!! END OF WARNING !!!!!!!!!!
Mon Aug 30 19:47:37 2021 - spawned uWSGI master process (pid: 23009)
Mon Aug 30 19:47:37 2021 - spawned uWSGI worker 1 (pid: 23014, cores: 1)
Mon Aug 30 19:47:37 2021 - spawned uWSGI worker 2 (pid: 23015, cores: 1)
Mon Aug 30 19:51:04 2021 - SIGINT/SIGQUIT received...killing workers...
Mon Aug 30 19:51:05 2021 - worker 1 buried after 1 seconds
Mon Aug 30 19:51:05 2021 - worker 2 buried after 1 seconds
Mon Aug 30 19:51:05 2021 - goodbye to uWSGI.
Mon Aug 30 19:51:05 2021 - *** Starting uWSGI 2.0.18-debian (64bit) on [Mon Aug 30 19:51:05 2021] ***
Mon Aug 30 19:51:05 2021 - compiled with version: 10.0.1 20200405 (experimental) [master revision 0be9efad938:fcb98e4978a:705510a708d3642c9c962beb663c476167e4e8a4] on 11 April 2020 11:15:55
Mon Aug 30 19:51:05 2021 - os: Linux-5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021
Mon Aug 30 19:51:05 2021 - nodename: immap-geonode
Mon Aug 30 19:51:05 2021 - machine: x86_64
Mon Aug 30 19:51:05 2021 - clock source: unix
Mon Aug 30 19:51:05 2021 - pcre jit disabled
Mon Aug 30 19:51:05 2021 - detected number of CPU cores: 4
Mon Aug 30 19:51:05 2021 - current working directory: /
Mon Aug 30 19:51:05 2021 - writing pidfile to /run/uwsgi/app/geonode/pid
Mon Aug 30 19:51:05 2021 - detected binary path: /usr/bin/uwsgi-core
Mon Aug 30 19:51:05 2021 - your processes number limit is 31710
Mon Aug 30 19:51:05 2021 - your memory page size is 4096 bytes
Mon Aug 30 19:51:05 2021 - detected max file descriptor number: 1024
Mon Aug 30 19:51:05 2021 - lock engine: pthread robust mutexes
Mon Aug 30 19:51:05 2021 - thunder lock: disabled (you can enable it with --thunder-lock)
Mon Aug 30 19:51:05 2021 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/geonode/socket fd 3
Mon Aug 30 19:51:05 2021 - setgid() to 33
Mon Aug 30 19:51:05 2021 - setuid() to 33
Mon Aug 30 19:51:05 2021 - your server socket listen backlog is limited to 100 connections
Mon Aug 30 19:51:05 2021 - your mercy for graceful operations on workers is 60 seconds
Mon Aug 30 19:51:05 2021 - mapped 218760 bytes (213 KB) for 2 cores
Mon Aug 30 19:51:05 2021 - *** Operational MODE: preforking ***
Mon Aug 30 19:51:05 2021 - *** no app loaded. going in full dynamic mode ***
Mon Aug 30 19:51:05 2021 - *** uWSGI is running in multiple interpreter mode ***
Mon Aug 30 19:51:05 2021 - !!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!
Mon Aug 30 19:51:05 2021 - no request plugin is loaded, you will not be able to manage requests.
Mon Aug 30 19:51:05 2021 - you may need to install the package for your language of choice, or simply load it with --plugin.
Mon Aug 30 19:51:05 2021 - !!!!!!!!!!! END OF WARNING !!!!!!!!!!
Mon Aug 30 19:51:05 2021 - spawned uWSGI master process (pid: 23449)
Mon Aug 30 19:51:05 2021 - spawned uWSGI worker 1 (pid: 23452, cores: 1)
Mon Aug 30 19:51:05 2021 - spawned uWSGI worker 2 (pid: 23453, cores: 1)
```

nginx error.log

```
2021/08/30 19:30:10 [error] 22148#22148: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 19:30:10 [error] 22148#22148: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org>
2021/08/30 19:30:57 [error] 22148#22148: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 19:30:57 [error] 22148#22148: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org>
2021/08/30 19:32:51 [error] 22149#22149: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 19:32:51 [error] 22149#22149: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org>
2021/08/30 19:37:48 [error] 22625#22625: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 19:37:49 [error] 22625#22625: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org>
2021/08/30 19:37:50 [error] 22625#22625: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 19:37:51 [error] 22625#22625: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org>
2021/08/30 19:37:57 [error] 22625#22625: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 19:37:57 [error] 22625#22625: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org>
2021/08/30 19:45:32 [error] 22625#22625: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 136.144.41.187, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "159.65.231.205:80"
2021/08/30 19:47:50 [error] 23038#23038: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 19:47:50 [error] 23038#23038: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org>
2021/08/30 19:48:07 [error] 23038#23038: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 19:48:07 [error] 23038#23038: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org>
2021/08/30 19:48:08 [error] 23038#23038: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 19:48:09 [error] 23038#23038: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org>
2021/08/30 19:50:39 [error] 23154#23154: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 66.249.73.92, server: csdc.immap.org, request: "GET /robots.txt HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 19:51:09 [error] 23259#23259: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 19:51:09 [error] 23259#23259: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org>
2021/08/30 19:51:10 [error] 23259#23259: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 19:51:10 [error] 23259#23259: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org>
2021/08/30 19:56:40 [error] 23549#23549: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 19:56:40 [error] 23549#23549: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org>
2021/08/30 19:56:42 [error] 23549#23549: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 19:56:42 [error] 23549#23549: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org>
2021/08/30 19:56:42 [error] 23549#23549: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 19:56:43 [error] 23549#23549: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org>
2021/08/30 19:56:44 [error] 23549#23549: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 19:56:44 [error] 23549#23549: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org>
2021/08/30 20:07:40 [error] 23549#23549: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 183.136.225.14, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "159.65.231.205:80"
2021/08/30 20:08:34 [error] 23549#23549: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 183.136.225.14, server: csdc.immap.org, request: "GET /robots.txt HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "159.65.231.205>
2021/08/30 20:08:35 [error] 23549#23549: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 183.136.225.14, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "159.65.231.205:80"
2021/08/30 20:08:36 [error] 23549#23549: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 183.136.225.14, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "159.65.231.20>
2021/08/30 20:09:30 [error] 23549#23549: *20 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 20:09:30 [error] 23549#23549: *20 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.or>
2021/08/30 20:09:32 [error] 23549#23549: *20 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.org"
2021/08/30 20:09:32 [error] 23549#23549: *20 connect() failed (111: Connection refused) while connecting to upstream, client: 186.30.121.183, server: csdc.immap.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "csdc.immap.or>
2021/08/30 20:10:03 [alert] 23549#23549: *19 open socket #13 left in connection 3
```

nginx.conf:

```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
  worker_connections 768;
  # multi_accept on;
}

http {
  ##
  # Basic Settings
  ##

  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  types_hash_max_size 2048;
  # server_tokens off;

  # server_names_hash_bucket_size 64;
  # server_name_in_redirect off;

  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  ##
  # SSL Settings
  ##

  ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
  ssl_prefer_server_ciphers on;

  ##
  # Logging Settings
  ##

  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;

  ##
  # Gzip Settings
  ##

  gzip on;
  gzip_vary on;
  gzip_proxied any;
  gzip_http_version 1.1;
  gzip_disable "MSIE [1-6]\.";
  gzip_buffers 16 8k;
  gzip_min_length 1100;
```

geonode.ini:

```
env = MONITORING_SERVICE_NAME=local-geonode
env = MONITORING_HOST_NAME=geonode

# Other Options/Contribs
env = MODIFY_TOPICCATEGORY=True
env = AVATAR_GRAVATAR_SSL=True
env = EXIF_ENABLED=True
env = CREATE_LAYER=True
env = FAVORITE_ENABLED=True

logto = /opt/data/logs/geonode.log
pidfile = /tmp/geonode.pid

chdir = /opt/geonode
module = geonode.wsgi:application

strict = false
master = true
enable-threads = true
vacuum = true                        ; Delete sockets during shutdown
single-interpreter = true
die-on-term = true                   ; Shutdown when receiving SIGTERM (default is respawn)
need-app = true

# logging
# path to where uwsgi logs will be saved
# logto = /opt/data/geonode_logs/geonode.log

daemonize = /opt/data/logs/geonode.log
touch-reload = /opt/geonode/geonode/wsgi.py
buffer-size = 32768

harakiri = 60                        ; forcefully kill workers after 60 seconds
py-callos-afterfork = true           ; allow workers to trap signals

max-requests = 1000                  ; Restart workers after this many requests
max-worker-lifetime = 3600           ; Restart workers after this many seconds
reload-on-rss = 2048                 ; Restart workers after this much resident memory
worker-reload-mercy = 60             ; How long to wait before forcefully killing workers

cheaper-algo = busyness
processes = 128                      ; Maximum number of workers allowed
cheaper = 8                          ; Minimum number of workers allowed
cheaper-initial = 16                 ; Workers created at startup
cheaper-overload = 1                 ; Length of a cycle in seconds
cheaper-step = 16                    ; How many workers to spawn at a time

cheaper-busyness-multiplier = 30     ; How many cycles to wait before killing workers
cheaper-busyness-min = 20            ; Below this threshold, kill workers (if stable for multiplier cycles)
cheaper-busyness-max = 70            ; Above this threshold, spawn new workers
cheaper-busyness-backlog-alert = 16  ; Spawn emergency workers if more than this many requests are waiting in the queue
cheaper-busyness-backlog-step = 2    ; How many emergency workers to create if there are too many requests in the queue

```
I check other issues: #6059, #6152, and i can't find a solution, i also try to install Geonode with docker, and with the basic installation and i was not able to succeeded, With the advanced installation i just need to solve this Bad Gateway issue, any hints, and help on this will be very appreciated.

**Comment by Calvitox** [comment]
Update, i was able to update geonode ip without errors, but i am still getting connection refused when accesing geonode, geoserver still running smooth. Please, i aam kind of desperate here. I installed geonode in the past, on version 2.8 without problems, and now this is the only thing that i can solve. Thanks

**Comment by afabiani** [comment]
The `UWSGI` service native daemon is not working properly on Ubuntu 20, nevertheless even though it says that the worker cannot start, it starts...

I would suggest to take a look at this virtual machine [here](https://www.dropbox.com/s/7sqdz0fe1i3hdem/GeoNode%203.2.1%20-%20GN2.ova?dl=1) which is based on GeoNode 3.2.1 and Ubuntu 20.0.
It has been configured through the advanced installation process.

More information about the VM can be found here:
https://github.com/geosolutions-it/geonode-training/blob/3.2.1/GN1/VM_STRUCTURE.md

Take a look how this is configured and compare it with your setup. Let me know if you find something useful.

**Comment by Calvitox** [comment]
Thank you very much @afabiani for this, i will check the VM and re-check the `UWSGI` service. I hope i will be back with good news.

**Comment by velekino** [comment]
Hello! i have this same issue by compiling the docker version of geonode (by following the docs) in ubuntu server 18.04 AND also in ubuntu server 20, everything compiles ok with no errors, i see the containers up and running, and I can access /geoserver correctly but the root site says Bad Gateway 502.

**Comment by Calvitox** [comment]
> The `UWSGI` service native daemon is not working properly on Ubuntu 20, nevertheless even though it says that the worker cannot start, it starts...
> 
> I would suggest to take a look at this virtual machine [here](https://www.dropbox.com/s/7sqdz0fe1i3hdem/GeoNode%203.2.1%20-%20GN2.ova?dl=1) which is based on GeoNode 3.2.1 and Ubuntu 20.0.
> It has been configured through the advanced installation process.
> 
> More information about the VM can be found here:
> https://github.com/geosolutions-it/geonode-training/blob/3.2.1/GN1/VM_STRUCTURE.md
> 
> Take a look how this is configured and compare it with your setup. Let me know if you find something useful.

Thank you very much for this @afabiani, i have completed the installation, i add some lines from the geonode.ini file in the VM, and setted some permissions in postgresql13 service, and now is running perfectly.

**Comment by afabiani** [comment]
@Calvitox good to know... if you have the chance to collect the changes to have made and write them here, we could envisage to update the documentation accordingly.

**Comment by Calvitox** [comment]
@afabiani I will, i am just adjusting some other things. Testing the installation and trying to upload layers i got this:
![image](https://user-images.githubusercontent.com/7959141/135772526-4061d6dd-a8b0-4129-87f2-033d31b0ec69.png)
I was checking the settings for correct urls under SSL but i can't find a solution for this. It is strange, when i enter the layer section, i got some mixed content warnings in browser console.
Thanks for your help.
