### ISSUE TITLE
DEBUG=False prevent django container to start

### ISSUE THREAD

**Issue by drumbsd** [GeoNode/geonode#8143]
## Expected Behavior
Using DEBUG=False inside .env, django container should start normally

## Actual Behavior

It gives this error:

```
Post-processing 'mapstore/dist/themes/preview.css' failed!

Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
    collected = self.collect()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 134, in collect
    raise processed
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 294, in _post_process
    content = pattern.sub(converter, content)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 193, in converter
    hashed_url = self._url(
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 132, in _url
    hashed_name = hashed_name_func(*args)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 343, in _stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 93, in hashed_name
    raise ValueError("The file '%s' could not be found with %r." % (filename, self))
ValueError: The file 'mapstore/dist/node_modules/react-widgets/lib/img/loader-big.gif' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7f60643ee3d0>.
```

## Steps to Reproduce the Problem

  1. Install GeoNode 3.3.x and run it using docker. In .env DEBUG=True
  2. Once up and running stop the docker-compose
  3. Change in .env DEBUG=False
  4. Start again docker-compose. 

The initial build of the project was done with DEBUG=True in .env. Didn't test what happens if we build the project with DEBUG=False.

## Specifications

  - GeoNode version: 3.3.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode docker
  - Platform: Ubuntu
  - Additional details:

**Comment by giohappy** [comment]
@allyoucanmap please take a look at this.

**Comment by giohappy** [comment]
Issue moved to [GeoNode/geonode-mapstore-client #510](https://github.com/GeoNode/geonode-mapstore-client/issues/510) via [**ZenHub**](https://www.zenhub.com/)
