### ISSUE TITLE
GeoNode tries to retrieve Geofence rules for Geoserver layer even if no rules are assigned to them

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#8154]
## Expected Behavior
When updatelayers is executed Geoserver layers that are new to GeoNode are imported in GeoNode.

## Actual Behavior
An error is thrown since [list_geofence_layer_rules_xml](https://github.com/GeoNode/geonode/blob/d27b221c44953a48b0d727f71f174e0d7deaeec5/geonode/security/utils.py?plain=1#L472) tries to read Geofence rules, which in general do not exist for Geoserver layers.

## Steps to Reproduce the Problem

  1. create a new layer `new_layer` in Geoserver (import data, uplod, whatever)
  2. run `python manage.py updatelayers -f new_layer`
  3. the follwoing error is raised:

```
Traceback (most recent call last):
  File "/home/giohappy/dev/ibf/GET-IT/src/geonode/geonode/security/models.py", line 421, in set_permissions
    self.set_dirty_state()
  File "/home/giohappy/dev/ibf/GET-IT/src/geonode/geonode/security/utils.py", line 163, in __exit__
    self._execute_requests()
  File "/home/giohappy/dev/ibf/GET-IT/src/geonode/geonode/security/utils.py", line 169, in _execute_requests
    self.adapter_requests_map[request["name"]](
  File "/home/giohappy/dev/ibf/GET-IT/src/geonode/geonode/security/utils.py", line 75, in purge_rules
    self.set_has_committed_changes()
  File "/home/giohappy/dev/ibf/GET-IT/src/geonode/geonode/security/utils.py", line 72, in set_has_committed_changes
    self.safe_point_rules = self.list_rules(xml=True)
  File "/home/giohappy/dev/ibf/GET-IT/src/geonode/geonode/security/utils.py", line 87, in list_rules
    rules = list_geofence_layer_rules_xml(workspace, layer_name)
  File "/home/giohappy/dev/ibf/GET-IT/src/geonode/geonode/decorators.py", line 57, in wrapper
    return func(*args, **kwargs)
  File "/home/giohappy/dev/ibf/GET-IT/src/geonode/geonode/security/utils.py", line 489, in list_geofence_layer_rules_xml
    if rule.find("layer").text == layer_name:
AttributeError: 'NoneType' object has no attribute 'text'

(.....)
```

## Specifications

  - GeoNode version: 3.2.x
  - Additional details: this is probably related to the work done in https://github.com/GeoNode/geonode/pull/8134

**Comment by italogsfernandes** [comment]
PR opened: https://github.com/GeoNode/geonode/pull/8155
