### ISSUE TITLE
 Update supportedDatasetTypes

### ISSUE THREAD

**Issue by italogsfernandes** [GeoNode/geonode#8658]
Remove `geojson` from the list of supported formats

## Context
* GeoJSON is not supported buy the importer (inside geonode, package gsimporter) 
* probably in the past, we supported another type of upload to Geoserver

## Error log
```
Error creating import session
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/upload/upload.py", line 358, in save_step
    import_session = gs_uploader.upload_files(
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 114, in upload_files
    session.upload_task(files, use_url, intial_opts)
  File "/usr/local/lib/python3.8/site-packages/gsimporter/api.py", line 436, in upload_task
    resp = self._client().post_multipart(addopts(url), files)
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 306, in post_multipart
    return self._request(
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 198, in _request
    raise RequestFailed(resp.status, content)
gsimporter.api.RequestFailed: (500, b'Found conflicting types ArrayList and String for property lines')
request failed
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/upload/views.py", line 709, in view
    resp = _steps[step](req, upload_session)
  File "/usr/src/geonode/geonode/upload/views.py", line 175, in save_step_view
    import_session, upload = save_step(
  File "/usr/src/geonode/geonode/upload/upload.py", line 406, in save_step
    raise e
  File "/usr/src/geonode/geonode/upload/upload.py", line 358, in save_step
    import_session = gs_uploader.upload_files(
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 114, in upload_files
    session.upload_task(files, use_url, intial_opts)
  File "/usr/local/lib/python3.8/site-packages/gsimporter/api.py", line 436, in upload_task
    resp = self._client().post_multipart(addopts(url), files)
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 306, in post_multipart
    return self._request(
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 198, in _request
    raise RequestFailed(resp.status, content)
gsimporter.api.RequestFailed: (500, b'Found conflicting types ArrayList and String for property lines')
Upload error response: (500, b'Found conflicting types ArrayList and String for property lines')
```

**Comment by pvgenuchten** [comment]
@italogsfernandes can you share your geojson file, i just uploaded one on the demo server and it works fine for me

**Comment by giohappy** [comment]
It looks like the issue is that Geoserver importer fails to parse string arrays correctly, as in the case of the `stations` example file.
The error says "Found conflicting types ArrayList and String for property lines".

GeoJSON support will be kept and an issue will be opened to improve the importer.
