### ISSUE TITLE
Error in updatelayers when no default style selected

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#869]
If a layer has no default style specified in GeoServer, the following error occurs when running updatelayers.

(geonode)behaim:geonode ortelius$ python manage.py updatelayers
Stopping process because --ignore-errors was not set and an error was found.
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/ortelius/.virtualenvs/geonode/lib/python2.7/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/Users/ortelius/.virtualenvs/geonode/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/ortelius/.virtualenvs/geonode/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/Users/ortelius/.virtualenvs/geonode/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(_args, *_options)
  File "/Users/ortelius/projects/geonode-dev/geonode/geonode/layers/management/commands/updatelayers.py", line 57, in handle
    owner=owner, console=console, workspace=workspace)
  File "/Users/ortelius/projects/geonode-dev/geonode/geonode/geoserver/helpers.py", line 269, in gs_slurp
    layer.save()
  File "/Users/ortelius/.virtualenvs/geonode/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/Users/ortelius/.virtualenvs/geonode/lib/python2.7/site-packages/django/db/models/base.py", line 565, in save_base
    created=(not record_exists), raw=raw, using=using)
  File "/Users/ortelius/.virtualenvs/geonode/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/ortelius/projects/geonode-dev/geonode/geonode/layers/models.py", line 550, in geoserver_post_save
    set_styles(instance, gs_catalog)
  File "/Users/ortelius/projects/geonode-dev/geonode/geonode/layers/models.py", line 557, in set_styles
    layer.default_style = save_style(default_style)
  File "/Users/ortelius/projects/geonode-dev/geonode/geonode/layers/models.py", line 568, in save_style
    style, created = Style.objects.get_or_create(name = gs_style.sld_name)
Exception: ('Failed to process test', AttributeError("'NoneType' object has no attribute 'sld_name'",))

**Comment by gannebamm** [comment]
Hi,
I have encountered the listed error with GeoNode Version 2.4b28. The layer is an image mosaic with geoservers raster style as default style. Here is the stacktrace:
https://gist.github.com/gannebamm/1e1cd8442f90769d4c31
