### ISSUE TITLE
GNIP 92: non-spatial structured data as (pre)viewable FAI(R) datasets

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#8714]
# GNIP 92 - non-spatial structured data as (pre)viewable FAI(R) datasets

## Overview

We need to store structured non-spatial datasets besides geodata as GeoNode resources. The non-spatial datasets shall provide a simple viewer as a preview and should be able to get used as part of dashboards. The datasets should be findable, accessible and provided in an interoperable way, therefore complying with the FAI(r) principles.

### Proposed By

Florian Hoedt, Thünen-Institute Centre for Information Management

>We intend to fund this development as part of an upcoming tender process. This GNIP shall start a discussion about how the developed feature could get upstreamed to the main project.

### Assigned to Release

This proposal is for GeoNode 4.0

### State

* [x] Under Discussion
* [ ] In Progress
* [ ] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation

**Status Quo**: Non-spatial but structured datasets like csv/ Excel files can be uploaded as documents. As document objects, these datasets do inherit the resource base metadata models but can not be viewed in a meaningful way. 
As a research institute, our scientists often use PostgreSQL databases and tables to store and structure their research data. Currently, those datasets can not be published in any way in GeoNode. As a research institute, we need to store/register **structured** non-spatial datasets besides geodata as GeoNode _datasets_ (in the meaning of a v4.0 dataset). 

**Objective**: Implement a new category of RessourceBase for structured non-spatial datasets. Instead of using the GeoServer importer to ingest, e.g. shapefiles, into the PostGIS enabled backend, _you should be able to define a connection string to the table to use [?]_. The non-spatial datasets shall provide a simple viewer as a preview and should be able to get used as part of dashboards.

## Proposal

**How to realize the above-mentioned feature is still to be discussed.**

As part of an internal discussion, we thought about using PostgREST as an accessible and interoperable tabular data provider. One major aspect is to synchronise authorization mechanisms with the new service. Currently, Django and GeoServer do synchronise their roles via GeoFence. Something similar should be implemented by the tabular service provider. There seem to be options to use JWT as part of the django-rest-framework to grant such authorization as explained here: https://gitter.im/begriffs/postgrest?at=61f06b40742c3d4b21b63843

Apart from using PostgREST as a tabular data provider we also considered the new OGC APIs. These may provide enough functionality for this GNIP. For example the EDR (https://ogcapi.ogc.org/edr/). 

### Backwards Compatibility

It is not intended to backport this GNIP to 3.x

## Future evolution

Explain which could be future evolutions.

## Feedback

See discussion below...

## Voting

Project Steering Committee:

* Alessio Fabiani:
* Francesco Bartoli:
* Giovanni Allegri:
* Simone Dalmasso:
* Toni Schoenbuchner:
* Florian Hoedt:

## Links

Remove unused links below.

* [Email Discussion]()
* [Pull Request]()
* [Mail Discussion]()
* [Linked Issue]()

**Comment by afabiani** [comment]
@gannebamm my +1 here, the proposal is actually very good. Of course we need to carefully choose how to convert the structured data into a "standard" format that GeoNode can use later on.
It would be nice if you could prepare/provide few samples of possible datasets or provide an idea of the complexity of the structures. You are speaking about Excel documents, but those ones might be very complex. We might need to envisage some hooks/harvesters able to parse and store specific formats.
We had a similar use case for the Afghanistan Risk Data portal. In that case we had to create some brand new data structures and parsers able to ingest very specific Excel files for each hazard type.

**Comment by afabiani** [comment]
Added the GNIP to the [wiki page](https://github.com/GeoNode/geonode/wiki/GeoNode-Improvement-Proposals)

**Comment by gannebamm** [comment]
Thanks @afabiani for adding it to the wiki page!

> It would be nice if you could prepare/provide few samples of possible datasets or provide an idea of the complexity of the structures. You are speaking about Excel documents, but those ones might be very complex. 

here you go: [soil example dataset](https://doi.org/10.3220/DATA20200203151139)

You can switch the metadata language to English and use the _BZE_LW English Version_. The site.xlsx is the spatial dataset we currently upload as a point layer. The other two xlsx files (LABORATORY_DATA, HORIZON_DATA) are examples of non-spatial datasets. I know, in the end, everything is spatial somehow since the lab and horizon datasets do explicitly or implicitly reference a sample site. Nonetheless, we would like to publish those as non-spatial datasets and enable custom applications to fetch those in an accessible and interoperable way through an API. An example of this kind of custom application can be seen at [soilgrids](https://soilgrids.org/). If you click a coordinate you will derive loads of additional data like this:
![grafik](https://user-images.githubusercontent.com/6172324/152202910-696ac059-e54a-4e38-95d5-3d289935d413.png)

However, most of our data is already stored in PostgreSQL databases. I know other research institutes also have working databases that could maybe just get integrated. If we use some ORM like sqlalchemy we could even open this up for a more diverse set of SQL-like data providers, as explained [here](https://docs.sqlalchemy.org/en/14/dialects/). But maybe that one is out of scope and we should stay true and close to our current stack, which does use PostgreSQL.

I will ask my colleagues to provide some more examples.

**Comment by matthesrieke** [comment]
As I had an offline discussion with @gannebamm on the topic, I am sneaking in on the discussion.

> However, most of our data is already stored in PostgreSQL databases. I know other research institutes also have working databases that could maybe just get integrated. 

I think @gannebamm is having a slightly different workflow in mind (correct me if I am wrong). The data would not be imported into a central data store, but managed as reference to an existing database. I guess this is the most flexible and scalable approach as otherwise you would need to make sure to preserve the structure in the `geonode_data`, without conflicts across datasets.

On the other hand, this would bring in the requirement of some sort of default structure anyways, if you do not want to implement special visualizers for each dataset. Maybe it could also be a mappable structure, filled out by the user during import.

Maybe also both scenarios (1. existing DB; 2. import into `geonode_data`) could be covered. The same questions would still require answers.

**Comment by gannebamm** [comment]
Maybe the https://github.com/rvinzent/django-dynamic-models technology evaluated and used (?) for the SOS integration (contrib module) can help for this feature request. See: https://github.com/GeoNode/geonode-contribs/issues/172

**Comment by matthesrieke** [comment]
Dear @giohappy, together with @gannebamm @mwallschlaeger we have started to iterate the requirements and the concept behind a non-spatial dataset feature for GeoNode. We have started a small prototype by setting up a Django App / Contrib module. At the moment, uploading data is achieved by providing a CSV file with a sidecar JSON [Tabular Data Resource](https://specs.frictionlessdata.io/tabular-data-resource/) that describes the schema and types of fields.

@gannebamm pointed us to the new [geonode-importer](https://github.com/geosolutions-it/geonode-importer) module and we were wondering if this would be a good fit for ingesting the data. It looks to be designed in a way that it would allow the addition of custom/new handlers. Do you think it would fit our purpose?

**Comment by giohappy** [comment]
Dear @matthesrieke sorry for the late reply.

First of all, a GNIP for the new importer is on its way, we want to make it a community module asap. At the moment it's hosted under GeoSolution's own repo.

As you note, the new importer lets you implement specific handlers, and it can assume complete control of the lifecycle of a resource. For example, the handler is in charge of doing any housekeeping when a resource backed by specific data and tables is deleted.
@mattiagiupponi can tell you much more about it since he's the module's author.

So, the primary use case here is to map a GeoNode resource to an external DB. If we generalize this I'd say that this case isn't strictly related to non-spatial datasets. In our vision, a non-spatial dataset could still be served by Geoserver, that way we can benefit from all the services and WFS-based client tools that we already have. They can work for non-spatial data too.
So, follow me, we have two "dimensions" here:

 - implement support for non-spatial datasets on top of the existing tools (here we don't care where the data is located)
 - implement support for alternative DBs to `geonode_data` (this can work both for spatial and non-spatial datasets)

IMHO we should agree on the first point first, which is the subject of this GNIP.
I'm a bit concerned with creating new data models and services. We can improve the current ones (always with back compatibility in mind!), but I'd try our best to avoid adding complexity.

**Comment by giohappy** [comment]
@gannebamm 

>We care where the data is located and would like to ingest it into the PostgreSQL backend for later use.

I'm not saying that this isn't relevant, My point is to distinguish the two requirements:

1. **Using an external DB**, which isn't strictly related to spatial/non-spatial tables. Notice that you can already publish resources from an external DB (we do it frequently) although there isn't a tool for end-users to configure it. At the moment you have to configure a new Geoserver store and then publish the layer on GeoNode, e.g. with the `updatelayers` command. However, it should be quite trivial to do it with the new importer
2. **Publishing of non-spatial tables**.  From my experience, QGIS plays nicely with non-spatial WFS featuretypes. I did a quick test to confirm this. The images you see below are the JSON output from WFS and the same table loaded in QGIS. I'm pushing forward this solution because it comes for free (almost).

We're happy to discuss this in a call. 

**WFS non-spatial table JSON output**
![image](https://user-images.githubusercontent.com/571129/207287202-b7757fa8-ccea-4bd3-b634-12484521fd6b.png)

**WFS non-aptial table loaded in QGIS**
![image](https://user-images.githubusercontent.com/571129/207287264-0785cf48-d14b-40ec-8942-7eb92d26fae6.png)

**Comment by gannebamm** [comment]
@giohappy @afabiani @matthesrieke @t-book @mattiagiupponi (and everyone else interested!)
I would like to schedule a web session to talk about the further development of this GNIP with you. I can provide a WebEx room. 

There are some open slots next week for me. Please fill out this poll: https://terminplaner4.dfn.de/FOKIDXEtIVBq8sQB

**Comment by t-book** [comment]
@gannebamm It looks today is winner? Does the meating happen?

**Comment by gannebamm** [comment]
I asked the 52N crew if one person is enough on their side. They should answer soon. I will provide the video conference room info by mail.

**Comment by mattiagiupponi** [comment]
Hi @gannebamm 
I'm sorry that yesterday I was not able to join the meeting but @giohappy give me an update.
I just created this small doc with the default handler structure which the importer expects to be available:
https://github.com/geosolutions-it/geonode-importer/tree/master/importer/handlers
Fell free to open new issues on the importer if something is not clear

**Comment by matthesrieke** [comment]
Hi @mattiagiupponi thanks for adding the documentation, we will take a closer look. Would you be available for a short meeting to discuss possible technical approaches? Maybe this Thursday between 10-12am? You could also reply to me by mail (`m.rieke@52north.org`), so we take this offline from this thread.

**Comment by mattiagiupponi** [comment]
> Hi @mattiagiupponi thanks for adding the documentation, we will take a closer look. Would you be available for a short meeting to discuss possible technical approaches? Maybe this Thursday between 10-12am? You could also reply to me by mail (`m.rieke@52north.org`), so we take this offline from this thread.

Hi @matthesrieke 
For me is fine from 10 am for about 1 hour.
I'll keep (for now) this here so we can see if someone else is interested in joining the meeting. 
If it for you is fine, I'll send u an invitation for the meeting via email

**Comment by matthesrieke** [comment]
thanks @mattiagiupponi ! Yes, 10am tomorrow is fine for me. I will be joined by @autermann and @ridoo

**Comment by gannebamm** [comment]
@mattiagiupponi I would like to attend, too.

**Comment by giohappy** [comment]
@matthesrieke @gannebamm we're planning to complete the transition to the [new importer](https://github.com/GeoNode/geonode/issues/10474) very soon, and make it the default importer in 4.1.x.

As you know the new importer misses the CSV handler. We were waiting to implement a solution that should replace the upload steps that we have now, where the lat/lon column can be selected at upload time. 
We cannot afford to implement a new UI for the custom selection of columns, so our proposal would be the following:

 - preconfigure the CSV handler with OGR `X_POSSIBLE_NAMES="x,lon*"` and `Y_POSSIBLE_NAMES="y,lat*"` [options](https://gdal.org/drivers/vector/csv.html#open-options)
 - accept a companion "*.csvt" file, as supported by the OGR CSV driver

This solution would provide an alternative that's not too expensive and complex to implement, and gives the opportunity to remove the current upload system (at the moment it's still required only for CSV files).

I'm not against the solution based on [Tabular Data Resource](https://specs.frictionlessdata.io/tabular-data-resource/) and VSI.
I think all these options could coexist, letting the handler pick up the best depending on the provided files, with `X_POSSIBLE_NAMES` and `Y_POSSIBLE_NAMES` preconfigurations as a fallback.

What's your opinion?

**Comment by gannebamm** [comment]
@matthesrieke please take a look at @giohappy comment. I do not see that as an issue. We will have two importer handlers, one for geospatial csv and one dedicated for non-spatial csv with TDR / VSI. What do you think?

**Comment by ridoo** [comment]
@gannebamm @giohappy We also see no problem. Both solution can co-exist and serve different use cases (one for simple csv uploads and one for whole datapackages). I like the "csvt solution" as well -- quite pragmatic. How would you communicate to the user about the configured name pattern for columns containing geometry information?

**Comment by giohappy** [comment]
@ridoo @gannebamm unfortunately our experiments with the CSV driver options and the `csvt` file didn't give the expected results. Apparently, the OGR Python API does not take them into account, and this is problematic since we leverage the API to extract schema information and prepare the dynamic models.

For the moment we have implemented the basic solution, where only a fixed set of column names are recognized. There's a PR ready for an internal review, but if you want to take a look and suggest improvements you're welcome! https://github.com/geosolutions-it/geonode-importer/pull/157

**Comment by ridoo** [comment]
@giohappy @mattiagiupponi That is a pity to read. I only played around with it on the CLI, so I cannot tell much more on this.

On our `datapackage.json` approach, we are now able to import csv data as described in the tabular data descriptor. However, there are still issues to solve:

* Pass a "fake" SLD file (see first comment below)
* Add a `tabular` subtype (see second comment below)
* Create a simple UI preview (instead of showing an empty map on the detail page)

**Comment 1:** I see that the style of a layer is mandatory during upload. To my understanding right now, I can decide to get errors either from the `rest_framework` (requiring SLD) and/or `geonode.geoserver.helpers.py#get_sld_for()` which tries to get a default style for layer's name. For now, I am trying to pass a minimal style file which becomes available under "Styles" in Geoserver, but does not appear in the GWC. I can see GeoServer throwing an exception:

```
02 Mar 15:52:59 DEBUG [geoserver.monitor] - Testing /gwc/rest/layers/geonode:laboratory_data.xml for monitor filtering
geoserver4thuenen_atlas  | 02 Mar 15:52:59 DEBUG [geoserver.monitor] - /geoserver/gwc/rest/layers/geonode:laboratory_data.xml was filtered from monitoring
geoserver4thuenen_atlas  | 02 Mar 15:52:59 ERROR [geoserver.rest] - Unknown layer: geonode:laboratory_data
geoserver4thuenen_atlas  | org.geowebcache.rest.exception.RestException 404 NOT_FOUND: Unknown layer: geonode:laboratory_data
geoserver4thuenen_atlas  |      at org.geowebcache.rest.controller.GWCController.findTileLayer(GWCController.java:45)
geoserver4thuenen_atlas  |      at org.geowebcache.rest.controller.TileLayerController.layerGet(TileLayerController.java:70)
```

Do you think this is the right way to pass a fake SLD file along the upload of non-spatial/tabular data?

**Comment 2:** During upload the the nonspatial/tabular data become of type VECTOR .. Calling http://localhost/geoserver/rest/layers/laboratory_data.xml gives me

```xml
<layer>
  <name>laboratory_data</name>
  <type>VECTOR</type>
  <resource class="featureType">
    <name>geonode:laboratory_data</name>
    <atom:link xmlns:atom="http://www.w3.org/2005/Atom" rel="alternate" href="http://localhost/geoserver/rest/workspaces/geonode/datastores/geonode_data/featuretypes/laboratory_data.xml" type="application/xml"/>
  </resource>
  <attribution>
    <logoWidth>0</logoWidth>
    <logoHeight>0</logoHeight>
  </attribution>
  <dateCreated>2023-03-02 15:49:59.20 UTC</dateCreated>
</layer>
```


It seems that  `geonode.geoserver.helpers.py#sync_instance_with_geoserver()` is mapping `subtype=dataStore` to `vector` and just overrides the `subtype=tabular` of my instance. What do you think would be the best location to make adjustments to add a `tabular` type?

The PR look ok on a first glimpse (could not spent too much time on it, though).

**Comment by mattiagiupponi** [comment]
Hi @ridoo 
By default, the SLD style is **never** mandatory during the import phase for the `geonode-importer` or the legacy upload system.
Geonode always tries to create a default one because it is `nature`, so you get that error.

A possible approach is to use the [custom_resource_manager](https://github.com/geosolutions-it/geonode-importer/blob/master/importer/utils.py#L24) provided by the importer. 

This manager is meant to override the default one to exclude common communication with GeoServer during create/copy/update phase of the resource, I guess in your case you have also to override the "create" method so GeoNode should not try to create the SLD style by adding something like this:

```python
def create(self, uuid, **kwargs) -> ResourceBase:
    return ResourceBase.objects.get(uuid=uuid)
```

**NOTE**: the layer in GeoServer (as always) should be imported and published by the previous step `importer.publish_resource`. With the other handlers, we let this be done since it will sync the GeoNode resource with the one in GeoServer.

Then override the handler `create_geonode_resource` function to use the custom resource manager instead of the default one, with something like:

```python
def create_geonode_resource(
    self, layer_name: str, alternate: str, execution_id: str, resource_type: Dataset = Dataset, files=None
):
   .......
    saved_dataset = custom_resource_manager.create(
        None,
        resource_type=resource_type,
        defaults=dict(
            name=alternate,
            workspace=workspace,
            subtype="raster",
            alternate=f"{workspace}:{alternate}",
            dirty_state=True,
            title=layer_name,
            owner=_exec.user,
            files=list(set(list(_exec.input_params.get("files", {}).values()) or list(files))),
        ),
    )

   .......
    return saved_dataset
```

Related to the second comment, I'm sure we talked about that for now, GeoNode is not ready to handle non-spatial resources and it will require some work to enable it.
@giohappy for sure can gives you more hints on it

**Comment by ridoo** [comment]
@mattiagiupponi thanks for the hint, I will by-pass the importer's `resource_manager` and use my own.

Yes, we have talked about the limitation regarding non-spatial/tabualr data in GeoNode. However, I was unsure if you had further thought about possible pitfalls and/or ideas to overcome those :).

**Comment by giohappy** [comment]
Since the GeoNode 4.1 release was postponed but is likely imminent, shall we try to get this new feature into the upcoming 4.1 release?

@gannebamm I'm a bit lost. I don't see a PR connected to this issue, and I'm not sure if a solution has been implemented for the presentation of non-spatial datasets.

**Comment by gannebamm** [comment]
@ridoo Giovanni is correct. Didn´t we create a PR somewhere for this feature?

**Comment by ridoo** [comment]
@gannebamm we did create PR https://github.com/GeoNode/geonode/pull/10842 which was needed to keep all unpacked files from an uploaded zip-file. However, the actual work to support non-spatial (tabular) data is a bit distributed:

* https://github.com/GeoNode/geonode/pull/10842 (The PR on upstream GeoNode mentioned above)
* [Needed adjustments in the geonode-importer](https://github.com/GeoNode/geonode-importer/pull/159) (have been merged already)
* [Custom geonode-importer handler implementation](https://github.com/Thuenen-52North-Erweiterung-GeoNode/geonode-contribs/tree/thuenen_importer-datapackage/importer-datapackage) as a python module app 
* [A tabular preview in the UI](https://github.com/Thuenen-52North-Erweiterung-GeoNode/geonode-mapstore-client/tree/feature/preview-tabular-data). Here, we do not have any PR as it is based contains assumptions not yet discussed in detail yet

**Comment by ridoo** [comment]
Nach Integration mit `4.1.0` wird beim Publizieren folgender Geoserver-/GeoWebCache-Fehler geworfen:

```
celery4thuenen_atlas_41x     | Requesting GeoFence rules on resource "geonode:horizon_data" :: Dataset
geoserver4thuenen_atlas_41x  | 13-Jun-2023 06:22:51.011 SEVERE [http-nio-8080-exec-1] org.geowebcache.rest.controller.RestExceptionHandler.handleRestException Unknown layer: geonode:horizon_data
geoserver4thuenen_atlas_41x  |  org.geowebcache.rest.exception.RestException 404 NOT_FOUND: Unknown layer: geonode:horizon_data
geoserver4thuenen_atlas_41x  |          at org.geowebcache.rest.controller.GWCController.findTileLayer(GWCController.java:45)
geoserver4thuenen_atlas_41x  |          at org.geowebcache.rest.controller.TileLayerController.layerGet(TileLayerController.java:70)
geoserver4thuenen_atlas_41x  |          at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
geoserver4thuenen_atlas_41x  |          at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
geoserver4thuenen_atlas_41x  |          at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
geoserver4thuenen_atlas_41x  |          at java.base/java.lang.reflect.Method.invoke(Method.java:566)

..
[ Cut for brevity]
..

celery4thuenen_atlas_41x     | Pushing 10 changes into GeoFence for resource horizon_data
``` 

Die Datensätze werden zwar dennot angezeigt, aber die Preview (GetFeatureRequest) geht nicht mehr. Ich untersuche das gerade

**Comment by ridoo** [comment]
Tabular Preview works again after re-adding the `tabular_viewer` again in `localConfig` (seemed to be removed during merging `4.1.0`). The GeoWebCache exeception still appears, which is comprehensible as tabular data is not a tile layer. Maybe the exception is just logged due to the updated version of GeoServer.

Further investigation:

Exception was not logged beforehand. It appears, that there was some orphaned code handling a faked thumbnail, which caused an error (but did not interfere with the whole workflow). This triggered the rollout action now, but was not listed in the actions list of the datapackage handler, yet.

For resolve the error, I added the `ROLLOUT` action (which is handled by the vector handler), and removed the orphaned code. Now, everything works as before.

**Comment by cesarbenjamindotnet** [comment]
this feature is still a must, but there is not movement about it, i think i have to touch the topic again.

**Comment by giohappy** [comment]
FYI, we're working on the first implementation of this feature. The plan is to leverage the Geoserver and MapStore capabilities to work with featuretypes without geometries.

The first implementation will be based on the OGR capabilities to parse field types, without the adoption of JSON Schema and/or libraries like [frictionless](https://github.com/frictionlessdata/frictionless-py). Basically, we will reuse the same path as with normal spatial vector uploads, which include CSVs. 
More structured control and validation on input files can be a future enhancement.

Notice that we're also working on Excel uploads, which will be considered optional for the moment, since robust control over Excel content is beyond the goals for this initial implementation.

Internal POCs are already ongoing; We'll start working on the presentation of non-spatial datasets inside the GeoNode preview soon. The MapStore attribute table component will be extended and adapted to be used as a tabular preview, even outside a map context.

Kudos to [Thuenen-GeoNode-Development ](https://github.com/Thuenen-GeoNode-Development), and in particular to @ridoo and @gannebamm  for sharing their work on this topic.

**Comment by ridoo** [comment]
Hey @giohappy , thanks for the update on this topic!

I understand, you have to shape this feature more generously, and that is fair enough 😉. The good thing is, you are able to implement this more natively (incl. GeoServer and MapStore) which would make possible more interesting features (like joining spatial and non-spatial datasets). However, as we made early steps in that direction, we are interested, if you are going to pick some ideas of our implementation or if you will focus on a completely different approach.

We already incorporated our custom changes into some broader contexts. For this reason, we'd had appreciated upstream to follow a similar path we decided to go.

So, it would be nice if you would share some insights of how you are going to actually implement non-spatial datasets in the end!

/cc @mwallschlaeger 
/cc @hvwaldow
/cc @matthesrieke

**Comment by hvwaldow** [comment]
For us and users in science-context in general, some sort of meta-data (describing structure and semantics) for tabular data would be most helpful. Format-wise , [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180) is good enough, I don't think there is a need to chase proprietary formats in our domain.

**Comment by giohappy** [comment]
Part of the GNIP has been covered by issue https://github.com/GeoNode/geonode/issues/13939 and related PR https://github.com/GeoNode/geonode/pull/13900, which introduces support for uploading non-spatial datasets. It's now ready for review.

At this stage, the implementation intentionally does not cover **dataset structure, schema semantics, or attribute-level semantics** as described in the original proposal @hvwaldow. Through several discussions, we agreed that these aspects should not be treated as a special case for non-spatial data only, but rather addressed consistently for **both spatial and non-spatial datasets**. This implies the need for a more comprehensive and unified approach to schema definition, metadata enrichment, semantics, and validation across all dataset types.

For the current iteration, the upload workflow follows the same approach already used for CSV ([and soon Excel](https://github.com/GeoNode/geonode/pull/13937)) datasets. The main difference is that spatial information is explicitly skipped. To support this, some internal assumptions in GeoNode—namely that all datasets are spatial—have been refactored. A new **tabular dataset subtype** has been introduced, allowing GeoNode to correctly manage and distinguish non-spatial tabular data.

On the frontend side, a corresponding PR is under review at https://github.com/GeoNode/geonode-mapstore-client/pull/2357, which replaces the map preview with a tabular preview for non-spatial datasets.

This work should be considered a first incremental step rather than a complete solution. As such, it does not close this GNIP. The issue should remain open (and likely be extended) to explicitly cover structured schema and attribute metadata, dataset semantics (for both spatial and non-spatial data), and validation mechanisms aligned with those semantics. For the moment, there isn't a plan or a timeline for this.
