### ISSUE TITLE
Duplicate keyword error raised on massive upload

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#8913]
## Expected Behavior
Given multiple and parallels calls to GeoNode `v2/uploads` API, the upload should be completed and the keywords correctly access if an `XML` file is provided.
Input payload:
```JSON
{
    "permissions": "{ \"users\": {\"AnonymousUser\": [\"view_resourcebase\"]} , \"groups\":{}}",
    "time": "false",
    "charset": "UTF-8",
    "store_spatial_files": false,
    "non_interactive": "true",
    "base_file_path": "/opt/test/file.shp",
    "dbf_file_path": "/opt/test/file.dbf",
    "shx_file_path": "/opt/test/file.shx",
    "xml_file_path": "/opt/test/file.xml",
    "prj_file_path": "/opt/test/file.prj"
}
```

## Actual Behavior
From the GeoNode log, an exception is raised saying that the keyword is already present.

```log
duplicate key value violates unique constraint "base_hierarchicalkeyword_name_key"
DETAIL:  Key (name)=(unità di misura giorni) already exists.
Traceback (most recent call last):
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "base_hierarchicalkeyword_name_key"
DETAIL:  Key (name)=(unità di misura giorni) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/core/geonode/geonode/upload/views.py", line 618, in final_step_view
    saved_layer = final_step(upload_session, upload_session.user, layer_id)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/core/geonode/geonode/upload/upload.py", line 820, in final_step
    saved_layer = _update_layer_with_xml_info(saved_layer, xml_file, regions, keywords, vals)
  File "/opt/core/geonode/geonode/upload/upload.py", line 949, in _update_layer_with_xml_info
    saved_layer = utils.KeywordHandler(saved_layer, keywords).set_keywords()
  File "/opt/core/geonode/geonode/upload/utils.py", line 684, in set_keywords
    self._set_free_keyword(keywords)
  File "/opt/core/geonode/geonode/upload/utils.py", line 726, in _set_free_keyword
    self.instance.keywords.add(*keywords)
  File "/opt/core/geonode/geonode/base/models.py", line 476, in add
    new_tag_obj = HierarchicalKeyword.add_root(name=new_tag)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/treebeard/mp_tree.py", line 617, in add_root
    return MP_AddRootHandler(cls, **kwargs).process()
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/treebeard/mp_tree.py", line 313, in process
    return last_root.add_sibling('sorted-sibling', **self.kwargs)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/treebeard/mp_tree.py", line 1098, in add_sibling
    return MP_AddSiblingHandler(self, pos, **kwargs).process()
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/treebeard/mp_tree.py", line 440, in process
    newobj.save()
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/taggit/models.py", line 63, in save
    return super().save(*args, **kwargs)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/db/models/base.py", line 743, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/db/models/base.py", line 780, in save_base
    updated = self._save_table(
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/db/models/base.py", line 873, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/db/models/base.py", line 910, in _do_insert
    return manager._insert([self], fields=fields, return_id=update_pk,
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql
    cursor.execute(sql, params)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "base_hierarchicalkeyword_name_key"
DETAIL:  Key (name)=(unità di misura giorni) already exists.
```

## Steps to Reproduce the Problem

  1. Load multiple datasets with XML files that has duplicate keywords
  2. check the logfile

## Specifications

  - GeoNode version: 33x (probably also on master)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): all
  - Platform: all
  - Additional details:

**Comment by giohappy** [comment]
@mattiagiupponi if this affects also master we expect to have the fix on master and a backport afterwards

**Comment by sairamMuddana** [comment]
i installed geonode-3.0.0 windows . please tell me it is possible to replace backend Postgresql to Oracle SQl

**Comment by gannebamm** [comment]
Even though this code is part of my codebase I encounter this error #8997 
I think it is linked to these changes. What do you think @mattiagiupponi ?

**Comment by sairamMuddana** [comment]
can i develop geonode on windows system only

not WLS

**Comment by giohappy** [comment]
@sairamMuddana please don't pollute issues. I invite you to ask general questions either using the ML or the Gitter channel.
