### ISSUE TITLE
Keywords filter only returns the root nodes of the tree

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#9101]
Apparently, the only root keywords, from the hierarchical tree, are returned inside the keywords filter, with the following result:

 - if resources have children keywords assigned only their root keywords are returned inside the filter, even if these root keywords are not explicitly assigned to any resource
 - the number returned inside the keyword filter only counts the resources directly assigned to the keyword, and not its children keywords

Let's make an example

Keywords tree:
 - "a"
   - "aa"  <- dataset_1
     - "aaa"   <- dataset_1
 - "b" <- dataset_2

Filter (current behaviour):
- "a" (0) 
- "b" (1)

You see that "a" is returned, since it's a parent of keywords with associated resources, and its number is 0 because it deosn't have resources directly associated

The expected results is:
Filter:
- "aa" (1)
- "aaa" (1)
- "b" (1)

i.e. the flattened keywords, with only the keywords with a direct association with one or more resources.

**Comment by marthamareal** [comment]
@giohappy can I have some steps on how to create this scenario.

**Comment by gannebamm** [comment]
We had a small discussion about the hierarchical keywords here:
https://github.com/GeoNode/geonode/issues/6727

From my understanding, it would be best to assign all parent keywords to a resource. Eg:

geology - magmatic rocks - basalt

if basalt is used, the geology and magmatic rocks keywords are added, too. If you filter for geology-related resources it does not make sense to not show basalt features IMHO.

**Comment by mattiagiupponi** [comment]
@giohappy I tried to replicate your scenario, but I have a different result (always wrong)

Tested on the local instance in 4.x 

Assuming the following scenario where:
- `external` is assigned to a dataset
- `parent`: is not assigned to any dataset
- `child` is assigned to a dataset
- `child_of_child` is assigned to a dataset

![image](https://user-images.githubusercontent.com/51856725/163419044-4ac536b5-8879-40c9-9971-08c38bb58b99.png)

The filter in UI is empty and from the backend, it raises an issue:

![image](https://user-images.githubusercontent.com/51856725/163419424-4f661adc-1fda-4c50-9bad-28fe6aa2fd2b.png)

```python
Traceback (most recent call last):
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mattia/.virtualenvs/master/lib/python3.8/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/opt/core/geonode/geonode/base/api/views.py", line 230, in get_queryset
    resource_keywords = HierarchicalKeyword.resource_keywords_tree(self.request.user)
  File "/opt/core/geonode/geonode/base/models.py", line 398, in resource_keywords_tree
    tree = cls._keywords_tree_of_a_child(hkw, tree, newobj)
  File "/opt/core/geonode/geonode/base/models.py", line 427, in _keywords_tree_of_a_child
    item_found = find_by_attr(node["nodes"], newobj["id"])
KeyError: 'nodes'
"GET /api/v2/keywords?page_size=20&page=1 HTTP/1.1" 500 216989
```

Technically this issue should have fix by this https://github.com/GeoNode/geonode/issues/7750 but something is going wrong. I'm on it
