### ISSUE TITLE
Upload Vector dataset with styles gives Error on replacing styles.

### ISSUE THREAD

**Issue by lsntdev** [GeoNode/geonode#9459]
## Expected Behavior
1. upload layer
2. look for sld file in the dataset, if yes then replace and delete the default one
## Actual Behavior
1. upload layer
2. copy styles and complain about attribute default_style because it is None.

## Steps to Reproduce the Problem

  1. Upload vector
  2. Check log

## Specifications

  - GeoNode version: 3.3.x
  - Geoserver version: 2.19.6
  - Installation method : Manual with paver_dev
  - Platform: Vagrant Debian Buster
  - Additional details: here are the log complain by helper.py
```
-- Finalizing Upload for geonode:pratiche... RUNNING
Creating points of contact records for pratiche
Creating style for [pratiche]
copying [/home/vagrant/venvs/dev/src/geonode/geonode/uploaded/tmprdgpigfl/pratiche.sld] to [/home/vagrant/venvs/dev/src/geonode/geonode/uploaded/pratiche.sld]
[sld_uploaded: True] sld_file: /home/vagrant/venvs/dev/src/geonode/geonode/uploaded/pratiche.sld
'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/home/vagrant/venvs/dev/src/geonode/geonode/geoserver/tasks.py", line 109, in geoserver_set_style
    set_layer_style(
  File "/home/vagrant/venvs/dev/src/geonode/geonode/geoserver/helpers.py", line 433, in set_layer_style
    name=layer.default_style.name))
AttributeError: 'NoneType' object has no attribute 'name'
'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/home/vagrant/venvs/dev/src/geonode/geonode/geoserver/helpers.py", line 2173, in sync_instance_with_geoserver
    set_styles(instance, gs_catalog)
  File "/home/vagrant/venvs/dev/src/geonode/geonode/geoserver/helpers.py", line 1147, in set_styles
    name=gs_layer.default_style.name,
AttributeError: 'NoneType' object has no attribute 'name'
 -- Upload completed for geonode:pratiche...
```

I suspected that the error came from the geoserver rest config so I have already check it with the latest [geoserver-restconfig](https://github.com/GeoNode/geoserver-restconfig) standalone script but the layer it has doesnt have default_style attribute but it has default style on geoserver.

```python
from geoserver.catalog import Catalog  
cat=Catalog("http://localhost:8080/geoserver/rest", username="admin", password="geoserver")

gs_layer = cat.get_layer("pratiche")

print(gs_layer.default_style)
```
output : None

**Comment by lsntdev** [comment]
I would like to confirm that downgrading to `geoserver-restconfig==2.0.4.10` [2.0.4.10](https://github.com/GeoNode/geoserver-restconfig/releases/tag/2.0.4.10) is working well. From my side It cant be changed in the requirements tho, it always get the 2.0.6.

**Comment by lsntdev** [comment]
I will close this, as it might not an issue on geonode but geoserver-retconfig.
