### ISSUE TITLE
Unable to print dataset with option "include Legend" selected

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#9818]
## Expected Behavior
Users should be able to print a dataset with all options provided

## Actual Behavior
500 error is thrown if you print with `include legend` enabled.
    `
    Error while generating PDF:
    java.lang.IllegalStateException: unsupported protocol: 'jar'
	    at org.apache.commons.httpclient.protocol.Protocol.lazyRegisterProtocol(Protocol.java:149)
	    at org.apache.commons.httpclient.protocol.Protocol.getProtocol(Protocol.java:117)
	    at org.apache.commons.httpclient.HttpHost.<init>(HttpHost.java:107)
	    at org.apache.commons.httpclient.HttpMethodBase.setURI(HttpMethodBase.java:280)
	    at org.apache.commons.httpclient.HttpMethodBase.<init>(HttpMethodBase.java:220)
	    at org.apache.commons.httpclient.methods.GetMethod.<init>(GetMethod.java:89)
	    at org.mapfish.print.PDFUtils.loadImageFromUrl(PDFUtils.java:276)
	    at org.mapfish.print.PDFUtils.handleImageLoadError(PDFUtils.java:379)
	    at org.mapfish.print.PDFUtils.loadImageFromUrl(PDFUtils.java:355)
	    at org.mapfish.print.PDFUtils.getImageDirect(PDFUtils.java:189)
	    at org.mapfish.print.PDFUtils.getImage(PDFUtils.java:109)
	    at org.mapfish.print.PDFUtils.createImage(PDFUtils.java:699)
	    at org.mapfish.print.PDFUtils.createImageChunk(PDFUtils.java:689)
	    at org.mapfish.print.config.layout.LegendsBlock$Renderer.createImageChunk(LegendsBlock.java:674)
	    at org.mapfish.print.config.layout.LegendsBlock$Renderer.createTableCells(LegendsBlock.java:924)
	    at org.mapfish.print.config.layout.LegendsBlock$Renderer.createTableLine(LegendsBlock.java:863)
	    at org.mapfish.print.config.layout.LegendsBlock$Renderer.createLegend(LegendsBlock.java:776)
	    at org.mapfish.print.config.layout.LegendsBlock$Renderer.render(LegendsBlock.java:254)
	    at org.mapfish.print.config.layout.LegendsBlock.render(LegendsBlock.java:152)
	    at org.mapfish.print.PDFUtils.createCell(PDFUtils.java:657)
	    at org.mapfish.print.PDFUtils.buildTable(PDFUtils.java:642)
    `

## Steps to Reproduce the Problem

  1. View dataset eg https://master.demo.geonode.org/catalogue/#/dataset/2000
  2. Print and check option `include legend`
  3. The error above is raised

## Specifications

  - GeoNode version: master, 4.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by afabiani** [comment]
That is due to the empty `LANGUAGE` query param passed to the `GetLegendGraphic` request, e.g.:

https://my_host/geoserver/ows?TRANSPARENT=true&EXCEPTIONS=application%2Fvnd.ogc.se_xml&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetLegendGraphic&LAYER=geonode%3Atiger_roads0&**LANGUAGE=**&STYLE=geonode%3Atiger_roads0&SCALE=273437.5&height=24&width=24&minSymbolSize=24&LEGEND_OPTIONS=forceLabels%3A%3BfontAntialiasing%3Atrue%3Bdpi%3A96%3BfontStyle%3A%3BfontName%3AVerdana%3BfontSize%3A8&format=image%2Fpng

That request is causing the following Exception on GeoServer side

```xml
<ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/ows https://geonode.geosolutionsgroup.com/geoserver/schemas/ows/1.0.0/owsExceptionReport.xsd">
<ows:Exception exceptionCode="NoApplicableCode">
<ows:ExceptionText>A Language parameter was provided in the request but it cannot be resolved to an ISO lang code. Parameter value is empty while supported languages are hun,swe,dut,est,fin,ice,gsw,rum,pol,cze,dan,nor,por,ger,lit,ita,fre,gre,eng,lav,gle,spa,hrv,mlt,slo,bul,slv</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
```

**Comment by afabiani** [comment]
Unfortunatelly is an issue on the INSPIRE extension LanguageDispatcher callback https://github.com/geoserver/geoserver/blob/670cc11f9c31673260f3651d4bd8917207e43491/src/extension/inspire/src/main/java/org/geoserver/inspire/LanguagesDispatcherCallback.java#L31

The temporary solution is to remove the inspire plugin from GeoServer
mv ../webapps/geoserver/WEB-INF/lib/gs-inspire-2.20.5.jar /geoserver_data/

**Comment by giohappy** [comment]
Fixed by disabling the Geoserver INSPIRE plugin in https://github.com/GeoNode/geoserver-geonode-ext/commit/dc6effb2b9ae11e070f3a7dda3e08d29161b7fef.
