### ISSUE TITLE
No such file or directory: '/backup_restore/2022-09-03_050419/geoserver_catalog.zip', during geonode backup 

### ISSUE THREAD

**Issue by krishnakafle** [GeoNode/geonode#9952]
## Expected Behavior

I was trying to backup my system from docker container:

`docker exec -i -t django4geonode /bin/bash`

Inside this container I am running the backup command.

```
python manage.py backup -f --backup-dir=/backup_restore --config=/usr/src/geonode/geonode/br/management/commands/settings_docker_sample.ini 

```

 I followed this docs: [https://docs.geonode.org/en/master/intermediate/backup/](https://docs.geonode.org/en/master/intermediate/backup/)

## Actual Behavior
I received following error:
```
Before proceeding with the Backup, please ensure that:
 1. The backend (DB or whatever) is accessible and you have rights
 2. The GeoServer is up and running and reachable from this machine
STARTED - 1/11
STARTED - 7/11
COMPLETED - 11/11
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_                                                                                                                               command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/src/geonode/geonode/br/management/commands/backup.py", line 108, in handle
    self.execute_backup(**options)
  File "/usr/src/geonode/geonode/br/management/commands/backup.py", line 143, in execute_backup
    self.create_geoserver_backup(config, settings, target_folder, ignore_errors)
  File "/usr/src/geonode/geonode/br/management/commands/backup.py", line 382, in create_geoserver_backup
    os.chmod(geoserver_bk_file, _permissions)
FileNotFoundError: [Errno 2] No such file or directory: '/backup_restore/2022-09-03_050419/geoserver_catalog.z                                                                                                                               ip'
```
## Context:
The script is working if I exclude the geoserver with following script:

```
# Skipping Geoserver: 
python manage.py backup -f --skip-geoserver --backup-dir=/backup_restore --config=/usr/src/geonode/geonode/br/management/commands/settings_docker_sample.ini
```

## Specifications

  - GeoNode version: **3.2**
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): **Docker installation**
  - Platform: **Ubuntu 20.04**

**Comment by giohappy** [comment]
Closing as part of a repository cleanup: this issue was last updated before 2025-01-01. Not a judgment on the report itself — feel free to reopen or file a fresh issue against `main` if it's still relevant. Thanks for the report.
